### ISSUE TITLE
서버에 올릴 API  예제가 필요합니다.

### ISSUE THREAD

**Issue by wanzang** [plusfriend/auto_reply#10]
자동응답 api에 관한 스펙이나 설명은 있는데 소스파일은 구할수가 없네요.

서버에 올릴 소스파일 요청드립니다.

**Comment by jjuakim** [comment]
안녕하세요 
현재 옐로아이디 API 샘플코드는 제공되고 있지 않습니다.  
추후 제공될 예정이니 양해 부탁드립니다.
