### ISSUE TITLE
가독성을 위해 메시지를 2번 

### ISSUE THREAD

**Issue by DoHyeong** [plusfriend/auto_reply#100]
긴 메시지의 경우 가독성을 위해 메시지를 2개로 나누어 보내고 싶은데요,
한번 들어온 요청에 대하여 2개의 메시지를 반환하는 것이 가능한가요

**Comment by plusfriendteam** [comment]
현재는 불가능합니다.
향 후 해당 기능을 제공할 수 있도록 검토해 보겠습니다. ^^
