### ISSUE TITLE
자동응답 시나리오 중 메시지(기본형, 카탈로그형) 전송이 가능한가요?

### ISSUE THREAD

**Issue by enjoyseo** [plusfriend/auto_reply#101]
안녕하세요.

AXA다이렉트 계정으로 자동응답 API를 사용중입니다
저희는 최초가입 시 기본형 메시지를 보내고, 시작이라는 키워드를 고객이 입력하면 세팅된 자동응답으로 시나리오를 진행하고 있습니다.

플러스친구 메시지 종류중 기본형(텍스트,링크,이미지) 과 카탈로그형이 있는데
고객으로 부터 아래 버튼형(혹은 텍스트형) 문구를 입력 받아서, 기본형과 카탈로그형 메시지 발송이 가능한가요? 가능 하다면 설정을 어떻게 해야 하는지요..

확인 부탁드립니다
감사합니다

![kakaotalk_20161025_093302106](https://cloud.githubusercontent.com/assets/22783850/19668917/1e9b3db8-9a96-11e6-86f9-de89078ec7b6.png)

**Comment by plusfriendteam** [comment]
@enjoyseo 안녕하세요!
지금은 제공하고 있진 않습니다.
하지만 조만간 제공 될 예정이오니 조금만 기다려주세요~!
