### ISSUE TITLE
타임아웃이 계속 나고 있습니다.

### ISSUE THREAD

**Issue by nupamore** [plusfriend/auto_reply#102]
일요일 오전 10시경부터 간헐적으로 나고 있는데, 건드린 것도 없는데 왜 날까 하다가
저번에 카톡서버 문제였다는게 기억나서 그냥 기다리면 되겠거니 하고 있었는데요.

멈추지 않고 지금까지도 계속 발생하고 있어서 이슈 남겨봅니다.

**Comment by plusfriendteam** [comment]
@nupamore 어떤 계정인지 알려주시면 확인해보겠습니다.

**Comment by nupamore** [comment]
@ 데레스테이벤트 입니다

**Comment by plusfriendteam** [comment]
@nupamore 저희쪽 비동기 처리 부분에 손볼 곳이 좀 있네요. 얼른 고쳐놓도록 하겠습니다!

**Comment by nupamore** [comment]
이슈 올린 이후부터 지금까지 나아진 적이 없는 것 같은데 카톡서버 문제가 맞는거죠..? ㅠㅠ

**Comment by plusfriendteam** [comment]
@nupamore 트래픽이 몰릴 경우 구조적으로 문제가 생길 수 있는 부분이 있어 손보고 있습니다만, 해당 계정은 지속적으로 타임아웃이 발생하고 있네요. 특정 메세지에서 5초 이상의 시간이 걸리는 경우가 있는지, 트래픽이 몰릴 경우 어느정도 받을 수 있는지 확인 해 보셔야 할 거 같아요.
