### ISSUE TITLE
자동응답 시스템 응답불가 

### ISSUE THREAD

**Issue by samko635** [plusfriend/auto_reply#103]
@LG유플러스 계정에서 다음과 같은 에러가 발생했는데 자세한 이유를 알 수 있을런지요 

응답내용:
"해당 프로필의 자동응답 시스템이 응답을 하지 않습니다. 문제가 보고되어 처리 예정입니다.  다음에 다시 시도해주세요."

감사합니다.

**Comment by plusfriendteam** [comment]
문제가 있는 부분이 있어 수정중입니다. 지금은 괜찮으실거에요. ^^;
