### ISSUE TITLE
1 depth이상의 메시지 구현의 편의

### ISSUE THREAD

**Issue by JungWinter** [plusfriend/auto_reply#105]
현재 방식은 request가 오면 user_id를 가지고 세션을 조사해 이전 request를 참고하여 기능을 구현하고 있는데 
혹시 유저가 message POST를 보낼 때 별도의 필드명으로 바로 직전 메시지의 히스토리를 가져오게끔 할 순 없을까요?

**Comment by plusfriendteam** [comment]
기능개선에 관한 건의 주셔서 감사합니다-! 서비스 개선시 검토해 보도록 하겠습니다.
