### ISSUE TITLE
해당 프로필의 자동응답 시스템이 응답을 하지 않습니다

### ISSUE THREAD

**Issue by KiHyunCho** [plusfriend/auto_reply#106]
자동응답 봇api를 이용하여 처음 톡방에 들어갔을 때 
키보드가 나오도록 하긴했는데 버튼을 클릭하면 아래와 같은 메시지가 뜹니다
왜 이런건가요?

"해당 프로필의 자동응답 시스템이 응답을 하지 않습니다
문제가 보고되어 처리 예정입니다. 다음에 다시 시도해주세요"

**Comment by plusfriendteam** [comment]
10초 이상 응답이 없을 때 리턴하는 에러메세지입니다.
메세지가 잘 수신 되는지 확인해보세요.^^
