### ISSUE TITLE
신규 프로필 연결 관련

### ISSUE THREAD

**Issue by enjoyseo** [plusfriend/auto_reply#107]
안녕하세요 ^^

axa다이렉트 와 axa다이렉트_  두 프로필을 사용중입니다
axa다이렉트는 실 운영 계정이며 (https://kakao.axa.co.kr)
axa다이렉트_ 는 개발,테스트용으로 사용중인데요 (https://kakaod.axa.co.kr, https://kakaot.axa.co.kr)

신규테스트 계정을 추가하려고 하는데요
신규 계정을 저희측 서버에 등록 및 연결을 하려면 어떤 작업을 해줘야 하는지요
최초 작업자를 알 수 없어서 가이드가 필요합니다

확인 부탁드립니다
감사합니다

**Comment by enjoyseo** [comment]
혹 프로필만 신규로 생성하고, 이전 서버를 그대로 이용한다고 하면
신규 프로필의 앱url만 기존 테스트 url(https://kakaod.axa.co.kr, https://kakaot.axa.co.kr )로
등록하여 사용해도 될까요?

**Comment by plusfriendteam** [comment]
계정은 옐로아이디로 만드시면 됩니다.
이전 서버 그대로 넣으시면 됩니다.
