### ISSUE TITLE
동영상을 전달 받고 싶습니다.

### ISSUE THREAD

**Issue by 4ox** [plusfriend/auto_reply#109]
@suya55 @YoungjaeKim @jjuakim @tttkt @plusfriendteam 
#동영상을 전달 받고 싶습니다.

KBS제보 란 YelloID 를 친구 추가해보니
좌측 하단에 사진 및 카메라 뿐만아니라 동영상도 첨부해서 전달 가능한걸로 보여집니다.

API문서에는 message API 에 text, photo 만 전달 가능한걸로 나와있습니다.
어떻게 처리하면 되는지 안내 부탁드립니다.

- 사용중인 계정 -
YelloID @연합뉴스

- API 자동응답 테스트 계정 - 
YelloID @웅봇

**Comment by plusfriendteam** [comment]
동영상 전달해보시면 video 타입으로 전송이 될겁니다. photo와 동일합니다.

**Comment by 4ox** [comment]
사용자측에서 동영상을 보내려해도 동영상 버튼이 활성화 되어있지 않습니다.
활성화 방법이 있는지 궁금합니다.
