### ISSUE TITLE
Home Keyboard API 관련 문의

### ISSUE THREAD

**Issue by nemusheewon** [plusfriend/auto_reply#11]
안녕하세요. 
네무스텍 정희원입니다. 

Home Keyboard API 관련해서 문의 드립니다. 
이전에 고객선터를 통해서 여러 차례를 문의를 드렸는데 해결이 되지 않아서 다시 문의 드립니다. 

고객센터를 통해서 문의했을 때는 아래와 같이 답변을 받았습니다.

> 문의하신 자동응답 API 사용관련 문의 확인 시, 키보드 이슈 관련은 일시적 동기화 관련 문제로 확인되어
> 동기화 재진행 하였습니다. 

마지막 답변을 받았을 때 일시적으로 해결된 것 같이 보였으나 동일한 이슈가 다시 발생되어 문의 드립니다. 

현재 5.1 Home Keyboard API 규격을 보면 아래와 같습니다. 

- 이용자가 최초로 채팅방에 들어올 때 기본으로 키보드 영역에 표시될 자동응답 명령어의 목록을 호출하는 API입니다.
- 챗팅방을 지우고 다시 재 진입시에도 호출됩니다. 다만 카카오 서버에서도 1분동안 캐쉬가 저장되기 때문에 유저가 채팅방을 지우고 들어오는 행동을 반복하더라도 개발사 서버를 1분에 한번씩 호출하게 됩니다. **즉, 개발사 서버에서 정보가 변경되어도 최대 1분뒤에 유저들에게 반영이 됩니다.**
- 유저가 자동응답으로 메시지를 주고 받았을 경우는 마지막 메시지에 담겨있던 자동응답 명령어 목록이 표시됩니다. 다만 메시지에 저장된 자동응답 명령어는 10분간 유효합니다. **10분이 지난 다음에는 다시 keyboard api를 호출하여 자동응답 목록을 초기화하게 됩니다.**

규격 내용대로라고 하면 키워드가 선택되지 않은 상태에서는 최대 1분, 키워드가 선택된 상태에서는 최대 10분 안에 개발서 서버에서 응답하는 키보드로 변경되어야 합니다. 

그런데 키보드를 변경하여도 반영이 되지 않습니다. 
(운영툴에서 서비스 중지 후 재시작시에는 반영됨)

해당 이슈로 현재 저희가 봇(API형 자동응답)을 제공하고 있는 파트너사(방송사, 서울시 등)들 API 전환을 진행을 하지 못하고 있습니다. 

다시 한번 확인 부탁 드립니다.

**Comment by suya55** [comment]
@nemusheewon 안녕하세요.
1분마다 리프레쉬 하는 로직이 이슈가 있어서 잠시 동작을 멈춘상태였었습니다.
알려주셔서 감사합니다.
수정 보완하여 다시 1분에 한번씩 refresh 되도록 수정되었습니다.

**Comment by nemusheewon** [comment]
@suya55 
위 이슈가 다시 발생되고 있습니다. 
확인 부탁 드립니다.
