### ISSUE TITLE
자동응답 API 등록시 API TEST 부분에서 요청하는 URL에 에러가 있습니다.

### ISSUE THREAD

**Issue by 4ox** [plusfriend/auto_reply#110]
@suya55 @YoungjaeKim @jjuakim @tttkt @plusfriendteam 
자동응답 API 등록시 API TEST 부분에서 요청하는 URL에 에러가 있습니다.

//keyboard
//friend/:user_key
//friend
//chat_root/:user_key
등으로 전달 됩니다.

실제 API 에서는 
/keyboard
/friend/:user_key
/friend
/chat_root/:user_key

슬래쉬가 정삭적으로 전달됩니다.

**Comment by plusfriendteam** [comment]
url 등록하실 때에 마지막 슬래시는 빼고 넣어주세요.

**Comment by 4ox** [comment]
감사합니다.

**Comment by YoungjaeKim** [comment]
@4ox 저 직원 아니에요;;
