### ISSUE TITLE
봇서버 에러 관련 [wrong keyboard initialization] [서버응답 제한 시간 초과. request timeout]

### ISSUE THREAD

**Issue by enjoyseo** [plusfriend/auto_reply#112]
안녕하세요~
AXA다이렉트  계정을 사용중인데요

12:17분 부터 아래 에러 메시지가 지속적으로 오고 있는데 무슨 문제인지 확인 부탁드립니다
저희쪽 서버 상태도 확인해 보겠습니다.

[AXA다이렉트] [오후 12:39] [관리자에게만 발송되는 메시지입니다] 사용자 봇서버에 에러가 감지 되었습니다. 
 내용:[wrong keyboard initialization]

[AXA다이렉트] [오후 12:39] [관리자에게만 발송되는 메시지입니다] 사용자 봇서버에 에러가 감지 되었습니다. 
 내용:[서버응답 제한 시간 초과. request timeout]

**Comment by plusfriendteam** [comment]
@enjoyseo 우선 지금 에러 블락 상태가 되었습니다. 봇을 다시 시작해주세요. 문제는 확인중입니다.

**Comment by enjoyseo** [comment]
재시작 했는데요 14:16분 다시  내용:[error.code.op.errorblocked] 메시지와 함께 정지 되었습니다

**Comment by plusfriendteam** [comment]
@enjoyseo 관련된 값을 조정해서 재배포 하였습니다. 다시 시도해보시겠어요?

**Comment by enjoyseo** [comment]
재시작을 하면 [error.code.op.errorblocked] 에러 메시지가 10여개정도 연속적으로 뜨고 다시 막히네요..

**Comment by enjoyseo** [comment]
현재 조치가 완전히 끝나신건가요?
서비스 시작만 하면 저 메시지가 연달아 오고 중지가 되어 할 수가 없습니다.


[관리자에게만 발송되는 메시지입니다] 사용자 봇서버에 에러가 감지 되었습니다. 
 내용:[error.code.op.errorblocked]

확인 부탁드립니다
감사합니다

**Comment by plusfriendteam** [comment]
@enjoyseo 아직 조치중입니다. ㅠㅠ

**Comment by enjoyseo** [comment]
넵 힘내세요 ㅜㅜ

**Comment by plusfriendteam** [comment]
@enjoyseo 다시 해보시겠어요? ㅠ

**Comment by enjoyseo** [comment]
일단 정상작동 되는거 같습니다!

간략하게나마 장애 원인을 알 수 있을까요?

**Comment by plusfriendteam** [comment]
@enjoyseo 시작 하자마자 죽었던 것은 에러 카운트 부분에서 문제가 있었어요. 요청이 많은 계정들의 경우 문제가 됐었을 거구요. 그 전에 타임아웃 문제는 트래픽이 한번에 몰려서 잡이 밀렸었네요. 타임아웃 정책 조정으로 일단 해결이 된 상태입니다. 관련해서 공지를 드릴 예정이에요.^^

**Comment by enjoyseo** [comment]
넵 감사합니다~
고생하셨어요 ^^
