### ISSUE TITLE
봇서버 에러 감지 확인 요청

### ISSUE THREAD

**Issue by infobankimedia** [plusfriend/auto_reply#113]
안녕하세요. 인포뱅크입니다.

해당 메세지 가 계속해서 관리자에게 들어오고 있습니다.

확인 부탁드립니다.

-----------------------------
[관리자에게만 발송되는 메시지입니다] 사용자 봇서버에 에러가 감지 되었습니다. 
 내용:[서버응답 제한 시간 초과. request timeout]
-----------------------------

* 서비스 업체 리스트
SBS파워FM
SBS러브FM    
FEBC극동방송  
CBS 라디오
CBS 음악FM
CBS JOY4U   
CBS TV    
세바시
엠넷
EBS 라디오  
EBS생방송 톡!톡! 보니하니
KBS 해피FM
KBS Cool FM
KBS Classic FM
KBS 1Radio
KBS 3Radio
TBS FM
광주 극동방송

**Comment by plusfriendteam** [comment]
확인중입니다.

**Comment by plusfriendteam** [comment]
@infobankimedia 현재 문제는 해결 된 상태 입니다. 트래픽 폭증과 너무 긴 타임아웃 정책으로 인한 문제로 추정되구요. 관련하여 공지를 드릴 예정입니다-!
