### ISSUE TITLE
에러 메시지 문의

### ISSUE THREAD

**Issue by nemusheewon** [plusfriend/auto_reply#114]
다른 곳에서도 동일한 문제로 문의하시고 계시는데 확인차 추가로 문의 드립니다. 

응답을 10ms 이내로 응답하고 있는데 에러 메시지가 계속 발생되고 있습니다. 

그럼 확인 부탁 드립니다. 

**메시지:** 
[관리자에게만 발송되는 메시지입니다] 사용자 봇서버에 에러가 감지 되었습니다. 
 내용:[wrong keyboard initialization]

**수신 채널:** 
서울시, 아모레퍼시픽백화점, 롯데백화점

**Comment by plusfriendteam** [comment]
확인중입니다.

**Comment by zfanta** [comment]
오늘 많이 오네요

**Comment by samko635** [comment]
@plusfriendteam 확인되시면 혹시 간단한 원인이라도 알려주시면 감사하겠습니다

**Comment by enjoyseo** [comment]
다른분들도 계정 잠겼나요? [error.code.op.errorblocked]

**Comment by plusfriendteam** [comment]
트래픽이 순간 몰려서 잡 큐가 꽉 차서 밀렸었네요. 지금은 어느정도 해소된 것으로 보입니다. 개발자 여러분 불편을 드려 죄송합니다 ㅠㅠ
