### ISSUE TITLE
메시지 자동응답 response 타입관련 문의

### ISSUE THREAD

**Issue by samko635** [plusfriend/auto_reply#115]
API연동관련 문의드립니다. 

"5.2 메시지 수신 및 자동응답 API" 에서 response의 keyboard 타입을 buttons로 받고 싶은데 API상에서 어떻게 request를 주어야 객관식형 키보드(buttons)로 응답을 받을수 있는건가요?

**Comment by plusfriendteam** [comment]
ybot.kakao.com에서 요청한 request에 대한 response에 키보드 타입을 buttons로 주시면 됩니다.
언급해주신 "5.2 메시지 수신 및 자동응답 API" 부분에 예제가 나와있습니다. ^^;
