### ISSUE TITLE
플러스친구와 엘로우아이디 자동응답API 호환 문의

### ISSUE THREAD

**Issue by enjoyseo** [plusfriend/auto_reply#116]
안녕하세요~

AXA다이렉트  운영 계정을 사용중이고
ADK다이렉트_테스트 라고 하는 테스트계정을 만들었는데요.
기존 계정들은 플러스친구로 만들었고 자동응답 API를 사용하고 있습니다
신규 계정은 엘로우아이디로 만들어 졌고 자동응답 API도 기존 앱URL을 입력하니 사용이 되는데요

나중에  운영 계정(플러스친구)에 테스트계정(엘로우아이디)의 자동응답 소스를 업데이트 해도
이상 없이 적용 및 사용이 가능 할까요?
아니면 테스트 계정을 플러스친구로 다시 만들어야 하나요?

확인 부탁드립니다
감사합니다 ^^

**Comment by plusfriendteam** [comment]
테스트 하실 때 처럼 동일하게 사용하실 수 있습니다-!
