### ISSUE TITLE
일단 테스트 해보려고

### ISSUE THREAD

**Issue by disasterpiec** [plusfriend/auto_reply#117]
keyboard.php
 <?php
 echo<<<EOD
 {
 "type" : "buttons",
 "buttons" : ["식단표", "인트라넷", "가위바위보"]
 }
EOD;
 ?>

이렇게 서버에 keyboard 폴더 만들고 돌렸는데 initialization 오류뜨면서 안되네요

어떻게 하면 되는제 예제를 주실수있나요?

**Comment by plusfriendteam** [comment]
구현에 대한 예제는 [문서](https://github.com/plusfriend/auto_reply/blob/master/README.md)를 보시면 되는데,  해당 문서보다 더 자세한 구현에 대한 도움은 저희가 드리기 힘들듯 하네요. ^^;

**Comment by disasterpiec** [comment]
아니 저렇게 썼는데 오류가 나는 이유가 뭐죠?

키보드만 구현하면 되는걸로 알고있는데요.

서버의 php 버젼은 5.3인데 이게 문제가 되기도 하나요?

**Comment by plusfriendteam** [comment]
@disasterpiec php에 대해서는 답변 해 드리기 힘들어요. 구체적으로 어떻게 서버에서 리스판스를 내려주시는지 알려주시면 확인해보겠습니다.
