### ISSUE TITLE
메시지를 받았지만 답변을 하고싶지 않을때..

### ISSUE THREAD

**Issue by csdevpublic** [plusfriend/auto_reply#119]
프로파일명: IoT Bot

안녕하세요.
자동응답 API를 사용하려고 하는데,
User가 보내는 모든 메시지가 아니라 부분적인 메시지에 대해서만 응답 하려면,
message request에서 답변이 없는 경우는 어떤식으로 response해주어야 하나요?
빈객체를 날려봤더니 에러나네요.
확인 부탁드립니다.

**Comment by plusfriendteam** [comment]
지금의 봇 서비스는 '요청하면 응답한다'라는 개념으로 서비스가 구성되어 있어요. 그래서 문의 주신것 처럼 응답을 하지 않게 될 경우는 에러로 간주하게 됩니다. 서비스를 개편할 때 응답을 주지 않는 경우에 대해서도 고려를 해 보도록 하겠습니다.^^;
