### ISSUE TITLE
TimeOut 문제 & 메시지 응답 개수 & 이미지 화질 조정

### ISSUE THREAD

**Issue by j-w-kim** [plusfriend/auto_reply#120]
프로필명: shoefinder, visualzzang

현재, 사용자 문의에 대한 자동응답 API 사용중입니다. (POST, /message)

내용이 많습니다만, 가급적 추가설명까지 읽어주시면 감사드리겠습니다 :)

**1. 위 프로필(계정)들에 대해, Timeout 시간 정책을 10s 이상으로(10~15s 수준) 늘려주실 수 있는지요?**
추가설명: 사용자 메시지에 대해 봇이 응답을 구성하는 과정에서 시간이 오래걸릴 경우, Timeout이 계속 발생하고 있습니다. 현재는, 실제 응답의 Timeout 빈도가 70%이상 되고 있는 상황입니다.

**2. 현재, 1개의 사용자 메시지에 1개의 답변이 가능한데, 혹, API 활용에 따라 1개의 사용자 메시지에 2개 이상의 답변도 가능한지요?** 
추가설명: 사용자가 이미지를 보냈을 때, "이미지를 분석중입니다" 메시지를 먼저 보내놓고, 실제 분석된 결과 응답을 추가로 보내는 방법이 궁금합니다.

**3. 사용자가 봇으로 전송하는 이미지의 화질(크기 또는 해상도)을 고정하여 전송이 가능한지요?**
추가설명: 사용자가 이미지를 봇에 전송할 때의 이미지의 해상도나 크기가 너무 클 경우, 불필요한 자원(트래픽, 적재 등 관점)를 사용하는 듯 합니다. 따라서, 예를들어, 사용자가 원본의 큰 이미지를 보내더라도 API단에서 리사이징해서 던져줄 수 있는지 궁금합니다.

감사합니다.

**Comment by plusfriendteam** [comment]
1: 타임아웃은 연결 대기5초, 연결 후 5초 입니다. 10초 이상은 전체 서비스에 문제를 줄 수 있어서 현재로선 지원 계획이 없습니다. 죄송합니당 ㅠ
2. 지금의 정책으로는 해당 시나리오는 지원해 드릴 수 없겠네요. ㅠ 하지만 response에 복수의 메세지를  담아 유저에게 응답할 수 있도록 하는 것은 계획에 있습니다. 하지만 시간이 걸리는 동작에 대해 async 하게 동작하는것은 여전히 지원계획이 _아직은_ 없습니다.
3. 현재는 해당 이미지의 링크만 전송하고 사용자의 클라이언트(카카오톡 앱)에서 축소된 thumbnail 이미지만 보여줄 수 있게 돼 있어서 걱정하시는 바와는 정 반대로 큰 이미지를 전달 할 수 없는 구조입니다. 이부분은 큰 이미지를 전달할 수 있도록 개선할 예정입니다.

2번이 해결되면 1번은 자연스레 해결 될 문제일텐데, 2번에 대해서는 기능개선에 대해 구상중입니다.
좋은 서비스 만드시는데 불편함이 없도록 최대한 빠르게 개선하도록 하겠습니다! ^^

**Comment by j-w-kim** [comment]
빠른 답변 감사드립니다. 기능 업데이트되면 또 써봐야 겠네요 :+1:
