### ISSUE TITLE
visualzzang-response message 관련

### ISSUE THREAD

**Issue by jussong** [plusfriend/auto_reply#121]
[관리자에게 발송되는 메시지입니다]사용자봇 로못에 에러가 감지되었습니다....
이 메시지가 발송되지 않게 설정할 수 있나요?

**Comment by plusfriendteam** [comment]
두가지 방법이 있습니다.
1. 봇 관리자를 다른 사람으로 등록한다.
2. 봇 에러 원인을 제거한다.
이거 말고 메세지를 받지 않게 설정하는 방법은 따로 없습니다. ^^;
