### ISSUE TITLE
자동응답 로그 관련

### ISSUE THREAD

**Issue by KORJAHO** [plusfriend/auto_reply#122]
자동응답한 내용을 log로 저장은 불가능 한가요???

**Comment by plusfriendteam** [comment]
@KORJAHO 로그를 남기는건 직접 구현하시면 되는데....
그게 아니라면 좀 더 자세히 다시한번 설명해주시겠어요?

**Comment by KORJAHO** [comment]
로그 구현 방법 예제 파일은 없으신가요?

**Comment by plusfriendteam** [comment]
구체적으로 무슨 로그를 말씀하시는 것인지 모르겠지만,
구현 방법에 대한 안내는 해드리기 어렵습니다. ^^;
