### ISSUE TITLE
PC버전

### ISSUE THREAD

**Issue by iamSTone** [plusfriend/auto_reply#124]
안녕하세요.

자동응답 API는,
이용자가 카톡 PC버전 에서  대화내용을 입력하면 작동하지 않는 것인가요?

**Comment by zfanta** [comment]
#104 그렇다고 합니다

**Comment by plusfriendteam** [comment]
@zfanta 감사합니다. ㅎㅎ
@iamSTone #104 그렇다고 합니다. ^^;
