### ISSUE TITLE
메시지를 여러개 보낼 수 없나요??

### ISSUE THREAD

**Issue by ps2ung** [plusfriend/auto_reply#125]
응답메시지를 보낼때 지금은 아래와 같이 한개만 보낼 수 있는 것 같은데요.
여러개의 메시지를 같이 보내면 안되나요??

**Comment by plusfriendteam** [comment]
@ps2ung 지금은 지원하지 않고 있어요. 앞으로의 서비스 개선시 보내는 메세지 갯수에 대해서도 늘릴 수 있도록 해보겠습니다. 지금 당장은 요청하면 응답한다 이정도의 단순한 개념이라서요 ^^;
