### ISSUE TITLE
자동응답과 1:1 대화관리를 함께 사용할수 있는지요?

### ISSUE THREAD

**Issue by nannavi** [plusfriend/auto_reply#126]
@nannavi 입니다.

옐로아이디의 자동응답 API를 이용한 서비스를 기획하고 있는 단계입니다.

이미 운영중인 다른 옐로아이디를 참고해 본 결과
자동응답 키워드를 이용한 하단 버튼 타입 UI로 먼저 제공 가능한 영역을 안내하고
그중 특정 버튼을 클릭하면 텍스트로 사용자 정보 입력을 요청하여 
입력한 고객에게 추가 서비스를 제공하고 있기에 동일한 구성으로 서비스를 제공하고자 합니다.

먼저 메시지 입력란 부분에 [1:1] 버튼이 보이지 않는것은 일대일 대화설정을 off 로하니 [1:1] 대화 버튼이 사라지는 것을 확인했습니다. 근데 특정 상황시에는 사용자가 입력한 정보를 확인하여 추가 서비스를 제공해야 하는데 어떤 방법으로 자동응답 API가 응답하지 않고 일대일 대화로 메시지가 들어오게 하는지를 알고 싶습니다.

감사합니다.

**Comment by plusfriendteam** [comment]
1:1 대화로 메세지가 들어온다는 것은, [카카오톡 옐로아이디 관리자 센터](https://yellowid.kakao.com/)를 통해 사용자와 1:1 대화를 하고 싶으시다는 것인가요?
유저가 봇에게 보낸 내용을 카카오톡 옐로아이디 관리자 센터의 '일대일대화' 기능을 통해 확인하는 방법은 현재는 없습니다.
근데 문의주신게 이게 아닌거 같은데..... 다시 설명좀 부탁드릴게요 ^^;

**Comment by nannavi** [comment]
머리속에만 있는것을 어떻게 운영해야 할지 추측하고 질문을 드리다 보니 명확히 설명 드리지 못한 점 죄송합니다. 

유저가 봇에게 보낸 내용을 엘로아이디 관리자의 '일대일대화' 기능을 통해 확인하는 방법이 없다면
결국 자동응답 API를 통해 뒷단에서 받는 비즈니스 처리 모듈이 모든것을 제어해야 한다는 것으로 이해했습니다.

다만, 이때는 양방향 대화가 안되기에 
혹시 처음에는 봇이 처리하다가 특정 시점에 [1:1] 버튼을 활성화하여 '일대일대화' 기능을 사용하거나
제공하시는 서비스 중 하나인 상담톡 API로 연동할 수는 없을까요?

감사합니다.

**Comment by plusfriendteam** [comment]
넵 그렇게 하실 수 있습니다-!

**Comment by nannavi** [comment]
한가지만 추가 문의 드립니다.
가능하다고 답변주신 사항이 
"처음에는 봇이 처리하다가 특정 시점에 [1:1] 버튼을 활성화하여 '일대일대화' 기능을 사용하거나
제공하시는 서비스 중 하나인 상담톡 API로 연동할 수는 없을까요?" 문의에 대한 답변 이신지요?

[1:1] 버튼을 활성화 하는 것은 오로지 유저 클릭으로  가능한 것이지 API 레벨로 할 수 없는것으로 알고 있는데요..
유저는 사실 [1:1] 버튼의 의미를 모르기에 제가 생각하는 모습은

[1:1] 버튼은 유저에게 항시 숨겨져 있는 상태이지만 내부적으로 off 상태여서 자동응답 API를 이용하고
특정 시점에 내부적으로 on 상태로 변경하여 고객이 입력한 메시지를 '일대일대화' 혹은 상담톡 API로 연동하고자 하는데 이 부분까지 가능할지 검토해 주셨으면 합니다.

감사합니다.

**Comment by plusfriendteam** [comment]
네 말씀하신바와 같이 유저의 클릭으로만 가능합니다. 1:1 버튼을 유저의 클릭이 아니라 문맥에 맞게, 그러니까 ARS 서비스에서 '상담원과의 연결을 원하시면 9번을 눌러주세요.'와 같은 형식으로 서비스를 구현하시려면 상담톡 서비스를 이용하셔야 합니다. 제대로 이해하셨어요. ^^
