### ISSUE TITLE
카카오톡 링크 웹뷰 관련 문의

### ISSUE THREAD

**Issue by enjoyseo** [plusfriend/auto_reply#127]
안녕하세요

카톡에서 링크를 걸면 카톡 내 웹뷰에서 화면이 보여지는데요
사이트에 따라 기능이 제대로 구현이 안되는 부분이 있습니다

타사의 웹뷰 기능중 하단에 사파리 아이콘이 있고 그 버튼을 누르면
사파리에서 페이지가 열리는데 해당 기능이 도입 될 수 있을까요?

이 페이지에 질문할 내용이 아닌거 같기도 하지만 
일단 문의 드립니다 ㅎ

좋은 하루 되세요 ^^

![kakaotalk_20161117_103609953](https://cloud.githubusercontent.com/assets/22783850/20373110/3fd85c3e-acb3-11e6-9884-b6cfc4a0a96f.jpg)

**Comment by plusfriendteam** [comment]
@enjoyseo iOS의 경우는 화면 아래 공유 버튼 눌러 보시면(위 캡춰의 사파리 아이콘 왼쪽 아이콘이랑 똑같이 생김)
사파리로 열기가 이미 있답니다~

**Comment by enjoyseo** [comment]
넵! 공유하기를 누르면 나오는데요.
첫 단계에서 확인이 되어야, 조작법을 잘 모르는 고객들의 대응이 수월할 듯 해서요..
적용이 어려울까요..?

**Comment by plusfriendteam** [comment]
@enjoyseo 건의 해 보도록 하겠습니다.^^
