### ISSUE TITLE
자동응답과 1:1대화의 통합

### ISSUE THREAD

**Issue by iamSTone** [plusfriend/auto_reply#128]
1:1 대화 on 설정을 해 놓으면, 자동응답 기능 설정 상태에서,
유저가 직접 1:1 대화 혹은 자동응답 모드를 선택해서 메세지를 보낼 수 있습니다.

하지만, 챗봇 서비스 제공자 입장에서 
자동응답과 1:1대화를 통합해서 대응할 수 있으면 좋을 것 같습니다. 
즉, 동일 채팅 세션에서 특정 질문에 대해서는 자동응답으로 대응하고, 
자동응답을 벗어난 질문에 대해서는  서비스 제공자가 1:1 대화로 대응하는 것이 가능했으면 좋겠습니다.
(현재 페이스북 메신저 API는 가능)

**Comment by plusfriendteam** [comment]
@iamSTone [카카오톡 비즈메세지](https://bizmessage.kakao.com/)를 사용하시면 원하시는대로 구현하실 수 있습니다.^^
