### ISSUE TITLE
주관식 입력 사용

### ISSUE THREAD

**Issue by KimDee** [plusfriend/auto_reply#129]
안녕하세요! 동아리용 Yellow 아이디를 만들고 있습니다.

익명으로 건의할 수 있는 기능을 만드려고 하는데, keyboard 로 입력받은 주관식 문장을 DB에 저장하는 기능을 구현하고 싶습니다.

혹시 입력받은 문장을 어떤 방식으로 사용할 수 있나요??

**Comment by plusfriendteam** [comment]
말씀하신대로 입력받은 문장을 DB에 저장하시면 될 것 같은데요..;;
구체적으로 어떤걸 알고 싶으신 것인지 다시 자세히 말씀좀 부탁드릴게요.

**Comment by KimDee** [comment]
Keyboard에 적힌 내용을 어떤 명령어로 불러올 수 있나요?

**Comment by plusfriendteam** [comment]
@KimDee Keyboard는 봇이 유저에게 응답할 방법을 제시하는 것입니다. 제시한 내용을 유저가 선택하게 되면 해당 내용은 등록하신 url/message 로 post로 전송됩니다.

**Comment by KimDee** [comment]
답변 감사합니다!!
