### ISSUE TITLE
API v. 2.0 에 관련한 질문 입니다.

### ISSUE THREAD

**Issue by mcvzone** [plusfriend/auto_reply#13]
안녕하세요.

1. "user_key": "encryptedUserKey" 라고 되어있는데요.
    > 파트너 사로 전달 되는 user_key 는 암호화 된 값으로 전송 되나요?

2. 앱 등록.
    API 2.0 에서 앱 등록이라는 것이 있는데요.
    앱에 파트너사의 호출 될 URL을 등록하는 것으로 알고 있습니다.
    아래의 URL은 각각 어떻게 호출 되는 것인가요?

    http(s)://:your_server_url/keyboard
    http(s)://:your_server_url/message
    http(s)://:your_server_url/friend
    http(s)://:your_server_url/chat_room/:user_key

    > 파트너사에서 앱 등록시 http(s)://:your_server_url 와 같이 하면 되는 것인가요?

3. 예제 관련
    curl -XPOST 'https://:your_server_url/message' -d
    curl -XPOST 'https://:your_server_url/friend' -d 
    curl -XDELETE 'https://:your_server_url/friend/:user_key'

    > 위와 같은 예제 소스는 무었을 의미 하는 건가요? 어떻게 호출 되는 것인가요?
    > curl 이 뭔가요?

**Comment by jjuakim** [comment]
1. 네. 
userKey는 카카오톡 이용자를 구분 하기 위한 암호화 된 값이며, 프로필 별로 각기 다르게 발급 됩니다. 
예) 동일한 유저일지라도 A프로필에서는 userKey 가 "aaaaaaaa" B프로필에서는 "bbbbbbbbb"일 수 있습니다.

2. 플러스친구/옐로아이디 운영툴에 앱을 등록 할때, 앱 URL란에 직접 구축한 봇에 접근할 수 있는 URL 을 적어 주시면 됩니다. 
등록한 URL을 기준으로 , 사용자의 액션이 있을때 아래와 같은 리퀘스트를 날리게 되고, 문서에 설명한 스펙 대로 응답을 구현해 주시면 됩니다. 
> http(s)://(앱등록시 등록한 URL)/keyboard
http(s)://(앱등록시 등록한 URL)/message
http(s)://(앱등록시 등록한 URL)/friend
http(s)://:(앱등록시 등록한 URL)/chat_room/:user_key

3. 문의 주신 예제 소스 
> curl -XPOST 'https://:your_server_url/message' -d
curl -XPOST 'https://:your_server_url/friend' -d 
curl -XDELETE 'https://:your_server_url/friend/:user_key'

위 3가지는  실제 자동응답 앱이 서비스 될 때, 개발 서버로 들어오는 요청을 가상으로 만들 수 있는 방법을 안내 한 것 입니다.  각 API url이 수행하는 역할은 문서상의 API 설명 항목에 자세히 기술되어 있습니다. 예를 들어,  `http(s)://:your_server_url/message` 은 5.2 메시지 수신 및 자동응답 API  항목에 기술된 대로, message에 정의된 명령어를 자동응답 server url로 전달합니다. 문의주신 다른 url 역시 동일한 방식으로 확인하실 수 있으니 문서의 각 항목을 참고 부탁드립니다.

curl 의 사용법은 아래 링크를 참고하시면 될 것 같습니다 😄 
https://www.lesstif.com/pages/viewpage.action?pageId=14745703
