### ISSUE TITLE
옐로우아이디 API로 인해 대화 내용을 복구

### ISSUE THREAD

**Issue by gglee89** [plusfriend/auto_reply#130]
안녕하세요,

따로 이슈는 아니고요, 문의드릴께 있어서 연락드고있습니다.
재가 옐로우아이디 설정을 정상적으로 완료되었고, 아래의 보시면 제 서버에서 받은 request랑 카카오톡 화면을 스크린샷을 넣었습니다.
```json
GET /api/keyboard 200 12.492 ms - 70
{ user_key: 'LTB9rSmfMquo', type: 'text', content: '안녕하세요' }
POST /api/message 200 3006.380 ms - 276
```
![15205684_1550299728320686_1776404677_o](https://cloud.githubusercontent.com/assets/16644017/20587021/01a62b18-b24d-11e6-8a80-9a3423b6435c.jpg)

재가 드리고 싶은 질문은 바로 옐로우아이디 API로 인해 대화 내용을 받으려고 하는데요 1:1 자동응답 버턴 기능이 켜져있어야만 저희 서버 쪽에서 post message request를 받을수 있는것 같아요 ㅠㅜ 

(저의 첫 질문은)
대화내용을 발송하는쪽이랑 받는쪽에서 1:1 자동응답 버튼이 켜져있거나 말거나 무상관으로 request를 받을수 있는 밤법이 없으신가요? :)

(두번째 질문은)
옐로우아이디 API로 인해 고객님에게 메세지를 발송하는 기능이 있으신가요?

감사합니다

이지우

**Comment by plusfriendteam** [comment]
문의 주신 기능은 [카카오톡 비즈메세지](https://bizmessage.kakao.com/)를 사용시면 구현하실 수 있습니다. ^^
