### ISSUE TITLE
message 템플릿 문의

### ISSUE THREAD

**Issue by jsona** [plusfriend/auto_reply#131]
옐로아이디관리 페이지에서 작성할 수 있는 앨범형, 카탈로그형, 쿠폰형 등의 메시지 템플릿을 API형 자동응답 respone로 쓸 수 있나요? 가능하다면 format을 알려주시면 감사하겠습니다.

**Comment by plusfriendteam** [comment]
현재는 [문서](https://github.com/plusfriend/auto_reply/blob/master/README.md)에 나와있는 타입 외에 다른 형식의 메세지는 지원하지 않고 있습니다. 따라서 언급하신 앨범형등의 메세지는 API형 자동응답을 이용하여 보내실 수 없습니다.
