### ISSUE TITLE
API TEST Initialize Api test : Fail 415 : wrong keyboard initialization 문제 입니다.

### ISSUE THREAD

**Issue by vljh246v** [plusfriend/auto_reply#132]
Required*
Initialize Api test : Fail 415 : wrong keyboard initialization
Optional
Friend add Api test : Fail 404
Friend block Api test : Fail 404
Chatroom leave Api test : Fail 404

이런 에러가 발생해서 서비스 시작이 안되고 있는 상황입니다.

단순 TEST와 학습차원에서 만들어보는 것이라 HTTPS 통신은 하지 않고 있습니다
서버는 AWS + nodejs를 사용중입니다.

http://ec2주소/keyboard 로 요청하고 있고

app.get('/keyboard', function(req, res){
        res.set('Content-Type', 'application/json');
        res.json({"type":"buttons","buttons":["aaa","bbb"]});
});

단순히 이런 식으로 응답하고 있습니다.

postman 으로 요청해본 결과

해더
Connection →keep-alive
Content-Length →42
Content-Type →application/json; charset=utf-8
Date →Thu, 24 Nov 2016 06:36:30 GMT
ETag →W/"2a-5vaeXfGKuVYrrr3ifS7HBQ"
X-Powered-By →Express
바디
{
  "type": "buttons",
  "buttons": [
    "aaa",
    "bbb"
  ]
}

이렇게 응답이 오고 있습니다 혹시 어떤 문제 인지 알 수 있을까요?

**Comment by plusfriendteam** [comment]
@vljh246v 테스트중이신 계정의 id를 알 수 있을까요? @로 시작하는 검색용 uuid 알려주시면 로그 확인해볼게요.^^

**Comment by plusfriendteam** [comment]
@vljh246v 아아 계정보다 개발중이신 서버 url을 알려주시는게 더 좋을듯 하네요.

**Comment by vljh246v** [comment]
@plusfriendteam 
계정 아이디는 '@번역하기' 입니다.

서버 url은 http://ec2-52-78-230-23.ap-northeast-2.compute.amazonaws.com:3000/keyboard
입니다

**Comment by plusfriendteam** [comment]
뒤에 /keyboard까지 다 넣으셨군요. ㅎㅎ 포트번호까지만 넣고 해보세요^^

**Comment by vljh246v** [comment]
@plusfriendteam
으아...너무 감사드립니다 ㅜㅜ 바쁘신데 감사합니다
