### ISSUE TITLE
Delayed responses?

### ISSUE THREAD

**Issue by AterIgnis** [plusfriend/auto_reply#133]
Hello,

I am working on bot, which could not respond instantly due to internal logic and requests to external services. Is there any way to send a message to user by User_key without requesting user to actively poll for updated responses manually?

Also there is a mention on App_key and App_secret, but no description on where they might be useful or any further reference in API.

**Comment by plusfriendteam** [comment]
@AterIgnis 
Unfortunately, we don't support sending messages asynchronously. 
Because App key and App secret was designed for async messages that is not unnecessary information as I mentioned above.
