### ISSUE TITLE
Image resizing

### ISSUE THREAD

**Issue by AterIgnis** [plusfriend/auto_reply#134]
Hello.

I am sending photo to my bot with KakaoTalk and it is being resized to 960points. Is this limit on transfer image size by bot API, or am I doing something wrong? What are constraints on images? (API has guides on image size and format when responding from bot, but does not define image constraints when sent from user)

Thanks.

**Comment by plusfriendteam** [comment]
You can choose a resolution of the picture when you select. There are three resolutions; standard, high, and original.

**Comment by d0nsergio** [comment]
@plusfriendteam,

Thank you for your answer. And could you please share more details how and where to select resolutions.?
I cannot find any way to select an image resolution in Kakao Talk messenger for Android.
Also I cannot find any information about resolution in API specification here.

Thank you.

**Comment by plusfriendteam** [comment]
You can find a button if you look at the bottom left of the screen.
![image](https://cloud.githubusercontent.com/assets/19848841/20702703/5326b7b0-b65c-11e6-991d-249029d40b02.png)

Click it.

Then, you can see this.
![image](https://cloud.githubusercontent.com/assets/19848841/20702876/e4ca4a7e-b65c-11e6-869f-5602deb734c3.png)

Choose one and click the next button on top right.
![image](https://cloud.githubusercontent.com/assets/19848841/20702918/10710e6a-b65d-11e6-9cb0-5a093cc75d8f.png)

Finally, you can meet the resolution select box! :-)
![image](https://cloud.githubusercontent.com/assets/19848841/20702997/58bdb83a-b65d-11e6-8ba4-0ca2c7b22d2e.png)

**Comment by d0nsergio** [comment]
@plusfriendteam, 

Ok, thank you for support!
