### ISSUE TITLE
관리자 메세지 문의

### ISSUE THREAD

**Issue by infobankimedia** [plusfriend/auto_reply#135]
안녕하세요. 인포뱅크 김지황입니다.

어제 27일(12:16~14:56) 사이에 KBS 라디오 5개 채널에서 다음과 같은 메세지가 간헐적으로 발생 하였습니다. (인입이 되는 경우도 있었고, 안되는 경우도 있었습니다.)

![default](https://cloud.githubusercontent.com/assets/19382791/20653992/1b9c7870-b558-11e6-914c-29bd5d406a0f.PNG)

#5개 채널
KBS 해피FM
KBS Cool FM
KBS Classic FM
KBS 1Radio
KBS 3Radio

해당 내용 관련하여, 저희쪽 수신로그에는 이상이 없는 것으로 보입니다.

이전에도 해당 메세지 관련 문의 드린 내용상으로는 타임아웃또는 json포맷 문제라고 답해 주셨습니다.
( https://github.com/plusfriend/auto_reply/issues/73#issuecomment-240957872 )

위의 내용 관련하여, 해당 시간에 플친 작업이나 이슈 또는 해당 메시지가 발생하는 추가적인 원인 확인 부탁드립니다.

그리고 현재 플친 타임아웃 설정값 확인 부탁드립니다.

다소 문의 내용이 명확하지는 않지만, 실시간으로 사용자가 참여하는 양뱡향 서비스이므로 해당 이슈가 크게 작용하는점 양해 부탁드립니다.

감사합니다.

**Comment by plusfriendteam** [comment]
@infobankimedia 안녕하세요. 해당 시간에 특별한 이슈는 없었습니다.
타임아웃은 5초입니다.
메세지의 경우 접속대기 5초, 접속 후 5초이고 키보드 정보의 경우 총 합 5초입니다.
말씀해주신 시간대에 로그를 확인해 보니 위 5개 계정에 연결 된 서버로의 연결에 문제가 있었습니다.
근데 응답을 저희가 못받은 경우가 많네요.
일단 저희쪽 로그로 봐서는 연결 시도 후 응답을 받지 못하고 있었습니다.

**Comment by plusfriendteam** [comment]
@infobankimedia 혹시 해당 문제가 있던 시간대에 DNS 문제가 있으셨던건 아닌지 확인 부탁드릴게요.

**Comment by infobankimedia** [comment]
안녕하세요. KBS 사내에서 해당 시간에 네트워크 작업이 있었던 것으로 확인되어, 해당 시간에 간헐적으로 응답을 제대로 주지 못한것 같습니다. 자세히 확인해 주셔서 감사합니다.

**Comment by plusfriendteam** [comment]
원인이 밝혀진거 같아 다행입니다. :-) 원활한 서비스를 제공하실 수 있도록 저희도 열심히 돕겠습니다~! ^^
