### ISSUE TITLE
서비스가 무조건 꺼집니다

### ISSUE THREAD

**Issue by nupamore** [plusfriend/auto_reply#136]
![image](https://cloud.githubusercontent.com/assets/11649322/20654226/88d78806-b55a-11e6-9ca5-f52bb5e8015b.png)

서버에 쓸대없는거 다 지우고 [GET /keyboard]만 남겨놨는데 서비스 시작하자마자 꺼지네요.
한 3번정도 키면 잠깐 괜찮았다가 아무 요쳥도 들어오지 않았는데 꺼집니다.
카톡서버쪽에서 뭐가 넘친거같은데 풀어주시면 감사하겠습니다..

**Comment by plusfriendteam** [comment]
@nupamore 다 지우셨다고 하셨는데 POST /message까지 다 지우셨나요? 로그상으로는 유저가 메세지를 보냈는데 응답을 못해서 계속 에러카운트가 누적되고 있는 것 같습니다.
메세지는 받도록 하시거나 옐로아이디 관리자센터에서 봇 사용을 중지하시거나 하셔야 할 거 같아요.

**Comment by nupamore** [comment]
아 POST /message 받는건 그대로 있구요, 원래 버튼을 통해서 메세지를 받았는데 버튼목록을 비워놨다는 뜻이였습니다.

![image](https://cloud.githubusercontent.com/assets/11649322/20655711/9772d24a-b568-11e6-85d6-353ad9a80b7c.png)

봇 사용은 꺼져있는 상태인데 서버 다시 올리고, 봇 사용을 다시 시작하게 되면 서버에는 저런 로그만 뜨고
(원래 메세지도 떴었습니다. 전부 카톡서버에서 보내는걸로 보입니다.)
동시에 카톡으로는 위의 에러메세지가 오면서 봇 사용이 중지됩니다.

**Comment by plusfriendteam** [comment]
@nupamore 에러 카운트를 리셋 시켰습니다. 다시 시작해보시겠어요?

**Comment by nupamore** [comment]
열심히 관찰하고 있었더니 가끔씩 카톡메세지를 보냈는데 제 서버에는 요청 자체가 오지를 않습니다.

**Comment by plusfriendteam** [comment]
@nupamore 혹시 ACL로 접근제한 하시나요?
110.76.143.236
위 ip에 대해 접근 가능하게 설정 돼 있는지 확인 부탁드릴게요.
저희측에서 접근하는 서버의 ip 목록은 [요기](https://github.com/plusfriend/auto_reply#71-proxy-server-information) 있습니다.

**Comment by plusfriendteam** [comment]
@nupamore 참고로 110.76.143.236 서버에서 연결을 시도할 때 syn을 보내고 syn/ack가 와야 하는데 오질 않아서 tcp 연결이 안되고 있어요.

**Comment by nupamore** [comment]
말씀하신대로 로그에 236은 보이지를 않네요! 문제를 해결해보도록 하겠습니다. 도움주셔서 감사합니다.

**Comment by nupamore** [comment]
![default](https://cloud.githubusercontent.com/assets/11649322/20668632/1bdb0b5c-b5b3-11e6-8d70-ccf4a8b1f9ac.png)

저도 그렇고 서버호스팅 업체 답변도 그렇고 딱히 막아놓지는 않았는데 모르겠네요..

**Comment by nupamore** [comment]
서버 이전으로 해결(?)했으니 이슈는 닫겠습니다.
