### ISSUE TITLE
자동응답 API 서비스 시작이 안됩니다.

### ISSUE THREAD

**Issue by dongchae1** [plusfriend/auto_reply#137]
프로필  : SCP, SCP Dev
위의 두개 프로필을 바꿔가면 서비스를 개발중인데요. 어제 부터 아래와 같은 에러가 뜨면서 시작이 안됩니다.
![image](https://cloud.githubusercontent.com/assets/22650470/20733599/915e36ae-b6d7-11e6-9229-9c016a3c1c75.png)

답변 부탁드립니다.

**Comment by plusfriendteam** [comment]
자동응답 개발중이신 서버에서 응답이 안오네요.
이럴 때 친절하게 안내가 되지 않는 문제가 있군요. 수정하도록 하겠습니다.
지금 안되는 문제는 서버에서 응답을 주시면 시작이 될겁니다.

**Comment by d0nsergio** [comment]
@plusfriendteam, thank you, **SCP** app was resumed successfully.
And could you please check what can be wrong with **SCP Dev** app?

**Comment by plusfriendteam** [comment]
@d0nsergio What I can found on log files are timeout Exceptions.
