### ISSUE TITLE
@어이브라더 문의드립니다.

### ISSUE THREAD

**Issue by washswat** [plusfriend/auto_reply#138]
안녕하세요! 자동응답 API 테스트 중에 있는데요,
저희 서버에서 카카오톡 자동응답을 종료하고 바로 상담을 할 수 있는 API는 없나요?
혹시 가능한지 여쭤봅니다.

**Comment by plusfriendteam** [comment]
@washswat [카카오톡  비즈메세지](https://bizmessage.kakao.com/)를 쓰시면 구현 가능합니다. ^^
