### ISSUE TITLE
[문의] 가끔 채팅 메시지가 서버로 request 가 오지 않는 경우가 발생합니다.

### ISSUE THREAD

**Issue by neptnt01** [plusfriend/auto_reply#139]
안녕하세요. 코난테크놀로지의 이지행이라고 합니다.

현재 자동응답 API 를 개발하고 있고, 프로필명은 "@치킨주문톡" 이고 앱 URL 은 "http://chicken-yellowid.pulsek.com" 입니다.

1. 가끔 채팅창에서 메시지 입력시 메시지가 읽음 표시가 되지 않고 서버 로그를 확인해 봐도 request 가 오지 않습니다. 이후로는 메시지를 아무리 입력해도 계속해서 동일한 상태이고 채팅방을 완전히 나갔다 들어와야 정상적으로 작동합니다. 이런 현상이 나타는 이유가 있을까요?

2. 관리자 채팅창으로 가끔 "wrong keyboard initialization" 메시지가 오는 데 어떤 경우 발생하는지 알고 싶습니다.

답변 감사합니다.

**Comment by plusfriendteam** [comment]
1. 요청이 가지 않은 시간을 정확히 알려주시면 로그를 확인하는데 도움이 되겠습니다.
2. GET /keyboard 요청에 대한 결과가 성공적이지 못할 경우, 그리고 어느정도 해당 에러가 쌓이게 될 경우 해당 메세지가 발송됩니다.

**Comment by neptnt01** [comment]
어제 2016년 12월 5일 20시 4분 경에 발생하였습니다. 보낸 메시지는 다음과 같습니다. 확인 부탁 드려요

우우아아
ㅓ러라라래
으라아아리라
너오어
조너어어아ㅏㅇㅇ

**Comment by plusfriendteam** [comment]
저희쪽 로그를 보니 정상요청하였고 5초 타임아웃에 걸렸었네요.
지금도 안된다고 하셨는데 http://chicken-yellowid.pulsek.com 으로 요청한 내역이 로그에 없습니다.
대화 입력창 우측에 1:1 버튼이 눌린 상태로 대화를 하실 경우 대화가 봇이 아닌 옐로아이디 관리자센터 대화방으로 전송이 됩니다. 확인 부탁드립니다.

**Comment by neptnt01** [comment]
혹시, 저희쪽 WAS 가 문제가 있어서 request 를 못 받아서 "해당 프로필의 자동응답 시스템이 응답을 하지 않습니다. 문제가 보고되어 처리 예정입니다. 다음에 다시 시도해 주세요." 메시지가 나오고 
그 이후에 WAS 가 정상작동하였는데 그 이후로 채팅창에 메시지를 보내는 경우 request 가 가는 건지요?

오후 1시 58분 경에 테스트 하였습니다.

**Comment by plusfriendteam** [comment]
봇에서 정상적으로 response가 내려와 메세지를 유저에게 다시 성공적으로 보내게 될 경우에 읽음처리가 됩니다.
1시 58분 요청은 503으로 내려와 메세지를 전송할 수 없었기에 읽음처리가 되지 않았습니다.

**Comment by neptnt01** [comment]
그 말씀은 무슨 말씀인지 알겠습니다.

제가 알고 싶은 내용은 503 에러가 난 메시지 이후에 보내는 메시지는 봇에 보내지 않는 것 같아서요?

503 에러 후의 메시지들의 후처리가 어찌 되는지 궁금합니다

503 에러 후 저희 쪽 서버를 정상화하고 나서 메시지를 보냈는데도 저희 쪽 서버에는 request 로그가 찍히지 않아서요.

감사합니다.

**Comment by plusfriendteam** [comment]
13시 58분 메세지 전송 에러 한 건 이 후 그 어떤 요청도 저희 로그에는 남아있지 않습니다.
위에 말씀드린것과 같이 1:1 버튼이 눌려서 상담원과의 대화 상태에서 전송하신게 아닌지 확인 해보시길 바랍니다.

**Comment by neptnt01** [comment]
네 친절하고 빠른 답변 감사합니다.

확인해 보도록 하겠습니다.

감사합니다.

**Comment by neptnt01** [comment]
관리자님, 다시 테스트 해 보니

에러가 난 후에 1:1 버튼이 눌려서 상담원가의 대화 상태로 가는 게아니라 

에러가 난 후에는 자동으로 상담원의 대화로 전환이 되어 버립니다.

그 이후로는 다시 상담원과의 대화에서 일반 대화로 오는 방법이 없더라구요.

참고해 주세요.

참고 부탁 드립니다.

**Comment by plusfriendteam** [comment]
메세지 전송에서 에러가 나고 키보드 정보 또한 내려주지 않는다면 봇에 메세지를 보낼 방법이 정의되지 않았기 때문에 1:1 상담모드로 전환됩니다. 대화방 나가기를 하고 다시 대화를 시도하면 될겁니다.

**Comment by neptnt01** [comment]
무슨 말씀 인지 알겠습니다.

감사합니다.
