### ISSUE TITLE
적절하지 않은 때에 보내는 wrong keyboard initialization 관련 오류

### ISSUE THREAD

**Issue by JoonyoungYi** [plusfriend/auto_reply#14]
일단, 제가 이해하고 있는 카카오 봇은 다음과 같습니다.
- 사용자가 채팅방에 들어와 있거나 사용자가 어떤 액션을 하거나(버튼을 누르는 등) 사용자가 메세지를 입력할 때, 이에 적절하게 반응해서 응답을 주는 봇

카카오봇을 운영하는 저희 서버에 오류가 있으면, 특정 사용자들에게 wrong keyboard initialization 이라는 메세지를 보내는 것 같습니다. 물론 서버에 오류가 있다면, 이런 메세지를 사용자들에게 보내는 것은 당연한 것 같습니다. 하지만, 문제는 보내는 타이밍인 것 같습니다.

특정사용자들의 경우, yellow id 페이지를 조회하지 않고 있음에도 불구하고, 카카오 측에서 봇 서버 측으로 api call을 하는 것 같습니다. 이 때에는 봇 서버에 에러가 있더라도 사용자에게 메세지를 보내지 않아야 한다고 생각합니다. 이를 에러로 인식하여 사용자들에게 "wrong keyboard initialization" 메세지를 보내는 것 같습니다. 

확인 부탁드립니다.

감사합니다.

**Comment by suya55** [comment]
#9 이슈를 참고해주세요~
유저에게는 해당 메시지가 날아가지않습니다.

오직 관리자에게만 날아갑니다.
