### ISSUE TITLE
서버에 SSL 설치 필수인가요?

### ISSUE THREAD

**Issue by ga2mi** [plusfriend/auto_reply#140]
앱 등록 - 앱 URL에 입력하고 api test  누르면
Server request time out! 떠서 #1  보고 방화벽도 열었거든요
근데 그래도 똑같이 Server request time out!이 떠요.
SSL 문제일까요?

앱 URL에 입력한 주소/keyboard 는 정상작동 하고 있는데..
왜 api test가 안되는지 모르겠어요.

**Comment by plusfriendteam** [comment]
SSL은 권장이지만 필수는 아닙니다.
url 마지막에 / 넣으셨다면 빼고 다시 시도해보세요. 보통은 이 문제입니다.

**Comment by ga2mi** [comment]
http://27.122.251.249/pulmuone/TEST 이렇게 빼고 넣어도 안되요..
확인 부탁드립니다..

**Comment by plusfriendteam** [comment]
해당 주소로 접근이 안되네요.
서버 설정부터 확인해보셔야 할 듯 합니다.

**Comment by ga2mi** [comment]
서버 설정 다시 해서 API TEST는 통과 됐어요!
주소로만 설정해 놓은 상태인데, 어떤 포트만 열어 놓아야 하는지 알 수 있을까요?

**Comment by plusfriendteam** [comment]
포트는 아무거나 상관 없습니다.
지금처럼 그냥 80으로 하셔도 되구요.^^
