### ISSUE TITLE
헤더값(userAgent)을 값을 받을 수 있나요?

### ISSUE THREAD

**Issue by enjoyseo** [plusfriend/auto_reply#141]
안녕하세요~ ^^
@AXA다이렉트 아이디를 사용중입니다

다름이 아니라 고객에게 메시지를 보낼때 아이폰유저를 구분하여 따로 보내려고 합니다. 
시스템파트에 물어봐야 확실하겠지만 현재는 헤더값을 별도로 받지 않는거로 알고 있는데,
그렇다면  헤더값을 보내주실 수 있나요?

확인 부탁드립니다
감사합니다 ^^

**Comment by plusfriendteam** [comment]
유저가 어떤 환경에서 메세지를 보냈는지에 대한 정보는 제공해드리기 어렵습니다.
반드시 그 디바이스에서 전송된 메세지를 본다고 보장할 수 없습니다.
PC버전을 사용할 수  있고 기기변경을 할 수도 있습니다.
