### ISSUE TITLE
카카오 응답장애 (계정 : CJ오쇼핑, GS SHOP 외 다수)

### ISSUE THREAD

**Issue by samko635** [plusfriend/auto_reply#144]
(계정 : CJ오쇼핑, GS SHOP 외 다수)

약 10분 전 가량부터 카카오페이 플러스친구/옐로아이디 응답이 오지 않고 있습니다. 
확인 후 원인 공지 부탁드립니다. 

감사합니다.

**Comment by plusfriendteam** [comment]
서비스 배포중 문제가 생겼었습니다.
발생 시간: 17:59-18:25
장애 현상: 유저의 메세지가 전송되지 않음.
장애 원인: 서버 설정 오류로 인하여 routing 에러 발생

간단한 설정 오류인데 복구에 너무 오래걸렸습니다.
모니터링 헛점을 발견하였고 해당 부분 보강하여 이번과 같은 문제는 발생하지 않도록 조취를 취할 예정입니다.
