### ISSUE TITLE
플러스 친구 미응답 이슈 문의

### ISSUE THREAD

**Issue by infobankimedia** [plusfriend/auto_reply#145]
안녕하세요. 인포뱅크 김지황입니다.

현재 운영중인, SBS, KBS, CBS, 극동방송, EBS 등 플러스 친구 미응답 현상이 발생하고 있습니다.

관리자에게 날라오는 푸쉬 메세지 조차 없네요.

확인 부탁드립니다.

**Comment by plusfriendteam** [comment]
서비스 배포중 문제가 생겼었습니다.
발생 시간: 17:59-18:25
장애 현상: 유저의 메세지가 전송되지 않음.
장애 원인: 서버 설정 오류로 인하여 routing 에러 발생

간단한 설정 오류인데 복구에 너무 오래걸렸습니다.
모니터링 헛점을 발견하였고 해당 부분 보강하여 이번과 같은 문제는 발생하지 않도록 조취를 취할 예정입니다.
