### ISSUE TITLE
시나리오 응답이 없습니다

### ISSUE THREAD

**Issue by enjoyseo** [plusfriend/auto_reply#146]
안녕하세요 AXA다이렉트  계정을 사용중인데요
테스트 계정하고 운영계정 둘 모두 첫 시작 메세지를 입력해도 응답이 없습니다

확인 부탁드립니다

**Comment by plusfriendteam** [comment]
서비스 배포중 문제가 생겼었습니다.
발생 시간: 17:59-18:25
장애 현상: 유저의 메세지가 전송되지 않음.
장애 원인: 서버 설정 오류로 인하여 routing 에러 발생

간단한 설정 오류인데 복구에 너무 오래걸렸습니다.
모니터링 헛점을 발견하였고 해당 부분 보강하여 이번과 같은 문제는 발생하지 않도록 조취를 취할 예정입니다.
