### ISSUE TITLE
user_key 에 대하여 질문있어요

### ISSUE THREAD

**Issue by 78lab** [plusfriend/auto_reply#148]
자동응답 API 에 사용되는 user_key 는 카카오톡 로그인시 사용되는 유저키 와는 다른건지요?

현재 서비스에 카카오톡 로그인을 사용하고 있는데요.

카카오톡 로그인 유저가 옐로우아이디로 문의할때 같은 유저인지 매칭할 수 있는 방법은 없는건가요?

**Comment by plusfriendteam** [comment]
두 키는 다른 값입니다.
아직은 저희가 동일한 키를 드릴 수 있는 준비가 되어있지 않습니다. ㅠㅠ
그래서 당장 이 문제를 해결하기 위해서는 초기에 유저에게 직접 전화번호 혹은 이메일 같은 키를 받아서 확인하는 방법밖에는 없습니다.
도움 못드려 죄송합니다. ㅠㅠ
이러한 기본적인 것들 빨리 제공할 수 있도록 노력하겠습니다! ㅠㅠ
아 쓰면서도 저도 참 속상하네요..

**Comment by 78lab** [comment]
빠른 답변 감사드립니다.
혹시 이 기능이 제공 예정인지 가능하다면 언제쯤인지 알 수 있을까요?
저희가 따로 매칭 로직을 구현해야할지 결정하는데 참고하려고 합니다.

**Comment by plusfriendteam** [comment]
아직 확실한 일정이 없기 때문에 직접 구현하시는게 더 현명한 선택이 되시리라고 봅니다.
