### ISSUE TITLE
봇서버 에러메시지가 너무 많이 오네요..

### ISSUE THREAD

**Issue by enjoyseo** [plusfriend/auto_reply#149]
안녕하세요~
AXA다이렉트 계정을 사용중입니다

근래 들어서 봇서버 에러메시지가 크게 늘었습니다.
이전에는 두어시간에 한두건이 온다면, 근래에는 한시간에 수십여건이 올정도고 
새벽에도 자주와서 수면장애까지 오네요 ㅜㅜ

무슨 문제일까요.. 사용자가 늘어서 생긴 문제인가요..
확인 부탁드립니다

![kakaotalk_20161213_144003923](https://cloud.githubusercontent.com/assets/22783850/21129031/95a3987e-c142-11e6-86f0-77e89646454d.png)
![kakaotalk_20161213_144002978](https://cloud.githubusercontent.com/assets/22783850/21129032/96b3a240-c142-11e6-98ff-e0a2a52380c2.png)

**Comment by plusfriendteam** [comment]
악사 봇의 사용자가 많아져서 그런지 keyboard 요청에 대해서 타임아웃이 많이 발생하고 있네요.
해당 값이 자주 변하지 않는다면 캐싱을 하거나 웹서버 설정에서 바로 정해진 json값으로 리턴하게 구성하신다면
응답이 더 빨라져서 타임아웃 에러 발생횟수가 줄지 않을까 합니다.
에러메세지 전송 횟수와 정책에 대해서도 좀 수정이 필요한듯 한데 불편함을 느끼지 않도록 대책을 마련해 보도록 하겠습니다.
