### ISSUE TITLE
자동응답 API 관련 문의 드립니다.

### ISSUE THREAD

**Issue by mcvzone** [plusfriend/auto_reply#15]
AXA 다이렉트 입니다.
사용중인 yellowid는 AXA다이렉트_ 입니다.

1. https://yellowid.kakao.com/bot/api 에서 앱 URL 을 등록 하고, API TEST 버튼을 클릭하면 아래와 같은 
메시지가 생성 됩니다
    등록한 앱 URL 은 오픈 되어있는 주소 이므로, 방화벽 관련 문제는 없습니다.
    (참고 : 등록된 앱 URL은 일반 인터넷으로도 접속이 가능한 오픈된 URL 입니다.)
    Required*
         Initialize Api test : Fail 500 : wrong keyboard initialization
    Optional
         Friend add Api test : Fail 500 : Received fatal alert: handshake_failure
         Friend block Api test : Fail 500 : Received fatal alert: handshake_failure
         Chatroom leave Api test : Fail 500 : Received fatal alert: handshake_failure

2. 기존에는 아래와 같은 parameter 를 받았습니다.
               room_key
               user_key
               country_iso
               message
               as-is 와 to-be 의 전문을 비교한 가이드가 있나요?

**Comment by suya55** [comment]
@mcvzone 안녕하세요.
기존 API와 같은건 오직 user_key같은 메타데이터 밖에 없습니다.

기존 문서를 의지하지 마시기바랍니다.

일단 등록하신 정보를 보니까 
https://kakaot.axa.co.kr/KakaoActionControler.action 이렇게 확인이 됩니다.

카카오 서버가 귀사의 서버를 호출하는데에는 필수적으로 2개의 api 주소가 필요합니다.

https://{사용자의 서버 주소}/keyboard
https://{사용자의 서버 주소}/message

하지만 제가 주소로만 봤을때는 KakaoActionControler.action이 path에 속하지 않는것 같으니
어드민에서 주소입력하는 부분에는 https://kakaot.axa.co.kr 여기 까지만 입력하시구요
그러면 카카오 서버가 귀사의 서버를 호출할 때 뒤에 keyboard와 message를 붙여서 아래와 같이 호출하게 됩니다.

```
https://kakaot.axa.co.kr/keyboard   - GET 요청
https://kakaot.axa.co.kr/message   - POST요청
```

각 주소에서 저희가 전달드리는 user_key, message등의 정보는 request body에 json 형태의 문자열로 실어서 보내게 됩니다.

그럼 server side에서 request.body를 추출하실 때 json object형태로 파라미터를 추출하셔서 사용하시면 됩니다.

**Comment by mcvzone** [comment]
확인 해보니, 운영에만 인증서가 있고, 개발 단에는 인증서가 존재 하지 않아서 발생된 문제 였습니다.
감사합니다.
