### ISSUE TITLE
자동응답 유저와 옐로아이디 관리자 페이지상의 유저는 어떻게 매칭 하나요?

### ISSUE THREAD

**Issue by 78lab** [plusfriend/auto_reply#150]
자동응답 API로 받은 유저키로 옐로아이디 관리자 페이지에서 검색이 가능한가요?

이게 안되면 자동응답 유저는 관리가 불가능할거 같은데요...

또는 유저가 자동응답 사용에 어려움을 겪고 있다면 별도의 안내를 해줄 수 있는 방법이 있나요?

**Comment by plusfriendteam** [comment]
안타깝게도 현재로서는 방법이 없어요.
옐로아이디 관리자 페이지의 대화방에서 볼 수 있는 상대방의 대화명을 유저키와 함께 보내드릴 수 있는지
검토 해 보고 말씀드리도록 하겠습니다.

**Comment by plusfriendteam** [comment]
@78lab 곧 개편될 관리자센터 일대일채팅 관리 메뉴에서 유저키를 통한 대화방 검색을 지원할 수 있도록 하겠습니다. 물론 정책적/기술적 이슈가 발생됐을 경우 지원이 어려워 질 수 있으니 참고 부탁드려요.^^
