### ISSUE TITLE
카톡을 통해 등록한 이미지를 볼 때 방화벽 요청을 해야하나요?

### ISSUE THREAD

**Issue by enjoyseo** [plusfriend/auto_reply#151]
안녕하세요~ AXA다이렉트 계정을 사용중인데요

현재 고객이 카톡에서 등록한 이미지를 볼 때
http://dn-m.talk.kakao.com/파일명 에 붙어서 다운로드하여 보고 있습니다.
이번에 저희 회사의 대표 IP가 변경이 되는데요.
혹시 방화벽 해제 관련하여 별도의 요청이 필요한가요?
이전에 작업하셨던 분의 말로는 이미지 다운로드관련 해서는 IP 관련 요청한게 없다고 들었습니다.

만약 필요하다면 어떠한 형식으로 요청을 해야하는지요..

확인 부탁드립니다
감사합니다 ^^

**Comment by plusfriendteam** [comment]
문의주신 건과 관련하여 따로 요청하실 일은 없어 보입니다.^^
