### ISSUE TITLE
Initialize Api test : Fail 415 : wrong keyboard initialization 문의 드립니다

### ISSUE THREAD

**Issue by webpl** [plusfriend/auto_reply#152]
안녕하세요.  옐로우ID 서비스를 이용하여, 카카오봇 을 만들려고 합니다.

계정 승인은 다 완료가 되었는데, API 테스트를 하니 아래와 같은 경고가 발생합니다.

현재 사용중인 정보는 아래와 같습니다.
조언 부탁드립니다.

▶ 프로필 : webpl_bot
▶ 서버 : nginx
▶ 포트 : 80
▶ 주소 : http://xxx.xxx.xxx/kakao

▶ 옐로우ID API 테스트 결과 출력
Required*
Initialize Api test : Fail 415 : wrong keyboard initialization
Optional
Friend add Api test : Fail 405
Friend block Api test : Fail 405
Chatroom leave Api test : Fail 405

▶ curl 로 해당 주소 접속시 출력 내용 :
root@203:~# curl -v http://xxx.xxx.xxx/kakao/keyboard
* Hostname was NOT found in DNS cache
*   Trying xxx.xxx.xxx...
* Connected to xxx.xxx.xxx (xxx.xxx.xxx) port 80 (#0)
> GET /kakao/keyboard HTTP/1.1
> User-Agent: curl/7.35.0
> Host: xxx.xxx.xxx
> Accept: */*
>
< HTTP/1.1 200 OK
* Server nginx is not blacklisted
< Server: nginx
< Date: Thu, 15 Dec 2016 04:03:45 GMT
< Content-Type: application/octet-stream
< Content-Length: 278
< Last-Modified: Mon, 12 Dec 2016 09:02:59 GMT
< Connection: keep-alive
< ETag: "584e67c3-116"
< Accept-Ranges: bytes
<
<?php
/**
 * auto_reply
 *
 * @author Jang Joonho <jhjang1005@naver.com>
 * @copyright 2016 Jang Joonho
 * @license GPLv3
 */
include_once 'lib.php';

if (!is_installed())
    exit('Need to install! <a href="' . BASE_URL . 'install.php">Install</a>');
 Connection #0 to host xxx.xxx.xxx left intact

**Comment by plusfriendteam** [comment]
url 마지막에 / 제거해주시면 됩니다.
그리고 GET /keyboard 요청에 대한 응답이 잘못되었네요.

**Comment by webpl** [comment]
죄송합니다. 말씀해 주신 사항으로, '/' 를 제거하고 해보았으나,
동일하게 415 error 가 발생합니다.

좀더 구체적인 정보 부탁드립니다.
"그리고 GET /keyboard 요청에 대한 응답이 잘못되었네요."

응답이 잘못됐다는 것은, 요청 방식이 잘못됐다는 얘기신지요?
잘못됬다면 어떻게 정정을 해야 되는지요?

**Comment by plusfriendteam** [comment]
직접 curl로 요청했을 때 결과를 써주신것을 보면 Keyboard 타입의 오브젝트 형식과 전혀 다르고 json도 아닙니다.
문서의 [Home Keyboard API](https://github.com/plusfriend/auto_reply#51-home-keyboard-api)를 참고해주세요.

**Comment by humit0** [comment]
서버에 php가 설치되어 있나요?

**Comment by webpl** [comment]
네. php 설치되어 있습니다. json 도 필요한 것 같아서 설치를 했는데, 실마리를 못 찾겠습니다.

혹시, 가이드 문서가 있는지요?

**Comment by humit0** [comment]
@webpl https://github.com/humit0/kakao_auto_reply/issues 여기에 url을 남겨주시겠어요?
