### ISSUE TITLE
3.2 자동응답 서비스를 위한 템플릿생성.. 메시지미리보기이미지 아래의 템플릿 url이 어디있나요?

### ISSUE THREAD

**Issue by a0809765** [plusfriend/auto_reply#153]
3.2 자동응답 서비스를 위한 템플릿 생성

자동응답 서비스 구현 중 운영툴을 통해 생성 가능한 템플릿(이미지앨범/쿠폰/카탈로그)을 사용하고자 하는 경우 다음 단계에 따라 진행할 수 있습니다. 
1.운영툴의 전체메시지 > 메시지 작성 메뉴에서 작성을 원하는 메시지 타입을 선택합니다. 
2.1단계의 메시지 작성 완료 후, '임시저장' 버튼을 클릭하여 메시지를 임시저장합니다. 
3.운영툴의 전체메시지 > 메시지 목록 메뉴에서 임시저장한 메시지를 클릭합니다. 
4.메시지 미리보기 이미지 아래의 '템플릿 URL' 을 복사합니다. 

5.응답 메시지(링크)의 message_button 항목에서 url에 복사한 템플릿 URL을 사용합니다. 

•임시저장한 메시지를 변경하는 경우 템플릿 URL도 변경됩니다. 메시지를 변경하셨다면 변경된 템플릿 URL을 응답 메시지의 url 링크에도 수정하여 적용해 주세요

임시저장한 메시지를 클릭하고 메시지 미리보기 이미지 아래에 있다는데.. 저는 안보여서..없어졌나요?
아무리 봐도 URL 같은건 안보이는군요.

**Comment by plusfriendteam** [comment]
문서 업데이트가 되지 않았네요.
서비스 운영상의 문제점이 발견되어 지금은 위 기능을 제공하지 않고 있습니다.
내년 상반기에 새롭게 개편되는 플러스친구에서는 좀더 나은 방식으로 메세지 템플릿을 사용하실 수 있도록 제공 할 계획입니다.
조금만 기다려 주세요. ^^

**Comment by a0809765** [comment]
친절한 답변 감사합니다.
