### ISSUE TITLE
문의드립니다.

### ISSUE THREAD

**Issue by zxsw22** [plusfriend/auto_reply#154]
@고양이가정분양

앱URL은 무었이며 어떻게 하는지 전반적으로 모르겠습니다.

메뉴얼에는 첫페이지에도 어떻게 해야 할지 가르쳐 주고 있지 않아요

**Comment by plusfriendteam** [comment]
[카카오톡 옐로아이디 자동응답 API](http://search.daum.net/search?q=%EC%B9%B4%EC%B9%B4%EC%98%A4%ED%86%A1+%EC%98%90%EB%A1%9C%EC%95%84%EC%9D%B4%EB%94%94+%EC%9E%90%EB%8F%99%EC%9D%91%EB%8B%B5+API) 검색 결과를 보시면 어느정도 도움이 되실거 같아요.
우선 키워드형 자동응답을 사용해 보시길 추천드립니다.
