### ISSUE TITLE
keyboard API 에 대한 제안

### ISSUE THREAD

**Issue by 78lab** [plusfriend/auto_reply#155]
현재 keyboard API 는 user_key 를 받지 않고 일괄적으로 get 방식에 응답하도록 되어있는데

keyboard API 도 user_key 를 받을 수 있게 수정해주셨으면 합니다.

이는 처음 자동응답을 사용하는 유저와 기존 유저와 구분에서 다른 키보드 메뉴를 보여줄 수 있게 해주고 싶은데

현재는 불가능해보이네요.

향후 업데이트에서 꼭 반영해주셨으면 합니다.

감사합니다.

**Comment by plusfriendteam** [comment]
좋은 의견 감사드립니다.
건의 주신 기능에 대해 긍정적으로 검토 해 보도록 하겠습니다.^^
