### ISSUE TITLE
모든 설정은 끝났지만. 

### ISSUE THREAD

**Issue by ochooma** [plusfriend/auto_reply#156]
api 테스트 완료 되었습니다. 스크린샷 참조,

하지만 , 문자를 넣으면 아무 대답이 업고, 똑 같은 내용으로 만 답변이 나옵니다. 

저희 url은 http://indigoworld.mytory.kr 이고 엘로우 id는 @ok프린팅 입니다.

![2016-12-16 11 32 27](https://cloud.githubusercontent.com/assets/578224/21266165/321e325c-c3e8-11e6-951e-c934a539e101.png)
![2016-12-16 11 34 52](https://cloud.githubusercontent.com/assets/578224/21266188/48f6d038-c3e8-11e6-9fdb-bffac96db435.png)

**Comment by enjoyseo** [comment]
자세한 상황은 봐야 알겠지만, 위의 응답은 상담원과 일대일대화로 연결되었을때 나오는 메시지네요

**Comment by plusfriendteam** [comment]
@enjoyseo 님 말씀대로 1:1 대화로 메세지를 보내셨네요. (덧글 감사드려요!)
카카오톡 대화방 입력창에 1:1 버튼이 켜져 있는 상태로 메세지를 보내시면 옐로아이디 관리자센터 대화방으로 메세지가 전송됩니다. 확인해주세요.^^
