### ISSUE TITLE
관리자 페이지에서 버튼 추가 기능

### ISSUE THREAD

**Issue by ochooma** [plusfriend/auto_reply#157]
관리자 페이지에서 버튼추가를 해도 추가가 안됩니다.

config 에서 디버그 true 로 하고 실행 화면 스크린샷 올립니다.

도움 부탁드립니다. 좋은 자료도 너무 감사합니다. 
![2016-12-17 12 13 40](https://cloud.githubusercontent.com/assets/578224/21284047/008799ca-c453-11e6-92cb-33e73583fb87.png)

**Comment by webpl** [comment]
제가 등록한 415 이슈 건도, 상기 문제와 동일한 현상이 있습니다.
답변 부탁드립니다.

**Comment by plusfriendteam** [comment]
@ochooma 위와 같은 봇 제작 도구는 저희가 제공해 드린것이 아니라 구체적으로 어떤 문제인지 알 수가 없네요.
@webpl 님도 동일한 도구를 사용하신 것이라면 해당 도구 개발사에 문의 주셔야 할 거 같아요.
저희도 확인해볼 수 있게 어떤 도구인지 알려주시면 참고하도록 하겠습니다.

**Comment by webpl** [comment]
답변 감사합니다.
인터넷의 "카카오톡 응답 봇 만들기" http://humit.tistory.com/248 를 참고했습니다.
Plusfriend Team 에서 제공하는 봇 제작 도구에 대한 정보는 어디서 열람할 수 있는지요?
답변 부탁드립니다.
