### ISSUE TITLE
버튼 이상 관련

### ISSUE THREAD

**Issue by enjoyseo** [plusfriend/auto_reply#158]
안녕하세요~ @axa다이렉트 계정을 사용중입니다

자동응답 시나리오를 진행하다 생기는 일인데요. 
특정 폰에서(노트5) 어쩌다 한번씩 시나리오가 정상적으로 저희 로직을 타지 않고, 
그럴때마다 그 폰에서는 버튼이 3개가 아닌 2개씩 보여지는데요
어떤 현상일까요?

![kakaotalk_20161220_164325928](https://cloud.githubusercontent.com/assets/22783850/21374187/2f7989b0-c768-11e6-8b4c-d11027ee4967.jpg)

**Comment by yoojinCHOI** [comment]
안녕하세요.답변을드리려는것이 아니라. 저는 스타트업을 준비하고있는 초보개발자입니다. 우연히 axa에서 카카오톡 자동응답봇 개발한것을보고 우리도 도입했으면 좋겠다라는생각이 들어 만들어보려하는데 주언어가 php가아니라 시작하기가 쉽진않네요. 실례가안된다면 소스좀 받아볼수있을까요? 가능하다면 chldbwls87@gmail.com 이쪽으로 부탁드리겠습니다

**Comment by enjoyseo** [comment]
@yoojinCHOI  안녕하세요. 도움을 드리고 싶지만, 여기 보안 및 계약 조항 상 소스를 드릴 수가 없네요..

**Comment by enjoyseo** [comment]
흠 이거 혹시 카톡 버젼 최신화 유무에 따른 문제일수 있나요?

**Comment by humit0** [comment]
https://github.com/plusfriend/auto_reply#34-클라이언트-테스트
여기에 보시면 10분이 지나면 기존 대화 맥락이 expire된다고 하는데 이 부분 때문에 그럴 수도 있을 것 같네요.

**Comment by plusfriendteam** [comment]
@enjoyseo 해당 문제를 관계 부서에 전달하여 보고 있긴 합니다. 시간이 조금 걸리고 있는데 양해 부탁드립니다. (_ _) 
좀 더 구체적으로 문제 상황을 말씀해 주실 수 있으실까요? 
해당 시나리오에서 보여져야 할 버튼 전체가 다 보이나요?
맞다면, 첫 페이지에서 보여야 할 버튼이 다음 페이지로 넘어가서 보이나요?
아니라면, 문제가 재현되는 경우의 메세지에 Keyboard 값들을 제대로 넣으셨는지 확인은 하셨죠?("전원은 꽂으셨나요?" 정도의 확인이라 죄송합니다만 다시한번 확인을 부탁드려요.)
버튼 리스트가 제대로 넘어오고 있고 리스트 어디에도 나타나지 않는다면, 해당 버튼의 문구를 알려주세요.
혹은 재현 가능한 시나리오를 알려주시면 확인 해 보겠습니다.
문제가 발생하고 있는 디바이스의 모델명과 통신사, 펌웨어 버전, OS 버전, 카카오톡 버전을 정확히 알려주세요.

**Comment by enjoyseo** [comment]
넵!
일단 버튼이 3개씩 보여지고 초과되는 버튼은 다음으로 넘기면 보여져야 하는데 
2개씩 나오면서 이후 버튼이 다음으로 넘어가서 나오게 됩니다. (정상: 3개씩 4화면, 에러: 2개씩 6화면)

상황을 재현하기 힘든게 연속적으로 그런게 아니고 어쩌다 한번씩 나오는 특이 케이스라서요..

저희 시나리오에서 시작 후 -> 초기 메뉴에서 5번 모바일 서비스을 누른 후, ->  # 을 누르면 
이전화면으로 가게 세팅을 해놨는데, 정상적으로 로직을 타면 초기메뉴를 버튼형으로 보여주게 됩니다.
그런데 해당 케이스는 텍스트형으로 나옵니다. 그래서 11.종료 or 시작(저희시나리오 초기입력)으로 
초기화면을 다시 출력하도록 하면 위와 같은 현상이 나옵니다

현재 확인 된건 노트5하고 다른 안드로이드 기종이였는데요, 노트5 유저 같은 경우는 일단 카톡버전이 최신이 아니였다고 합니다. 업데이트 후 같은 증상이 나오는지는 확인이 아직 안됐습니다.

해당 케이스의 정보가 더 들어오면 공유해 드리겠습니다 
감사합니다^^
