### ISSUE TITLE
사용자 응답 받은 후 다시 응답받기(?)

### ISSUE THREAD

**Issue by KORJAHO** [plusfriend/auto_reply#159]
사용자 응답을 받은 후 다른 맨트를 한 후 다시 응답받는건 불가능한가요?
ex> 봇 : 이름을 입력해주세요.
사용자 : 홍길동
 봇 : [홍길동]이 맞으십니까? 맞으면 1번 틀리면 2번을 눌러주세요.
사용자 : 1
봇 : 전화번호를 입력해주세요.
사용자 : 01012345678
봇 : 완료되었습니다.
같은 건 불가능 할까여?

**Comment by plusfriendteam** [comment]
가능합니다.
