### ISSUE TITLE
Bot is not starting up

### ISSUE THREAD

**Issue by AterIgnis** [plusfriend/auto_reply#161]
I am still working on our bot for KakaoTalk. We have test version and developer versions and developer version could not be working 24/7. Version used for development testing (@scp) is stopped once more and not starting up (although startup tests are passing successfully):
![default](https://cloud.githubusercontent.com/assets/910422/21389548/5928b7ce-c793-11e6-8b53-b236d7508062.png)

Could you please help?

**Comment by plusfriendteam** [comment]
Check your server status. It's not responding.

**Comment by AterIgnis** [comment]
You can clearly see from attached image, that even optional tests are passing, how it may be that service is not working then?
If you meant it is not working at the current moment - yes, I described that abowe: this is development version and it is run locally and only when I am at work.

**Comment by plusfriendteam** [comment]
Would you reopen this issue when you run your application? I cannot check the problem if it's not running.
