### ISSUE TITLE
자동응답 API에 대해 제안하고 싶은 사항이 있습니다.

### ISSUE THREAD

**Issue by humit0** [plusfriend/auto_reply#164]
현재 [카카오톡 자동응답](https://github.com/humit0/kakao_auto_reply) 서비스를 제작하고 있는 개발자입니다.
서비스를 제작하고 기능을 추가하려는 과정에서 keyboard api에서 아래와 같은 기능이 추가가 되면 편할 것 같아 문의를 드리게 되었습니다.

지금은 keyborad api를 받을 때
```json
{
"type" : "buttons",
"buttons" : ["선택 1", "선택 2", "선택 3"]
}
```
과 같이 받고 있는데 아래와 같은 방식으로도 파싱을 해주실 수 있다면 좋을 것 같습니다.
```json
{
"type" : "buttons",
"buttons" : {"선택 1":"cnt1", "선택 2":"cnt2", "선택 3":"cnt3"}
}
```
그래서 카카오톡 상에서는 버튼이 '선택 1', '선택 2', '선택 3'과 같이 나타나고, '선택 1'을 눌렀을 때는 message를 호출할 때 content 값이 'cnt1'이 되도록 할 수 있었으면 좋겠습니다.

여러 depth에 해당하는 대화를 구축할 때 기존의 방식은 이전 대화 상태를 저장해놓고 그것을 기반으로 컨트롤을 했다면, 이 기능이 구현된다면 따로 이전 대화의 상태를 저장할 필요가 없이  _와 같은 구분자를 사용해서 요청한 내용을 통해서 이전에 어떤 상태였는지를 바로 알 수도 있어서 구현하는 부분에서 편리할 것 같아서 제안을 해봅니다.

**Comment by plusfriendteam** [comment]
문의 주신 방법은 많이 고민 해 보았던 문제입니다.
라벨과 데이터를 분리하여 얻을 수 있는 이점이 분명히 존재합니다.
하지만 둘의 차이로 인하여 복잡도가 높아지고 문제가 발생할 확률이 더 높아지게 됩니다.
물론 저희가 서비스를 운영하는데 드는 노력 또한 더더욱 높아지게 되지요.
결국 해당 기능을 제공해서 얻는것 보다 잃는게 더 크다고 판단하여 제공하지 않게 되었습니다.
하지만 실제로 서비스를 구현하시는 입장에서 필요하다고 하셨으니 한번 더 검토 해 보도록 하겠습니다.

**Comment by humit0** [comment]
확실히 문제가 생길 가능성이 높긴 하겠네요... 어쨌든 감사합니다!
