### ISSUE TITLE
한가지 질문에 여러 답변

### ISSUE THREAD

**Issue by KORJAHO** [plusfriend/auto_reply#166]
Ex)
User : 사진 주세요
카톡봇 : 사진 1
카톡봇 : 사진 2
카톡봇 : 사진 3
이런것도 구현이 가능할까요?

**Comment by plusfriendteam** [comment]
자동응답 API의 기본 구조는 문/답 입니다.
유저의 질문 하나에 답 하나만 할 수 있습니다.
따라서 문의 주신것 처럼 사진 1, 2, 3을 한번에 줄 수는 없습니다.
