### ISSUE TITLE
include 관련

### ISSUE THREAD

**Issue by KORJAHO** [plusfriend/auto_reply#167]
서버주소/message/index.php
파일 안에 include를 적어두고 다른 php파일을 연결시켜도 정상작동 하나요?

**Comment by plusfriendteam** [comment]
구현에 대한 문의에 대해서는 답변드리기가 힘들어요.
특히나 지금 질문 주신 건에 대해서는 저희가 제공해 드린 툴도 아니고 전혀 알 수가 없습니다.
