### ISSUE TITLE
메세지 이력을 받을 수 있을까요?

### ISSUE THREAD

**Issue by enjoyseo** [plusfriend/auto_reply#168]
안녕하세요 AXA다이렉트 계정을 사용중인데요

혹시 지난주에 저희가 고객에게 보낸 messages 이력(유저키, 메시지 등) 을 받을 수 있을까요?

확인 부탁드립니다
감사합니다

**Comment by plusfriendteam** [comment]
해당 내역은 제공이 불가합니다.
