### ISSUE TITLE
 Fail 415 : wrong keyboard initialization

### ISSUE THREAD

**Issue by nwsoft** [plusfriend/auto_reply#169]
앱 이름kakao_reply 정보수정 
앱 URLhttp://kakao.snwsoft.com API TEST 

Required*
Initialize Api test : Fail 415 : wrong keyboard initialization

Optional
Friend add Api test : OK 200
Friend block Api test : OK 200
Chatroom leave Api test : OK 200
앱 설명카카오톡 자동응답

설치까지는 완료 했는데 API 발급 페이지 에서 해당 오류를 뿜어내는군요 
설치 퍼미션은 755 로 했는데 문제가 있는것 같어서 일단 777로 하였습니다.

**Comment by humit0** [comment]
혹시 keyboard라는 이름의 폴더를 생성하셨나요?

**Comment by plusfriendteam** [comment]
@nwsoft 해당 issue는 여기가 아닌 https://github.com/humit0/kakao_auto_reply/issues
여기로 가서 문의주셔야 할 것 같네요. ^^ close 하겠습니다.
@humit0 옐로아이디 봇 생성기 만들어주셔서 감사합니다~!

**Comment by nwsoft** [comment]
??? ?? ???? ????  ???????

PirateK

2016. 12. 28. ?? 4:52 humit <notifications@github.com<mailto:notifications@github.com>> ??:


?? keyboard?? ??? ??? ???????

-
