### ISSUE TITLE
USER_KEY 관련 문의 드립니다.

### ISSUE THREAD

**Issue by mcvzone** [plusfriend/auto_reply#17]
안녕하세요.

API 내용 중 프로필 별로 USER_KEY  가 생성 된다고 되어있습니다.

저희 같은 경우 기존 플친의 USER_KEY 를 가지고 시나리오를 계속 유지해 나가는 방식인데,
이것이 API2.0 으로 전환되면서 새 프로필을 생성 하면, 기존 USER_KEY 의 매핑은 어떻게
해야 하는 것인지요?

**Comment by tttkt** [comment]
안녕하세요.
(구) 커스텀 봇 API를 통해 수집하신 user_key는 자동응답 API(v.2)의 user_key와 동일합니다. 그러나 만일 (구) 인증형 TMS를 이용해 user_key를 수집하신 경우라면, 기존에 사용하시던 user_key는 현재 API의 user_key와 다릅니다.
후자의 경우에 해당하신다면 아래의 방법을 통해 user_key 변경을 지원해드릴 수 있습니다.

1) 구버전 user_key를 발급하는 API를 자동응답 API로 변경 (구버전 API를 통해 새로운 구버전 user_key가 생성되지 않도록)
2) 기존에 보유중인 모든 user_key 데이터를 plusfriend_api@kakaocorp.com 을 통해 카카오로 전달
3) 카카오에서 구버전 user_key를 신버전 user_key로 변환하여 메일로 회신

*(구) 인증형 TMS API에서 제공되었던 user_key 기반 메시지 발송 기능은 카카오에서 새롭게 제공하는 ‘친구톡 API’를 통해 7월 중 적용 예정입니다.(현재는 전화번호 기반 발송을 지원하고 있습니다.) 변경 작업을 진행하시는 경우 이 점 참고 부탁드립니다.
