### ISSUE TITLE
이미지 url  - 404 not found

### ISSUE THREAD

**Issue by enjoyseo** [plusfriend/auto_reply#170]
안녕하세요~ @AXA다이렉트  입니다

고객들로 부터 이미지를 받는 부분이 있는데요.
일부 이미지 URL을 보면 없는 것들이 있습니다.
고객이 카톡측에 업로드를 하다 유실된 건가요, 아님 URL이 잘못 오는건가요?
이전 이력들을 보면 적게는 일 2~3건 많게는 20여건 정도 그런거 같네요

예 )
http://dn-m.talk.kakao.com/talkm/oWvb9OrPVT/fsa7rSNvAKz8A8Fi9H7LI1/i_ejk0pu6eoqrt.jpg
http://dn-m.talk.kakao.com/talkm/oWmUaBiRin/4fG03G0Wh4s2Nk94UEZux0/i_svakxla5r58v1.jpg

확인 부탁드립니다
감사합니다 ^^

**Comment by plusfriendteam** [comment]
현재는 20일간 보관 후 지워집니다.
업로드 중 실패 할 경우 메세지가 전송되지 않기 때문에 가장 유력한 원인은 보관기간 초과 후 요청이 아닐까 싶습니다.
보관기한이 지난 후 요청한 것이 아닌지 확인 부탁드립니다.

**Comment by enjoyseo** [comment]
안녕하세요~

일단 12월 말의 데이터라 기간은 초과하지 않았습니다.

저희 시나리오 에서 이미지를 받는 부분이 몇개 있는데, 보통 2 ~ 4개를 받습니다.  
위같은 케이스들을 보면 보통 2개의 이미지를 카톡에 등록하고 카톡측으로도 그 값을 받습니다. 
그런데 간혹 1개의 url은 있는데 1개의 url은 404가 뜨더군요
위 말씀대로라면 카톡으로 업로드는 성공 했는데, url값이 제대로 세팅이 안되는 문제인건가요?


확인 부탁드립니다
감사합니다^^

**Comment by enjoyseo** [comment]
추가로 아래 링크는 2016.12.31 23시48분쯤 TK1hUzoukSsM  유저가 이미지 등록을하여 
저희에게 넘어온 값들입니다
하나는 링크가 있으나 하나는 404가 뜹니다.

http://dn-m.talk.kakao.com/talkm/oWmSbUq25E/FrtBSWDr9KDiH19MTC0BK1/i_au9envzrtcmt.jpg
http://dn-m.talk.kakao.com/talkm/oWwl6QYrI2/Eak11L7kxRT14D3obJ3Oyk/i_uoag7nxzri761.jpg
