### ISSUE TITLE
버튼 대체 UI

### ISSUE THREAD

**Issue by seongkwang** [plusfriend/auto_reply#171]
안녕하세요.

 ![2016-12-30 1 24 59](https://cloud.githubusercontent.com/assets/2390924/21559647/68c927e8-ce93-11e6-9cc8-b2b714239844.png)

 자동응답 API 서비스에서 제공되는 버튼은 위와 같은 형식만 있는 것으로 알고 있었는 데, 일부 업체의 옐로아이디 계정에서 아래와 같은 버튼 UI를 제공하는 것을 발견했습니다. 아래 UI가 화면을 많이 가리지 않아 더 편리하고, submenu 같은 고급 기능도 제공하는 것 같아 이용해보고자 하는 데 문서에서 내용을 찾을 수 없어 문의드립니다. 아래와 같은 버튼 UI를 사용하려면 어떻게 해야하나요?

 답변 부탁드립니다.
 감사합니다.

![2016-12-30 1 22 46](https://cloud.githubusercontent.com/assets/2390924/21559634/19dec8ae-ce93-11e6-8d42-d5c6798cb7c0.png)

**Comment by plusfriendteam** [comment]
위 UI는 향후 제공 될 계획을 갖고 있습니다만 자동응답 API형으로 제공 될 계획은 아직 없습니다.
