### ISSUE TITLE
대화방에서 친구 추가 시 버튼 노출되지 않음

### ISSUE THREAD

**Issue by seongkwang** [plusfriend/auto_reply#173]
안녕하세요.

 열려있는 옐로아이디와의 대화방에서 친구 추가를 하는 경우 자동응답 기능이 활성화되지 않아 고객이 자동응답 기능이 제공됨을 인지하지 못하는 문제가 있습니다. 친구추가 감사메시지 하단에 자동응답 기능을 이용하시려면 방에서 나갔다 다시 들어오라는 문구를 추가하는 방법으로 workaround하고 있는 데 좋은 방법은 아닌 것 같습니다. 해당 사항 개선 계획이 있는 지 궁금합니다.

 답변 부탁드립니다.
 감사합니다.

**Comment by plusfriendteam** [comment]
일반적으로는 친구를 맺지 않은 상태에서 대화방으로 진입하는 경우는 잘 없는데, 어떤 경우인지 구체적인 재현 경로를 말씀해주시겠어요?

**Comment by enjoyseo** [comment]
@plusfriendteam 테스트하면 많이 생기는 경우같네요.

1. 테스터들이 방을 나가지 않고 차단 및 추가하는 경우
2. 대화방에서 친구차단만 하고 방을 나가지 않았다가 훗날 친구를 맺는 경우

**Comment by seongkwang** [comment]
알림톡으로 메시지 수신 후 친구추가 하는 상황입니다.

**Comment by plusfriendteam** [comment]
@seongkwang 카카오톡 앱 다음버전 업데이트에 처리 될 예정입니다.
