### ISSUE TITLE
자동응답 API 개발 관련

### ISSUE THREAD

**Issue by khs3141** [plusfriend/auto_reply#174]
현재 Microsoft Bot Framework를 사용하여 서비스를 계획중에 있습니다.
facebook, skype, telegram등의 메신저들을 지원하는데 자동응답 API도 
타 Framework로 확장되어 개발이 되면 좋을 것 같습니다.
관련 하여 개발 계획이 있으신지 문의 드립니다.
https://dev.botframework.com/

**Comment by plusfriendteam** [comment]
우선 지금 당장은 지원 계획이 (아직은) 없답니다. ^^;
향후 다양한 개발 플랫폼에서 편리하게 만들 수 있도록 노력 하겠습니다-!
