### ISSUE TITLE
response is not OK(200) 에러...

### ISSUE THREAD

**Issue by krquddnr37** [plusfriend/auto_reply#175]
keyboard랑 message 만 만들어도 기본적 응답이 된다 길래 일단 그 두개만
구성했는데..
api test 는 keyboard 에서 일단 ok 되게 했어요.

![sdfsdf](https://cloud.githubusercontent.com/assets/5886226/21561907/c405605e-ceb6-11e6-97a7-34bbe19f542b.png)

그리고 keyboard는 buttons 타입으로 했고,
message에서도 json 형태로 나타나게 했어용.

![aaass](https://cloud.githubusercontent.com/assets/5886226/21561959/3fe6b31c-ceb7-11e6-86a4-4c9ba52fe6e1.png)

근데 옐로아이디에서 버튼을 누르면 아래 같은 에러가 뜨네용..
message의 json 을 하나 만들어놔서 
어떤 버튼을 누르든 text test 라는 응답이 와야 할거 같은데..
뭐가 문제인걸까요?

![kakaotalk_20161230_172947227](https://cloud.githubusercontent.com/assets/5886226/21561993/9588ea74-ceb7-11e6-9b19-09b746059f0c.jpg)

**Comment by choong2** [comment]
해결하셨나요?
