### ISSUE TITLE
단체 채팅방이나 오픈 채팅방 문의

### ISSUE THREAD

**Issue by KORJAHO** [plusfriend/auto_reply#177]
단체 채팅방 또는 오픈 채팅방에서 사용 가능한 자동응답은 없나요?
오픈채팅방에 투표 기능도 추가 됬으면 좋겠습니다.

**Comment by plusfriendteam** [comment]
단체 채팅방 혹은 오픈 채팅방에서의 자동응답은 현재는 제공되고 있지 않습니다.
저도 빨리 제공 해 드릴 수 있었으면 좋겠네요. ^^
