### ISSUE TITLE
5.3, 5.4의 Response 형식에 관해

### ISSUE THREAD

**Issue by JungWinter** [plusfriend/auto_reply#178]
친구 추가/차단, 채팅방 나가기에 대한 명세를 보면
- **Response**

| http status code | code | message | comment |
| ---------------- | ---- | ------- | ------- |
| 200 | 0 | SUCCESS | 정상 응답 |

라고 되어있는데 여기서 `code`, `message`와 `comment`가 의미하는게 무엇인가요?
```
{
    "code": 0,
    "message": "SUCCESS",
    "comment": "정상 응답"
}
```
이런식의 json타입으로 응답해줘야 한다는 것 인가요?

**Comment by plusfriendteam** [comment]
네, 그렇게 주시면 됩니다. ^^
참고로 구 시스템과의 호환을 위해 존재했었던건데 곧 deprecated 예정입니다.
