### ISSUE TITLE
요금체계 문의

### ISSUE THREAD

**Issue by jbb100** [plusfriend/auto_reply#179]
안녕하세요.

챗봇 운영을 염두에 두고 옐로우 아이디 자동응답 API를 검토중인데요.

호출 건수에 따른 과금 정책이 있는지 궁금합니다.

만약 본 서비스 외에 챗봇을 위하여 존재하는별도의 서비스가 있다면, 

안내 부탁드리겠습니다.

감사합니다.

**Comment by plusfriendteam** [comment]
현재는 구체적인 과금정책은 없습니다.
