### ISSUE TITLE
자동응답 기능관련하여 문의드립니다.

### ISSUE THREAD

**Issue by keirapark** [plusfriend/auto_reply#18]
안녕하세요, 호텔엔조이 마케팅팀의 박민지 매니저라고 합니다.
자동응답 API 개발작업을 하려고 하는데요, 

앞서 한 가지 문의드릴 점이 있습니다.
자동응답 API가 적용된 타 업체 사례를 보니 1:1 상담 기능은 동시에 사용이 불가한 것 같은데
맞는지요?

현재 당사는 카카오톡 1:1 상담 관리자를 두어 별도로 상담 운영을 하고 있는데
자동응답을 적용하게 되면 더이상 1:1 상담은 따로 못하는 건가요? 

관련하여 회신 주시면 감사하겠습니다.

**Comment by jjuakim** [comment]
아닙니다 ~ 일대일채팅과 기능과 자동응답 기능은 독립적으로 두개 모두 사용 할 수있습니다.

![image](https://cloud.githubusercontent.com/assets/2723640/15847595/307ac018-2cc2-11e6-95a2-049ac7ede087.png)

채팅기능을 사용할 경우, 자동응답키워드 오른 상단에 1:1 버튼이 생기며,
해당 버튼을 누르면 채팅을 할 수있는 키보드로 전환됩니다.
