### ISSUE TITLE
유저가 데스크탑에서 메세지를 보낼 때 이슈

### ISSUE THREAD

**Issue by qudrnr1479** [plusfriend/auto_reply#180]
안녕하세요 @오버인포 라는 옐로아이디를 사용하고있는 개발자입니다.
다름이 아니고, 모바일에서는 채팅바에 1:1 버튼 활성/비활성화를 통해서 일대일 대화 또는 자동응답 변경이 가능하던데, 데스크탑 버전에서는 지원을 하지 않는것인지 제가 잘 모르고있는지 분간이 되지않아 문의를 드립니다.

혹, 지원을 하지않고있다면 언제쯤 지원할 예정인지에 대해서도 알려주시면 좋겠습니다.

항상 서비스를 잘 쓰고있습니다.
감사합니다.

**Comment by plusfriendteam** [comment]
아직은 지원하지 않고 있어요.
지원에 대한 계획은 있으나 일정을 명확히 말씀드리기 어려운 점 이해해주실거죠? ㅠㅠ
