### ISSUE TITLE
url scheme좀 알 수 있을까요?

### ISSUE THREAD

**Issue by rlagurdls** [plusfriend/auto_reply#181]
안녕하세요.

옐로아이디 관리자의
App에 대한 URL Scheme을 알고싶습니다.

사용 목적은 모바일에서의, html link를 통한 앱호출입니다.

**Comment by plusfriendteam** [comment]
옐로아이디 관리자앱을 실행시킬 수 있는 앱 스킴은 공식적으로 제공하고 있지 않습니다.
