### ISSUE TITLE
Initialize Api test : Fail 415 : wrong keyboard initialization

### ISSUE THREAD

**Issue by stanley-kim** [plusfriend/auto_reply#182]
안녕하세요
새로운 자동응답 API 구현을 하고 있는 중입니다.

먼저 자동응답 API의 API test를 눌렀는데 아래와 같은 메세지가 뜹니다.
저의 웹서버 주소는  http://c2kws015.cafe24.com  입니다.
----------------------------------
Required*
Initialize Api test : Fail 415 : wrong keyboard initialization
Optional
Friend add Api test : Fail 404
Friend block Api test : Fail 405
Chatroom leave Api test : Fail 405
-------------------------------------------------

Fail 415 가 어떤 메세지인지 궁금합니다.
감사합니다.

**Comment by plusfriendteam** [comment]
필수로 제공해주셔야 하는 GET /keyboard API에서 실패를 하였네요.
문서를 한번 더 읽어보고 하셔야 할 거 같아요. ^^;
