### ISSUE TITLE
1대1 대화 메세지 발송 API 문의드립니다

### ISSUE THREAD

**Issue by heoseok** [plusfriend/auto_reply#183]
안녕하세요.

현재 옐로우아이디의 자동응답 기능을 사용하여 개발을 진행중입니다.

개발중 자동응답 만으로 응대가 불가능한 경우,
별도로 API를 활용하여 사용자에게 메세지를 전달하고자 하는데
별도로 공개된 API가 없는 것 같아 문의 드립니다.

기존의 자동응답 기능에서는 message로 요청이 들어오는 경우,
timeout이 걸려있어 일정시간내에 응답하지 못하는 경우에
오류메세지를 출력하는 걸로 보이는데
이 timeout을 명시적으로 조절하거나
관리자가 API호출을 통해 직접 답변을 하는 방법은 없는 것인가요?

검색해본 결과 상담톡을 이용하는 경우에는 메세지 발송 API사용이 가능한 것으로 보이는데,
별도의 리셀러를 통한 문의밖에 안내사항이 없어서
구체적으로 어떤 기능들을 사용가능한지 알고 싶은데 공개된 정보는 더 없는지 궁금합니다.

**Comment by plusfriendteam** [comment]
메세지 발송을 위한 공개된 API는 없습니다.
구체적인 것에 대해서는 [카카오톡 비즈메세지](https://github.com/plusfriend/auto_reply/issues/183) 페이지를 방문해보시면 됩니다.
각 페이지에 [상품소개서](https://bizmessage.kakao.com/assets/file/bizchat.pdf)가 링크 되어 있으니 참고 부탁드립니다.
