### ISSUE TITLE
신규 플러스친구 관련 문의드립니다

### ISSUE THREAD

**Issue by enjoyseo** [plusfriend/auto_reply#184]
안녕하세요~

곧 신규 버전이 도입되는거로 알고 있는데요
스마트채팅에서 API형이 있는데, 기존 API 자동응답의 앱 URL을 등록해서 사용하면 되는건가요?
추가로 마이그레이션이 되면 기존 친구들도 모두 이관 되는건가요?

확인 부탁드립니다
감사합니다^^

**Comment by plusfriendteam** [comment]
기존과 동일하게 쓰시면 됩니다.
친구들 역시 그대로 변함없이 이관됩니다.
