### ISSUE TITLE
신규 플러스친구 메시지 문의

### ISSUE THREAD

**Issue by enjoyseo** [plusfriend/auto_reply#185]
안녕하세요~ 

추가로 하나 더 문의 드립니다
현재 자동응답 api 에서 카탈로그 메시지를 링크로 보내서 이용자가 볼 수 있게 사용을 하고 있습니다 
(예 :   https://plus-talk.kakao.com/plus/mini/page/v3/204955.html   )
기존의 메시지는 더이상 사용이 불가능 하다고 알고 있는데요
그렇다면 저 url 도 신규 로 전환시 이용이 안되는 건가요?

확인 부탁드립니다
감사합니다 ^^

**Comment by plusfriendteam** [comment]
지금 사용하고 계신것과 동일한 타입의 카탈로그 메세지를 새로운 플러스친구에서는 지원하지 않을 예정입니다.
따라서 지금 예를 들어주신 url은 사용하지 못하실거에요.
카탈로그 대신 다른 방식으로 컨텐츠를 작성할 수 있게 준비중이며 해당 페이지도 url을 제공할 예정입니다.
