### ISSUE TITLE
php 파일입출력

### ISSUE THREAD

**Issue by disasterpiec** [plusfriend/auto_reply#186]
`<?php
// content : X
use \kakao\Msg;
use \kakao\Msg\Message;
use \kakao\Keyboard;

$xclass = ["[X226]","[X234]","[X330]","[X332]","[X349]","[X353]","[X426]","[X428]","[X429]","[X430]","[X512]","[X513]","[X515]","[X519]"];

$yoil = date("w");
$time = date("Gi");
if($yoil=='0') $yoil="일";
if($yoil==1) $yoil="월";
if($yoil==2) $yoil="화";
if($yoil==3) $yoil="수";
if($yoil==4) $yoil="목";
if($yoil==5) $yoil="금";
if($yoil==6) $yoil="토";

$fp=fopen("ftp://sogangtime:(FTP비번)@sogangtime.dothome.co.kr/html/resource/msg/x.txt","r");

while($classinfo = fscanf($fp, "%s %s~%s %[^\n]s"))
{
	list($yoil1,$xtime1,$xtime2,$xclass1)=$classinfo;
	
	if($yoil1==$yoil)
	{
		
		if($time>=$xtime1&&$time<=$xtime2)
			{

				$key = array_search($xclass1, $xclass);
				array_splice($xclass, $key, 1);
			}

	}
}
fclose($fp);
$xclassall=implode(" ",$xclass);

$time = date("G시 i분");

echo new Msg(
	new Message(
		"{$yoil} {$time} 현재 비어있는 강의실은 {$xclassall} 입니다.",
		NULL,
		NULL
	),
	TRUE
);'
파일 입출력을 이용해서 나타 내려고 하는데요 계속 fopen으로 안열리는데 카톡 api에서는 지원안하는 기능인가요? PHP를 기반으로 해서 상관없을텐데;

가능하시다면 저 파일이 왜 안열리는지 알려주실수있나요?

저 url 주소로 들어가면 txt파일은 잘열립니다.

**Comment by plusfriendteam** [comment]
특정 언어/프레임웍에서의 개발에 관한 질문은 받지 않고 있어요.
그리고 파일 오픈과 옐로아이디 자동응답 API는 큰 관련이 없답니다.
식당을 예로 들자면 POST /message를 주방으로 주문서를 전송하는 것에 비유할 수 있겠네요.
주방으로 손님의 주문을 전달해 드리고 주문한 음식을 받아 테이블로 전달하는게 옐로아이디 자동응답 API의 역할입니다.
주방 안에서의 일은 관여하지 않아요. ^^
