### ISSUE TITLE
자동 응답 중첩 가능성 여부

### ISSUE THREAD

**Issue by qudrnr1479** [plusfriend/auto_reply#187]
안녕하세요, 옐로아이디로 자동응답을 개발하고 있는 @오버인포 개발자입니다.

일전에 여쭤본 질문에 친절히 답해주셔서 감사합니다.

이번에 물어 볼 질문은 유저가 메세지 1개를 보냈을때
자동응답 쪽에서 2개의 메세지를 보낼 수 있는지 여쭤보고싶습니다.

감사합니다.

**Comment by plusfriendteam** [comment]
말 풍선 두개에 해당하는 메세지를 보내는 것은 현재는 지원하지 않고 있습니다.
말풍선 여러개로 내용을 나누어서 보낼 수 있도록 방안을 생각 해 보고 있긴 하지만,
구체적인 지원 일정에 대해서는 말씀드리기가 힘든점 양해해주세요~!
