### ISSUE TITLE
응답이 오지 않는 현상

### ISSUE THREAD

**Issue by samko635** [plusfriend/auto_reply#188]
링크를 타고 이니스프리 옐로아이디 계정으로 들어온 사용자가 시작키워드를 눌렀는데 아무런 반응이 오지 않는 경우가 발견되었습니다. 약 30분간 어떤 반응도 오지 않았다고 합니다.
1월 11일 오전에 발생한 현상으로 극히 일부 사용자만 겪은 이슈로 보입니다. 
혹시 해당 시간에 비슷한 오류건 접수된것이 있었나요? 
있었다면 원인 공유 부탁드립니다. 
감사합니다.

**Comment by plusfriendteam** [comment]
로그를 확인 해 보니 10시 49분 13초, 11시 16분 51초, 14시 6분 57초, 20시 44분 19초에 요청에 대한 타임아웃이 있었네요.
요청 건수는 각 시간별로 두세건정도 되구요.
원인은 위에 말씀드렸다시피 request timeoout입니다.
