### ISSUE TITLE
Time out 시간 연장

### ISSUE THREAD

**Issue by jh3282** [plusfriend/auto_reply#189]
안녕하세요.

@Shop for shoes 입니다.
 Time out 시간이 10-> 5초로 변경 된 이후에 기존 서비스에서 오류를 여러번 표출하였습니다.
그래서 시스템 구조를 변경하여 Response가 빨리나오게 개선을 하였습니다. 
해당건은 사내 시스템이기 때문에, 개선이 가능하였지만, 
기획중인 새로운 기능은 업무 특성상 사외 시스템에서 웹서비스로 실시간으로 데이터를 받아와서 카카오톡에 보내줘야하기때문에,Time Out 시간이 너무 짧게 느껴집니다.

TimeOut을 을 기존대로 10초로 변경은 가능한지,
해당 계정에 대해서만 Timeout 설정 가능한지 확인 부탁드립니다.

**Comment by plusfriendteam** [comment]
전체적, 혹은 개별적으로 타임아웃 시간 연장은 불가합니다.
자동응답 시스템의 안정적 운영과 더 나은 사용자 경험 제공을 위해서입니다.
서비스 제공하시는 입장에서 현재의 request-response 구조가 어려움이 있음을 잘 알고 있습니다.
해당 문제 해결을 위해 개선중입니다만 구체적 일정에 대해서는 말씀드리기 어려운 점 양해 부탁드립니다.^^
