### ISSUE TITLE
API TEST 문의 드립니다. 

### ISSUE THREAD

**Issue by com2best** [plusfriend/auto_reply#19]
URL: https://wefund.co.kr:8443/

Required*
Initialize Api test : Fail 500 : wrong keyboard initialization
Optional
Friend add Api test : Fail 500 : General SSLEngine problem
Friend block Api test : Fail 500 : General SSLEngine problem
Chatroom leave Api test : Fail 500 : General SSLEngine problem

API 테스트하면 위와 같은 에러 메세지가 출력 됩니다. 
크롬 브라우저에서 https://www.wefund.co.kr:8443/keyboard 하면 정상 동작 합니다. 
SLL 인증서는 StartCom 에서 발급 했습니다. 
혹시 SSL 관련 오류라서 혹시 StartCom이 인증된 CA로 등록이 안되있어서 그런 건가요?

도와주세요~

**Comment by suya55** [comment]
@com2best  #1 이슈를 확인해주세요.
