### ISSUE TITLE
API TEST 정상적으로 다 끝내고 서비스실행하는데 이렇게 에러가뜹니다.

### ISSUE THREAD

**Issue by socialearning** [plusfriend/auto_reply#190]
안녕이라는 버튼을 누르면 자동응답하도록 API 설정을 해놨는데
해당 프로필의 자동응답 시스템이 응답을 하지 않습니다. 

라고 뜹니다. 계정아이디는 mrmention@naver.com 입니다.
프로필명 : 미스터멘션

kakaochat-mrmention.c9users.io/kakao_auto_reply_c9/
해당 서버에서 테스트도 다 끝낸상태입니다.

![kakaotalk_20170119_005735934](https://cloud.githubusercontent.com/assets/8294302/22071723/65996498-dde3-11e6-848d-48f2790aab30.jpg)

![2](https://cloud.githubusercontent.com/assets/8294302/22071583/e92a412a-dde2-11e6-8a4b-f281833393cf.JPG)

![3](https://cloud.githubusercontent.com/assets/8294302/22071671/35ea07ac-dde3-11e6-8fb8-54d52e05b78c.JPG)

**Comment by plusfriendteam** [comment]
현재 응답을 정상적으로 하고 있지 않네요.
캠풔해주신 에러메세지 내용으로 보건데 5초 타임아웃에 걸린 것 같습니다.

**Comment by socialearning** [comment]
http://green-narae.kr/kakao_auto_reply/keyboard.php 여기로 설정해놓았습니다. 확인부탁드립니다.

**Comment by plusfriendteam** [comment]
메세지 응답이 잘못됐습니다.
문서를 확인하시기 바랍니다.
