### ISSUE TITLE
TEST문의

### ISSUE THREAD

**Issue by JonghyeokPark** [plusfriend/auto_reply#191]
카카오톡 봇 프로필명은 @vldb_bot입니다.
TEST가 계속 통과되지 않아서 무슨 문제인지 궁금합니다.
방화벽 설정, 그리고 웹에서 JSON형식 뜨는 것 확인했습니다.

감사합니다.

**Comment by plusfriendteam** [comment]
GET /keyboard 요청에 응답을 하지 않네요.
문서를 다시 읽어보시면 좋겠네요.
