### ISSUE TITLE
자동응답이 먼저 말을 거는 상황에 대해

### ISSUE THREAD

**Issue by wuhibbuka04** [plusfriend/auto_reply#192]
안녕하세요, 

사용자가 1:1 대화에서 자동응답 모드로 들어오면 자동응답 API가 먼저 사용자에게 사용방법을 안내하도록 만들고 싶은데요,
자동응답이 먼저 말을 거는건 안되나요?

**Comment by plusfriendteam** [comment]
말씀하신 기능을 구현하기 위해서는 [카카오톡 비즈메세지](https://bizmessage.kakao.com)를 이용하셔야 합니다.
