### ISSUE TITLE
[문의] 휴대폰 번호 변경된 사용자에 대한 인지여부

### ISSUE THREAD

**Issue by samko635** [plusfriend/auto_reply#195]
이슈는 아니나 문의드립니다.
현재 사용 기기는 그대로이고 사용자의 번호만 변경된 경우 카카오톡에서 번호가 바뀐것을 인지가 가능한가요? 번호만 바뀐 경우는 카카오톡 챗방이 유지되서 챗방 아이디는 변경이 되지 않는듯한데.. 번호만 바뀐 걸 알 수 있는 방법이 카카오에 존재하는지 알고싶어서요..

가능하다면 어떤 API로 확인이 가능할까요?

**Comment by plusfriendteam** [comment]
사용자의 전화번호 변경 여부에 대한 정보는 확인 불가합니다.
