### ISSUE TITLE
자동응답 관련 문의 드립니다

### ISSUE THREAD

**Issue by moonkipark** [plusfriend/auto_reply#196]
문의 내용은요 
제가 상황에 따른 자동응답 서비스 관련 Api 부분을 개발하고 있는데요
엘로우아이디 채팅창안에서 특정 문자 또는 버튼 입력시 
해당 문자 출력을 진행에 성공했습니다.
하지만 제가 정말 구현하고 싶은것은 자동적으로 엘로우아이디 채팅창안에서 특정 입력없이
상황에 따른 문자 출력을 진행하고 싶은 것입니다. 
이러한 진행을 위해서는 아마 제가 만든 웹서버에 특정 request가 들어가야겠죠?
그럼 여기서 질문입니다 그럼 제가 만든 웹서버에 특정 request를 요청하면 
엘로우아이디에서 사용자에게 상황에 따른 문자 출력을 자동적으로 즉 사용자 입력없이
진행할 수 있는지 여부에 대해 확인하고 싶습니다

**Comment by qudrnr1479** [comment]
이 부분은 저도 되게 궁금한데 답변을 공유해주실 수 있으신가요?!

**Comment by moonkipark** [comment]
네 공유해드리겠습니다 
제 생각에는 아마 카카오톡 비즈니스? 이쪽부분에 접근해야 해결가능할 것 같긴한데 
운영자님의 답변을 일단 기다리고 있습니다

**Comment by plusfriendteam** [comment]
@moonkipark 정답! [카카오톡 비즈메세지](https://bizmessage.kakao.com)를 이용하시면 구현 가능합니다.

**Comment by moonkipark** [comment]
방금 카카오톡 비즈메세지 상담을 받았는데요 
어떤 특정 정보에 관해서만 개인이 개인한테 전송이 갈 수 있도록 되어있더라구요 
제 3자한테 정보 발송은 정보통신법률 쪽에 의거하여 안된다고 하더라구요 ... 
요금은 한달에 만원? 건당 8원씩이라 들었습니다 
제 기억을 토대로 글 남겨봅니다
