### ISSUE TITLE
https가 아니면 안되는 건가요

### ISSUE THREAD

**Issue by JihoonNa** [plusfriend/auto_reply#197]

**Comment by JihoonNa** [comment]
문서에는 https를 권장한다고 되어있던데, http로 요청하면 아예 안되는 건가요?

**Comment by qudrnr1479** [comment]
저는 https 가 아니지만 잘 되고있는 듯 합니다.

**Comment by plusfriendteam** [comment]
@qudrnr1479 님이 언급해주신 바와 같이 https를 '권장' 할 뿐 반드시 필요한 것은 아닙니다.
