### ISSUE TITLE
응답 단톡방 자동 공유

### ISSUE THREAD

**Issue by qudrnr1479** [plusfriend/auto_reply#198]
안녕하세요, @오버인포 개발자입니다.

또, 이렇게 궁금한 점이 있어 찾아 뵙게되었습니다.

다름이 아니고, 유저로 받은 채팅에 대한 응답을 수동적으로 공유하는 것이 아닌
자동적으로 단톡방에 공유도록 유도(?)하거나 가이드 하는 방법이 존재하는지 궁금합니다.
혹여, 존재한다면 어떻게 해야하는지 알려주시면 감사하겠습니다.

**Comment by plusfriendteam** [comment]
안타깝게도 지금은 1:1 채팅만 지원하고 있답니다. ^^
