### ISSUE TITLE
KAKAO Yellowid - API test : wrong keyboard initialization

### ISSUE THREAD

**Issue by ejjang** [plusfriend/auto_reply#199]
카카오 옐로아이디에서 API 자동 응답 테스트를 하면 아래와 같이 415 error 가 발생합니다. 

프로필 :ejjang 
   
URL :  https://test-for-kakao-api.mybluemix.net/ 

Initialize Api test : Fail 415 : wrong keyboard initialization
Optional
Friend add Api test : Fail 404
Friend block Api test : Fail 404
Chatroom leave Api test : Fail 404

**Comment by plusfriendteam** [comment]
[문서](https://github.com/plusfriend/auto_reply/blob/master/README.md)를 참고해주세요.
