### ISSUE TITLE
자동응답 API의 잘못된 응답 횟수가 초가되어 앱이 차단 상태로 변경되었습니다.

### ISSUE THREAD

**Issue by nupamore** [plusfriend/auto_reply#2]
서버로그는 정상이고, 카톡알림도 오지 않았는데 바로 차단 상태로 빠지는 상황입니다.
자동요청이 굉장히 많이 들어오긴 하는데 혹시 요청제한같은게 걸려있나요?
정상적으로 response해주고 있는데 자꾸 차단되서 계속 다시 켜주고 있습니다..

**Comment by suya55** [comment]
@nupamore 이슈는 해결하셨나요? 정상적 response 중에 간간히 오류가 나고 계실것 같습니다. 네트웍 상태가 좋지 않았다거나 응답시간이 너무 느린 리퀘스트들이 생겼었다거나. 
그렇게 실패되는 request가 일 100~300건이 넘어가게 되면 카카오 서버는 유저의 서버가 오류인것으로 판단하여 자동적으로 봇을 내리게 됩니다.

**Comment by nupamore** [comment]
@suya55 네 방금 해결했습니다 ㄷㄷ
img.url 에 null값이 들어오는게 문제였습니다. 요청중에 0.1%만 발생하는거라 찾기가 힘들었네요 ㅠㅠ 왜 밤에 많이 발생하나 했더니 오류가 초과되어 1번만으로 내려가기 때문인가보네요. 답변해주셔서 감사합니다!
