### ISSUE TITLE
api테스트 부분

### ISSUE THREAD

**Issue by m3pop2002** [plusfriend/auto_reply#200]
엘로우 아이디 api테스트를 하면 php만 200응답이고 다른 형식파일들은

에러 Initialize Api test : Fail 415 : wrong keyboard initialization 라고 나온는데요

텔넷으로 접근해서 curl 명령으로 .asp .json 파일을 검색하면 결과가 리턴됩니다

파일을 php만 해야 하나요 
예) 실패메세지
https://www.kkangsangjo.com:41247/keyboard.asp

성공메세지
https://www.kkangsangjo.com:41247/keyboard.php

텔넷으로 확인한 메세지
$ curl -XGET 'https://www.kkangsangjo.com:41247/keyboard.asp'
{
"type" : "buttons",
"buttons" : ["선택 1", "선택 2", "선택 3"]

**Comment by plusfriendteam** [comment]
자동응답 api 개발을 위하여 언어나 플랫폼 등을 따로 제한하지는 않습니다. 
바꿔 말하면 어떤걸로 개발하셔도 상관 없습니다.
[문서](https://github.com/plusfriend/auto_reply/blob/master/README.md)에 정의된 내용만 구현해주시면 됩니다.
