### ISSUE TITLE
[긴급장애]키보드 입력창이 노출이 안되고 있습니다.

### ISSUE THREAD

**Issue by ollehtv** [plusfriend/auto_reply#201]
프로필 @올레tv   대화창 진입시 키보드 입력창이 노출이 안되고 홈으로 가기 홈버튼만 노출되고 있습니다.

현재 서비스 장애가 발생하고 있으니 긴급하게 확인 부탁합니다.

**Comment by plusfriendteam** [comment]
@ollehtv 인증서 만료된거 같은데 확인해보시겠어요?
