### ISSUE TITLE
설정 문의입니다.

### ISSUE THREAD

**Issue by uig2197** [plusfriend/auto_reply#202]
자동 API 설정중 아래와 같은 오류가 생겨서 문의합니다.

Initialize Api test : Fail 415 : wrong keyboard initialization

해당 부분 어떻게 대응해야 할지 문의합니다.

**Comment by plusfriendteam** [comment]
GET /keyboard 요청에 실패한 경우입니다.
[문서](https://github.com/plusfriend/auto_reply/blob/master/README.md)를 참고해보세요.
