### ISSUE TITLE
Photo 이미지의 위치를 바꿀 수 없나요?

### ISSUE THREAD

**Issue by wuhibbuka04** [plusfriend/auto_reply#204]
안녕하세요, 자동응답 API로 이미지를 전달하는 부분을 구현하고 있는데요

이미지가 반드시 텍스트 밑에 고정된 크기로 나타나는 것을 확인 하였습니다.

1. 이미지가 텍스트 위나 텍스트 사이에 위치하도록 설정할 수 있나요?
2. 이미지는 확대가 되지 않는데 혹시 확대할 수 있나요?
3. 이미지를 저장하거나 복사할 수 있나요?
위 처럼 이미지를 자유롭게 이용하고 싶은데 가능한지 궁금합니다

**Comment by plusfriendteam** [comment]
현재는 지원하고 있지 않습니다.
향후 지원할 수 있도록 계획중입니다.
