### ISSUE TITLE
User 에게 메세지 보내기

### ISSUE THREAD

**Issue by hjjo** [plusfriend/auto_reply#205]
안녕하세요.

제가 만들고 있는 자동응답 시스템은 예약시스템인데
예약 후에 예약 시간에 도달하면 사용자에게 알려줄 수 있는 방법이 있나요?

다시 말하면, 앱이 사용자에게 메세지를 보내는게 가능한가요?

**Comment by plusfriendteam** [comment]
[카카오톡 비즈메세지](https://bizmessage.kakao.com)를 이용하시면 구현하실 수 있습니다.
