### ISSUE TITLE
플러스친구 스마트채팅 API형 키보드 미노출

### ISSUE THREAD

**Issue by nemusheewon** [plusfriend/auto_reply#206]
안녕하세요. 네무스텍 정희원입니다. 

고객사들을 지원하기 위해서 테스트용으로 사용하는 채널에 키보드가 노출되지 않아서 문의 드립니다. 

프로필: 네무스New(@bot_admin3) 

플러스친구이고 현재 스마트 채팅으로 연동되어 있습니다. 
API 테스트 시에는 정상적 통화합니다. 

그런데 서비스 시작하면 주기적으로 들어와야 하는 keyborad api 호출되고 있지 않습니다. 

확인 부탁 드립니다.

**Comment by plusfriendteam** [comment]
비정상적인 데이터가 있었네요. 이젠 잘 되실거라 믿습니다.

**Comment by nemusheewon** [comment]
비정상적인 데이터라고 함은 어떤 것을 이야기하시는 것인가요? 
저희가 응답을 잘못 전달한 부분이 있다면 개선할 필요가 있을 것 같습니다.

**Comment by plusfriendteam** [comment]
저희쪽 버그였습니다. ^^; 문제 없으시다면 이슈 닫을게요~!
