### ISSUE TITLE
API test : wrong keyboard initialization 가뜨는데요

### ISSUE THREAD

**Issue by hihk** [plusfriend/auto_reply#207]
id : 대신it 
앱이름 : 자동응답_키워드

https://beta.daishin.com/kakaopi/keyboard.ds

json형태로 버튼구성하는 키보드 api 를 만든후
앱 url 에 등록하였는데 다음처럼 결과가 뜨네요 ~ 
혹시 어떤점이 잘못된건지 알수 있을까요

Required*
Initialize Api test : Fail 415 : wrong keyboard initialization
Optional
Friend add Api test : OK 200
Friend block Api test : Fail 405
Chatroom leave Api test : Fail 405

개별적으로 postman 같은걸로 send해보면
reponse가 형식대로 잘오는거 같은데 확인부탁드려요

**Comment by plusfriendteam** [comment]
GET /keyboard 구현하지 않으셨네요. /keyboard.ds가 아니라 /keyboard로 요청이 들어갑니다.
더 자세한 사항은 [문서](https://github.com/plusfriend/auto_reply/blob/master/README.md)를 참고해주세요.

**Comment by hihk** [comment]
다른 개발자들의 레퍼런스를 보면 확장자를 쓰고도 
앱url 테스트가 성공하는 경우도 있던데요 ~
https://github.com/plusfriend/auto_reply/issues/200
