### ISSUE TITLE
Response Code 관련해서 문의드립니다.

### ISSUE THREAD

**Issue by hihk** [plusfriend/auto_reply#208]
https://github.com/plusfriend/auto_reply
에 보면 8. Response Code가 있는데요 

이게 고객사가 코드에 따른 상태를 참고하는 용도인가요? 
아니면 별도로 특정에러가 났을때 
카카오톡에 보내줘야 하는코드인건가요? 

만약 별도 처리를 할 경우 
Error Response 코드에 기재되어 있지 않은 
 404 / 403 등의 에러일 경우는 어찌해야할지? 
헷갈려서 문의드립니다. 감사합니다~

**Comment by plusfriendteam** [comment]
언급하신 코드들은 카카오톡 자동응답 서버에서 에러를 리턴 할 때 사용하는 코드들입니다.
하지만 현재는 카카오톡 자동응답 서버로 request를 할 수 없기 때문에 해당 코드들에 대한 설명은 무시하셔도 됩니다.
