### ISSUE TITLE
API형 자동응답 질문입니다. 

### ISSUE THREAD

**Issue by moomin7575** [plusfriend/auto_reply#209]
엘로우 아이디 자동응답 api형에 대해 문의드립니다. 

1. 키를 발급하기 위해 앱URL을 등록하도록 되어있는데  어떤 URL 인가요?
 
2. 1번의 URL이 홈페이지(PC 혹은 모바일) 이라면 API형을 사용하기 위한 소스를 입력해야 하나요?

3. 2번 맞다면 소스를 입력하지 않으면 사용이 불가능한가요?

4. API 자동응답을 사용하면 아래와 같이 사용이 되는건가요?
 1) 사과 / 배 / 바나나  => 3개의 선택 리스트가 있고,   1개를 선택했을 뗴 (예로 사과)
 2) 사과를 선택하셨군요~~ 사과 관련하여 아래 버튼을 선택해주세요 
 3) 답변과 같이 선택버튼 생성 : 구매하기 / 가격 / 문의하기  
이런식으로 선택버튼 생성을 여러개 할 수 있나요??

이상입니다. 답변 부탁드립니다.

**Comment by plusfriendteam** [comment]
1. RESTful 요청을 받기 위한 url 입니다.
2. 위 요청을 처리하기 위한 어플리케이션을 개발하셔야 합니다.
3. 직접 개발하지 않으셔도 단답형 자동응답은 관리자센터에서 설정하실 수 있습니다.
4. 맞습니다.
