### ISSUE TITLE
카카오톡 메세지 날리기

### ISSUE THREAD

**Issue by stanley-kim** [plusfriend/auto_reply#211]
안녕하세요

옐로우아이디 자동응답 기능을 잘 사용 중입니다.

문의사항은  request가 없는 상황에서 카카오톡 메세지를 날릴 수 있는 방법이 있을까요?
현재의 자동응답 구현은 request가 오면 거기에 대한 답변 메세지만 날리고 있는데요.

특정 상황이 되면 어떤 사용자가 request가 없더라도 카톡 메세지를 날리는 방법이 있을 지 궁금합니다.

감사합니다.

**Comment by plusfriendteam** [comment]
해당 기능을 이용하기 위해서는 [카카오톡 비즈메세지](https://bizmessage.kakao.com)를 이용하셔야 합니다.
