### ISSUE TITLE
wrong keyboard initialization

### ISSUE THREAD

**Issue by newkilho** [plusfriend/auto_reply#212]
https://yellowid.kakao.com/bot/api 에서 API Test 를 하면 아래와 같이 정상적으로 되는 것으로 확인 되었습니다.

Required*
Initialize Api test : OK 200: {"type":"text"}

Optional
Friend add Api test : OK 200
Friend block Api test : OK 200
Chatroom leave Api test : OK 200

그리고 curl -XGET https://bot.kilho.net/yellowid/kilhobot/keyboard 를 실행했을때
{"type": "text"} 로 출력됩니다.

그런데 아래와 같이 카카오톡으로 계속 메세지가 오는 이유가 무엇인지 알려주세요.

[관리자에게만 발송되는 메시지입니다] 사용자 봇서버에 에러가 감지 되었습니다. 
 내용:[wrong keyboard initialization]

@길호넷 입니다.

**Comment by plusfriendteam** [comment]
타임아웃이 나고 있군요.
참고로 타임아웃은 5초입니다.
