### ISSUE TITLE
관리자페이지 변경 일자 문의

### ISSUE THREAD

**Issue by enjoyseo** [plusfriend/auto_reply#215]
안녕하세요~ 

현재 일부 계정은 변경되는 관리자페이지를 사용중이고
3월부터 모든 관리자 페이지가 변경된다고 알고 있는데요.
그 시점이 정확히 언제부터인가요?

3월 1일 00시 부터 변경이 되는 부분인가요?

확인 부탁드립니다.
감사합니다.

**Comment by plusfriendteam** [comment]
변경 시점은 현재 결정되지 않았습니다.
시점이 확정되면 관리자센터에 해당 내용을 공지해드릴 예정입니다.

공지 이전까지는 현재 사용중인 관리자센터를 계속 사용해주시면 됩니다.
감사합니다.

**Comment by enjoyseo** [comment]
@plusfriendteam 넵. 그렇다면 기존에 사용중인 카탈로그형 메시지도 그 전까지는 사용 가능한것이죠?
