### ISSUE TITLE
API TEST 가 안돼요 ㅠ

### ISSUE THREAD

**Issue by ps2ung** [plusfriend/auto_reply#219]
API 테스트를 진행하면 아래와 같은 오류 메시지가 나오는데 어떤 것을 살펴봐야 하나요???

WebSocket connection to 'wss://yellowid.kakao.com/ws' failed: Error during WebSocket handshake: Unexpected response code: 403

**Comment by plusfriendteam** [comment]
api url을 알려주시겠어요?

**Comment by ps2ung** [comment]
http://talk.lawnorder.go.kr/api

입니다.

**Comment by plusfriendteam** [comment]
API 테스트는 다음의 순서로 진행됩니다.
```
DELETE /friend
POST /friend
DELETE /chat_room
GET /keyboard
```

앞의 세 요청에 대한 에러가 GET /keyboard 요청에 영향을 끼치는거 같네요.
모두 구현 하시거나 앞선 요청들에 영향을 받지 않게 구현하셔야 할 거 같아요.
구현의 문제이기 때문에 issue는 닫도록 하겠습니다.
