### ISSUE TITLE
Fail 415 : wrong keyboard initialization

### ISSUE THREAD

**Issue by shinhua0425** [plusfriend/auto_reply#220]
api테스트 시

아래와 같은 애러가 나타납니다.
Required*
Initialize Api test : Fail 415 : wrong keyboard initialization
Optional
Friend add Api test : OK 200
Friend block Api test : OK 200
Chatroom leave Api test : OK 200

원인이 먼지 모르겟습니다

**Comment by plusfriendteam** [comment]
원인은 GET /keyboard 요청을 실패했기 때문입니다.
실패원인은 200 OK가 아니거나, 5초 이상 응답이 없었거나, 적절한 포맷의 json 응답을 주지 않아서 입니다.
자세한 내용은 [문서](https://github.com/plusfriend/auto_reply/blob/master/README.md#51-home-keyboard-api)를 확인해보세요.
