### ISSUE TITLE
API 테스트에서 오류가 나는데요.

### ISSUE THREAD

**Issue by ps2ung** [plusfriend/auto_reply#221]
오전에 문의에 대한 답변을 보고 작업을 해서 테스트를 하고 있는데요.
또 오류가 나는데 어떤게 안되는건가요?

테스트 url : http://112.175.32.83:5080/moj2 이렇구요.
응답은 {"code":300,"message":"Server request time out!"} 이렇게 나오네요.

그리고 /friend 에 대한 응답으로 {"code":"0","comment":"정상 응답","message":"SUCCESS"} 이렇게 내주면 되는건가요???

답변 부탁드립니다.

**Comment by plusfriendteam** [comment]
외부에서 접근할 수 없는것 같네요.
응답에 대한것은 [문서](https://github.com/plusfriend/auto_reply/blob/master/README.md)를 확인해주세요.
