### ISSUE TITLE
USER_KEY 관련해서 질문이 있습니다.

### ISSUE THREAD

**Issue by emaDdoG** [plusfriend/auto_reply#222]
IOT 관련 졸업작품을 제작중에 있습니다. 메세지를 받았을 때 서버에서 대상의 USER_KEY를 분별해서

권한이 있는 대상의 커맨드만 수행하도록 하고 싶은데 USER_KEY를 인식하는 방법을 모르겠습니다.

실력이 많이 모자라서 괜찮으시다면 가급적 상세하게 가이드좀 해 주실 수 있을까요?

가능하다면 고생스러우실 것 알지만 꼭 부탁드립니다...!!

**Comment by plusfriendteam** [comment]
말씀하신바와 같이  user_key는 사용자를 구분할 수 있는 키값입니다.
자세한 내용은 [문서](https://github.com/plusfriend/auto_reply/blob/master/README.md)를 참고해주세요. 구현에 대한 자세한 설명은 드리기 어렵습니다. ^^;
