### ISSUE TITLE
API문의드립니다.

### ISSUE THREAD

**Issue by songsooyeon** [plusfriend/auto_reply#223]
자동응답 API를 하려고하는데 별도의 APP은 저희가 자체적으로 만들어서 자동응답 API 를 하게되면
별도의 비용은 발생하지않나요?

**Comment by plusfriendteam** [comment]
자동응답 API는 현재는 무료로 사용하실 수 있습니다.

다만, 차후 API 고도화에 따라 최대 사용량이 정해질 수 있습니다.
변경사안이 생길 경우 사전 공지드릴 예정입니다.
