### ISSUE TITLE
자동응답 API 신청시 앱 URL 

### ISSUE THREAD

**Issue by kangmyonggyu** [plusfriend/auto_reply#225]
안녕하세요
@AIBRIL보험챗봇 의 자동응답 API 를 신청을 했는데
 앱이름/ 앱URL/ 앱설명 / 전화번호를 입력 하라고 나와 있는데
 이 앱 URL 이 Android/iOS Marget URL 인가요? 저희는 따로 마켓 어플리케이션이 없는데 그럼 어떻게 입력 해야 하는지 궁금합니다.

그리고 추가로 저희가 자동응답 API를 이용하여 사용자의 답변을 받아 의도를 파악하여 답변해주는 시스템 구현을 자동응답 API를 이용하여 Test 해보고 싶은데 제가 이야기한 기능 구현이 자동응답 API를 통해 구현이 가능한지 궁금합니다!

감사합니다!

**Comment by plusfriendteam** [comment]
URL은 RESTful 요청을 받기 위한 URL입니다.
각 모바일OS의 설치 URL과는 관련이 없습니다.
자동응답 API를 이용하여 문의 주신 기능은 구현 가능합니다.
