### ISSUE TITLE
API 테스트가 안됩니다.

### ISSUE THREAD

**Issue by ps2ung** [plusfriend/auto_reply#226]
WebSocket connection to 'wss://yellowid.kakao.com/ws' failed: Error during WebSocket handshake: Unexpected response code: 403

위와 같은 에러가 계속 발생을 하는데 어떻게 해야 하나요?

{"code":300,"message":"Server request time out!"}

이전에 질문했을 때 

=================================================
API 테스트는 다음의 순서로 진행됩니다.

DELETE /friend
POST /friend
DELETE /chat_room
GET /keyboard
앞의 세 요청에 대한 에러가 GET /keyboard 요청에 영향을 끼치는거 같네요.
모두 구현 하시거나 앞선 요청들에 영향을 받지 않게 구현하셔야 할 거 같아요.
구현의 문제이기 때문에 issue는 닫도록 하겠습니다.

=================================================

이렇게 테스트를 하는데 friend와 chat_room 을 지정하지 않아서 발생하는 것 같다고 하셔서 추가로 했는데도 같은 에러가 납니다.

테스트 URL은 http://talk.lawnorder.go.kr/api 입니다.
확인 좀 부탁드립니다.

**Comment by plusfriendteam** [comment]
개발상의 문제로 보이네요.
앞서 말씀드린 바와 같이 구현의 문제는 저희가 도움을 드리기 힘들답니다.
양해 부탁드려요. ^^;
