### ISSUE TITLE
API 테스트가 안됩니다. 

### ISSUE THREAD

**Issue by ps2ung** [plusfriend/auto_reply#227]
무조건 개발상의 문제라고만 하시면 어떤 부분을 고쳐야 하는지 알 수 가 없는데요;;;

제가 직접 해당 URL로 호출을 하면 정상적으로 나오는데 여기 api test만 하면 응답이 안오고 있습니다.
호출 결과를 좀 받아 볼 수 없을까요???

그리고 답변만 달면 무조건 closed 되는건가요??

**Comment by plusfriendteam** [comment]
동시에 여러 요청이 올 경우 제대로 대응이 되고 있는지 확인하실 필요가 있어 보입니다.
그래서 구현의 문제라고 말씀드린겁니다.
저희가 추가로 대응 할 여지가 없는 경우 close 합니다.
새로 이슈 올리셨으니 해당 글에서 이어서 문의 받도록 하겠습니다.
