### ISSUE TITLE
외부 봇 빌더 연동시 메세지 수신에 대한 api 제공 여부

### ISSUE THREAD

**Issue by luhyun** [plusfriend/auto_reply#228]
현재 morph.ai 라는 챗봇 빌더와 연동하여 카카오톡 자동응답 서비스를 제공하려 합니다.
이때 응답 데이터를 외부와 연동하여 저장할 수 있다는 이야기를 듣고 
이 챗봇 빌더에 메세지를 "수신"하고 "저장"하려고 하는데요,
메세지를 "발송"하는 것 외에 "수신" 및 "저장"을 외부 서버에서 할 수 있는지 궁금합니다.
즉, "수신" api를 제공하는지 궁금합니다.

**Comment by plusfriendteam** [comment]
수신 API를 제공해드리고 있습니다.
수신 후 응답으로 메세지를 주시면 유저에게 그 메세지를 보냅니다.
문의 주신 내용으로 구현하실 수 있습니다.
