### ISSUE TITLE
response is not OK(200) : 500 / Internal Server Error

### ISSUE THREAD

**Issue by choong2** [plusfriend/auto_reply#229]
버튼클릭시 에러가 발생합니다.
![image](https://cloud.githubusercontent.com/assets/26083304/23442038/7ff796a6-fe69-11e6-9dd2-ba9072205bce.png)

**Comment by plusfriendteam** [comment]
에러 메세지 내용과 마찬가지로 "행사"라는 키워드에 대한 응답 메세지 포맷이 맞지 않은것으로 보입니다.
[문서](https://github.com/plusfriend/auto_reply/blob/master/README.md)를 확인해주세요.
