### ISSUE TITLE
5.2 메세지 수신 및 자동응답 API

### ISSUE THREAD

**Issue by speedeng** [plusfriend/auto_reply#23]
{
	"keyboard":{
		"buttons":["처음으로","다시 등록하기","취소하기"],
		"type":"buttons"
	},
	"message":{
		"photo":{
			"width":"640",
			"height":"480",
			"url":"https://dn-m.talk.kakao.com/talkm/oWqohwO3le/TFkOcvPYbiBqKkzkdULCLk/i_g849a9qow5411.jpeg"
		},"
		message_button":{
			"lable":"주유 쿠폰받기",
			"url":"http://www.naver.com"
		},
		"text":"처리 되었습니다."
	}
}
서버에서 리턴한 내용인데..
자동응답 설정이 잘못되어 오류가 발생하고 있습니다. 설정을 다시 한 번 확인해주세요. wrong message format이라고 카카오톡에 나옵니다.

다빼고 message 에 text만 있는 경우는 정상 응답되네요.
확인 부탁드립니다.

그리고 api 가이드에 보면 자동응답 명령어에 대한 응답 메세지의 내용. 7.2에서 상세기술 이라고 적혔는데 문서에 7.2는 없습니다.

**Comment by plusfriendteam** [comment]
문서가 수정되었습니다. 7.2가 아니라 6.2(https://github.com/plusfriend/auto_reply/blob/master/README.md#62-message)  에서 확인해보시기 바랍니다. 

응답 값중에 오타가 있습니다. 
`message_button > lable` 을 `message_button > label` 로 수정해보시기 바랍니다.
