### ISSUE TITLE
API 테스트를 할 때요

### ISSUE THREAD

**Issue by ps2ung** [plusfriend/auto_reply#230]
안녕하세요. API 테스트에 대해서 문의가 있는데요.

https://yellowid.kakao.com/json/apibot/extUrl/check?url=테스트 URL
테스트가 진행되는 단계에 대해서 알려주실 수 있나요?

브라우저에 직접 테스트 URL을 입력해보면 응답이 빠르게 오는데요.
위 카카오의 테스트 URL을 통해서 하면 waiting time이 10초 정도 걸리네요.

지금 공공기관을 통해서 서비스를 하려고 하는데 Proxy 서버를 통하지 않고 테스트를 할 수는 없는 건가요?

답변 꼭 부탁드립니다.

**Comment by plusfriendteam** [comment]
API 테스트시 다음의 순서대로 진행됩니다.
```
DELETE /friend/:user_key
POST /friend
DELETE /chat_room/:user_key
GET /keyboard
```
`GET /keyboard` 요청만 성공해도 API 테스트는 성공 처리가 됩니다.

proxy 서버는 어떤 서버를 말씀하시는거죠?

**Comment by ps2ung** [comment]
가이드에 보면 아래와 같은 내용이 있던데 이쪽 프록시 서버를 통해서 테스트를 하시는 것 아닌가요?

![image](https://cloud.githubusercontent.com/assets/23470759/23601442/c9e38602-028e-11e7-874e-fbb99e46afa9.png)

**Comment by plusfriendteam** [comment]
언급해주신 리스트는 ACL등으로 접근 제한을 하실 경우에 접근 허용을 위해 저희가 제공해드리는 정보입니다.
프록시 서버의 유무와 봇 구현은 큰 관련이 없습니다.

**Comment by ps2ung** [comment]
https://yellowid.kakao.com/json/apibot/extUrl/check?url=http://talk.lawnorder.go.kr/api

위와 같이 테스트 하는 것과 브라우저에서 직접 http://talk.lawnorder.go.kr/api/keyboard 를 해보는 것의 차이는 뭔가요?

브라우저에서 직접 http://talk.lawnorder.go.kr/api/keyboard 해보면 응답이 바로바로 오는 데 apibot을 통해서는 아래 첨부한 그림과 같이 waiting time 이 10초 가량 걸리거든요.

![image](https://cloud.githubusercontent.com/assets/23470759/23602066/eaeb9012-0291-11e7-903f-945e41a0b1e9.png)

**Comment by plusfriendteam** [comment]
저희가 제공해드리는 API 테스트를 이용 할 경우 GET /keyboard 요청만 하는것이 아니라 위에 답변 드린것처럼 친구 차단, 친구 추가, 대화방 나가기에 대해서도 요청을 하게 됩니다.
그 차이가 있네요.

**Comment by ps2ung** [comment]
혹시 API 테스트 할 때 DELETE (친구 차단, 대화방 나가기) 를 체크하지 않고는 안되는 건가요?

**Comment by plusfriendteam** [comment]
네.
