### ISSUE TITLE
405 Method Not Allowed

### ISSUE THREAD

**Issue by ninja099** [plusfriend/auto_reply#231]
Required*
Initialize Api test : OK 200: {"type":"buttons","buttons":["쿠폰 보기"]}
Optional
Friend add Api test : OK 200
Friend block Api test : Fail 405
Chatroom leave Api test : Fail 405

test시 POST관련 페이지는 정상이나
DELETE 관련 페이지는 405에러가 뜹니다.
405 Method Not Allowed 이던데 무엇이 문제인지요.

**Comment by plusfriendteam** [comment]
말 그대로 405 에러가 난겁니다. ^^;;
서버 설정을 확인해보시면 해결하실 수 있을거에요.
환경 설정의 문제이므로 이슈는 닫도록 하겠습니다~!
