### ISSUE TITLE
채팅 Flow 의 데이터 전송

### ISSUE THREAD

**Issue by kangmyonggyu** [plusfriend/auto_reply#232]
안녕하세요 자동 답변 API를 이용하여 챗봇을 구현 하고 있는데

API 를 호출 할때 Response 로 받는 어떤 데이터(객체) 를 Request 로 보낼수 있는지요..?

이 데이터를 이용하여 채팅 Dialog 를 구현 하려고 하는데 채팅의 Text 외의 다른 정보를 Session 처럼 담을수 있는가 궁금하네요

**Comment by plusfriendteam** [comment]
채팅 메세지 그대로 전달되고 다른 데이터를 파라미터로 추가한다거나 하는것은 지원하지 않고 있어요.

**Comment by kangmyonggyu** [comment]
그렇군요 ㅠㅠ 그럼 "user_key" 로 데이터를 저장 해야겠네요..
채팅 할때 마다 HttpServletRequest 의 session 의 id 가 바껴서 session 에 담기 힘들거 같은데 그럼
user_key 로 db 에 담는 방법 밖에 없나요, 구현 부분이라 답변이 어려우시겠지만, 혹시 팁을 아시면 알려주시면 감사하겠습니다

**Comment by plusfriendteam** [comment]
네. 유저키를 사용하셔야 합니다.
자세한 구현에 대해서는 말씀드리기 힘들어요. ^^
