### ISSUE TITLE
API TEST 링크

### ISSUE THREAD

**Issue by leesilver** [plusfriend/auto_reply#233]
앱 등록할 때 API TEST 링크를 적어야 하는데 어떤 링크를 적어야 하나요?
저의 이벤트 링크를 삽입하니 
링크: https://activity.efunkr.com/actionHai_test.shtml?gameCode=test&activityCode=testActivity
Required*
Initialize Api test : Fail 415 : wrong keyboard initialization
Optional
Friend add Api test : OK 200
Friend block Api test : OK 200
Chatroom leave Api test : OK 200
415라는 에러가 뜹니다.

답변 꼭 부탁드립니다.

**Comment by plusfriendteam** [comment]
RESTful 요청을 받을 URL을 입력하시면 됩니다.
GET /keyboard 요청에 대한 적절한 응답이 오지 않아서 입니다.
자세한 내용은 [문서](https://github.com/plusfriend/auto_reply/blob/master/README.md)를 읽어보세요.
