### ISSUE TITLE
카카오톡 전송 문의

### ISSUE THREAD

**Issue by pcappli** [plusfriend/auto_reply#234]
1. 대화를 2개로 나누어 보내는 것이 가능한지요?

2. 줄바꿈은 어떻게 표현할 수 있나요?

3. keyboard 변수를 보낼떄 user_key를 가져올 수 없는지 알고 싶습니다.

플러스친구 : 더블온라인미디어 (추후 변경 예정)

**Comment by plusfriendteam** [comment]
현시점을 기준으로 봤을 때
1. 불가합니다.
2. '\n' 쓰시면 되지 않을까요?
3. GET /keyboard 요청은 모든 유저에게 공통으로 보여주는 기본 입력 방법에 대한 정의이므로 user_key를 보내드리고 있지 않습니다. 따라서 현재는 제공하고 있지 않아요. 하지만 기능 추가에 대해서는 검토해 보도록 하겠습니다.
