### ISSUE TITLE
자동응답 API 의 Response 문제 

### ISSUE THREAD

**Issue by haeruseok** [plusfriend/auto_reply#235]
[5.2. 메시지 수신 및 자동응답 API](https://github.com/plusfriend/auto_reply#52-메시지-수신-및-자동응답-api) 의 Response 부분에 message 필드는 Required 이고 keyboard 필드는 Optional 이라고 하셨는데,
실제 서비스시에 keyboard 필드를 추가하지 않으면 "[관리자에게만 발송되는 메세지입니다] 사용자 봇서버에 에러가 감지되었습니다." 라고 에러메세지를 보여주네요 ㅠ. 확인 부탁드립니다.

**Comment by plusfriendteam** [comment]
응답의 keyboard 필드는 옵셔널이 맞는데 이상하네요. ^^;
봇 계정의 (@으로 시작하는)검색 id를 알려주시겠어요?

**Comment by haeruseok** [comment]
@해석이 라고 검색하시면 됩니다~
지금은 keyboard 옵션을 추가한 상태입니다

**Comment by plusfriendteam** [comment]
json 응답 형태에 뭔가 문제가 있을 것이라 예상했었는데
해당 봇 계정에서 난 에러들을 보니 응답이 200 OK가 아닌 500으로 에러를 주셨었네요.
일단 Keyboard는 옵셔널이 맞습니다. ^^

**Comment by haeruseok** [comment]
친절한답변 감사합니다!
