### ISSUE TITLE
API 테스트시 415 Error가 나는데

### ISSUE THREAD

**Issue by JaeWoongKang** [plusfriend/auto_reply#238]
안녕하세요. 앱 URL 테스트시 415 에러가 납니다. 

앱 URL은 http://13.124.3.215:8082/rest/kakao/ 위와 같이 적었구요. 

다른 RESTful 클라이언트에서는 동작합니다.
저도 ACL 설정을 해야하나요?

ACL설정이 안되어 있으면 아래처럼 안나오고 다른 에러가 나는 걸로 알고 있는데요.
저는 아래와 같이 나옵니다.
```
curl -XGET 'http://13.124.3.215:8082/rest/kakao/keyboard'
{"type":"buttons","buttons":["오마이플레이 제휴체육관","나의 플레이 영상"]}

**Comment by plusfriendteam** [comment]
외부 접근을 막아놓으셨다면 접근 허용을 해주셔야 합니다. 지금은 에러를 내고 있네요.
