### ISSUE TITLE
Photo 타입에 대한 정보가 약간 부족한 것 같습니다.

### ISSUE THREAD

**Issue by humit0** [plusfriend/auto_reply#24]
[Message](https://github.com/plusfriend/auto_reply#62-message) 항목에서 photo 필드에 대한 설명으로 가로, 세로, 용량 제한이 있다고 나와 있는데, 정확한 수치로 알려주시면 좋을 것 같습니다.

그리고 지금은 JPEG만 가능하다고 나와있는데 추가적인 포맷은 더 지원해줄 생각이 없으신가요?

**Comment by plusfriendteam** [comment]
[문서](https://github.com/plusfriend/auto_reply/#63-photo)에 이미지 권장 가이드 추가 하였습니다. 
참고 바랍니다. 

```
이미지 권장 사이즈 : 720 x 630px
지원 파일형식 및 파일용량 : jpg, png /  500KB
```

자동응답 API의 이미지 가이드는 
플러스친구/옐로아이디 운영툴의 자동응답키워드의 이미지 가이드와 동일 합니다. 

감사합니다.
