### ISSUE TITLE
채팅방에서 ".... 응답을 하지 않습니다.  문제가 보고되어..." 라는 메시지가 노출됩니다.

### ISSUE THREAD

**Issue by namghiwook** [plusfriend/auto_reply#241]
채팅방에서 
"해당 프로필의 자동응답 시스템이 응답을 하지 않습니다.  문제가 보고되어 처리 예정입니다. 다음에 다시 시도해주세요." 
라는 메시지가 노출됩니다.

API 를 수정해서 "API TEST" 를 통해 모두 200 OK 되게 했습니다.
이후에도 계속 위 메시지가 노출되는데 어떻게 해야하나요?

**Comment by plusfriendteam** [comment]
에러메세지 그대로 응답을 하지 않는 경우, 그러니까 타임아웃이 나는 경우에 발생하는 에러메세지입니다.
타임아웃은 5초입니다.

**Comment by namghiwook** [comment]
옐로우아이디 자동응답 API 화면에서 API TEST 버튼을 누른 경우 모두 200 OK 떨어졌습니다. 타임아웃 발생 안하는데.. 왜 실제 채팅창에서는 발생하나요?
