### ISSUE TITLE
해당 프로필의 자동응답 시스템이 응답을 하지 않습니다" 메시지에 관해서

### ISSUE THREAD

**Issue by namghiwook** [plusfriend/auto_reply#242]
채팅방에서
"해당 프로필의 자동응답 시스템이 응답을 하지 않습니다. 문제가 보고되어 처리 예정입니다. 다음에 다시 시도해주세요."
라는 메시지가 노출됩니다.
API 를 수정해서 "API TEST" 를 통해 모두 200 OK 되게 했습니다.
이후에도 계속 위 메시지가 노출되는데 어떻게 해야하나요?

옐로우아이디 자동응답 API 화면에서 API TEST 버튼을 누른 경우 모두 200 OK 떨어졌습니다. 타임아웃 발생 안하는데.. 왜 실제 채팅창에서는 발생하나요?

또..

"오류 횟수 초과로 인해 중지된 앱은 운영툴에서 오류 수정 후 직접 다시 서비스를 시작할 수 있습니다." 이런 안내가 있는데...
운영툴은 무었이며 다시 서비스를 시작한다는건 어디서 하는건가요?

**Comment by plusfriendteam** [comment]
테스트 환경은 GET /keyboard 요청을 제대로 주는지만 확인합니다.
POST /message 요청에 대해서는 확인하지 않습니다.
실제 환경에서는 API 테스트의 경우와 달리 많은 요청이 들어가게 됩니다.
예를 들어 상점을 운영한다고 가정하였을 경우, 점원을 한명만 두면 테스트 환경에서는 잘 통과가 될겁니다.
하지만 실제 오픈을 하고 손님 수천명이 몰려 올 경우라면 점원 한명에서 모든 손님들의 요구사항을 들어줄 수 없겠죠.
이런거라고 생각하시면 될거 같네요.
운영툴은 옐로아이디 관리자 센터를 말합니다.
봇 설정에 가보시면 정지된 상태로 나올텐데 거기서 다시 시작하시면 됩니다.
