### ISSUE TITLE
옐로아이디 자동응답 'API TEST'에서 애를 먹고 있습니다.

### ISSUE THREAD

**Issue by mothcar** [plusfriend/auto_reply#243]
앱url : https://chatbot.cafe24.com:3000/keyboard

`Required*`
`Initialize Api test : Fail 415 : wrong keyboard initialization`
`Optional`
`Friend add Api test : Fail 500`
`Friend block Api test : Fail 500`
`Chatroom leave Api test : Fail 500`

이렇게 나옵니다.

많은 방법들을 써봤으나 같습니다.
다른 test방법으로는 
1. terminal에서 
`$ curl -XGET http://chatbot.cafe24.com:3000/keyboard`
로 리퀘스트 날리면 결과값으로 
`{"type":"buttons","buttons":["메뉴1","메뉴2"]}%`
로 잘 들어옵니다.

2. 일반 브라우저에서도 
`http://chatbot.cafe24.com:3000/keyboard` 로 입력하면 
화면에 JSON으로 잘 나옵니다.
`{"type":"buttons","buttons":["메뉴1","메뉴2"]}`

무슨 문제일까요?

한가지 안 써본 방법은 ACL을 허용하라고 하는데 어떻게 하는지 방법을 모르겠습니다.
만약 이 문제라면 알려주시면 고맙겠습니다.
서버는 cafe24에서 운영하는 가상서버를 쓰고 있습니다. (ubuntu 16.X)
서버환경은 node.js express 환경입니다.

부탁드립니다.

**Comment by plusfriendteam** [comment]
앱 url은 https://chatbot.cafe24.com:3000 까지만 입력하셔야 합니다.

**Comment by mothcar** [comment]
네, 답변 감사합니다.
추가로 자답입니다.

저의 문제는 https의 문제였습니다.
옐로아이디에서 https://github.com/plusfriend/auto_reply 를 참조하면 
"**HTTPS를 통하여 API를 이용하는 파트너사 서버는 유효한 공인인증서를 사용해야 합니다.**"한다고 해서 
반드시 https로만 챗봇이 **초기화**되는 줄 알았습니다.

일단 문제해결은 공인인증서(SSL)을 만드는 방법과 // 이 방법은 조금 많이 번거로워서 비추입니다.
그냥 http로 초기화해서 사용하는 방법인거 같습니다.
