### ISSUE TITLE
message 문의

### ISSUE THREAD

**Issue by toring92** [plusfriend/auto_reply#245]
/message 에서 궁금증이 있습니다.
echo <<< EOT
{
	"message": {
		"text": "1. 1번입니다. 2. 2번입니다."
	}
}
EOT;
ㅌ
1. 1번입니다.
2. 2번입니다.
로 메세지를 보여주고 싶습니다.
다음줄에 쓰거나 \n <br> 다 안 되던데 어떻게 해야하는지 궁금합니다 :( ..

**Comment by plusfriendteam** [comment]
보통은 \n 쓰시면 됩니다.
개발 환경에 따라 달라질 수 있을텐데 그 부분에 대해서는 저희가 답변을 드리기 곤란한 점 양해 부탁드려요.^^
구현에 관한 문제이므로 close 하겠습니다.
