### ISSUE TITLE
사진메시지

### ISSUE THREAD

**Issue by minji737** [plusfriend/auto_reply#247]
자동응답시 사진이미지를 보고 판단해서 답변을 해주려고하는데
사진이미지 데이터도 받을수있는건가요 ?
예를 들어 빨간원피스사진을 보내주면
빨간원피스입니다. 이런식으로 답변을 하려고합니다.

**Comment by plusfriendteam** [comment]
네 가능합니다.
자세한 내용은 [문서](https://github.com/plusfriend/auto_reply#52-메시지-수신-및-자동응답-api)를 읽어보세요. ^^
