### ISSUE TITLE
친구 차단과 BOT_USER_KEY 관련

### ISSUE THREAD

**Issue by enjoyseo** [plusfriend/auto_reply#249]
안녕하세요~ @AXA다이렉트 입니다 

친구 데이터를 관리할 때

1. 친구추가시 추가날짜 INSERT (신규row, 상태값 친구)
2. 인증시 인증날짜 UPDATE       (기존row, 상태값 친구)
3. 차단시 차단날짜 UPDATE       (기존row, 상태값 차단)

위 3개로 관리를 해주고 있습니다.

Uri를 indexOf하여 "friend" 값의 유무로 친구관리 로직을 태워서
if ( "friend".equals(strUri.substring(strUri.lastIndexOf("/")+1))  일때는 친구추가,
else 일때는 친구차단으로 봇유저를 관리 하고 잇습니다.

그런데 통계 자료를 추출하는데 차단관련 데이터가 조회하는 일자마다 상이해서 확인해보니
이전에 차단으로 되어있는 봇유저의 차단날짜가 최근일로 변경이 되었습니다.
ex) 03월15일 조회시 A유저의 차단일 = 20130830
      03월16일 조회시 A유저의 차단일 = 20170316

차단 상태인 고객이 다시 차단을 할 수 있는 경우가 있는건가요
아니면 차단한 고객의 USERKEY 값이 친구차단 말고, "friend"를 통해서 저희서버로 다시 값이 오는 경우가 있는지요?

확인 부탁드립니다
감사합니다  ^^

**Comment by plusfriendteam** [comment]
차단 후 다시 차단 요청이 가진 않습니다.
차단 했던 유저가 다시 친구를 맺게 되면
동일한 유저키로 POST /friend 요청을 하게 됩니다.
