### ISSUE TITLE
어플 버그 문제

### ISSUE THREAD

**Issue by pcappli63** [plusfriend/auto_reply#250]
옐로아이디 : @급식몬

현재 서비스에서 버튼을 클릭하고 나서 카카오톡이 응답하지 않습니다라고 오류 문구가 뜨는 문제가 가끔 발생합니다.

확인 부탁드립니다.

그리고 응답에 대해서 속도를 줄이는 방법은 서버의 문제가 가장 큰가요?

**Comment by plusfriendteam** [comment]
앱의 응답 관련 오류는 수정될 수 있도록 관련 부서에 요청을 드리도록 하겠습니다.
어떤 응답속도를 말씀하시는지요?

**Comment by pcappli** [comment]
메시지 전송 내용을 받고 나면 후에 응답 메시지 전송까지의 시간입니다,.

**Comment by plusfriendteam** [comment]
네. 메시지에 대한 응답은 서버가 빨리 응답을 줄 수 있도록 해 주셔야 합니다.
