### ISSUE TITLE
API 관련 건의

### ISSUE THREAD

**Issue by BJbit** [plusfriend/auto_reply#251]
안녕하세요 작은 게임서버를 운영중인 사람입니다.
다름이 아니라 게임서버와 옐로 아이디를 연동하여 다양한 기능을 제공하고자 계획중입니다.
그 중 하나가 게임 서버 접속 시 옐로 아이디를 통해서 "[닉네임]님께서 서버에 접속하셨습니다. ([아이피])"라고 메세지를 전송하고 본인이 아닐 경우 적절한 조치를 취할려고 합니다.

하지만 API는 전부 응답만 가능할 뿐 API 쪽에서 먼저 메세지를 보낼 수 있는 기능은 없더군요.
혹시 이와 관련한 기능을 구현해주실 의향이 있으신가 여쭙고자 문의 남깁니다.

**Comment by pcappli** [comment]
카카오톡에서는 이 기능을 비즈메시지라는 수익모델로 가지고 있어서 서비스 안한다고 합니다..

**Comment by plusfriendteam** [comment]
@pcappli 님 말씀대로 현재는 해당 기능을 [카카오톡 비즈메세지](https://bizmessage.kakao.com/)를 통해서만 제공해 드리고 있씁니다.
