### ISSUE TITLE
자동응답api 의 줄바꿈기능 그리고 이미티콘 넣는 방법은 어떻게 하나요?

### ISSUE THREAD

**Issue by tobby2002** [plusfriend/auto_reply#252]
안녕하세요. 
github아이디 @tobby2002
카톡아이디 : @neoxio
이메일: tobby2002@gmail.com

현재 자동응답api를 이용하고 있습니다.
그런데 줄바꿈기능을 하는 방법이 없나요?
(참고, message 기능으로 
curl -XPOST 'https://:your_server_url/message' -d '{ "user_key": "encryptedUserKey", "type": "text", "content": "참고문구, {줄바꿈을 하는 기능을 알려주세요 <br>등 tag코드가 안먹이구요 \r\n 등도 안먹히네요 그리고 이모티콘도 넣고 싶어요  }"
}'
주고 받을때 입니다.)

혹시 예제가 있으면 부탁해요

**Comment by pcappli** [comment]
제가 대신 답변드리면 카카오톡에서는 아이템스토어 이모티콘은 지원을 하지 않고 있습니다.
대신 (야호) 처럼 되어 있는 이모티콘은 전송이 가능합니다.
(참고, http://yellowid.tistory.com/84)

그리고 줄바꿈은 \n을 쓰면 됩니다. 하지만 경우에 따라 전송이 안될 경우에는 \\n을 쓰면 줄바꿈이 됩니다. (링크를 쓰면 그렇더군요)

**Comment by plusfriendteam** [comment]
@pcappli 님이 답변을 다 해주셨네요. 감사합니다.^^

**Comment by pcappli** [comment]
@plusfriendteam  자주 아는 답변 있으면 포럼답게  답변 하겠습니다.
