### ISSUE TITLE
친구 차단과 BOT_USER_KEY 관련  #249  연장 질문

### ISSUE THREAD

**Issue by enjoyseo** [plusfriend/auto_reply#254]
안녕하세요~

그렇다면 친구를 차단 했거나 신규친구인 경우에는 
Uri 값으로 "/friend" 만 넘겨주고,  "/friend/봇유저키"는 저희쪽으로 보내지 않는다는 말씀이신데요
차단했던 친구나, 신규친구가 "/friend" 값 뒤에 다른 값을 가져오는 경우는 없는건가요?

uri값이 "/friend" 가 아닐 경우에만 저희 쪽 친구테이블에서 차단을 업데이트 하는데 이상하네요..

**Comment by pcappli** [comment]
@enjoyseo 주소는 도메인/friend가 오고 json의 user_key로 받으시면 됩니다.
