### ISSUE TITLE
카카오톡 키보드 버튼 생성 API 문의

### ISSUE THREAD

**Issue by samko635** [plusfriend/auto_reply#255]
안녕하세요, LG CNS 톡주문 서비스 개발자입니다. 

그동안 API형 자동응답을 이용하여 아래와 같이 초기 진입시 키보드를 생성하여 서비스를 해왔습니다.
{ "type": "buttons", "buttons": [ "선택 1", "선택 2", "선택 3" ] }

그런데 최근 첨부파일과 같은 형태의 버튼도 가능하다는 것을 알고  API문서 및 옐로아이디 가이드를 확인해보았는데 관련 세팅내용을 찾을수가 없어서 어떤식으로 해야 저런식의 세팅이 가능한지 문의드립니다. 
홈버튼 바로 옆의 버튼은 누르자마자 외부 링크로 연결이 되고
그 옆의 FAQ버튼은 클릭하면 서브 메뉴 키보드 버튼이 나오고, 서브메뉴 버튼을 클릭하면 일반 메시지 자동응답처리 처럼 진행이 됩니다. 

답변 부탁드립니다.
![20170329_110856](https://cloud.githubusercontent.com/assets/22001843/24435694/d2242ea8-1471-11e7-9447-a501f0fa0395.png)

**Comment by kwanlae** [comment]
issue #171 참조하세요.
