### ISSUE TITLE
에라 메세지 원인 요청

### ISSUE THREAD

**Issue by KIMRAKKYUN** [plusfriend/auto_reply#256]
안녕하세요.

앱 URL : http://m.4cgate.com/auto_reply/keyboard.jsp

API TEST 버튼을 선택 할 경우 아래와 같이 에라가 발생되고 있습니다. 

확인을 부탁 드립니다.

Required*
Initialize Api test : Fail 415 : wrong keyboard initialization
Optional
Friend add Api test : Fail 404
Friend block Api test : Fail 403
Chatroom leave Api test : Fail 403

**Comment by plusfriendteam** [comment]
타임아웃 혹은 잘못된 응답을 내려줄 때 발생합니다.
자세한 내용은 [문서](https://github.com/plusfriend/auto_reply#51-home-keyboard-api)를 참고하세요.
