### ISSUE TITLE
자동응답 API 이용시 사용자 이름 획득 방법

### ISSUE THREAD

**Issue by kwanlae** [plusfriend/auto_reply#258]
encryption 된 사용자 고유키를,
카카오 서버에서 개발사 서버로 쏘는 request API body의 "user_key" 를 통해 얻을 수 있는데요,

"안녕하세요, OOO 님" 과 같은 메시지를 사용자 채팅화면에 출력하려면,
고유키가 아닌 사용자 이름이 필요한데
이것은 현재는 불가능한 것인가요?

혹시 이것이 가이드 문서상의
[2. 개인정보 수집 및 이용에 대한 주의사항] 에 저촉이 되어 원칙적으로도 불가능한 것인지 궁금합니다.

**Comment by pcappli** [comment]
안녕하세요.
같은 사용자 로서 답장 드리면  직접 서비스를 개발할 당시에 사용자 이름을 수집하는 건 가능합니다.(관련 법령에 의거하여 ) 그런데 카카오에서 사용자 이름을 제공하지는 않습니다.

**Comment by plusfriendteam** [comment]
카카오에서는  해당 사용자 정보를 제공해드리지 않고 있습니다. 
감사합니다.
