### ISSUE TITLE
Message  photo 변경 후 반영 시점

### ISSUE THREAD

**Issue by stanley-kim** [plusfriend/auto_reply#259]
안녕하세요 
6.2. Message   에서 photo 관련 질문입니다.
photo 파일의 이름은 그대로 인데 내용을 변경하였습니다.
그래서 동일한 url 이지만, 변경된 다른 파일이 자동응답 시에 보이게 하려고 하는데요

파일 변경하고 서버에 반영 후 대화 창을 열어서 보니 기존의 photo가 그대로 보이는데요
(카카오톡을 재실행 시키고, 대화창을 바꾸고 여러가지 하다보니 어느 순간 변경되긴 하였습니다.)
혹시 photo의 내용을 바꾸었을 경우 언제부터 대화창에서 변경된 photo가 나오게 되는 지 
궁금하네요

감사합니다.

**Comment by plusfriendteam** [comment]
이미지 파일은 카카오톡 클라이언트에서 캐싱을 하고 있습니다. 따라서 해당 캐시를 지우기 전까지 바뀌지 않습니다.
