### ISSUE TITLE
서버 이미지 유효기간

### ISSUE THREAD

**Issue by speedeng** [plusfriend/auto_reply#26]
API를 통해서 이미지를 받는 경우 https://dn-m.talk.kakao.com/talkm/oWqohwO3le/TFkOcvPYbiBqKkzkdULCLk/i_g849a9qow5411.jpeg
이런식으로 url로 들어오는걸 확인했는데요 서버에 저 이미지가 영구 보관인가요? 아니면 삭제할수 있는 방법이 있는지도 궁금합니다.

**Comment by suya55** [comment]
@speedeng 카카오톡으로 전송된 이미지의 보존기간은 20일입니다.
따로 보관하길 원하시면 이미지 주소에서 직접 내려받아 두셔야 합니다.
그리고 따로 삭제하는 API를 제공하지 않습니다.

그리고 이미지의 보존기간은 카카오 서버의 상황에 의에 조금씩 늘어날수도 줄어들수도 있습니다.
