### ISSUE TITLE
상담원에게 메시지를 전송할 수 있는방법

### ISSUE THREAD

**Issue by haneu89** [plusfriend/auto_reply#260]
우측에 1:1 모드일때를 제외하고 봇이랑 대화할때
일정 텍스트나 response를 상담원에게 전달하는 방법이 있나요?
예를들어
"상담요청 배송문제"
이라고 타이핑을 했을때
상담원에게
"상담 : 배송문제, 시간 : 현재시간"
이런식으로 전달하고 싶습니다.

**Comment by plusfriendteam** [comment]
[https://github.com/plusfriend/auto_reply#52-메시지-수신-및-자동응답-api](url)
를 이용해서 처리 하실수 있습니다. 
관련 내용 검토하시고 추가 문의해 주시면 답변드리도록 하겠습니다.
