### ISSUE TITLE
오류문의

### ISSUE THREAD

**Issue by j1soft** [plusfriend/auto_reply#261]
keyboard와 message를 생성했고 postman으로 테스트해 보면 정상적으로 데이타가 출력이 되는데
계속해서 "해당 프로픨의 자동응답 시스템이 응답을 하지 않습니다." 라는 메세지가 출력이 됩니다.

옐로우아이디는 @제이원소프트

**Comment by plusfriendteam** [comment]
5초 이내에 응답메세지가 오지 않아 타임아웃이 발생한 경우입니다.
