### ISSUE TITLE
문서 markdown 깨지는부분...

### ISSUE THREAD

**Issue by brendaniel** [plusfriend/auto_reply#262]
api 제공해주는것 너무나 감사한데...
\``` 코드블럭 안에 설명이 들어가있는데도 있고 아닌곳도있고
5.2번부터 보기가 힘들어요ㅠㅠ 부탁드립니다.

**Comment by kwanlae** [comment]
수정해서 pull request 보내놓은 상태입니다. 채택 여부는 모르겠지만, :)
https://github.com/kwanlae/auto_reply
로 보시면 될 것 같습니다. 내용은 전혀 변경 없습니다.

**Comment by brendaniel** [comment]
@kwanlae 감사합니다. 포크해갈게요.

**Comment by plusfriendteam** [comment]
@kwanlae 풀리퀘스트 감사합니다. 반영했어요.^^
