### ISSUE TITLE
응답 메시지 여러개 보낼 수 있는지요?

### ISSUE THREAD

**Issue by summsu84** [plusfriend/auto_reply#263]
안녕하세요, 자동응 답 API 이용시, 한번에 한개의 자동응답 메시지를 전송하는 형태로 되어 있던데요.
혹시, 자동으로 여러개의(약 2~3개) 메시지를 한번에 전송 할 수 있는지요?

**Comment by kwanlae** [comment]
#123 이슈 참고하세요.

**Comment by plusfriendteam** [comment]
안녕하세요 
현재는 지원하지 않고 있습니다. #123 내용 참고해주세요
