### ISSUE TITLE
신규 관리자 페이지 전환 관련 문의

### ISSUE THREAD

**Issue by enjoyseo** [plusfriend/auto_reply#264]
안녕하세요~

5월 말부터 신규 관리자페이지로 전환이 되는 것으로 공지를 받았습니다

예전에 기존 카탈로그형 메시지와 카카오스토리 연동이 되지 않을 예정이라고 하셨는데 확정인지요
-카탈로그메시지 (예 : https://plus-talk.kakao.com/plus/mini/page/v3/204955.html )
-카카오스토리 : https://story.kakao.com/ch/axa

위 두개가 신규에서는 더이상 사용할수 없는지 다시한번 확인 부탁드립니다

감사합니다 ^^

**Comment by plusfriendteam** [comment]
안녕하세요. 답변이 늦은 점 사과드립니다.

카탈로그 메시지는 개편되면서 더이상 서비스되지 않고 있고,
그리고 스토리 연동은 전환 초기엔 되지 않았지만 현재는 개발되어 연동이 가능하십니다.
카탈로그 메시지 대신 카드뷰를 생성하시고, 그 카드뷰 포스트를 첨부한 메시지를 발송하시면 카탈로그 메시지보다 더 뛰어난 사용성의 메시지를 발송하실 수 있으세요.
