### ISSUE TITLE
옐로아이디 API형 자동응답 질문드립니다

### ISSUE THREAD

**Issue by yhm9636** [plusfriend/auto_reply#265]
옐로아이디 API형 자동응답 관련 질문드립니다.

1)이 기능은 별도의 개발이 필요하다고 되어있던데 여기서 별도의 개발은 무엇을 말하나요?(구체적으로)

2)앱 등록하는 절차가 있던데요...여기서 앱이라면 별도로 제작한 앱을 말하는건가요? 저는 별도로 제작한 네이티브 앱을 가지고 있습니다.

3)key발급을 위해 앱을 등록한다고 되어있던데 여기서 key발급은 뭔지요? 무엇을 위해 발급받는건지요?

4)앱을 등록하여 앱 생성 후 API Document 버튼을 클릭해
자동응답 API 가이드를 확인하세요.=> API가이드에서 무엇을 하는건지요? 여기서 답변 시나리오 및 이벤트를 자유롭게 구성하여...라는 부분을 구현하는 것인가요?

답변은 어디를 통해 받는지요? 이메일로 가능하시다면 부탁드립니다. 감사합니다^^
yhm9636@naver.com

**Comment by plusfriendteam** [comment]
안녕하세요.
먼저 답변이 많이 늦은점 사과드립니다.

별도의 개발을 통해서 카카오톡 이용자가 플러스친구에세 보낸 메시지를 전달받고, 이에 대한 응답을 내려줄 수 있는 API 를 개발하셔야 합니다. 이는 http(s) restful api 여야합니다.
이렇게 개발된 앱을 관리자센터에서 등록을 하면 내부적으로 key가 발급이 되는데, 이 key 들에 대한 설명은 
[4. 용어 설명] 부분에서 확인 가능하십니다.
그리고 API 가이드에서는 개발에 필요한 필수 요소들을 확인하실 수 있구요, 답변 시나리오 및 이벤트를 자유롭게 구성하는 부분을 구현하시는게 맞습니다.
