### ISSUE TITLE
text 안에 url 링크 주소가 있는 경우.. 

### ISSUE THREAD

**Issue by Luke830** [plusfriend/auto_reply#266]
안녕하세요

<img width="496" alt="2017-04-11 1 49 39" src="https://cloud.githubusercontent.com/assets/25580452/24893291/c9ba2ae6-1ebd-11e7-9d38-4125021c4cc5.png">

해당 이미지는 보시면 text 안에 페이코 홈페이지 링크 주소가 들어가 있습니다.
링크 주소로 인해서 하단 별도의 링크 텍스트가 자동으로 생성 됩니다.

제가 궁금한 점은 이부분입니다. 하단 링크 이미지 생성을 막고 싶습니다.
즉, text 안에 url 링크 주소가 있어도 별도로 하단 링크가 안 생기도록 처리하고 싶습니다.

혹시 방법이 있는지 알려주세요.

**Comment by plusfriendteam** [comment]
안녕하세요 위사항은 링크가 있을경우 톡의 메세지가 처리하는 방식이고 
공통규약이여서 현재는 예외 처리되지 않고 있습니다. 
업무에 도움이 되셨으면 합니다.
