### ISSUE TITLE
Fail 415 : wrong keyboard initialization

### ISSUE THREAD

**Issue by webhacking** [plusfriend/auto_reply#269]
기재 URL 에서, Json 포맷으로 응답함.
Status 200 정상입니다.

위 에러 해당 레포 이슈에서 검색해보니 포맷이 잘못내려오거나 상태값이 틀리면 응답한다고하는데..;

**Comment by webhacking** [comment]
curl -XGET 'https://:your_server_url/keyboard'

해당 [문서](https://github.com/plusfriend/auto_reply#specification) 참고함.

**Comment by webhacking** [comment]
여전히 안됨. :qatar:

**Comment by kwanlae** [comment]
카카오 서버에서, 만드신 서버로
HTTP GET /keyboard 요청에 대해
{type: 'text'} 로 응답(헤더값은 Content-Type: application/json)을 보내주고 있는지 한번 확인해 보세요.

**Comment by intellectuel** [comment]
https://your_server_url/keyboard 뒤에 ? (물음표) 붙이던가 
또는 https://your_server_url/keyboard?type=buttons 이렇게 하니깐 Test 성공하더라구여..
옐로아이디 API 개발 가이드가 너무 부실함..
