### ISSUE TITLE
응답 메세지 photo 관련 문의사항

### ISSUE THREAD

**Issue by speedeng** [plusfriend/auto_reply#27]
https://www.meritzfire.com/default/images/common/bg_login_aftercon.jpg

사진크기는 137 * 100 이며 사이즈도 11.4kb 입니다.

자동응답 시스템이 응답을 하지 않습니다. 문제가 보고되어 처리 예정입니다. 다음에 다시 시도해주세요.

bot api 도메인과 동일해야 된다거나 그런 조건이 있나요?]

**Comment by plusfriendteam** [comment]
@speedeng 도메인등과는 상관이 없습니다.
유저 입장의 톡으로 받으신거라면 유저의 서버에서 카카오 서버로 응답하는 json이 오타가 있거나 규격이 안맞거나 할 수 있습니다. 
응답 json을 알려주시거나 조금더 자세한 정보를 알려주시면 문제를 파악하는데 도움이 될 것 같습니다.

**Comment by speedeng** [comment]
{"message":{"photo":{"width":"137","height":"100","url":"https://dn-m.talk.kakao.com/talkm/oWqohwO3le/TFkOcvPYbiBqKkzkdULCLk/i_g849a9qow5411.jpeg"},"text":"등록되었습니다."}}

이렇게 입니다. 감사합니다.

참고로 아이폰에서 테스트 중입니다.

**Comment by humit0** [comment]
{"message":{"photo":{"width":137,"height":100,"url":"https://dn-m.talk.kakao.com/talkm/oWqohwO3le/TFkOcvPYbiBqKkzkdULCLk/i_g849a9qow5411.jpeg"},"text":"등록되었습니다."}}

로 변경해보시기 바랍니다.

**Comment by plusfriendteam** [comment]
@humit0 감사합니다!

**Comment by speedeng** [comment]
**@humit0**  감사합니다 ㅎ
