### ISSUE TITLE
API 자동응답 제작에 관련하여..

### ISSUE THREAD

**Issue by cjj0125** [plusfriend/auto_reply#270]
옐로아이디 API형 자동응답 관련 질문드립니다.

1)이 기능은 별도의 개발이 필요하다고 되어있던데 여기서 별도의 개발은 무엇을 말하나요?(구체적으로)

2)앱을 등록하는 절차가 있다는데.. 제작 및 등록과 관련한 안내 매뉴얼이 있나요?

3)key발급을 위해 앱을 등록한다고 되어있던데 여기서 key발급은 뭔지요? 무엇을 위해 발급받는건지요?

4)앱을 등록하여 앱 생성 후 API Document 버튼을 클릭해
 
답변은 어디를 통해 받는지요? 이메일로 가능하시다면 부탁드립니다. 감사합니다^^
cjj0125@naver.com

**Comment by plusfriendteam** [comment]
우선 
https://github.com/plusfriend/auto_reply/blob/master/README.md
를 참고해 주시면 위질문에 도움이 되실것으로 생각됩니다. 
검토하시고 추가 설명이 필요한 부분이 있다면 코멘트 주시면 답변드리도록 하겠습니다.
