### ISSUE TITLE
해당 프로필에 자동응답시스템이 응답하지 않습니다. 오류에 대해서

### ISSUE THREAD

**Issue by j1soft** [plusfriend/auto_reply#271]
@제이원소프트

keyboard 테스트는 정상적으로 200ok라고 테스트가 되었고 설정한 대로 버튼도 정상적으로 출력이 되어 집니다.
message파일도 프로그램 작업을 했는데 버튼 클릭시 위 오류가 표시가 됩니다.

curl을 이용해서 message에 post 전송하면 정상적으로 값이 출력되어 지는데 뭐가 문제인가요?

**Comment by plusfriendteam** [comment]
5초 내에 메세지 응답이 오지 않아서 타임아웃이 발생한 경우입니다.
서버 설정 혹은 네트워크 상태에 대한 확인이 필요해보입니다.
