### ISSUE TITLE
오류문의

### ISSUE THREAD

**Issue by j1soft** [plusfriend/auto_reply#272]
[관리자에게만 발송되는 메시지입니다] 사용자 봇서버에 에러가 감지 되었습니다. 
 내용:[잘못된 응답입니다. response json parsing error. user_key : fqURqCGof1dN, You'r server response : {
    "type" : "buttons",
    "buttons" : ["문제 풀기", "나가기"]
}]

위와 같은 오류가 발생합니다.

프로필명 @제이원소프트

**Comment by pcappli** [comment]
@j1soft 
보내실 때 json형태를 잘 못 보내면 위 오류가 발생합니다.
