### ISSUE TITLE
자동응답 시간 관련

### ISSUE THREAD

**Issue by summsu84** [plusfriend/auto_reply#276]
안녕하세요,
이번에 옐로아이디가 
플러스 친구로 변경된다고 하던데요..
혹시 플러스 친구로 변경되면서, 자동응답 타임아웃시간 5초로 그데로 인가요?
혹시, 추가 비용을 지불하는 방법과 같이 타임아웃 시간을 늘릴 수 있는 방법이 혹시 있는지요?
감사합니다.

**Comment by plusfriendteam** [comment]
관련해서 #281 참고해주시면 감사하겠습니다.
