### ISSUE TITLE
자동응답 API 관련 문의 드립니다.

### ISSUE THREAD

**Issue by anji1219** [plusfriend/auto_reply#277]
자동응답 API 관련 문의 드립니다.

앱URL
1. 앱 URL을 여러개 생성할 수 있나요?
2. 앱 URL 변경을 옐로아이디 관리 페이지가 아닌 API 형태로 제공하고 있는지요?

테스트 방안
1. 테스트 서버와 상용 서버를 별도로 운영하려 합니다. 
테스트를 위한 베타 버전의 앱을 위한 방안이 혹시 있는지요? 
(없다면 별도 테스트용 옐로 아이디를 만들어야 하는지요?)

가이드 부탁 드리겠습니다.
감사합니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 먼저 답변이 늦은점 사과드립니다.

앱 URL은 한개만 등록이 되고, 관리자센터가 아닌 API로는 제공을 하고 있지 않습니다.

테스트 방안에 대해서 답변을 드리면, 별도의 테스트 환경이 없기 때문에 
말씀하신 방법대로 테스트용 플친을 생성해서 테스트 하시는 방법이 좋을 듯 합니다.

감사합니다.
