### ISSUE TITLE
자동응답 타임아웃 시간 관련

### ISSUE THREAD

**Issue by SeoktaeKang** [plusfriend/auto_reply#278]
안녕하세요. 
요청드릴 사항이 있습니다.
현재 자동응답 타임아웃시간 5초로 되어 있다보니 자동화된 시스템 구현에 있어서 어려움이 있습니다.
현 5초에서 12초 정도로 변경할 수는 없는지요?
일부 시스템이 약 7초에 응답을 하다보니 바로 timeout에 걸려서 서비스를 구현할 수가 없습니다.
시스템에 부하가 많이 걸리겠지만 검토 좀 부탁 드리겠습니다.

**Comment by plusfriendteam** [comment]
issue #281 참고해 주세요
