### ISSUE TITLE
카카오톡 옐로아이디 자동응답 간헐적 비활성화 상태 (하단 회색 홈버튼 출력) 이슈 (아이폰) 

### ISSUE THREAD

**Issue by seoav99** [plusfriend/auto_reply#279]
안녕하세요.
카카오톡 자동응답 API를 custom하게 연계해서 이용하고 있습니다.
옐로아이디 자동응답이 접근시 간헐적으로 비활성화 상태로 빠지면서, 하단에 회색 홈버튼 출력이 나타납니다.
여러개의 옐로아이디를 프로파일로 갖고 있습니다만, 특정 아이디만 그런 현상을 보이고 있습니다.
이유를 알수 잇는지요? 아니면 특정 아이디에 연결된 카카오서버가 문제 있는 것일까요?
확인부탁드립니다. 
(profile id : dbcb_test)

**Comment by plusfriendteam** [comment]
안녕하세요 
위 증상은 서비스의 안정성을 위하여 운영상에 정책이 있습니다. 
24시간에 1000건의 응답지연등에 대한 오류가 발생하면 비활성화 상태로 설정을 변경하도록 시스템에서 
제어 하고 있습니다. 위상황은 그런상황에서 발생한 오류입니다. 
감사합니다.

**Comment by seoav99** [comment]
답변 감사드립니다. 주신 답변을 명확히 이해하고자 한번더 질문드립니다. 그렇다면 상기처럼 간헐적인 초기 진입 응답지연이 발생하는 오류가 발생하는 본 프로필 아이디에 대해서는, 외부사용자가 접속하여 24시간안에 1000번 이상의 응답지연을 발생시키면 계속해서 본 오류는 지속된다는 의미인가요? 언젠가부터 24시간에 1000번 이상 응답지연을 안발생시키면, 자연스럽게 본 이슈는 해결된다는 의미인지요?

**Comment by plusfriendteam** [comment]
안녕하세요 답변이 늦었습니다. 
저희가 24시간은 하루를 기준으로 1000번이상의 오류 응답지연일경우 서비스 안정성을 위해서 비활성화로 전환된다고 보시면 되겠습니다. 또한 확인후에 관리페이지에서 활성으로 변경하시면 다시 서비스 하실수 있습니다. 
또한 임의로 시스템에서 다시 활성화는 하지 않고 있습니다.
많은 도움이 되셨으면 합니다. 
조금 빠르게 답변 드릴수 있도록 하겠습니다. 감사합니다.
