### ISSUE TITLE
자동응답API 메뉴 규격 관련

### ISSUE THREAD

**Issue by SeoktaeKang** [plusfriend/auto_reply#28]
안녕하세요.
카카오톡 자동응답API를 이용하여 톡주문 서비스를 구현한 LG CNS의 강석태 차장입니다.

다름 아니라.. 현재 키보드API 규격에는 기존 방식과 달리 메뉴를 사용자가 접근하는 방법이 
메시지를 직접 입력하는 방법(예를 들어, 메뉴를 입력하면 키보드API가 활성화) 밖에는 없는데..

실제 서비스를 구현하다보니 사용자들의 불편에 대한 목소리가 많이 나오고 있습니다.
(GS 뿐만 아니라 CJ 고객들도 실제 써보면 메뉴를 접근하는게 너무 어렵다고 호소하고 있습니다).

채팅을 하다고 처음부터 다시 시작하려고 하면 가이드가 없어서 Session이 끝날 때까지 기다리는 고객들도 많이 나오고 있습니다.

현재 키보드API 방식 외에 대화창에 # 검색이 노출되는 것 처럼 메뉴를 누를 수 있게 Toggling될 수는 없는지요?

고객Voice에 대한 Back Data가 필요하시면 별도로 전송해드리겠습니다.

바쁘시겠지만 이 부분에 대한 검토 부탁 드리겠습니다.

감사합니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 
문의주신 내용에 보면, <사용자가 메뉴를 접근하는 방법이 메시지를 직접 입력하는 방법밖에 없다>고 말씀주셨는데요.
플러스친구/옐로아이디 2.0 API에서 제공하는 Home Keyboard API 를 이용하시면 사용자가 채팅방에 들어왔을 때 바로 키보드 영역에 사용자가 선택하여 시작할 수 있는 키워드를 표시해줄 수 있습니다. 구버전 봇을 이용하셨다면, 구버전 UI에서 제공했던 상담원 아이콘을 클릭했을 때 나오는 시작 키워드의 모음과 동일한 용도로 Home Keyboard API를 구성해서 사용하실 수 있습니다.

또한 중간에 처음으로 돌아가는 기능을 제공하고 싶으신 경우, 각 단계별 키보드의 선택항목 중 하나로 Home Keyboard로 돌아가는 명령어를 삽입하실 수 있습니다. 필요하신 단계에서 자체적으로 구현해주시면 됩니다. 

혹시 답변드린 내용이 문의에서 의도하신 바와 다른 경우에는 다시 한번 말씀 부탁드립니다. 감사합니다.

**Comment by SeoktaeKang** [comment]
안녕하세요.. 위에 말씀하신 부분 1) 채팅방 진입 시 Home Keyboard 메뉴, 2) 각 단계에서 키워드로 Home Keyboard 를 모두 구현하였습니다.

사용자들이 불편해 하는 것은 중간 단계에서 키워드를 입력해야 한다는 것 자체를 모르는데 있습니다. 메뉴라고 하면 보통 버튼 형태로 눌러야 한다고 생각하기 때문에 글자를 입력한다고 생각을 못하는 것이죠. 그래서 부득이하게 '다시 시작하시려면 메뉴를 입력해주세요'라고 모든 메시지에 넣는데 각 메시지에 모두 들어가니까 메시지 가독성이 떨어지고 사용자가 메시지의 의미를 잘 모르고 세션 종료될때까지 한참을 기다리거나 대화창을 나가버리는 문제가 발생하고 있는것이죠.

채팅은 익숙한 방식이지만 메뉴를 입력하는 방식은 생소한 것에서 기인한 것 같습니다.

바쁘시겠지만 검토 부탁 드리겠습니다.

**Comment by plusfriendteam** [comment]
@SeoktaeKang 네 좋은 의견 감사합니다.
저희도 유저들이 직접 명령어를 입력하는데에서 발생하는 불편함은 잘 알고 있습니다.

현재는 봇 프로세스를 구성함에 있어서 적절하게 버튼식으로 메뉴를 구성함으로 유저들이 조금더 쉽게 초기메뉴로 이동할 수 있게 짜는게 중요하다고 생각됩니다.

초기메뉴로 이동 할 수 있는 홈 버튼 또는 그에 상응하는 기능을 다음 API버전에서는 고려해 보겠습니다.

많은 관심 감사합니다.
