### ISSUE TITLE
자동응답 api 앱 등록할때 앱 URL엔 어떤 주소가 들어가는거죠?

### ISSUE THREAD

**Issue by ksj6543** [plusfriend/auto_reply#280]
옐로아이디를 이용해서 웹캠 제어를 해보고자 하는데 앱 등록에 URL을 어떤 주소를 입력해야 되는지 모르겠습니다...

**Comment by hmu332233** [comment]
본인의 서버 URL 주소를 넣으시면 됩니다!

**Comment by plusfriendteam** [comment]
안녕하세요 
서비스를 운영하시게 될 서버의 URL을 등록하시면됩니다.
https://github.com/plusfriend/auto_reply 
에 README파일을 참고해 주시면 감사하겠습니다.
