### ISSUE TITLE
자동응답관련 async callback

### ISSUE THREAD

**Issue by SungHyeJeon** [plusfriend/auto_reply#281]
현재 카카오톡은 라인이나 페북 웹훅과는 다르게 sync로 대답을 주게끔 되어있어,timeout와 같은 불편을 겪고있습니다. 
많은 이슈가 있으시겠지만, 혹 async 로 지원해 주실 가능성이 있는지 궁금합니다. 
그것이 불가능 하다면, 다른분들이 말씀하시는것과 같이 timeout 시간을 박아두신 5초가 아니라, 사용자의 인풋을 받아 새로 세팅할수잇는 api를 뚫어주실 수 있나요? 감사합니다.

**Comment by plusfriendteam** [comment]
안녕하세요 

현재는 session안에서 처리할수 있도록 하고 있습니다. 
ayanc 기능에 대해서는 일정과 정책등에 검토가 필요해서 지금은 시일을 말씀드리기가 입장은 아니구요 
관련한 내용을 들을 검토하고 따로 기능업에 대한 고민을 해보도록 하겠습니다. 
지금은 말씀하신 기능을 지원하지 않고 있습니다.
