### ISSUE TITLE
API 자동응답 설정의 Home Keyboard API에 대해 질문

### ISSUE THREAD

**Issue by keultae** [plusfriend/auto_reply#282]
안녕하세요. @엠지기

https://github.com/plusfriend/auto_reply 문서의 "5.1. Home Keyboard API" Response에 keyboard 필드가 있는데, 예제는 
{
    "type" : "buttons",
    "buttons" : ["선택 1", "선택 2", "선택 3"]
}
로 되어 있는데, 다음과 같이 되어야 하는거 아닌가요?
{ 
    "keyboard": {
        "type" : "buttons",
        "buttons" : ["선택 1", "선택 2", "선택 3"]
    }
}
키보드 영역에 버튼을 표시하지 않기 위해서는
http(s)://:your_server_url/keyboard 요청시 응답을 공백으로 주거나 아래와 같이 지정하면 되나요?
{
    "type" : "text"
}
또는
{ 
    "keyboard": {
        "type" : "text"
    }
}

http(s)://:your_server_url/keyboard 요청시 자동응답 명령어 목록을 표시하지 않고 텍스트 문구를 표시할려면 어떻게 하면 되나요?
http(s)://:your_server_url/keyboard 요청에 대한 응답으로 "5.2. 메시지 수신 및 자동응답 API" Response 포맷의 필드명들을 모두 사용할 수 있는지 궁금합니다.

5.2. 메시지 수신 및 자동응답 API의 user_key로 사용자의 핸드폰 번호나 이름을 찾으려면 어떻게 해야하나요?

**Comment by plusfriendteam** [comment]
안녕하세요 
1. curl -XGET 'https://:your_server_url/keyboard' request에 명시적으로 keyboard가 표현 되어있어서 
따로 필드 구분을 하지 않아도 명시적으로 판단될수 있습니다. 

"type" : "buttons",
"buttons" : ["선택 1", "선택 2", "선택 3"]
}
2.키보드 영역에 버튼을 표시하지 않기 위해서는
{
"type" : "text"
}
로 처리하시는게 맞습니다.

3.  현재는 정책상 지원하지 않고 있습니다. 

감사합니다.
