### ISSUE TITLE
자동응답 API 문의드립니다.

### ISSUE THREAD

**Issue by samsamheamul** [plusfriend/auto_reply#283]
자동응답 API생성을 하려고 합니다.
앱 URL에는 어떤 URL을 넣는건가요?
확인 후 빠른 피드백 부탁드립니다.

가이드도 있으면 가이드 첨부하여 답변 부탁드립니다.

samsam@secondlist.co.kr

**Comment by humit0** [comment]
자동 응답 서비스를 운영하실 서버의 url을 입력하시면 됩니다.

**Comment by samsamheamul** [comment]
정확히 어떤 운영할 서버를 말씀하시는걸까요? 자사홈페이지, 엘로우페이지 url, 카카오스토리 url 모두 안되던데... 새로 생성해서 올리란 얘긴가요?? 정확한 답변 부탁드립니다.

**Comment by humit0** [comment]
정확히 말하자면 자동응답 API를 운영할 서버의 url을 입력을 해주시면 됩니다.

**Comment by samsamheamul** [comment]
그래서 저희 자사 홈페이지 url을 넣었으나 fail 이라고 떠서...
가이드는따로없는건가요

**Comment by humit0** [comment]
아마 fail이 뜨는 이유는 여기에 있는 README.md를 참조하지 않았기 때문에 그런 것 같습니다. 서버가 php로 되어있다면, https://github.com/humit0/kakao_auto_reply 로 구축을 하실 수 있습니다.

**Comment by plusfriendteam** [comment]
안녕하세요 
https://github.com/plusfriend/auto_reply#5-api-specifications 참고하시기 바랍니다. 
자동응답을 운영 하게될 자사의 서버에 참고 문서형태의 데이터가 표현이 되어야 합니다. 참고하시기 바랍니다. 
https://github.com/plusfriend/auto_reply 참고문서입니다.
