### ISSUE TITLE
자동응답 text 입력시 검색 알고리즘(조건, 정책)

### ISSUE THREAD

**Issue by minibigman** [plusfriend/auto_reply#285]
자동응답 기능중 사용자가  text를 직접 입력시 노출되는 결과의 메시지 검색 알고리즘에 대해 파악 할 수 있도록 어떤 정책에 따라 결과를 노출하게 되는지 설명 부탁드려요.
-keyboard 와 message 의 관계 ..

**Comment by plusfriendteam** [comment]
지금 주신 말씀이 구체적으로 어떤것에 대한 문의인지 답변이 어렵습니다. 
조금 구체적인 질문을 주시면 확인하고 정리해서 답변드리도록 하겠습니다. 
감사합니다.
