### ISSUE TITLE
user_key, type, content외에 추가로 받을 수 있는 정보가 있나요?

### ISSUE THREAD

**Issue by hotbloodf** [plusfriend/auto_reply#286]
안녕하세요.
@열혈패밀리 입니다.

유저가 텍스트를 입력하면 서버에서 수신을 받게 되는데 
user_key, type, content외에 추가로 받을 수 있는 정보가 있나요?

시나리오가 길 경우 동일한 답변을 들어 올 수 있는데 
동일한 답변일 경우 구분해 줄수 있는 값이 없어서요 

밥을 먹었나요? 
예
물은 마셨나요?
예
여기서 예가 두번 반복되는데 구분해줄수 없어서요

혹시 content에서 표시는 안되지만 구분해줄수 있는 방법(이미지의 넣는 것처럼 예시 : alt="설명")이나 
위의 필드 말고 추가로 더 있는지 궁금합니다.

**Comment by plusfriendteam** [comment]
안녕하세요 아직까지는 저희가 메세지에 대한 구분자값을 드리고 있지 않습니다. 
진행에 참고해 주세요 감사합니다.
