### ISSUE TITLE
자동응답 API  message 관련해서 질문있습니다

### ISSUE THREAD

**Issue by ksj6543** [plusfriend/auto_reply#289]
예제를 보며 따라가던중 message에서 막혀서 질문 드립니다. 

버튼을 만들고 그에 맞게 message.php파일을 만들었는데 실제로 적용해보면

대화창에서는 

"해당 프로필의 자동응답 시스템이 응답을 하지 않습니다. 문제가 보고되어 처리 예정입니다. 다음에 다시 시도해주세요." 

라고 뜨네요... 어떤 부분에서 문제가 있는지 알 수 있을까요? 

페이지 이름은 inuESE 입니다. 아래는 제가 작성한 코드입니다.

![sdf](https://cloud.githubusercontent.com/assets/28589121/26311372/08a2c38e-3f3f-11e7-91f8-cad5c0509ea1.PNG)

**Comment by plusfriendteam** [comment]
안녕하세요 메세지 포맷은 맞는것 같은데요 
위와 같은 에러는 http response code 가 200이 아닌경우와 
json format이 안맞는경우인데요 

말씀주신 호출 url이  http(s)://:your_server_url/message로 끝나야 됩니다 
해서 php지시자 없이 rest방식으로 제공해서 테스트 해주시면 좋을듯 합니다.
