### ISSUE TITLE
플러스친구 API 2.0 ver 일대일 대화 설정 메뉴 이슈

### ISSUE THREAD

**Issue by infobankimedia** [plusfriend/auto_reply#29]
안녕하세요. 인포뱅크 iMedia 사업부 김지황입니다.

기존의 EBS 보니하니 플친 계정을 옐로우아이디(API 2.0)으로 이관 하면서, 해당 일대일 대화 설정 메뉴가 안보여서 문의 드립니다.

![default](https://cloud.githubusercontent.com/assets/19382791/16028680/8c374b7e-321c-11e6-82ad-4eb62d3f7a31.PNG)

첨부된 이미지와 같이 옐로우 아이디로 접속시 일대일 대화 메뉴를 통해서 대화설정 on/off 가 가능 한데, EBS 보니하니 플친 계정(@ebstv)으로 접속시 해당 메뉴가 보이 지 않아 문의 드립니다.
(추가적으로, 과거 엠넷 계정(@엠넷) 2.0 API 적용시, 해당 메뉴를 통해서 1:1 대화를 off 시켰습니다.)

현재 @ebstv 로 접속 하여, 입력시, 입력폼 우측에 1:1 버튼을 숨기고 싶은게 목적입니다.

해당 1:1대화를 통해 입력시, '죄송합니다. 상담을 지원하지 않는 프로필입니다.' 라는 문구가 노출 되어, 참여자에게 혼돈을 줄 수 있어 숨길려는게 목적입니다. 
(참고로, 플러스 친구이니 1:1대화는 필요하지 않습니다.)

현재 진행 중인 서비스 이므로 빠른 확인 부탁드립니다.

감사합니다.

**Comment by infobankimedia** [comment]
혹시, 플친 권한에서 해당 메뉴를 hide 처리 하신거 같습니다. 엠넷 슈스케와 뮤직톡의 적용 시점은 5월 2일 입니다. 이당시에는 '일대일대화' 메뉴가 존재하였습니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 플러스친구 관리자툴에서는 일대일대화 메뉴가 노출되지 않도록 설정되어 있습니다. 
문의주신 카톡에서의 1:1대화 버튼은 보이지 않도록 처리해 드렸으니 확인 부탁드립니다. 감사합니다.

**Comment by infobankimedia** [comment]
추가 적으로 5개 방송국 플친 이관이 남아 있는 상태입니다. 이경우에도 따로 요청을 드려야 하나요? 아니면 플친의 경우 일괄 1:1대화가 사라지게 적용을 한건가요?

만약 따로 요청을 들려야 한다면 진행은 어떻게 해야 하나요?

**Comment by plusfriendteam** [comment]
네 5건이라면 따로 요청 주시면 동일하게 처리해 드리도록 하겠습니다. github 코멘트로 전달주셔도 되고, 개별적으로 전달을 원하시는 경우는 plusfriend_api@kakaocorp.com 메일로 전달주셔도 됩니다.

**Comment by infobankimedia** [comment]
아직 이관 전인 5개 방송사(현 API 1.0)에 해당 1:1대화 처리 시, API 1.0이 종료 되거나 하지는 않는거죠?

**Comment by plusfriendteam** [comment]
아직 API 2.0으로 변경 전인 프로필이 총 9개 있다는 말씀이시군요. 앞서 처리해드린 내용은 2.0 변경 후 위와 같은 현상이 발생하는 경우에 해당하는 것이므로, 아직 변경하지 않으신 프로필에 대해서는 처리해드릴 수 없는 부분인 점 양해 부탁드립니다. 2.0 변경 후 동일한 문제가 발생하는 경우에 다시 확인 요청해 주시면 처리해 드리도록 하겠습니다.

**Comment by infobankimedia** [comment]
안녕하세요. 인포뱅크 김지황입니다.

금일 4시 20분 부로 극동방송(@FEBC극동방송), API 1.0 -> 2.0 이관이 완료되어, 채팅창내에 1:1대화 숨김처리 요청 드립니다.

추후 이관 완료 후, SBS 2개, CBS 5개, EBS 1개 요청 드리도록 하겠습니다.

감사합니다.

**Comment by infobankimedia** [comment]
안녕하세요. 인포뱅크 김지황입니다.

위에 요청 드린 극동방송 1:1대화 숨김 요청이 아직 미처리 되어, 다시 요청드립니다.

현재 서비스 중이므로, 빠르게 처리 부탁드립니다.

감사합니다.

**Comment by plusfriendteam** [comment]
@infobankimedia  
변경 처리 하였습니다. 
다음부터 요청 주실때는 새로 이슈를 만들어 주시거나, 이슈가 닫혀있을 경우에는 오픈처리해주시기 바랍니다.  
감사합니다.
