### ISSUE TITLE
message중에 photo 같이 보내게 하는게 안됩니다.

### ISSUE THREAD

**Issue by sinsu01** [plusfriend/auto_reply#290]
'message': {
          'text' : '안녕하세요'
                 },
        'keyboard' : {

           'type' : 'buttons',
           'buttons' : [
                	 '처음으로'
                       ]
                     },
	'photo' :{
		'url' : 'https://story.kakao.com/ch/homecc/fLVNNWQSJB0/photos/0',
		'width' : 640,
		'height' : 480
			}
                
위의 소스에서 사진이 안받아지는데 혹시 url에 있는 사진의 크기가 너무 커서인가 싶어서 크기가 작은 것들도 테스트를 해보았으나 해결하지 못하였습니다. 문제의 원인이 있다면 알려주시면 감사하겠습니다.
@sinsu01로 연력주시면 감사하겠습니다. 
sinsu01@hanmail.net  메일로 보내주셔도 됩니다

**Comment by sinsu01** [comment]
해결하였습니다... 답변이 없는게 아쉽습니다 ㅠ

**Comment by plusfriendteam** [comment]
안녕하세요. 
답변이 늦어진 점에 대해 사과드립니다. ㅠ
해결을 하셨다니 다행이네요.
다른 궁금한 점이 있으시면 다시 문의해주세요.
감사합니다.
