### ISSUE TITLE
앱 URL의 trailing slash (/) 관련 문의

### ISSUE THREAD

**Issue by rokoroku** [plusfriend/auto_reply#291]
안녕하세요. 카카오톡 옐로아이디와 플러스친구 통합 이후 전에 보지 못하던 이슈가 생겨서 제보드립니다.

기존에는 URL 끝에 slash가 붙어 있어도 kakao측에서 제거하고 요청을 보냈었던 것 같은데, 현재는 이 기능이 사라진 것으로 보입니다. 
예를 들어, 기존 `https://some.kakao.autoreply.com/endpoint/` 주소로 등록되어 있던 URL은 

> `https://some.kakao.autoreply.com/endpoint//keyboard`
> `https://some.kakao.autoreply.com/endpoint//friend`
> `https://some.kakao.autoreply.com/endpoint//message`
> ...

의 주소로 요청이 전송되어, 기존 서버에서 404 Not Found등의 response를 반환하게 됩니다. 
때문에 기존 URL을 사용하던 플러스친구 자동응답 기능에 장애가 발생하였습니다.

플러스친구 이전 작업에서 URL이 변경된 것인지, 아니면 기존 URL concatenation 과정에서 문제가 발생한 것인지 확인 부탁드리며, 가능하면 `trailing slash`를 허용하는 방향을 건의드립니다.

**Comment by plusfriendteam** [comment]
확인하고 답변드리겠습니다.

**Comment by plusfriendteam** [comment]
@rokoroku 
안녕하세요. 답변이 늦었습니다. ^^;
말씀하신 slash 문제의 경우 기존 옐로아이디 시절에도 있었던 문제입니다.
이걸 어찌할까 하다가 유저의 의도일 수도 있기 때문에 그냥 놔두고 있었거든요.
의도라기 보단 실수일 가능성이 더 높겠죠?
근데 당장 모든 url들의 끝에 붙어있는 슬래시를 다 제거하는것도 문제가 생길 수 있기 때문에
앞으로 url을 입력할 때 처리를 할까 하고 있습니다.
귀찮으시겠지만 당장은 직접 처리를 해 주셔야 하겠습니다. ^^;
