### ISSUE TITLE
"예상하지 못한 오류가 발생했습니다. 잠시 후 다시 시도해주세요."

### ISSUE THREAD

**Issue by pilwon** [plusfriend/auto_reply#292]
API 테스트 시,

```
Required*
   keyboard Fail
```

라고 뜨며 아래 alert 메시지 이후 어떠한 문제인지 알려주지 않아 문제해결이 어렵습니다.

```
예상하지 못한 오류가 발생했습니다. 잠시 후 다시 시도해주세요.
```

여러 호스트에서 http, https 둘 다 시도 해보았으나 같은 결과입니다.

**Comment by pilwon** [comment]
그동안 북미 서버에서만 테스트 했었는데 혹시나 해서 아시아 서버에서 돌려보니 성공했네요. 이 에러의 원인은 Latency 때문이었나요? Documentation 에는 5초 응답지연시간에 대해서만 언급되었을 뿐 latency limit 에 대한 정보는 없는데, 200-300ms 정도도 너무 큰 latency 로 간주되나요? Latency 를 재는 기준이 있으시면 공개 부탁드립니다. 또한, 해외 유저들이 대부분인 플러스친구 계정의 경우 서버가 해외에 있으면 Latency 를 줄일 수 있다고 생각했는데, Auto Reply 기능은 user device 의 위치와 무관하게 무조건 한국 서버를 거쳐가게 되어있나요?

**Comment by kwanlae** [comment]
주로 localhost 에 tunneling 으로 테스트하고 있었는데, 같은 오류가 발생합니다. 상용으로 사용하고 있는 국내서버에서는 정상동작 합니다.

**Comment by kwanlae** [comment]
한국을 제외한 해외 region 에 있는 서버에서는 같은 오류가 발생합니다. 긴급으로 처리 부탁드리겠습니다.

**Comment by pilwon** [comment]
일본, 싱가폴에 있는 서버에서도 성공적으로 돌아가는 것을 확인 하였습니다. 결국 Latency 가 특정 숫자를 넘어갈 때 발생하는 문제라고 생각합니다.

**Comment by kwanlae** [comment]
@pilwon 확인 감사합니다. :) 옐로우 아이디때는 문제가 없었는데, 빨리 조치가 되면 좋겠군요.

**Comment by hjjo** [comment]
같은 오류를 보고 있습니다. 
앱이 유럽 지역의 클라우드에 있으나 latency는 충분히 짧습니다.
카카오 관리자 페이지의 콘솔 상에는 500 Internal Error로 응답이 나오더라구요.

**Comment by deepseasw** [comment]
저도 같은 문제가 발생하네요.
서버는 북미에 있습니다.
현재 연결중인 챗봇은 정상적으로 동작하는데 API Test 버튼만 에러가 나네요.
Latency 보다는 카카오톡 쪽에서 막아놓은 것 아닐까요?
빨리 수정 부탁드립니다 ㅠㅠ

**Comment by dotnetpower** [comment]
저도 같은 문제가 발생합니다. 국내에서는 문제 없는데 해외에서는 문제가 생기네요.. 빠른 조치 부탁 드립니다.

**Comment by seosuho** [comment]
저도 같은 문제가 발생합니다 ㅡㅡ;; 빠른 조치 부탁드립니다.

**Comment by seosuho** [comment]
저도 같은 문제가 발생합니다 ㅡㅡ;; 빠른 조치 부탁드립니다.

**Comment by dialogbox** [comment]
ngrok을 이용하고 있는데 동일한 문제가 발생합니다.

**Comment by plusfriendteam** [comment]
위 사항은 timeout을 조정하였습니다. 서비스 안정성을 위해서 느끼시는 timeout 시간은 5초입니다. 
운영에 문제가 있으시면 의견 부탁드리겠습니다.

**Comment by kwanlae** [comment]
처리해 주셔서 감사합니다.
테스트해 보니 정상동작은 하는데요, 옐로우아이디와 플러스친구 통합 이전에도 5초이내로 응답이 왔던 상황이었는데, 이번 통합시 timeout 설정이 5초 이내로 잘못 세팅 되어 발생했던 문제였던건가요?
