### ISSUE TITLE
message에서 이미지 보내기

### ISSUE THREAD

**Issue by ksj6543** [plusfriend/auto_reply#294]
예제를 하나하나 천천히 따라해 보고있는데 메세지에 이미지를 첨부해서 보내는 부분에서 막혔습니다...

예제를 보면
{
  "url": "https://photo.src",
  "width": 640,
  "height": 480
}
이런 형식으로 보내라고 되어있어서 제 php 코드에서

echo << EOD
{
    "photo" : {"url" : "http://server_url/image.jpg", "width" : 720, "height" : 640}
}
EOD;

이런 형식으로 작성했는데 작동이 안되서 질문 드립니다.

http://server_url/image.jpg를 인터넷 창에 치면 제가 원한는 사진은 뜨는데 혹시 저부분에 다른게 들어가야 되는건가요?

버튼을 눌렀을 때 오류는 안뜨는 걸로 봐서는 처리는 하는거 같은데 사진은 안보내지네요...

답변 부탁드립니다.

**Comment by sinsu01** [comment]
http://tv02.search.naver.net/ugc?q=http://post.phinf.naver.net/20160423_199/selleope2_1461351763498IPlMR_PNG/mug_obj_201604230402478825.jpg

이거가 url에 넣어서 되시면 코드는 문제가 없는거구 용량의 문제일 수 있습니다.
아니라면 코드에 문제가 있는겁니다.
저랑 비슷한 문제같지만 php로는 안짜봐서 정확하게는 모르겠네요
저는 다른방식에 문제가 있어서 해결했습니다.
