### ISSUE TITLE
와이드형 메시지 이용이 가능한가요?

### ISSUE THREAD

**Issue by enjoyseo** [plusfriend/auto_reply#295]
안녕하세요 ~

자동응답 api를 이용해서 응답을 하면 현재
text는 기본형으로만 나가고 있는데요
새로 추가된 와이드형으로도 응답이 가능한가요?

수고하세요~^^

**Comment by plusfriendteam** [comment]
현재는 기능을 제공하지 않고 있습니다. 
다양한 기능들을고민하고 있습니다. 많은 의견 부탁드리겠습니다. 
많은 관심 감사합니다.
