### ISSUE TITLE
#292 와 동일한 이슈

### ISSUE THREAD

**Issue by kwanlae** [plusfriend/auto_reply#296]
#292 와 동일한 이슈 입니다. "예상하지 못한 오류가 발생했습니다. 잠시 후 다시 시도해주세요."

현재 테스트 진행에 어려움이 있는데, 언제쯤 해결이 될 수 있을까요?

**Comment by plusfriendteam** [comment]
#292 답변 참고해 주시면 감사하겠습니다.
