### ISSUE TITLE
'예상하지 못한 오류가 발생' test in IBM blue mix 

### ISSUE THREAD

**Issue by jihobak** [plusfriend/auto_reply#297]
#292 와 동일한 이슈로 생각됩니다.

현재 IBM BlueMix에 존재하는 영국, 독일, 미국남부, 시드니 서버에서 다 테스트를 해보았으나

똑같이 '예상하지 못한 오류가 발생했습니다. ~' 라고 시작하는 오류가 나타납니다.

빠른 해결 부탁드리겠습니다.

감사합니다.

**Comment by plusfriendteam** [comment]
#292 답변 참고해주세요
