### ISSUE TITLE
type 변경

### ISSUE THREAD

**Issue by SoreCarnival525** [plusfriend/auto_reply#298]
type을 button에서 text로 바꾸는 법은 없을까요? php를 사용하고 버튼을 누르면 type을 button에서 text로 바꾸고 싶습니다.

**Comment by plusfriendteam** [comment]
type은 button text를 같이 사용하고있습니다. 말씀주시건것은 동적으로 변경되는것을 요청 하신것으로 이해하는데요 그기능은 제공하지 않고있습니다.
