### ISSUE TITLE
api 오류 발생

### ISSUE THREAD

**Issue by jhcho3800** [plusfriend/auto_reply#299]
현재 문제점은 api 테스트를 할 수 있는 postman툴을 사용하면 연결이 잘 되지만
플러스친구 관리자 계정으로 접속하여 api 테스트를 하면
keyboard Fail 415
wrong keyboard initialization
오류가 발생합니다.

구글링을 해본 결과 방화벽 문제이며
ip를 aws에서 허용 해주어야 한다고 하여 aws에서
Security Groups -> Launch-wizard-1 -> InBound에 들어가
110.76.143.234/32
110.76.143.235/32
110.76.143.236/32
를 허용해 주었으나 계속 같은 오류가 발생합니다.

어떻게하면 이 오류를 해결할 수 있을까요?

**Comment by plusfriendteam** [comment]
저도 확인해보겠습니다만 저희쪽에서 요청 하는 IP가 공인 아이피인가요?
kakao --> aws 접속하는 서버의 Public IP 말씀부탁드립니다.

**Comment by jhcho3800** [comment]
오류 해결하였습니다.
aws 가입 시 설정을 잘 못하여 발생한 문제였습니다. 감사합니다.

**Comment by work8** [comment]
jhcho3800 님 어떤 설정을 잘못하여 발생하셨나요.

저도 동일한 오류가 발생하여 여쭤봅니다.
