### ISSUE TITLE
동영상 문의 드립니다. 

### ISSUE THREAD

**Issue by infobankimedia** [plusfriend/auto_reply#3]
안녕하세요 인포뱅크 류병현입니다. 

엠넷 플러스 친구 계정으로 슈퍼스타k8 동영상 지원 참여를 받고 있는데요. 
5월 13일(금)이후부터 오늘까지 지원한 동영상을 다운받을때, 
소리는 정상적으로 나오지만 화면이 다시 처음으로 돌아가 반복해서 재생되는 현상이 발생되고 있습니다. 
대부분의 파일은 오류가 나는 상태이고, 일부는 정상적인 파일이 다운로드 된다고 합니다. 

확인 부탁 드립니다. 
감사합니다. 

참고로 아래 파일을 새로운 인터넷창에서 열면 열리네요.
[정상파일]
[http://bigfile.mail.naver.com/bigfileupload/download?fid=4/eCM6J516mjK3Y9KAuwFqMlFxv9HqUmKxMmFxurKxtqFxEdHqudFoMmKAUXaxvjKxpoaxtrKqv/ax0oKzEwKx00az3oKqK9KA0SFxMdpxg=](url)

[오류파일]
[http://bigfile.mail.naver.com/bigfileupload/download?fid=4/eCM6J516mjK3Y9KAuwFqMlFxv9HqUmKxMmFxurKxtqFxEdHqudFoMmKAUXaxvjKxpoaxtrKqv/ax0oKzEwKx00az3oKqK9KA0SFxMdpxg=](url)

**Comment by suya55** [comment]
@infobankimedia 안녕하세요.
첨부해주신 링크는 메일로 파일을 받은것 같은데 위 주소를 확인이 어렵구요.( 적으신 링크는 네이버 메일의 첨부파일 링크입니다.)
비디오 타입으로 파일을 받으셨다면 비디오 파일의 주소정보를 알려주셔야 확인이 가능할 것 같습니다.
제가 임의로 @엠넷에 테스트를 해보았는데요.. 일단 정상으로 확인이 됩니다.
비디오 파일이 저희 카카오서버에 전송이되서 저장이 된 후 링크를 자동응답 API로 주고 받게 되는건데요.
만약 파일이 오픈되었을때 문제가 있다면 여러가지 이유가 있을 수 있습니다.
파일을 보낸 유저의 네트웍이 좋지 못하여 파일이 깨졌을 수 도 있구요.
많은 종류의 기기들이 같은 형태로 동영상을 저장하는게 아니다보니 동영상의 포멧이 다를 수 도 있습니다.
문제가 있다고 생각되시는 동영상의 비디오 링크를 알려주세요.

**Comment by infobankimedia** [comment]
말씀하시는 API를 통해서 인입된 동영상 비디오 링크는 아래와 같습니다. 
http://dn-v.talk.kakao.com/talkv/wkJDlpOqSs/kuq1HnEdwNZgqgMjhbnewK/talkv_high.mp4

**Comment by suya55** [comment]
@infobankimedia 이 건은 사내의 동영상 시스템쪽에서 확인을 해주셔야 하는부분이라 확인시간이 조금 거릴것 같습니다. 확인후 답변 드리겠습니다.

**Comment by suya55** [comment]
@infobankimedia 해당 문제는 2016/05/13 11:04 ~ 05/16 10:53 사이에 발생한 장애였음으로 확인되었습니다.
이후 장애는 복구되었습니다. 
현재는 이슈가 없는것으로 확인됩니다.

불편함을 드려서 죄송합니다.
