### ISSUE TITLE
자동응답API 아이폰 이미지 미노출 문제 관련 확인 요청 

### ISSUE THREAD

**Issue by SeoktaeKang** [plusfriend/auto_reply#30]
안녕하세요 

다름 아니라 CJ오쇼핑 톡주문 서비스에서
처음에 실시간 방송 주문을 누르면 아래 그림과 같이 현재 방송 상품에 대한 정보가 나오는데..

문제는 상품 이미지가 안드로이드에서는 나오는데 아이폰에서는 나오지가 않습니다.
모든 단말로 테스트 해봤는데 동일한 결과가 나오더군요.

 
자체 서버에 내장되어 메신저 대화창에서 보여주는 이미지들은 아이폰과 안드로이드 모두 정상적으로  #보여주는데..
 

CJ홈쇼핑 서버에 있는 이미지 URL을 가져와서 보여줄 때는 아이폰에서는 전혀 노출이 되지 않는 것 같습니다.

파일이나 이미지 첨부가 안되어서 화면을 보여줄 수 가 없네요.

캡쳐된 화면을 메일로 보내드릴 수 있는지요?
이메일 주소 좀 부탁 드립니다. 
 

바쁘시겠지만 확인 좀 부탁 드리겠습니다.

 

감사합니다.

**Comment by plusfriendteam** [comment]
메일은 plusfriendteam@kakaocorp.com으로 보내주시면 감사하겠습니다.

**Comment by SeoktaeKang** [comment]
방금 보내드렸습니다. 제 메일은 이메일 발송이 거부당해서 팀원 메일로 보냈습니다.

**Comment by SeoktaeKang** [comment]
메일로 보내드렸습니다~~ 급한 건이므로 필요하신 정보가 있으시면 010-9705-1003 으로 연락 주십시오

**Comment by plusfriendteam** [comment]
해당 이슈는 메일로 커뮤니케이션 하겠습니다.
