### ISSUE TITLE
api 테스트 오류발생

### ISSUE THREAD

**Issue by gogo2825** [plusfriend/auto_reply#300]
api 테스트를 하면
keyboard Fail 415
wrong keyboard initialization 오류가 발생하고 예상하지 못한 오류가 발생했다는 팝업창이 뜹니다.

110.76.143.234
110.76.143.235
110.76.143.236
위 3개의 ip모두 ufw를 이용하여 허용해놓은 상태 입니다.

현재 개발중인 작업은 nginx+flask+uwsgi를 이용한 서버구성 작업입니다.

다른글들 모두 답변 확인했는데 해결이 안되서 질문해봅니다..

해결방법  알려주시면 감사하겠습니다.

**Comment by plusfriendteam** [comment]
@gogo2825 
문제의 원인은 보통 다음과 같아요.
- 타임아웃
- 잘못된 결과값 리턴
GET /keyboard 요청 후 5초 안에 답이 오지 않으면 실패입니다.
GET /keyboard 요청 후 형식에 맞는 응답이 오지 않으면 실패입니다.
우선 외부에서 해당 서버로 GET /keyboard 요청시에 5초 내에 200 OK로 형식에 맞는 json 오브젝트가 내려오는지 확인해보시겠어요?

**Comment by gogo2825** [comment]
![image](https://user-images.githubusercontent.com/11566156/26963158-2f83a05a-4d26-11e7-9f8e-79d05e607951.png)
![image](https://user-images.githubusercontent.com/11566156/26963176-425902ec-4d26-11e7-9491-6e3f20da31c6.png)
테스트한 코드 내용인데 혹시 잘못된부분 있는지 확인 가능할까요..?

**Comment by plusfriendteam** [comment]
유감스럽지만 외부 코드에 대한 확인은 지원하고 있지 않습니다.
양해부탁드려요.
