### ISSUE TITLE
PHP파일에서 파이썬파일을 연동하여 메시지를 보내는방법이 궁금합니다.

### ISSUE THREAD

**Issue by abpq** [plusfriend/auto_reply#301]
저희 챗봇에서는 파이썬을통해 크롤링을하는데요
사용자에게 대화를 전송하는 부분은 PHP코드 내에서 처리를하는데
이 파이썬으로 크롤링한 내용을 어떻게 출력해야할지 잘 모르겠어서 질문드립니다.
 저희 PHP에서는 다음과 같은 형태로 출력합니다.
 echo new \kakao\Msg(new \kakao\Msg\Message("{$str}"), TRUE);
감사합니다!

**Comment by plusfriendteam** [comment]
@abpq 구현에 대해서는 저희가 답변을 드릴 수 없어요.^^;
