### ISSUE TITLE
자동응답 api 문의

### ISSUE THREAD

**Issue by mwjin7** [plusfriend/auto_reply#303]
안녕하세요.

현재는 한번의 호출에 대해 한번의 응답메시지만 가능한 것 같습니다...

사용자의 호출에 대해 응답메시지가 길 경우, 여러번에 나눠 보여주고 싶습니다..

ex) 사용자 : 안녕
      자동응답 api : 안녕
      자동응답 api : 반가워요

이런 형태로 구현이 가능한가요?

반복 리턴을 하려니..끝에 ] 문자가 하나 더 붙는다며 오류가 나네요..

postman 이나 기타 툴에서 테스트 할 때는 정상입니다..

**Comment by woongy** [comment]
불가능합니다 #123

**Comment by HayunJin** [comment]
가독성이 너무 안좋네요.. 빨리 업뎃 됐으면......
