### ISSUE TITLE
user_key가 변경되는 경우

### ISSUE THREAD

**Issue by woongy** [plusfriend/auto_reply#304]
> 카카오톡 이용자가 프로필을 차단했다가 다시 추가한 경우에는 user_key가 갱신되지 않으며, 이용자가 카카오톡 탈퇴 후 재가입한 경우 갱신됩니다.

탈퇴 후 재가입 이외에, 혹시 기기변경 혹은 장기간 카톡 미사용 등으로도 user_key가 바뀔 수 있나요?

**Comment by plusfriendteam** [comment]
@woongy 기기변경 후 카카오계정 로그인으로 기존 계정을 살리는 경우가 아니라면 새로운 계정이 생성됩니다. 즉, 탈퇴 후 재가입과 동일합니다.
장기간 미사용의 경우, 그사이에 기기의 os가 업데이트 되고 기기정보가 변경되거나 할 경우라면 동일한 계정으로 유지되지 않을 가능성이 있습니다. 그런 경우라면 기존 카카오계정으로 로그인 되어있지 않은 경우라면 user_key가 바뀔 가능성이 있습니다. 그런데 최악의 상황만 가정한거라 없다고 보셔도 될거에요.^^;
