### ISSUE TITLE
api 테스트 에러 문의

### ISSUE THREAD

**Issue by syc3800** [plusfriend/auto_reply#305]
전문지식이 없는 일반이용자 입니다.
api 앱 등록에 url 을 입력하고 테스트 버튼을 눌렀더니
에러 메세지 같은게 나옴니다.

keyboard Fail 415
wrong keyboard initialization

어떻게 해야 하는지 자세히 부탁 드림니다.

**Comment by lstar2397** [comment]
http://{등록하신 URL}/keyboard 세팅 하셨나요?

**Comment by syc3800** [comment]
안녕하세요?
 
API도큐먼트를 읽어 봤는데  제가 개발쪽이 아니라서 어떻게 세팅하는지를 잘 모름니다. ㅠ
세팅을 플친 관리자페이지에서 하는 것이 아니라 다른 방법으로 하는 것 같은데 그런가요?
전 그냥 관리자페이지에서 하면 되는줄 생각 했거든요.
 
일반이용자 수준으로 할 수 있을가요?
방법을 알려 주시면 정말 좋겠습니다.
 
부탁 드림니다.
 
 
-----Original Message-----

**Comment by plusfriendteam** [comment]
@syc3800 
관리자페이지에서 간단하게 하시려면 API형이 아니라 자동응답형을 쓰시면 됩니다. ^^
API형을 쉽게 사용하기 위해 설명을 드릴려면 소프트웨어 개발을 처음부터 알려드려야 하는데
지면과 시간이 부족하여 힘들것 같네요 ^^;;;
도움 못드려 죄송합니다. ㅠㅠ

@lstar2397 도움 감사드려요.^^

**Comment by syc3800** [comment]
자동응답형으로는 설문이 안돼서 그럼니다.
그럼 개발을 하려면 어떻게 해야 하는지 힌트 좀 주세요.
설마 개발을 모르는 사람은 api 사용하지 마라는 뜻은 아니시겠죠?
제게 꼭 필요합니다.
부탁 드림니다.
 
-----Original Message-----
