### ISSUE TITLE
혹시 홈페이지 이용하여 글보내기 가능한가요?

### ISSUE THREAD

**Issue by girlsapink** [plusfriend/auto_reply#307]
홈페이지에 글보내기 기능 이용하여 플러스 친구에 포스팅 되도록 하고싶은데

혹시 이게 가능한가요??

매번 플러스친구 관리자 페이지 접속하여 글 포스팅 하는게 상당히 번거롭더라구요.

api 이용하여 홈페이지 글작성하면 플러스친구 에도 글 포스팅 되도록 하고싶은데 가능한가요?

**Comment by plusfriendteam** [comment]
포스팅 api는 현재 제공하고 있지 않습니다.
검토해보도록 하겠습니다.
