### ISSUE TITLE
스마트채팅관련 문의

### ISSUE THREAD

**Issue by seosuho** [plusfriend/auto_reply#310]
카카오톡기반의 챗봇을 사용하기 위해 스마트채팅 (자동응답형, API형)을 꼭 사용해야 되는지요? 
스마트채팅이 아닌 다른 방법으로 챗봇연동이 가능한 솔루션이 있는지요? (예를 들면, 상담톡을 사용할 경우 스마트채팅을 사용하지 않아도 챗봇 연동이 가능한 방법이 있는지?)

**Comment by plusfriendteam** [comment]
지금으로선 제공되는 방법 외에 다른 솔루션은 없습니다. ^^
