### ISSUE TITLE
appkey 확인요청

### ISSUE THREAD

**Issue by shinkh1129** [plusfriend/auto_reply#312]
안녕하세요.
기존에 옐로 아이디에서는 App Key를 확인할 수 있었는데, 플러스 친구로 바뀌고 나서는 App Key를 확인할 수 있는 곳이 없어졌네요.
정확하게 어느 위치에서 확인해야되는지 자세히 알려주시기 바랍니다.
감사합니다.

**Comment by plusfriendteam** [comment]
앱키를 더이상 사용하지 않아도 되기 때문에 표시하는 부분을 제거하였습니다.
안쓰셔도 되요~
