### ISSUE TITLE
알림톡과 자동응답API연동 가능한지 여부

### ISSUE THREAD

**Issue by seosuho** [plusfriend/auto_reply#313]
동일한 플러스친구ID로 알림톡과 자동응답API연동이 가능하나요? 
카카오톡 공식딜러사를 통해 들은 내용은 알림톡과 자동응답API기반의 챗봇을 연동하면 알림톡기능은 사용할 수 있는데 자동응답API기반의 챗봇은 사용이 불가능하다는 말을 들어서 (1:1채팅창 비활성화 된다고 함) 확인차 문의 드립니다.

**Comment by plusfriendteam** [comment]
답변 들으신바와 같이 한개의 프로필에서 알림톡과 자동응답 API의 동시 사용은 불가능합니다.
