### ISSUE TITLE
플러스친구 관리자 앱에 있는 채팅목록

### ISSUE THREAD

**Issue by kwanlae** [plusfriend/auto_reply#314]
옐로우아이디 + 플러스친구 통합전에는, 스마트채팅으로 발생한 채팅은 (그당시) 옐로우 아이디 관리자의 채팅목록에 들어오진 않았던거 같은데요,

통합후에는 스마트채팅(자동응답 API 를 사용한 채팅)도 플러스친구 관리자 앱의 채팅목록으로 들어옵니다. 그러면서 푸쉬 노티피케이션도 같이 오는데, 이 노티가 없어지는 시점도 애매하고, 채팅방으로 접속하면 이전의 스마트채팅 대화목록이 시차를 두고 계속 들어오는 것이 눈으로도 확인가능한데요,

이것이 혹시 의도된 기능인가요? 예전처럼 플러스친구의 관리자앱(또는 페이지)의 채팅목록에는 직접 대화한 내용만 남고 API를 통한 자동응답 채팅 내용은 들어오지 않게 해 주실 순 없으신지요.

**Comment by plusfriendteam** [comment]
해당 현상은 의도된 동작입니다. 둘 사이의 구분이 모호하여 보기 어려운점은 개선할 수 있도록 하겠습니다. 조언 감사드립니다.
