### ISSUE TITLE
user_key 문의 및 건의사항

### ISSUE THREAD

**Issue by khj7744** [plusfriend/auto_reply#315]
user_key는 무조건 어디서나 자리수가 동일한가요?

'5.2. 메시지 수신 및 자동응답 API'에서 type의 설명으로 text, photo 밖에 없습니다.
미디어 타입(사진/동영상/오디오) 부분도 추가되어야 된다고 생각합니다. 확인바랍니다.

**Comment by plusfriendteam** [comment]
user_key의 길이가 동일하다고 보장할 수는 없습니다.
미디어 타입은 유저에게 답변을 보낼 때 보낼 수 있는 타입에 대한 설명입니다.
유저에게 동영상/오디오/사진을 받을 수 있지만 반대로 유저에게 보내는것은 사진만 가능합니다.
