### ISSUE TITLE
카카오톡 챗방 세션

### ISSUE THREAD

**Issue by samko635** [plusfriend/auto_reply#316]
안녕하세요, 카카오챗방 세션관련 문의가 있는데요

메뉴얼에는 10분이라고 나와있는데 실제로 테스트해보니 4-5분 사이에 끊겨서 initKeyboard 가 호출되는것같은데 실 세션시간이 얼마인가요?

**Comment by theseung** [comment]
카카오는 아니지만 대신 답변 드리면 개발하실 때는 실 세션시간 5분정도로 생각하고 개발하시면 됩니다.
#292

**Comment by samko635** [comment]
감사합니다~!
요즘 카카오가 깃허브 관리안하나보네요...

**Comment by plusfriendteam** [comment]
안녕하세요. 
확인이 많이 늦어진 점에 대해 정중히 사과드립니다.
다른 문의점이 있으시면 다시 말씀해주세요.
감사합니다.
