### ISSUE TITLE
테스트 서버 문의

### ISSUE THREAD

**Issue by rurara** [plusfriend/auto_reply#317]
kakao plus아이디를 이용하여 서비스를 만들고 있는데 이제 곧 서비스를 하게 될거 같은데 서비스 중일때 테스트를 하려면 어떻게 해야하나요?
새로 플러스 아이디를 만들어야 하나요?

**Comment by pcappli** [comment]
카카오에서 특별히 제공하는 테스트 방법은 없습니다.

저 같은 경우 api 테스트 페이지를 만들어 그것으로 테스트하거나 다른 플러스 친구가 있습니다.

**Comment by rurara** [comment]
불편하긴 하지만 그렇게 써야겠어요 
답변 감사드립니다 :D

**Comment by plusfriendteam** [comment]
안녕하세요.
현재 테스트 환경을 따로 제공하고 있지 않습니다.ㅠ
테스트 환경에 대한 필요성에 대해 내부적으로 검토해보겠습니다.
감사합니다.
