### ISSUE TITLE
개행 처리는 어떻게 하나요?

### ISSUE THREAD

**Issue by awds15456** [plusfriend/auto_reply#318]
IBM Watson API를 사용하고 있는데, 개행처리를 위해 어떤 처리가 필요한가요??

**Comment by pcappli** [comment]
보내는 문자에 \n을 포함하면 됩니다. 경우에 따라 에러가 발생하시면 \\n 입력해 주시면 개행 가능합니다.

**Comment by awds15456** [comment]
감사합니다. 해결되었어요!
