### ISSUE TITLE
keyboard 요청 후 에러 문의.

### ISSUE THREAD

**Issue by sheeh** [plusfriend/auto_reply#319]
안녕하세요.

앱등록 URL API TEST 성공 후 플러스친구와 대화를 하면 키보드 버튼은 정상 출력되나
버튼을 클릭하면 하기와 같이 에러 메세지를 출력하는데요, 
json 파싱이 어느 부분이 잘못 된것인가요?
keyboard 호출 시  : {"type":"buttons","buttons":["information"]}
message 호출 시 : {"message":{"text":"!!! WELCOME TO IO_DEV TEAM ERROR!!!}}

[관리자에게만 발송되는 메시지입니다] 사용자 봇서버에 에러가 감지 되었습니다. 
내용:[잘못된 응답입니다. response json parsing error. user_key : xxxxxxxxx, You'r server response : {"type":"buttons","buttons":["information"]}]
해당 프로필의 자동응답 시스템이 응답을 하지 않습니다. 문제가 보고되어 처리 예정입니다. 다음에 다시 시도해주세요.

확인 부탁드립니다.

감사합니다.

**Comment by kwanlae** [comment]
{"message":{"text":"!!! WELCOME TO IO_DEV TEAM ERROR!!!}}

에서 뒷부분 !!! 뒤에 따옴표가 없습니다. :)

**Comment by sheeh** [comment]
하기와 같이 수정하였는데도 "해당 프로필의 자동응답 시스템이 응답을 하지 않습니다. 문제가 보고되어 처리 예정입니다. 다음에 다시 시도해주세요." 라는 에러가 나옵니다..
HTTP Request 테스트 해본 결과 카카오 예제와 동일한 response 값이 나오는데 왜 에러가 나오는 것인가요~? 

답변 부탁드립니다. 

감사합니다.

keyboard GET 호출 시 response
{
    "type": "buttons",
    "buttons": [
        "info1",
        "info2",
        "info3"
    ]
}
message POST 호출 시 response 
{
    "message": {
        "text": "!!! WELCOME TO IO_DEV TEAM SUCCESS!!!"
    }
}

**Comment by ByungwooKang** [comment]
혹시...
Response Content-Type이 application/json이 아니라서 그런 건 아닐가요?

**Comment by sheeh** [comment]
첨부한 이미지와 같이 코딩하여쓴데요..
어떤 점이 문제인가요?


![default](https://user-images.githubusercontent.com/29564020/27363723-2934234c-5671-11e7-9b23-8a812edb21af.JPG)

**Comment by plusfriendteam** [comment]
안녕하세요. 
kwanlae 님께서 말씀하셨다시피, 
String 타입 데이터인 "!!! WELCOME TO IO_DEV TEAM ERROR!!!"
에 따옴표 텍스트(") 가 빠진듯 합니다.
