### ISSUE TITLE
unknown error 메시지 발생

### ISSUE THREAD

**Issue by gwuijeonglim** [plusfriend/auto_reply#32]
특별한 사용자 action이 없는 상태였는데 
대화창에 unknown error 라는 메시지가 수신되었습니다.

발생 원인 확인 부탁드립니다.

![_ api_unknown error](https://cloud.githubusercontent.com/assets/19964814/16103213/6a765b24-33b1-11e6-9971-e06fa6b069fb.jpg)

**Comment by plusfriendteam** [comment]
해당 메시지는 고객님의 봇 서버에 에러가 발생할 경우 관리자에게 발송되는 메시지 입니다. 
봇 서버의 에러를 확인해 보시기 바랍니다.

앞으로 에러 메시지가 발송 될 때, 관리자에게 발송되는 메시지라고 표기하여 전송 되도록 하겠습니다. 
감사합니다.
