### ISSUE TITLE
자동응답 문의드립니다.

### ISSUE THREAD

**Issue by sungwuk** [plusfriend/auto_reply#320]
초보 개발자인데  자동응답 api를 구현하던중에  앱등록 url 입력에서 오류가나 문의드립니다.

Home Keyboard API 스펙에 보면 url 란에  /keyboard라고 나와있는데 이건 php 파일을 말하는 것 인가요? 

스펙만보고 잘 이해가 되지 않아 문의드립니다.

**Comment by plusfriendteam** [comment]
안녕하세요.
/keyboard, 이 부분은 php 파일이 아닌 REST api 로 키보드 정보를 요청하는 url을 뜻하는 겁니다. 
즉, sungwuk 님의 개발서버에 "https://:your_server_url/keyboard" 이라는 형식의 url로 요청(GET)을 했을 때 그에 대한 응답을 내려줄 수 있도록 구현이 되어야 하구요.
