### ISSUE TITLE
카카오 친구플러스 API형 질문

### ISSUE THREAD

**Issue by bulue510** [plusfriend/auto_reply#322]
카카오 친구플러스 관리자 화면에서 스마트채팅 API형 테스트 중입니다.

크롬 포스트맨에서 API를 호출하면 JSON 형태로 데이터가 오는 것을 확인을 했습니다.

{
    "type": "buttons",
    "buttons": [
        "버튼1",
        "버튼2",
        "버튼3"
    ]
}

그런데 카카오에서 API테스트를 http://39.115.122.40/keyboard  하면 아래와 같은 에러메세지가 옵니다.
Required*
keyboard Fail 415
wrong keyboard initialization

어떤 문제인지 알수가 없어서 이렇게 문의 드립니다.

**Comment by since88** [comment]
저도 크롬플러그인에서 정상 동작하는데 플친 API TEST 하면 똑같은 에러가 발생하네요 ㅠ.ㅠ

**Comment by anpaul0615** [comment]
관리자페이지에서 API 테스트는 루트 URL 만 기입하면 됩니다.

실제로 위에서 말한대로라면 테스트 모듈은 http://39.115.122.40/keyboard/keyboard 를 호출하기때문에 정상적으로 동작하지 않겠네요.

**Comment by plusfriendteam** [comment]
@anpaul0615 님 답변처럼 /keyboard 부분을 빼고 입력하셔야 해요. 답변 감사드립니다~!
