### ISSUE TITLE
등록된 친구에게 메세지 발송 or 관리자에게 메세지 발송이 가능한가요?

### ISSUE THREAD

**Issue by EJShim** [plusfriend/auto_reply#324]
제 옐로우아이디를 등록한 특정 친구나 전체메세지, 혹은 관리자에게 메세지를 보내는 것이 가능한가요?

**Comment by plusfriendteam** [comment]
[카카오톡 비즈메세지](https://bizmessage.kakao.com)를 이용하시면 구현이 가능합니다.
