### ISSUE TITLE
미디어타입의 message전송에 대한 문의

### ISSUE THREAD

**Issue by roharon** [plusfriend/auto_reply#325]
api중 미디어타입의 message전송에 대한 코드에서

curl -XPOST 'https://:your_server_url/message' -d '{
  "user_key": "encryptedUserKey",
  "type": "text",
  "content": "차량번호등록"
}'

"encryptedUserKey" 문자열이 있는 곳에 유저키를 갖고있는 변수를 넣어야하는건가요?
또한, 미디어타입으로 전달된 것들을 서버에서 저장할 수 있는것인지 아니면, 카카오 관리자페이지에서만 다룰수있는것인지 궁금합니다

**Comment by plusfriendteam** [comment]
user_key는 유저를 구분할 수 있는 키입니다. 저희가 제공해서 보내드리고 있어요.
미디어타입으로 전송된 것들을 저장하는 기능을 구현하는것에 대한 제약은 없습니다.
다만 유저에게 동의를 구하거나 하는 정책/법률적인 부분에 대해서는 직접 관리하셔야 합니다.
저희는 따로 관여를 하지 않습니다.
