### ISSUE TITLE
json 내 유니코드는 자동 한글로 변환하나요?

### ISSUE THREAD

**Issue by pokapark** [plusfriend/auto_reply#326]
예를들어 입력값이 '한글' 이라면
여기에 해당하는 유니코드 값인
'\ud55c\uae00' 를 보여주고 싶습니다.
해당 값을 담았더니 자동으로
'한글'이라는 한글로 변환하여 보여지고 있는데,
혹시 이를 해결할 수 있는 방안이 있는지요?
서버는 php 입니다.

**Comment by humit0** [comment]
\\ud55c\\uae00 와 같이 이스케이프를 하면 될 것 같네요

**Comment by plusfriendteam** [comment]
@humit0 님 답변 감사드려요. urldecoding을 하셔야 합니다.

**Comment by pokapark** [comment]
답변 감사드립니다.
