### ISSUE TITLE
[기능제안] 1:1 버튼 활성화/비활성화를 프로그램에서 할 수 있도록.

### ISSUE THREAD

**Issue by kwanlae** [plusfriend/auto_reply#327]
현재는 1:1 채팅 버튼(입력창 오른쪽에 있는 1:1 이라고 적혀있는 아이콘 버튼) 활성/비활성을 관리자 화면의 [1:1 채팅설정 > 1:1 채팅 사용]의 ON/OFF 만을 통해 하고 있는데요,

이것을 프로그램내에서 선택적으로 조정할 수 있는 API를 제공해 주실 순 없으신지요.

즉, 사용자 입력에 대한 답변을 보낼때, 특정 flag 의 값을 true/false 토글링을 하게 해서 사용자의 다음 답변에서는 1:1 버튼이 아예 보여지지 않는다든가 하는 식으로 계정 단위가 아닌, 대화단위로 조정할 수 있었으면 좋겠습니다.

---
#314 issue 에 대해서도 답변 부탁드리겠습니다.

**Comment by plusfriendteam** [comment]
@kwanlae 시스템 구조상 위 부분을 제공해드리기에 어려운 점이 많습니다. 건의해주신 방법에 대해서는 인지하고 있었고 개선할 수 있는 방법을 찾고 있습니다.
