### ISSUE TITLE
[기능제안] Home Keyboard API 의 user_key 획득과 텍스트 메시지 표시

### ISSUE THREAD

**Issue by kwanlae** [plusfriend/auto_reply#328]
사용자가 최초 채팅방에 진입할때 호출되는 Home Keyboard API (/keyboard) 를 보면 /message API 와는 다르게 텍스트 표시 없이 오로지 버튼만 표시할 수 있고, 암호화 처리된 user_key도 획득할 수 없는 것으로 알고 있습니다.(혹시나 싶어 HTTP header 정보를 봐도 전달되는 user_key 는 없더군요.)

기술적으로는 /message API 와 동일한 스펙으로 가져가도 괜찮을 것 처럼 보이는데,(오히려 저 개인적으로는 더 명료해 지는 것 같습니다./keyboard 로 들어오는 GET 요청은

```
{
    "type" : "buttons",
    "buttons" : ["선택 1", "선택 2", "선택 3"]
}  
```
응답을 해야 하고,

/message 로 들어오는 POST  요청은
```
{
  "message": {
    "text": "귀하의 차량이 성공적으로 등록되었습니다. 축하합니다!",
    "photo": {
      "url": "https://photo.src",
      "width": 640,
      "height": 480
    },
    "message_button": {
      "label": "주유 쿠폰받기",
      "url": "https://coupon/url"
    }
  },
  "keyboard": {
    "type": "buttons",
    "buttons": [
      "처음으로",
      "다시 등록하기",
      "취소하기"
    ]
  }
}
```
이렇게 응답을 해야 하는데, 이것을 하나로 통일할 수 있을테니까요.)

GET /keyboard 요청에 대해서

1. user_key 전달
2. 응답부분에 버튼 외 text 를 표시할 수 있는 항목 추가(인사말이나 공지등으로 사용)

를 고려해 주실 수는 없으신가 해서 문의드립니다.

고맙습니다.

**Comment by roharon** [comment]
저도 keyboard에서 user_key가 전달되지않아서
사용자들이 한번의 과정을 더 거치는 불편함을 겪고 있습니다
해당 기능이 추가되면 더 간편해질거같네요

**Comment by plusfriendteam** [comment]
GET /keyboard 요청의 의도는 대화방 최초 진입시 모든 사용자에게 공통적으로 내용을 보여주기 위함입니다. 
클라이언트에서 캐시를 하기도 하고 해서 유저별로 다르게 처리를 하기 위한 방법을 제공해 드리기엔 어려움이 있습니다.

인사말 혹은 공지등을 공통으로 출력하는 기능을 제공하는것에 대해서는 검토해 보겠습니다.

**Comment by kwanlae** [comment]
GET /keyboard 요청시 user_key 는 같이 보내주고, 전체 사용자를 위한 공통된 내용을 보여줄지, 아니면 그 user_key에 대한 개별 내용을 보여줄지는 개발사가 선택하도록 하면 어떨까요. 

GET /keyboard 와 POST /message 에 대해 동일한 REST 형태로 응답을 주는 spec. 이 되었으면 좋겠습니다. :)
