### ISSUE TITLE
[기능제안] 카톡 업로드 이미지 사진 크기 통제 기능 

### ISSUE THREAD

**Issue by seoav99** [plusfriend/auto_reply#329]
안녕하세요.
카톡 자동응답 챗 환경에서도, 폰의 이미지의 현재 3가지 형태로 사용자가 취사해서 올릴수 있게 되어있는데요 (일반화질/고화질/원본). 혹시 이 부분을 챗봇 레벨에서 강제 지정을 할수 있는 API를 릴리즈하면 좋겠다라는 생각이 듭니다. 혹 계획이 있는지, 요청을 드려도 되는지요.

**Comment by plusfriendteam** [comment]
이미지 파일의 화질 관련 부분에 대해서는 개선의 계획은 있습니다만 구체적인 일정에 대해서는 확답을 드리기 어려운점 양해 부탁드립니다.^^
