### ISSUE TITLE
user_key 관련 입니다.

### ISSUE THREAD

**Issue by mcvzone** [plusfriend/auto_reply#33]
안녕하세요.

BOT_USER_KEY 가 API2.0 에서 아래의 user_key 와 똑같은 값이라고 말씀 해 주셨는데,
다른 값으로 전송받고 있습니다.

기존 BOT_USER_KEY 는 숫자로만 구성되었는데요.
API2.0 을 통해 요청되는 값의 USER_KEY 는 암호화 된 값이더라고요.

| 1. 암호화에 차이인 것인지요? 복호화 되면 똑같은 값이 되는 건가요? 아니면 아예 다른 값인가요?

| 2. 암호화에 따른 차이여서, 복호화 하면 똑같은 값이 될 경우에는, 복호화 할수 있는 방법이 있나요?

curl -XPOST 'https://:your_server_url/message' -d '{
  "user_key": "encryptedUserKey",
  "type": "text",
  "content": "차량번호등록"
}'

**Comment by plusfriendteam** [comment]
안녕하세요.
이전에 동일한 문의를 주셨습니다.
#17 이슈를 참고해주세요.

사용자는 user_key를 암복호화해서 사용하지 않습니다.
그대로 사용하시면 됩니다.
