### ISSUE TITLE
api test 오류확인

### ISSUE THREAD

**Issue by since88** [plusfriend/auto_reply#330]
크롬 플러그인 rest client로 테스트 시

Request URL: http://eldertree1.cafe24.com/keyboard
Request Method: GET
Response Time: 0.023 seconds
Response Status: 200 - OK

{
  "type": "buttons",
  "buttons": [
    "사진",
    "라벨",
    "에코메세지"
  ]
}

응답값이 제대로 넘어오나 카카오플러스친구에서 API TEST를 하면 

Required*

keyboard Fail 415
wrong keyboard initialization

위와 같은 에러가 납니다.  답변 부탁드립니다.

**Comment by plusfriendteam** [comment]
뒤에 "/keyboard" 를 제외한 " http://eldertree1.cafe24.com" 까지 입력후 다시 테스트 해보시겠습니까?
