### ISSUE TITLE
비공개 API 적용방법 문의

### ISSUE THREAD

**Issue by anpaul0615** [plusfriend/auto_reply#331]
안녕하세요,  비공개 API 적용방법에 대해서 문의드립니다.

현재 저희는 카카오봇에서 저희쪽 API를 정상적으로 호출하고 있는 상황입니다.

하지만 앞으로는 저희 API 서버를 카카오에서만 접근가능하도록 변경하려고 하는데요. 대략 생각하고 있는
방식은 저희가 발급한 인증키를 요청 헤더에 포함시켜서 API를 호출하는 것입니다. 헌데 카카오 플러스친구 관리자페이지에서는 API 서버 url 기입하는 곳 외에 별도의 헤더값을 넣을 수 있는 곳이 없는 것 같습니다.

다시말해서 카카오에 등록한 API 서버는 무조건 public API가 되어야 한다는 말같은데요.  서버자원을 아무나 사용할수 있도록 하는건 문제가 있지않을까요?

어떻게 하면 저희 API 를 카카오에서만 사용할 수 있도록 할 수 있는지 알려주시기 바랍니다.

**Comment by kwanlae** [comment]
현재는 앱 URL 외에는 플러스친구 관리자센터에 설정할 수 있는 항목이 없어서, 말씀하신 HTTP header 상에 별도의 키 값을 설정하실 수는 없을 것 같습니다.

일반적인 단어를 사용해서 유추 가능한 url path 때문에 걱정하시는 거라면, hash 형태의 키 값을 url path 상에 포함시켜 사용하시면 어떨까요. 카카오측에서 정식으로 키값을 헤더에 포함시켜 사용할 수 있게 해 주기 전까지는 아쉬운데로(?) 버틸 수는 있을 것 같습니다. :)

**Comment by humit0** [comment]
Readme 파일을 보시면 요청하는 IP 목록이 있으니 그 IP가 아닌 경우에는 에러 페이지를 보여주는 방식으로 구현하시면 되겠네요.

**Comment by plusfriendteam** [comment]
@humit0 님의 방법을 추천해드립니다.

**Comment by anpaul0615** [comment]
@kwanlae 
답변 감사합니다.
url 이나 header 를 저희가 컨트롤할 수가 없으니 별수없이 다른방법을 찾아봐야겠네요.
아래 humit0 님 말대로 네트워크 레벨에서 설정하는게 좋을 것 같아요.
해싱값을 url로 만드는 것도 좋은방법인 것 같아요.


@humit0 
답변 감사합니다.
현재로써는 API 서버의 네트워크 인바운드를 설정하는 방식이 최선인 것 같습니다.
