### ISSUE TITLE
카카오톡 링크 클릭시 이중 호출 관련

### ISSUE THREAD

**Issue by robinchoi** [plusfriend/auto_reply#333]
안녕하세요

카톡에서 메세지에 있는 링크를 클릭해서 모바일 웹으로 이동하게 구현 했습니다.
특정 폰(아이폰)에서 이 링크를 클릭 하면 호출을 두번 하는 현상이 있어 문의 드립니다.
이 웹페이지는 인스턴스키 값을 이용해서 이 값이 유효하면 정상적인 화면으로, 이 키 값이 유효하지 
않으면 경고페이지로 가도록 했는데요. 
아이폰에서 카톡 대화창에서 이 링크를 클릭 하면 동일한 호출을 두번하게 되어 정상적인 화면으로 가지 않고 경고페이지로 가게 되는 현상이 있어 문의 드립니다.
톰켓 로그에 보면 아래와 같이 두번 호출한 로그가 남습니다.

혹시 이런 경우 어떤 문제로 그러는지 답변 부탁드립니다.

![image001](https://user-images.githubusercontent.com/29878178/28253076-f93a0526-6ad9-11e7-9305-6bc101f255ec.png)

**Comment by plusfriendteam** [comment]
다음번 아이폰 카카오톡 업데이트시 수정사항이 반영 될 예정입니다.
