### ISSUE TITLE
카카오 챗봇 ACL 허용

### ISSUE THREAD

**Issue by gsk120** [plusfriend/auto_reply#334]
안녕하세요. 카카오 챗봇 방화벽 해제 관련하여 문의드립니다.

파트너사에서 3개의 Proxy 서버에 대한 ACL을 허용해야 한다고 문서에 적혀있는데

해당 Proxy 서버의 특정한 특정한 포트 번호는 필요없는지 궁금합니다.

또한, 포트번호 443인 ybot.kakao.com에 대한 IP는 nslookup을 통해 확인하니 110.76.142.95 이던데

이 IP에 대한 방화벽 해제가 필요할 것 같은데 맞는지 궁금합니다.

답변 부탁드립니다!

**Comment by plusfriendteam** [comment]
1. 포트번호는 사용하시는, 그러니까 80과 443에 대해서 해주시면 되겠습니다.
2. ybot.kakao.com에 대해서는 설정하지 않으셔도 됩니다.
