### ISSUE TITLE
webview 내에서 대화화면으로 돌아가기

### ISSUE THREAD

**Issue by kwanlae** [plusfriend/auto_reply#336]
message_button 에 있는 URL을 통해서 웹페이지로 들어온 후에,
그 웹페이지내에서 버튼을 만들고, 그 버튼을 눌렀을때 원래의 대화화면으로 돌아갈 수 있는 방법이 있을까요?

iOS, Android 에 있는 디폴트 웹뷰 back 버튼의 위치와 모양등이 약간씩 달라서, 그리고 UX flow 상 대화화면으로 바로 돌아갈 수 있는 hot button 기능이 있으면 좋겠는데요,

history.back 등을 살펴봤지만 동작하는 것 같지는 않고해서 질문드립니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 먼저 답변이 많이 늦은 점 사과드립니다.
안타깝지만 웹페이지 내 버튼을 통해 다시 카톡 대화방으로 유입할 수 있는 방법은 없습니다.ㅠ
