### ISSUE TITLE
카카오톡 대화방 바로가기 관련 문의

### ISSUE THREAD

**Issue by robinchoi** [plusfriend/auto_reply#337]
안녕하십니까.
카카오톡 대화방 바로가기 관련하여 문의를 드립니다.

대화방 바로가기 : http://plus.kakao.com/talk/bot/@shopingmall

-> @shopingmall : 플러스 친구 아이디

카카오톡 대화방 바로가기 를 위와 같이 생성 후 카카오톡 인앱 브라우저 또는
모바일 브라우저에서 대화방 바로가기 URL을 입력하고 난 후 아래 이미지와 같은 
페이지가 나온 후 대부분은 카카오톡 대화방으로 바로 진입해 집니다.

그러나 특정 폰에서 (아이폰, 안드로이드) 아래 페이지만 나온 후 카카오톡 대화방으로 진입하지 않습니다
예를 들면 구글 크롬 브라우저에서(현재 폰은 G6입니다) 위와 같은 형식으로 진입하면 아래 페이지만 나온 후 대화방으로 들어가지 않습니다. 그런데 같은 폰에서 파이어 폭스 브라우저로 진입하면 아래 이미지와 같은 페이지가 나온 후 카카오톡 대화방으로 진입하게 됩니다. 

크롬 브라우저에서 자주 발생하고 있습니다.

관련하여 위와 같은 현상 발생시 어떻게 하면 조치가 가능한지 문의 드립니다.
감사합니다.
![image002](https://user-images.githubusercontent.com/29878178/28408482-9950541c-6d72-11e7-939c-3d16c3e19c4b.jpg)

**Comment by plusfriendteam** [comment]
현재는 발생하지 않는 문제로 보입니다. 
해당 현상 재발생 시 다시 문의주시면 확인해보도록 하겠습니다. 감사합니다.
