### ISSUE TITLE
1Depth 이상의 채팅을 구현하고 싶으나 적절한 예제가 없습니다.

### ISSUE THREAD

**Issue by dlvmwpr** [plusfriend/auto_reply#339]
1Depth 이상의 채팅을 구현하고 싶으나 적절한 예제가 없습니다.
좋은 예시가 있을까요?

주로 PHP를 사용하고 있습니다만, 방식에 따라 python을 함께 쓰는 것이 좋을 것 같기도 합니다.

**Comment by hunkim** [comment]
1 depth이상이라 말씀하시면 context를 keep하시고 싶으시다는 말씀이신가요?

**Comment by axiatutu** [comment]
multi-turn 대화를 말씀하시는 것 같네요.
앞의 context에 근거해서 6하원칙 생각하면서 대화를 연결하면 조금 쉬워요.

```
U:주말에 뭐했니?
S:친구랑 놀았어
U:뭐하고 놀았어? or 친구 누구? -- "놀다", "친구"에 근거해서 좀 더 구체적인 질문으로 대화 전개
S:...                    -- context 고려하지 않고 답을 했을 때 우연히 어색하지 않을수도 있지만, 적절한 답을 안정적으로 하기 위해서는 context를 고려하지 않으면 불가능.
```

재미있는 주제죠!

**Comment by dlvmwpr** [comment]
axiatutu님 말씀이 맞습니다

Q. ~가 뭐야?
A. 이거야!
Q. 그럼 ~랑 관련된건 ~야?
A. 응!

이런식으로 연속된 질문을 하고싶은데 적절한 예제가 없어서 고민되네요

**Comment by HayunJin** [comment]
사용자: 공항까지 어떻게 가나요?
봇: 어떤 공항으로 가시죠?
사용자: 인천
봇: 인천공항은 이 앞 버스정류장에서 OOO버스를 타시면 됩니다.
사용자: 얼마야?
봇: 2000원입니다.
사용자: 시간은?
봇: 인천공항으로 가는 OOO버스의 타임테이블은 아래의 링크를 참고하세요

는 어떠신가요

**Comment by osori** [comment]
유저마다 고유한 user_key가 있는데요, 저는 이 값을 이용해서 유저가 이전에 한 말이나 의도를 저장해서 맥락을 파악하고 있습니다.

**Comment by dnjstm123** [comment]
저도 osori님이 하는거처럼 userkey와 이전content값을 저장해서 사용중입니다.
