### ISSUE TITLE
앱등록 관련입니다.

### ISSUE THREAD

**Issue by byeonnamseok** [plusfriend/auto_reply#34]
앱등록 url 입력하려는데 어떤 url을 입력해야하는지 궁금합니다.
(api활용하여 개발하려는 url 입력해야 하는지, 윈폼으로도개발 가능한지)
https로 무조건 사용해야하는지 답변 부탁드려요

**Comment by humit0** [comment]
https는 추천 사항이고 http를 사용하셔도 무방합니다. (직접 돌려본 결과..)

그리고 사용하시려면 호스팅을 구매하시거나 혹은 개인 서버를 돌리셔서 사용을 하셔야 합니다.
입력을 해야할 url은 구매한 서버의 주소의 경로를 입력하시면 됩니다.

**Comment by plusfriendteam** [comment]
답변 감사합니다.
