### ISSUE TITLE
버튼 갯수 문의

### ISSUE THREAD

**Issue by JonghyeokPark** [plusfriend/auto_reply#340]
안녕하세요.
버튼형으로 자동응답 api를 구현하고 있습니다.
버튼이 한 화면(?)에 3개까지만 부여가 되서 혹시, 한화면에 표시할 수 있는 버튼 갯수를 늘릴 수 있나요?

감사합니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 현재로서는 한 화면내의 버튼 갯수를 늘릴수는 없고, 3개까지만 한화면에 표시, 3개가 넘어가게 되면 페이징되어 다음 페이지에 버튼이 노출되게 됩니다. 소중한 의견 참고해서 앞으로의 정책에 참고하겠습니다.
감사합니다.
