### ISSUE TITLE
api에 의한 push 기능 문의

### ISSUE THREAD

**Issue by axiatutu** [plusfriend/auto_reply#342]
안녕하세요.

사용자의 요청을 처리하는데 5초 이상 걸리는 경우(5~10분)가 있는데 timeout이 5초로 제한되잖아요.
이런 경우 일단 "처리가 끝나면 알려드리겠습니다"와 같이 응답하고 처리가 끝나면(5분 후) 결과를 알려주도록 하고 싶어요.
이럴 때 사용자의 요청 없이도 메세지를 보낼 수 있는 일종의 push 기능이 필요할 것 같은데, 계획에 있으신지 질문 드립니다.
이 기능 꼭 좀 넣어주십사 부탁드립니다.

감사합니다.

ps. 자동응답의 취지에는 안 맞을지도 모르겠네요 ㅜㅜ

**Comment by plusfriendteam** [comment]
현재 시스템 구조상, 말씀하신 시나리오는 구현이 어렵습니다.ㅠ
하지만 앞으로 개선과정에 위와 같은 시나리오가 포함되어 있습니다. 구체적인 일정은 미정입니다.

감사합니다.
