### ISSUE TITLE
Message 보낼때 내용에 단어를 링크 걸어 버튼처럼 사용가능 한가요?

### ISSUE THREAD

**Issue by kjs0902** [plusfriend/auto_reply#343]
스마트채팅  API형을 테스트 진행중에 있습니다.

Message 보낼때 Keyboard type:buttons, type:text 같이 사용 할려고 했으나 
둘중 하나만 선택해야 한가고 API Document에 보았습니다.

1. 질문 : Keyboard 에  type:buttons, type:text 같이 사용 할 수 있는지
2. 질문 : txt형식으로 보낼때 단어에 링크를 걸어서 버튼처럼 요청 보낼수 있는지 궁금하여 질문 드립니다.
예) 우리나라 자동차는 
  자동차 단어를 클릭하였을때 txt에 자동차을 입력한것과 같은 반응을 할수 있나요?

답변 기다리겠습니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 답변이 많이 늦어서 죄송합니다.

지금 지원하는 시스템에서는 말씀하신 시나리오의 구현이 어렵습니다.
긍정적인 답변이 아니라 유감스럽습니다.

감사합니다.
