### ISSUE TITLE
Type keyboard인데 예제는 좀 다른것 같습니다. 처음에 키보드 말고 그냥 메세지로 "안녕하세요" 보내려면 어떻게 해야 하나요?

### ISSUE THREAD

**Issue by hunkim** [plusfriend/auto_reply#344]
![image](https://user-images.githubusercontent.com/901975/28559298-ec72b0e0-7150-11e7-9a32-7a6e4d8e08cd.png)

**Comment by kwanlae** [comment]
현재는 최초 채팅방 진입시에는 버튼만이 나오는 것으로 되어 있습니다.
#328 이슈 참고해 주세요.

**Comment by plusfriendteam** [comment]
안녕하세요. 먼저 답변이 많이 늦은점 사과드립니다.
최초에 챗방에 진입하였을 때, 인사말 등을 보여주는 시나리오는 현재로서는 지원하지 않습니다.ㅠ

긍정적인 답변이 아니라 유감스럽네요.
감사합니다.
