### ISSUE TITLE
"Invalid Request"라고 하시는데, 무엇이 Invalid인지 알려주시면 좋을듯.

### ISSUE THREAD

**Issue by hunkim** [plusfriend/auto_reply#345]
![image](https://user-images.githubusercontent.com/901975/28559794-ff64d1ea-7152-11e7-8fb7-3a863d03a534.png)

카카오플러스친구에서 스마트채팅/API형에서 (https://center-pf.kakao.com/_Txmtuxl/chat/smart/api) 저장할때 이런 메시지가 나옵니다.

API  Test에서 OK를 받았는데도 그렇습니다.

![image](https://user-images.githubusercontent.com/901975/28559867-50ff3946-7153-11e7-9af7-e58ee3c2525b.png)

그런데 여러번 하거나 아래 전화번호를 바꾸면 운좋게 성공하는 경우가 있습니다. 왜그런것일까요?

**Comment by woozoo73** [comment]
안녕하세요.

두 가지 정도로 생각해볼 수 있겠습니다.

1. [API 응답 속도]
교수님께서 설정하신 바에 따르면   
API 테스트시 
GET https://evmuk7zsrk.execute-api.ap-northeast-2.amazonaws.com/dev/keyboard
를 호출하는데요.
이게 응답 속도가 허용 범위 안으로 떨어지지 않으면 실패하는 경우가 있습니다.
**Timeout: 5초**
- 저도 Ngrok로 설정하는 경우에 비슷한 API 테스트 실패 경험이 있습니다.

2. [Keyboard API 응답 Body]
{"type":"text"}
를 응답하셨는데요.
문서에 따르면 
**{
    "type" : "buttons",
    "buttons" : ["선택 1", "선택 2", "선택 3"]
}**
와 같은 형식을 요구합니다.
https://github.com/plusfriend/auto_reply

![screenshot from 2017-08-03 17-45-19](https://user-images.githubusercontent.com/3204395/28913994-fcb2fa5c-7874-11e7-8c4f-a2af2f69fa62.png)

![screenshot from 2017-08-03 17-45-11](https://user-images.githubusercontent.com/3204395/28914010-0f144f70-7875-11e7-9447-baf7f46ec03d.png)

교수님 문의글을 보고 반가운 마음에 답변드립니다.
올려주신 ML 강의는 잘 보고 있습니다.
조금이나마 도움이 되었으면 좋겠습니다.

고맙습니다.

**Comment by gomjellie** [comment]
저도 똑같은 상황을 겪었었는데 아마존서버를 northeast 서버에서 seoul 서버로 바꾸면 되더라구요. 아마 지연시간때문에 그런것같아요. 
ml강의 잘 보고있습니다.

**Comment by plusfriendteam** [comment]
플친 관리자센터에서 오류 발생 시, 좀더 상세한 오류 메시지를 노출할 수 있도록 수정하겠습니다.
감사합니다.

**Comment by kjstart** [comment]
Still have this issue now.

**Comment by kjstart** [comment]
![kakaoerropr](https://user-images.githubusercontent.com/2688027/32435655-7c04a2a0-c31c-11e7-87fb-9a04ecfc85cc.png)
