### ISSUE TITLE
PC버전에서는 봇에게 입력이 안됩니다. (iOS는 잘됩니다.)

### ISSUE THREAD

**Issue by hunkim** [plusfriend/auto_reply#346]
PC버전에는 입력이 안된다고 합니다. "Unable to chat with this Plus Friend."

![image](https://user-images.githubusercontent.com/901975/28560010-f1376c8a-7153-11e7-821c-742f0fb6a0b7.png)

iOS는 잘됩니다.

![image](https://user-images.githubusercontent.com/901975/28560057-1184d6d0-7154-11e7-9c12-8a061f012a8b.png)

**Comment by jic5760** [comment]
원래 PC/Mac에서는 전송이 안될거에요.
Windows PC버전에서도 안되더라구요..

**Comment by hunkim** [comment]
@jic5760 감사합니다. 왜 그런것일까요? PC 에서도 되면 좋은데.

**Comment by catastrp** [comment]
카카오톡 정책 상, PC버전 카카오톡과 업데이트하지않은 구버전 카카오톡으로는 사용이 불가능합니다.

라고 하네요

**Comment by plusfriendteam** [comment]
현재로서는 PC 및 맥톡에서는 스마트 채팅을 지원하지 않습니다.
추후 개선할 수 있도록 소중한 의견 반영하겠습니다.
감사합니다.
