### ISSUE TITLE
플러스 프랜즈 단톡방 초대

### ISSUE THREAD

**Issue by hunkim** [plusfriend/auto_reply#347]
혹시 플러스 프랜즈 단톡방 초대 가능할까요?

둘만 하는것 보다 단톡중 있으면 봇으로서의 더 많은 기능을 하게 될텐데, 아쉽습니다. 혹시 단톡방 초대 기능이 있으면 정말 좋을것 같습니다.

감사합니다.

**Comment by djasonPark** [comment]
저도 궁금한데 답변부탁드립니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 아직 해당 스펙은 현재 지원하지 않고 있습니다. 
보내주신 의견은 긍정적으로 검토하여 서비스에 반영될 수 있도록 노력하겠습니다.
