### ISSUE TITLE
자동응답형처럼 message 응답 후 button hold

### ISSUE THREAD

**Issue by walter-ghost** [plusfriend/auto_reply#349]
자동응답형처럼 버튼을 한두개만 놓고 텍스트로 응답하게 하고 싶은데

message를 text type으로 반환하면 홈버튼이 사라지고 입력창으로 바뀌네요

방법이 있을까요?

**Comment by ilhanjo** [comment]
{
  "message": {
    "text": "귀하의 차량이 성공적으로 등록되었습니다. 축하합니다!",
  },
  "keyboard": {
    "type": "buttons",
    "buttons": [
      "처음으로",
      "다시 등록하기",
      "취소하기"
    ]
  }
}

이렇게 쓰면 되지 않나요?
message는 text로 응답후
keyboard type은 buttons으로

**Comment by walter-ghost** [comment]
넹...  아래 에러가 뜨네요

사용자 봇서버에 에러가 감지 되었습니다. 
 내용:[잘못된 응답입니다. response json parsing error. user_key : OLNN76p-BDQs, You'r server response : {
 "type" : "buttons",
 "buttons" : ["처음으로","다시 등록하기","취소하기"]
}
