### ISSUE TITLE
카카오톡 플러스친구 기능 문의

### ISSUE THREAD

**Issue by EugeneJang** [plusfriend/auto_reply#352]
안녕하세요.

카카오톡 플러스친구 기능에 대해서 여쭤봅니다.

사용자가 입력한 시점이 아니더라도 특정 메세지(URL)을 받으면 그에 따른 메세지를 사용자에게 뿌려줄수 있는지 여쭤봅니다

ex) 결제완료 controller 호출 > 결제완료 Message 사용자 PUSH

**Comment by plusfriendteam** [comment]
안녕하세요.
현재 자동응답에서는 해당 기능을 제공하고 있지 않습니다.
주문/결제/배송 등은 카카오톡 비즈메시지인 알림톡을 사용해보는 것은 어떠신가요?
비즈메시지 관련 정보는 https://bizmessage.kakao.com/ 에서 보실 수 있습니다.
