### ISSUE TITLE
message_button 문의

### ISSUE THREAD

**Issue by tkdvmf423** [plusfriend/auto_reply#353]
안녕하세요 문의드릴께 있습니다

message_button에 이미지를 입힐수 있을까요??

**Comment by plusfriendteam** [comment]
안녕하세요. 
먼저 답변이 늦어진점 사과드립니다.

현재로선 message 버튼에 이미지를 입힐 수가 없습니다.
의견 주신 점을 잘 참고하여 개선할 수 있도록 검토하겠습니다.
감사합니다.

**Comment by tkdvmf423** [comment]
그럼 한가지 더 질문드릴께있습니다.

아래 이미지와 같이 공유하기나 구경하기처럼

클릭해서 특정url 넘기려고 할려면 어떤식으로 해야하나요??

[image: 본문 이미지 1]

2017년 8월 16일 오전 11:06, Plusfriend Team <notifications@github.com>님이 작성:
