### ISSUE TITLE
이미지 url 문의

### ISSUE THREAD

**Issue by tkdvmf423** [plusfriend/auto_reply#357]
질문드릴께있습니다.

아래 이미지와 같이 공유하기나 구경하기처럼 

클릭해서 특정url 넘기려고 할려면 어떤식으로 해야하나요??.

![wqe](https://user-images.githubusercontent.com/12468879/29348070-df06558c-828b-11e7-9952-df89c4d5473f.png)

**Comment by plusfriendteam** [comment]
안녕하세요.
README.md 에 있는 **6. Object 의 6.2.1 MessageButton** 의 내용으로는 부족하신가요?
MessageButton 을 사용하시면 하단에 링크 버튼이 표시되어 특정 링크로 넘어가실 수 있습니다.
