### ISSUE TITLE
파이썬을 이용해서 API 형 자동응답을 만들어 보려합니다.

### ISSUE THREAD

**Issue by hanjongsoomd** [plusfriend/auto_reply#359]
구글링해 봤더니 PHP으로 구현한 예제들은 좀 있는 것 같습니다.
파이썬으로 프로그래밍할 경우 참고할 만한 문서나 간략한 전체적인 가이드라인을 주실 수 있을까요?
감사합니다.

**Comment by gomjellie** [comment]
https://github.com/JungWinter/yellowid-flask
플라스크 쓰신다면 이건 어떠신가요

**Comment by hanjongsoomd** [comment]
유용한 조언 감사합니다. 아직 파이썬이 서툴러서 막연하게 장고를 사용해야하나 생각하고 있었는데 플라스크로 구현하는게 더 쉬운 편일까요?

**Comment by gomjellie** [comment]
저는 플라스크먼저 만 쓰다가 지금 장고 막 배우고 있는중인데 플라스크가 더 쉬운거같아요ㅋㅋ 둘다 좋지만 챗봇 만드는데 그렇게 많은 기능이 필요한 것도 아니라서 가벼운 플라스크 추천드립니다.

**Comment by hanjongsoomd** [comment]
네, 감사합니다^^ 플라스크쪽으로 시도해 봐야겠네요.
