### ISSUE TITLE
채팅 창 화면 바로가기 URL 문의

### ISSUE THREAD

**Issue by SeoktaeKang** [plusfriend/auto_reply#36]
안녕하세요. LG CNS의 강석태 차장입니다.
기존 구API에서 아래와 같이 홈화면 및 채팅창 URL이 가능하여 봇API 키워드를 붙이면 자동으로 채팅이 가능한 것으로 알고 있습니다.

예를들어 http://plus.kakao.com/@GSSHOP/주문 
이러 URL을 누르면 주문 키워드를 인식하여 채팅창에 초기 메시지를 전달하여 주문 프로세스가 가능했습니다.

그런데 신규API를 가지고 위와 같은 조건을 테스트해보니까 URL이 전혀 먹히지 않더군요.

기업 입장에서는 사용자가 메뉴 진입이라든지 초기 페이지 접근이 용이하게 위와 같이 URL로 제공할 경우 매우 유용한데 해당 기능이 구API에만 가능하고 신규API에는 전혀 제공되지 않는거 같아 많이 아쉽습니다. 

위의 기능을 제공할 경우 푸쉬로 광고를 보내고 주문이나 이벤트 참여로 이어질 수 있는 다양한 부가 기능 개발이 가능한데.. 기존API에 비해 기능들이 많이 제약이 발생한 것 같습니다.

위 기능에 대해 다시 검토가 가능할런지요?

추가적으로 플러스친구를 활용하는 많은 기업들이 위의 링크에 상품코드와 같은 파라미터를 파터너 시스템에 던져줄 수 있다면 배너 연동되어 상품을 주문하거나 푸쉬 연동되어 상품을 주문할 수 있고..
QR코드나 NFC 태그 같은 것 인식하여 플러스친구 상품 구매 채팅창로 바로 연결되는 기능들이 가능할 것입니다.

실제 저희가 만나본 고객들이 그런 니즈가 상당히 많이 있습니다.
이러한 API 요건 변경에 대해 깊은 검토 부탁 드립니다.

감사합니다.

**Comment by plusfriendteam** [comment]
문의주신 url은 지원이 중단된 것이 아니라, 유효하지 않은 url입니다. 
해당 url은 플러스친구에게 제한적으로 제공되는 기능이므로, plusfriend_api@kakaocorp.com 메일로 문의주시면 정상적인 url을 안내해 드리도록 하겠습니다.

**Comment by SeoktaeKang** [comment]
안녕하세요. 엊그제 알려주신 메일 주소로 URL 확인 요청 메일을 보내드렸는데 아직 회신이 없어서요.
고객사에서 SMS로 URL 발송을 할 예정이라 대기하고 있는 상태입니다.
빠른 확인 좀 부탁 드리겠습니다.
