### ISSUE TITLE
해당 프로필의 자동응답 시스템이 응답을 하지 않습니다. 조치방법

### ISSUE THREAD

**Issue by kimtaejin7** [plusfriend/auto_reply#360]
안녕하세요 옐로아이디로 챗봇을 구현중입니다.

소스에 이상이 없도록 만들었는데 계속 아래 에러가 발생합니다.

해당 프로필의 자동응답 시스템이 응답을 하지 않습니다. 문제가 보고되어 처리 예정입니다. 다음에 다시 시도해주세요.

서버는 taesama.cafe24.com 입니다.

 소스는 아래와 같습니다.

gugu@gugu-virtual-machine:~/simplebot$ curl -XGET 'http://taesama.cafe24.com/keyboard'
{
"type":"buttons",
"buttons":["start","help"]
}
gugu@gugu-virtual-machine:~/simplebot$ curl -XPOST 'http://taesama.cafe24.com/mssage' -d '
{
>    "user_key": "xxxxxxxxxxx",
>    "type": "text",
>    "content": "start"
>  }'
    {
        "message": {
            "text": "ready!"
        }
    }

꼭 확인 부탁드립니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 늦게나마 답변을 남깁니다.
현재 curl -XGET 'http://taesama.cafe24.com/keyboard' 로 접근 시 404 로 응답이 옵니다.
방화벽 등 네트워크 이슈를 확인해주세요.
