### ISSUE TITLE
message 에러 좀 확인해 주세요

### ISSUE THREAD

**Issue by jinuki** [plusfriend/auto_reply#363]
http://도매인/comm/plusfriend

으로 등록해서

Required*
keyboard OK
{"type":"buttons","buttons":["버튼1","버튼2","버튼3"]}

으로 등록을 하니 keyboard 는 잘 넘어간듯 합니다.

하지만 message 에서 계속 에러가 발생을 하네요

iis + classic ASP 를 사용하고 있는데요..

<% @CODEPAGE="65001" language="vbscript" %>
<%
Session.CodePage = 65001
Response.CharSet = "utf-8"
response.ContentType = "application/json"
%>
{
	"message": {
	"text" : "hi"
	}
}

그냥 요렇게 테스트를 하는데 

해당 프로필의 자동응담 시스템이 응답을 하지 않습니다. 문제가 보고되어 처리 예정입니다. 다음에 다시 시도해주세요.

라는 메세지만 계속 나오네요..

당연히

http://도매인/comm/plusfriend 아래에 /message/default.asp 파일이 있습니다.

수고하세요

**Comment by plusfriendteam** [comment]
안녕하세요. 
플러스친구로 {"message": {"text" : "hi"}} 로 요청을 보냈다는 말씀인가요?
해당 json 은 플러스친구에서 내려주는 응답 형태입니다.
요청을 보내실 때는 

> curl -XPOST 'https://:your_server_url/message' -d '{
  "user_key": "encryptedUserKey",
  "type": "text",
  "content": "차량번호등록"
}' 

이러한 형식으로 보내주셔야 합니다.
자세한 내용은 README.md 를 참고해주세요.
