### ISSUE TITLE
IIS + classic ASP 확인좀 해주세요

### ISSUE THREAD

**Issue by jinuki** [plusfriend/auto_reply#364]
w2k + IIS7.0 + Classic ASP 를 사용하고 있습니다.

IIS로는 실행이 안되는것 같아 nodejs 로 해서 구현했습니다.

내용은 삭제처리합니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 
확인이 늦은점 사과드립니다.
추가로 문의하실 부분이 있으시면 말씀해주세요.
감사합니다.
