### ISSUE TITLE
기능 문의

### ISSUE THREAD

**Issue by ghost** [plusfriend/auto_reply#365]
안녕하세요 플러스 친구의 기능에 대해 잘못 이해 하고 있는지 확인 차 문의 드립니다
사용자가 정해진 'keyboard' 버튼 형식의 메세지 외에 직접 메세지를 전송하여 서버가 전달 받을 수
있는 방법은 없는건가요?
'keyboard' 에서 설정한 버튼 외에는 메세지 직접 입력창을 선택할 수 없어서 문의 드립니다

**Comment by plusfriendteam** [comment]
안녕하세요.
버튼 형식 이외에도 사용자가 직접 입력한 텍스트 혹은 미디어 파일을 받을 수 있습니다.
README.md 의 5.2. **메시지 수신 및 자동응답 API**  를 확인해주세요 :)
