### ISSUE TITLE
버튼노출기능문의드립니다.

### ISSUE THREAD

**Issue by loveily** [plusfriend/auto_reply#366]
프로필명 : @안양사랑

채팅창 접속시 최초 버튼은 잘 나오는데 버튼을 클릭하면 버튼이 없어집니다.

없어지더라도 1:1대화처럼 버튼목록을 나타나게 하는 버튼을 추가해주실수는 없는지요?

봇질문시 답변내용도 나오지만..
다른 예상답변 내용을 버튼으로 노출시키고 싶습니다.
검색할때 처럼 검색자동필터 기능처럼.

가능할까요?

**Comment by plusfriendteam** [comment]
안녕하세요.
최초 버튼 클릭 후 응답을 내려줄 때 버튼이 사라진다는 말씀이시죠?
**5.2. 메시지 수신 및 자동응답 API** 의 response 형태를 보시면 message 필드 외에 keyboard 필드가 있습니다.
keyboard 필드에 **5.1. Home Keyboard API** 에서 사용자에게 내려준 것과 같은 값을 내려주면 버튼이 없어지지 않고 계속 보이게 됩니다.
마찬가지로 예상 답변 내용들을 keyboard 필드에 넣어주시면 구현 가능할 것 같습니다.
질문하신 내용이 답변 내용과 다르면 다시 코멘트해주세요 :)
