### ISSUE TITLE
user_key(유효기간)에 대해 궁금합니다.

### ISSUE THREAD

**Issue by YoungKwonJo** [plusfriend/auto_reply#367]
안녕하세요.

user_key에 대해 궁금한 점이 있어서 문의를 드립니다.
user_key가 유저가 앱을 설치시 설정이 되는 것으로 이해가 되는데요,
만약 유저가 앱을 지운 후에 user_key가 회수(?, 아닐수도 있구요.)가 될텐데요.

이때 혹시, 그 user_key를 다시 다른 유저에게 줄 가능성은 없는지 궁금합니다.
그래서 정말 user_key가 unique한 것인지 궁금해서 문의를 드립니다.

**Comment by plusfriendteam** [comment]
안녕하세요.
user_key 는 카카오톡 가입 후 발급되고, 카카오톡 계정 탈퇴 후 재가입 시에는 새로 발급 됩니다.
발급된 user_key는 다른 사용자에게 할당되지 않으며, user_key 는 unique 한 값으로 보시면 됩니다.

더 궁금하신 사항은 추가 문의 주시거나 README.md 의 4.4. user_key 항목을 참고해주시기 바랍니다.
