### ISSUE TITLE
Photo 오브젝트 문의 

### ISSUE THREAD

**Issue by Newlunar** [plusfriend/auto_reply#368]
설명을 보면 이미지 응답시 url을 적게 되어 있던데 
하드디스크에 있는 사진을 보내려면 웹에 업로드를 하고 그 url주소를 활용하는 방법밖에 없나요?

**Comment by plusfriendteam** [comment]
안녕하세요.
네, 현재는 이미지를 url 로만 저장하고 있습니다. 
별도로 이미지를 업로드해서 사용하는 기능은 지원하지 않으니 참고해주시기 바랍니다.
