### ISSUE TITLE
자동응답과 API형을 섞어서 구현 가능할까요?

### ISSUE THREAD

**Issue by JeeYongPark** [plusfriend/auto_reply#369]
안녕하세요.
플러스친구를 추가하면 첫 메세지는
버튼중에 하나를 선택하는 메세지로 뜨고,
사용자가 버튼을 클릭해서 선택하면

그 이후부터는 사용자에게 텍스트 및 시진으로 입력받게 하고 싶습니다.

구현이 가능할지 궁금합니다.

**Comment by plusfriendteam** [comment]
안녕하세요.
현재 두 기능을 함께 사용하는 것은 구현되어 있지 않습니다.
말씀주신 기능들은 API형에서 구현 가능할 것으로 보이는데요, 
README.md 의 **5.2. 메시지 수신 및 자동응답 API** 에서 자동응답 API로 구현하시면 될 것 같습니다 :)
