### ISSUE TITLE
user_key 가 똑같이 오지 않습니다.

### ISSUE THREAD

**Issue by mcvzone** [plusfriend/auto_reply#37]
안녕하세요.

USER_KEY 의 유형이
    1. 플친만 맺어도 오는 USER_KEY   <<-- API2.0 에서도 변경없음
    2. 인증을 거쳐 받게 되는 USER_KEY   <<-- API2.0 에서 바뀜

위와 같이 설명 해 주신걸로 알고 있습니다.

그런데 1번에 해당 하는, 플친만 맺어도 얻을 수 있는 USER_KEY가 아래와 같이 전혀 다른 유형으로 오고 있습니다.

USER_KEY 의 값입니다.

  기존 값 : 248757548 (숫자로만 구성)
  API 2.0 값 : G3KLt3OUo_nm (영숫자 조합)

확인 부탁 드립니다.
감사합니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 
AXA에서 사용하시는 타입의 봇에서는 1,2번에서 말씀하신 USER_KEY 모두 현재의 USER_KEY와 다릅니다. 
따라서 사전에 안내해 드린 대로 1, 2번 모두 USER_KEY 변환의 대상이며, 변환할 USER_KEY를 전달해 주실 때 어떤 API를 통해 획득한 USER_KEY인지 명시해 주시면 그에 따라 현재의 USER_KEY로 변환해 드리도록 하겠습니다.
