### ISSUE TITLE
이미지 풀스크린으로 확대방법 문의

### ISSUE THREAD

**Issue by jaeyong1** [plusfriend/auto_reply#370]
안녕하세요.

아래와 같이 자동응답 API로 이미지를 회신할 수 있는데요,

    {
        "message": {        
        	  "text": "$pictext" , 
            "photo" : {
            	"url": "$picurl" ,
      				"width": 640,
      				"height": 480
            }
          ...

전송된 사진을 카카오톡에서 받았을때,
그 사진을 클릭했을때 풀스크린으로 띄울 수 있는 옵션이 있는지요?

일반적으로 카카오톡 사용시, 친구들로 부터 받은 사진은 클릭해서 크게 보는게 습관이 있어서,
자동응답 API로 전달된 사진도 크게 볼수 있었으면 좋겠습니다. 
사진확대를 허용하는 옵션이 있는지 궁금합니다.

수고하세요.

플러스친구 아이디: @집에서키우는화분

**Comment by plusfriendteam** [comment]
안녕하세요. 
먼저 해당 기능을 제공하지 않고 있어 죄송하다는 말씀을 드립니다.
추후에 사진을 확대할 수 있는 기능을 추가할 수 있도록 검토해보겠습니다. 
불편하신 점 거듭 사과드리며, 앞으로 더욱 노력하는 플러스친구가 되겠습니다.

**Comment by jaeyong1** [comment]
네. 바쁘실텐데 답변주셔서 감사합니다.
