### ISSUE TITLE
카카오톡 api 이용 과제물

### ISSUE THREAD

**Issue by Mintphobia** [plusfriend/auto_reply#371]
안녕하세요 저는 상원고등학교에 재학중인 학생입니다.

다름아니라 진로보고서대회가 있는데 과제물로 카카오톡api서비스를 제작해 보려합니다 

제가 원하는 과제물은 

현재 상원고 학생회 라는 플러스 친구가 있으나 가끔가다 학생회 지원, 학교휴일 등 몇몇 알려주는 정보가 없어서 

과제물로 위에 학생회 플러스 친구를 개선하여 

학교 긴급공지, 날씨, 급식, 학사일정, 대회일정, 시간표 등 이외에도 학생들이 학교정보에 대해서, 그이외에 대해서도 편리하게 알수있도록 

챗봇을 만들어 보고자 합니다. 그런데 어떻게 만드는지 잘몰라 혹시 어떻게 만드는지 도움을 받을수 있을까 연락드려봅니다..

**Comment by LeeKyungwook** [comment]
이런건 너무 광범위한 질문이고 하나부터 열가지 다 해달라는 질문같아서 답변이 안달리실거같아서 대신 남겨드립니다. 코드를 어느정도 진행하시고 안되는 부분이라던가 궁금한 점에 대해 남기셔야 아마도 답장이 잘 달리실것 같습니다~

**Comment by plusfriendteam** [comment]
안녕하세요.
@LeeKyungwook 말씀대로 대단히 답변드리기 어려운 내용입니다만...

자동응답 API를 만들기 위해서는 README.md 에 기술된 API들이 정상적으로 응답할 수 있는 서버가 필요합니다.
서버에는 말씀하신 기능들이 API 규격에 맞게 동작하도록 작성되어야 합니다.
말씀해주신 기능들은 플러스친구의 관리자센터에서 스마트채팅 > 자동응답형에서도 충분히 구현할 수 있을 것으로 보입니다. 
플러스친구를 이용해주셔서 대단히 감사드리며, 자동응답 API 이용 중 다른 질문이 생기시면 언제든지 issue를 작성해주세요 :)
