### ISSUE TITLE
API Test 서버 구성 관련 문의입니다.

### ISSUE THREAD

**Issue by kimhyunseung** [plusfriend/auto_reply#372]
현재 문서에 나온 대로 

ybot.kakao.com 80, 443

110.76.143.234 80, 443
110.76.143.235 80, 443
110.76.143.236 80, 443

center-pf.kakao.com 80, 443

방화벽 오픈 했습니다.
(80 포트는 8080이 아닌 80입니다.)

후에 플러스친구 관리자에서 api 테스트를 했을 때 
Required*
keyboard Fail
라는 해당 에러 메세지만 나옵니다.

실제로 서버에는 접근 못한걸로 확인되었구요.

위의 서버들 외에도 접근 추가해야하는 IP, Domain, Port가 따로 있나요?

**Comment by plusfriendteam** [comment]
문의 주신 설정으로는 문제가 없어보입니다.
API 테스트 시에는 해당 서버에 **5.1. Home Keyboard API** 가 있는지 확인합니다.
keyboard Fail 메시지는 해당 API 를 요청했을 때 정상적으로 요청 받지 못해서 내려주는 에러입니다.
서버에 해당 API 가 정상적으로 동작하는지 확인해보시고, 그래도 안되시면 네트워크 설정을 다시 확인해주시기 바랍니다.
