### ISSUE TITLE
플러스친구에서 유저를 차단할 수 있나요?

### ISSUE THREAD

**Issue by YoungKwonJo** [plusfriend/auto_reply#373]
유저가 플러스친구를 차단하는 기능은 있는 것으로 알고 있습니다.

그런데, 만약 플러스친구가 유저를 차단하는 방법도 존재하는지 궁금합니다.

**Comment by plusfriendteam** [comment]
안녕하세요.
플러스친구에서 특정 유저를 친구 맺지 못하도록 하는 기능을 말씀하시는건가요?
해당 기능은 현재 제공하고 있지 않습니다. 
어떤 경우에 필요하신지 좀 더 자세히 말씀드리면 추후 기능으로 검토해보도록 하겠습니다.

**Comment by YoungKwonJo** [comment]
안녕하세요. 
아마도 api서버 자체적으로 가능하겠지만, 혹시나 카카오톡 일반유저처럼  차단기능이 있는지 궁금했습니다.

그리고 혹시나, 플러스친구에 chatbot으로 서비스를 만들었을 때 이를 악용하는 사용자(어떤 식으로 악용할지는 확실하진 않습니다.)를 차단하는 기능이 있는지 궁금했습니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 아직 해당 스펙은 현재 지원하지 않고 있습니다.
보내주신 의견은 긍정적으로 검토하여 서비스에 반영될 수 있도록 노력하겠습니다.
