### ISSUE TITLE
플러스친구 계정으로 사용자의 사진을 받을 수 있나요?

### ISSUE THREAD

**Issue by 1fas** [plusfriend/auto_reply#374]
안녕하세요.
자동응답api를 이용해서 사용자가 카카오톡으로 전송하는 사진을 db에 저장하려고 합니다.
기술적으로 가능한가요? api document에는 없는 것 같아서요..

**Comment by plusfriendteam** [comment]
안녕하세요.
원하시는 기능이 사용자가 전송한 사진을 서버에서 받아 해당 서버에서 DB 로 저장하려고 하시는 것이 맞나요?
README.md 의 **5.2. 메시지 수신 및 자동응답 API** 로 가능할 것 으로 보이는데요.
사용자가 보낸 사진의 url은 request 에 content 필드로 들어가는데요, content 의 값을 DB에 저장하시면 될 것 같습니다.
