### ISSUE TITLE
user_key 스펙은 아직 정해진게 없는 건가요?

### ISSUE THREAD

**Issue by khhwang838** [plusfriend/auto_reply#377]
user_key에 대한 길이 정보를 알고 싶어서 검색해본 결과 작년에 동일한 질문에 대한 답변으로 스펙이 정해진게 없다라고 되어있던데 아직도 스펙에 대해서는 정해진게 없다고 봐야하나요?

감사합니다.

**Comment by plusfriendteam** [comment]
안녕하세요.
확정된 스펙은 아니지만 현재 12자리 문자열로 받고 있습니다.
추후에 변경될 가능성이 있어 참고만 해주시길 바랍니다. 
감사합니다.
