### ISSUE TITLE
user_key 변경 이벤트에 대해 문의 드립니다.

### ISSUE THREAD

**Issue by nshnshnsh** [plusfriend/auto_reply#379]
한 단말에서 유심변경 등을 통해 핸드폰 번호 변경을 한 경우 user_key 가 변경이 되는지 궁금합니다. 
아니면, kakao 계정 기반이라 폰 번호와는 상관없이 고정인건가요?

또 user_key 가 변경될 수 있는 상황에 대해 답변 부탁드립니다.

**Comment by plusfriendteam** [comment]
안녕하세요.
핸드폰 번호를 변경하거나 톡을 탈퇴하고 재가입하는 경우에도 변경됩니다.
