### ISSUE TITLE
문의 드립니다.

### ISSUE THREAD

**Issue by byeonnamseok** [plusfriend/auto_reply#38]
안녕하세요 궁금한게 좀 있는데요

1. 앱등록을 해야하는 이유가 뭔가요?? 단순히 app_key 를 얻기위한 목적인지 아니면 개발시 어떤 용도로 사용을 하기 때문인지 등 어떤 이유가 있는지 궁금합니다.

2. API 플랫폼 운영정책에서 서비스 제공 범위 > (2) user-key를 통해 특정개인에게 메세지 발송 API 
이걸 활용하고 싶습니다. 별도의 제휴절차 거쳐 적절한 이용자격을 갖춘 제한된 이용자 라는 문구가 있는데 어떤 이용자격을 갖춰야 하나요?

3. 개발을 윈도우 폼으로 할 예정인데 무리가 없을까요?

4. app test 시 fail 뜨면 (예 fail 405 ) 어떤 이유로 실패 뜬건지 조치사항이나 이유가 정리 되어 있는 곳이 있나요?

5. 옐로우 ID로 상대방에게 메시지 보낼때 상대방이 친구추가 되어 있어야 보내지는지, 아니면 전화번호로 상대방에게 메세지 보낼수 있는지 궁금합니다.

답변 부탁드립니다.

고생하세요~!!!

**Comment by plusfriendteam** [comment]
안녕하세요.
 
1. 앱등록을 통한 앱 정보 제공 절차는 자동응답을 이용하는 파트너/서비스의 관리 등 내부적 용도와 app_key 발급을 위한 목적으로 이용하고 있습니다.

2. 현재는 문의주신 API를 외부 파트너용으로 공개하고 있지 않습니다. 제휴가 아닌 비즈니스용으로는 별도의 비즈메시지 API가 서비스되고 있으니 카카오톡 비즈메시지의 상품소개서를 참고해주시기 바랍니다. (http://bizmessage.kakao.com/main)

3. 윈도우 폼으로 개발을 하신다는 말씀이 윈도우 서버 환경에서 개발하신다는 말씀이 맞나요?
윈도우 서버 환경에서도 API 규격만 맞춰주시면 정상적으로 사용하실 수 있습니다.

4. README.md 의 8번 Response Code를 참조해주시면 됩니다.

5. 2번에서 말씀드린 비즈메시지 API를 기준으로 답변드리면, 상대방에게 메시지를 보낼 때 상대방이 먼저 친구추가가 되어 있어야 메시지를 발송하실 수 있습니다. 또한 친구추가가 이미 되어 있는 상대방이라면 전화번호를 기반으로 메시지를 발송하실 수 있습니다.
