### ISSUE TITLE
전자정부프레임워크 REST API  적용 관련 문의

### ISSUE THREAD

**Issue by dablase** [plusfriend/auto_reply#380]
spring 전자정부 프레임워크에 카카오톡 플러스친구 기능을 테스트해보려하는데, web.xml의 서블릿 url-pattern을 *.do로 사용중입니다. 따라서, 모든 페이지가 xxx.xxx.xxx.xxx:1234/keyboard.do로 호출되는 형태입니다.

현재 상태에서  REST 방식인 카카오 API를 사용할 수 있는 방법이 있을까요?

**Comment by plusfriendteam** [comment]
안녕하세요.
고정적으로 "~/keyboard" 라고 호출을 하고 있어서 ".do"가 붙으면 키보드 정보를 제대로 가져올 수가 없습니다.ㅠ 
메시지 수신 및 자동응답 API인 "~/message" 인 경우도 동합니다. 
api url 을 spec 에 맞게 개발해주셔야 합니다.ㅠ

**Comment by min-jo** [comment]
URI 필터를 사용하시면 될듯 싶습니다.
