### ISSUE TITLE
JSONDecode 에러 / message (python/django)

### ISSUE THREAD

**Issue by wkddnjset** [plusfriend/auto_reply#381]
python 3.6 / django 1.11

keyboard 까지는 웹상에서 json으로 출력이 되는데 
message는 에러가 뜹니다.
- views.py
```
def answer(request):
    json_str = ((request.body).decode('utf-8'))
    received_json_data = json.loads(json_str)
    cafeteria_name = received_json_data['content']
    today_date = datetime.date.today().strftime("%m월 %d일")
    return JsonResponse({
            'message': {
                'text': today_date + '의 ' + cafeteria_name + ' 중식 메뉴입니다.'
            },
            'keyboard': {
                'type': 'buttons',
                'buttons': ['상록원', '그루터기', '아리수', '기숙사식당', '교직원식당']
            }
        })
```
- 에러메세지

**JSONDecodeError at /message**
Expecting value: line 1 column 1 (char 0)

보니깐 데이터가 없다고 나오는거 같은데 왜그런걸까유ㅠㅠ

**Comment by plusfriendteam** [comment]
안녕하세요.
올려주신 코드만으로는 원인 파악이 어렵습니다. 
request 를 어떻게 보내고 계신지 알려주시겠어요?

**Comment by GENIEYOO** [comment]
저도 이 문제 때문에 한참 고민했는데~
주소를 '서버주소/keyboard/message'로 하면 받아온 메시지 보실 수 있고,
cafeteria_name = received_json_data['content'].encode('utf-8')
이렇게 encode해주시면 카톡상에서도 정상작동합니다.!!
