### ISSUE TITLE
API테스트관련 질문있습니다.

### ISSUE THREAD

**Issue by shylock3d** [plusfriend/auto_reply#382]
안녕하세요. 
플러스친구 챗봇을 구성하려고하는데 API테스트에서 막혔습니다.
이클립스에서 REST API 구성후 localhost로 서버를 띄워서 테스트를 해보면
keyboard Fail 이후 아무런반응이 없습니다.
localhost 테스트의 경우에도 그 3개의 아이피에대해 ACL허용이 이루어져야하는건가요?
아니면 localhost는 아예 막혀있는건지 궁금합니다.

**Comment by plusfriendteam** [comment]
안녕하세요.
localhost로 띄운 서버는 해당 장비에서 밖에 접근할 수 없습니다.
외부에서도 접근할 수 있는 웹서버를 사용하여 ACL 허용해주시고 테스트 해주세요 :)
