### ISSUE TITLE
관리자 센터 웹 Request를 활용한 플러스친구 1:1 채팅 시스템화 사용 가능 문의

### ISSUE THREAD

**Issue by blackss2** [plusfriend/auto_reply#383]
안녕하세요.
지금 고객에게 안내를 하기 위해 [플러스친구 채팅], [알림톡], [친구톡], [상담톡]을 검토하였고 플러스친구 채팅과 알림톡이 가장 적합한것 같아 테스트 중입니다.
이 중 [플러스친구 채팅]은 카카오 관리자 센터에서만 되서, 관리자 센터 웹 Request를 이용하여 플러스친구 1:1 채팅을 관리자 센터를 웹이 아닌 서버를 통해 사용할 수 있도록 간단히 테스트 해봤습니다.
1:1 고객센터에서 사용 가능 문의를 했더니 여기에 문의를 올리라고 해서 올립니다.

모든 과정은 서버 상에서 일어나며, 순서는
[로그인]
[로그인 콜백]
[Me로 내 정보 획득]
[CheckStrong으로 2차 인증 여부 확인] 
[RequestStrong으로 2차 인증 코드 카톡으로 발송]
[카톡으로 온 코드 시스템에 입력]
[VerifyStrongCode로 코드 발송 및 2차 인증]
[CheckStrong으로 2차 인증 여부 완료 확인] 
[Chats로 현재 채팅방 목록 획득]

이후 [SendChat으로 1:1 채팅 메시지를 목표 고객에게 보내기]와 [Websocket을 열어서 1:1 채팅 내용 수신]을 합니다.

테스트 코드는 go 언어로 작성되었으며, 비공개 문의가 따로 없어서 소스가 필요하시면 카카오 메일주소를 주시면 발송해드리도록 하겠습니다.

**Comment by plusfriendteam** [comment]
안녕하세요.
수신가능한 이메일 주소를 남겨주시면 담당자를 통해 답변드리겠습니다.
감사합니다.

**Comment by blackss2** [comment]
blackss2@nate.com 입니다.
