### ISSUE TITLE
자동응답 api 사용 중 1:1 채팅 기능 문의

### ISSUE THREAD

**Issue by ronierjjh** [plusfriend/auto_reply#384]
안녕하세요 
자동응답 api 를 이용한 bot 을 제작 중입니다.

기본적인 대화는 bot 을 통해서 하다가 특정 이벤트(ex:1:1채팅 이라고 입력) 시 1:1 채팅 기능이 활성화되게 가능한가요?

기본 상태는 1:1 채팅이 꺼져 있는 상태로 하구요, 해당 이벤트 발생시에만 관리자 페이지에서 대화 할수있게 요

추가적으로 현재 카카오톡에서 5초제한이 더 늘어날 여지가 있는지요?

**Comment by plusfriendteam** [comment]
안녕하세요.
1:1 채팅기능을 활성화시키려면 대화입력 창에 1:1 아이콘 클릭을 통해서만 가능합니다.ㅠ
그리고 시스템 안정성을 위해 5초 타임아웃을 더 늘릴 수는 없을거 같습니다.
감사합니다.
