### ISSUE TITLE
초기 keyboard method 에서 웰컴메시지

### ISSUE THREAD

**Issue by since88** [plusfriend/auto_reply#385]
안녕하세요.

카카오플친 개발중인데 초기 메서드인 /keyboard 에서 버튼은 버튼데로 보이고 진입시 웰컴메시지를 뿌려 줄 방법이 있는지요?

**Comment by plusfriendteam** [comment]
안녕하세요. 현재 웰컴메시지를 뿌려줄 수 있는 스펙은 구현이 되어 있지 않습니다.
향후 개선 방향에 반영할 수 있게 논의해보겠습니다.
감사합니다.
