### ISSUE TITLE
메시지를 한번에 여러개 보낼 수 있는 방법이 무엇인가요?

### ISSUE THREAD

**Issue by deepseasw** [plusfriend/auto_reply#386]
http://aidev.co.kr/freeboard/2355

위 링크의 스크린샷처럼 LG HomeChat은 여러 메시지를 한번에 표시할 수 있습니다. 
예전에는 불가능 하다고 아래처럼 답변을 하셨는데 지금은 수정된 건가요?

https://github.com/plusfriend/auto_reply/issues/123

방법을 알려주시면 고맙겠습니다.

**Comment by plusfriendteam** [comment]
안녕하세요.
불편을 드려서 죄송합니다만, 자동응답 API 는 해당 기능을 제공하고 있지 않습니다.
LG HomeChat은 자동응답 API 를 사용하지 않고 카카오의 비즈메시지를 사용하고 있습니다.
카카오 비즈메시지 관련된 정보는 이 링크를 참고해주세요. https://bizmessage.kakao.com/ 
만족스러운 답변을 드리지 못해서 죄송합니다. 추후 개선을 통해서 지원할 수 있도록 노력하겠습니다.
