### ISSUE TITLE
[message, image전송] 이미지 필드에 대해 

### ISSUE THREAD

**Issue by SeungyounShin** [plusfriend/auto_reply#387]
안녕하세요 고등학생 대상으로 입시봇 구현 중인 학생입니다. (플러스친구에 입시봇 검색)
이미지를 보내고 싶은데 이미지 json구조를 보면

{
  "url": "https://photo.src",
  "width": 640,
  "height": 480
}

다음과 같고,
url에다 python PIL로 이미지를 오픈하고 PIL class를 넣으면 안되더라구요(당연한거긴한데)
이처럼 로컬서버에 있는 이미지를 오픈하고 url이 아니라 정적파일을 전송하는 방법을 알고싶습니다.

**Comment by plusfriendteam** [comment]
안녕하세요.
자동응답 API 에서는 로컬에 있는 이미지를 업로드하는 기능을 제공하고 있지 않습니다.
별도로 이미지 파일을 웹에서 접근할 수 있도록 업로드 해주시고 업로드 된 경로를 url 에 넣어주세요.
이용해주셔서 감사드리며, 만족스러운 답변을 드리지 못해 죄송합니다.
