### ISSUE TITLE
텍스트 입력창  관련 질문드립니다.

### ISSUE THREAD

**Issue by shylock3d** [plusfriend/auto_reply#388]
현재 api형을 이용해서 자동응답서비스를 구현했습니다.
그런데 문제가 키보드 상태를 기본은 type text로 가고 중간중간 type을 buttons로 구현했는데
사용자의 질문 또는 답변에 대한 응답이 늦게날라올경우 버튼키보드가 여러번 눌릴수있게 계속 올라와있더라구요.
혹시 코드상에서 버튼이 눌렸을경우에 키보드를 내리거나 텍스트 키보드로 바뀔수있게 바꾸는 방법이있는지 궁금합니다.

**Comment by plusfriendteam** [comment]
안녕하세요.
현재 응답 지연 시에 버튼 제어하는 기능은 제공하고 있지 않습니다.
여러 번 키보드가 눌릴 시에는 자동응답 API를 구현하는 서버에서 처리해주셔야 합니다.
추후에 해당 기능 고려해보도록 하겠습니다. 감사합니다.
