### ISSUE TITLE
플러스친구 일대일 대화 숨김요청

### ISSUE THREAD

**Issue by infobankimedia** [plusfriend/auto_reply#39]
안녕하세요. 인포뱅크 iMedia 사업부 김지황입니다.

EBS 라디오 플러스 친구 API 변경(1.0->2.0)이 완료 되어, 1대1 대화 버튼 숨김 처리 요청드립니다.

플러스 친구 ID : @EBS라디오

감사합니다.

**Comment by plusfriendteam** [comment]
@infobankimedia  처리완료 되었습니다. 😃
