### ISSUE TITLE
에러 관련

### ISSUE THREAD

**Issue by JonghyeokPark** [plusfriend/auto_reply#391]
안녕하세요
제가 잘 못찾아서 그런것일 수 도 있는데요, 
혹시 "응답 속도 초과" 혹은 "Internal server error(500)" 와 같은 상황에서 
사용자가 어떤 입력을 했을 때 해당 에러가 발생했는지 로깅을 남기고 싶습니다.

혹시 해당사항 검출되는 경로(?) 에 대해 알 수 있을까요?

**Comment by khhwang838** [comment]
이건 카톡측에서 해줄 일이 아닌 것 같네요. 카톡에서 보낸 메시지를 받아주는 API쪽에서 로깅을 하시면 될것 같습니다.
