### ISSUE TITLE
5.2 메시지 수신 및 자동응답 API 에서 message post 에 아무런 파라메터가 들어오지 않던데, 다른 방식으로 받아야 하나요?

### ISSUE THREAD

**Issue by jeedy** [plusfriend/auto_reply#4]
request 받은 후 response는 정상적으로 되는 것으로 봐선 정상적으로 호출이 이루어 지고있긴 합니다.
단지 parameter 값이 없어서 어떤 메시지를 보냈는지 확인할 수가 없네요.

**Comment by suya55** [comment]
request body에 json 형태의 데이터로 전송하고있습니다.
request.body 의 데이터를 확인해 보세요.

그리고 코드나 결과값 또는 개발 환경등을 알려주시면 좀더 자세한 안내가 가능할 것 같습니다.

**Comment by jeedy** [comment]
아 그렇군요~ 해결했습니다. 고맙습니다.
