### ISSUE TITLE
플러스 친구 1:1 대화 숨김요청

### ISSUE THREAD

**Issue by infobankimedia** [plusfriend/auto_reply#40]
안녕하세요. 인포뱅크 iMedia 사업부 김지황입니다.

금일 새벽 플러스 친구 API 변경 으로 인한 1:1대화 숨김 요청 드립니다.

내용은 다음과 같습니다.

1. SBS
@sbslovefm 
@sbspowerfm 

2. CBS
@CBS시사FM 
@CBS음악FM 
@CBSTV 
@세바시 
@CBSJOY4U 

7개 플러스 친구 1:1 대화 숨김 요청 드립니다.

감사합니다.

**Comment by plusfriendteam** [comment]
@infobankimedia  처리 완료되었습니다. 😄
