### ISSUE TITLE
답변API 사용시 카카오TV에 등록된 동영상이나 등록된 포스트를 이용해서 답변할수 없는지요.

### ISSUE THREAD

**Issue by loveily** [plusfriend/auto_reply#406]
답변할때
현재는 이미지,텍스트만 보낼 수 있는데...

카카오TV에 등록된 동영상이나 등록되어있는 포스트를 답변으로 보낼수는 없는지요..
위내용이 지원되면 활용할 곳이 많을거 같은데..
활용할 수 있는 방법이 있는지 문의드립니다.

**Comment by khhwang838** [comment]
메시지 버튼의 링크를 이용하실 수는 있을 것 같습니다만....동영상이나 포스트라면 썸네일 이미지도 있는 것이 좋겠죠...이건 API쪽에서 구현하셔야 할 것 같네요..
