### ISSUE TITLE
대화하기 링크 관련 문의

### ISSUE THREAD

**Issue by nemusheewon** [plusfriend/auto_reply#41]
대화하기 링크 관련해서 문의 드립니다. 

기존에는 아래와 같은 URL 형식으로 대화창에서 자동응답 키워드(기존 봇 연결 키워드)를 입력할 수 있었습니다. 

- http://plus.kakao.com/chat/{플러스친구 또는 옐로아이디의 UUID}/{키워드} 

현재는 위 URL을 사용하면 1:1 대화로 연결되어 실제 서비스에서 사용하지 못하고 있습니다.  

대체할 수 있는 URL이 있다면 확인 부탁 드립니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 
https://github.com/plusfriend/auto_reply/issues/36 문의에 동일한 내용이 포함되어 있으니 참고하셔서 문의 부탁드립니다. 원 문의에 기재하신 url은 외부에 노출이 제한된 내용으로 삭제 처리하였습니다.
