### ISSUE TITLE
현재 메뉴가 떠져있는 상태인지 확인하는 방법

### ISSUE THREAD

**Issue by whdtjstm** [plusfriend/auto_reply#419]
예를 들어 문의드리겠습니다.

사용자가 'A'라는 메시지를 입력하면,
'아래 메뉴 중 선택하세요'라는 메시지와 함께 버튼으로 'B', 'C', 'D'를 표시합니다.

이때, 사용자가 아직 버튼을 누르지 않은 상태에서
카카오톡 앱을 종료하거나 일정시간이 경과해서
다시 채팅방에 들어오면..

'아래 메뉴 중 선택하세요'라는 메시지는 그대로 보이나,
'B', 'C', 'D' 메뉴는 보이지 않고
그냥 텍스트 입력창이 보이게 됩니다.

이 때에 현재 사용자의 채팅방 상태가
메뉴가 보이는 상태인지
아니면 안보이고 텍스트 입력 상태인지
확인할 수 있는 방법이 있나요?
아니면, 텍스트 입력 상태로 가지 않고 어떠한 상황에서도 메뉴가 보이게 할 순 없는지요?

**Comment by klkim** [comment]
스펙문서 5.1 Home Keyboard API 부분을 보시면, 채팅방에 진입시에 http(s)://:your_server_url/keyboard 가 호출된다고 나와있습니다.

사용 시나리오에 맞게 이 부분을 구현하시면 될 것 같습니다.
질문하신것처럼 현재 카톡 대화창의 상태 관리를 해 주거나 알 수 있는 API는 없는것으로 알고 있습니다.
