### ISSUE TITLE
채팅방이 유지된 상태로 친구차단한 경우에 대한 문제 입니다.

### ISSUE THREAD

**Issue by mcvzone** [plusfriend/auto_reply#42]
안녕하세요~
 
신API개발 화면에서 테스트 시 문의사항이 있습니다.
 
채팅방에서 나오지 않고, 친구차단을 한 후, 다시 채팅방을 열면
캡쳐 화면과 같이 +추가,  알림톡 차단 바가 뜨지 않습니다.
 
신API에서는 제공하지 않는 기능인지,
만약, 제공하는 기능이라면 적용하는 방법을 문의 드립니다.
 
감사합니다.

![c](https://cloud.githubusercontent.com/assets/13563636/16443314/0df73b86-3e13-11e6-9428-53f511238c98.png)

**Comment by plusfriendteam** [comment]
설명이 조금 꼬인것 같습니다.

> 채팅방에서 나오지 않고, 친구차단을 한 후, 다시 채팅방을 열면

나오지 않았는데 열었다는게 설명이 조금 꼬인듯합니다. :)
다시 자세히 설명 부탁드리겠습니다.

감사합니다.
