### ISSUE TITLE
이 API는 라이센스가 어떻게되나요?

### ISSUE THREAD

**Issue by jaeho93** [plusfriend/auto_reply#425]
이 API는 라이센스가 어떻게되나요? 플러스친구 API 이용해서 챗봇 구현하려는데 라이센스가
어디 써있는지 모르겠네요.

**Comment by byeonggukgong** [comment]
[플러스친구 이용약관](https://center-pf.kakao.com/terms) **제 9 조**를 참고하시면 될 것 같습니다.
