### ISSUE TITLE
pc 연동 문의

### ISSUE THREAD

**Issue by dablase** [plusfriend/auto_reply#427]
카카오톡 플러스 친구 PC연동 관련 문의 드립니다.

카카오톡 플러스 친구를 생성하면 플러스 친구 홈으로 이동가능한 URL이 생성되는걸로 알고있습니다.

PC에서 해당 URL을 타고 들어가면, 제가 생성한 플러스 친구 홈으로 이동합니다.

이후 친구추가 버튼을 누르게되면 "친구추가는 카카오톡 모바일앱에서 가능합니다." 라는 문구가 나오는데, 여기서 사용자의 카카오톡 앱으로 메시지를 보내거나 카카오톡 앱에서 플러스 친구 홈페이지가 바로 노출되는 방법은 없을까요?

가능한 방법이 있는지 혹은 비즈메시지와 같은 유료 서비스를 이용하면 가능한건지 궁금해 문의드립니다.

감사합니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 답변이 늦어 죄송합니다. 
말씀하신 기능 현재 서비스 중이니 참고해주시기 바랍니다. ^^
