### ISSUE TITLE
아이폰 자동응답 버튼 미노출 현상

### ISSUE THREAD

**Issue by infobankimedia** [plusfriend/auto_reply#43]
안녕하세요. 인포뱅크 김지황입니다.

현재, 아이폰에 플러스친구 자동응답 버튼이 미노출 되는 현상이 발생되는 것으로 확인 되었습니다.
(7월 1일 부로 API 1.0 종료 및 2.0으로 이동과 관련하여 문제인지 의심됩니다.)

현상 : 
1. 현재 하단에 홈버튼만 노출 되고 있습니다.
2. 홈버튼 선택시, 계속해서 로딩이 진행 중으로 보입니다.

테스트폰 정보

IOS ver : 9.3.2
카카오톡 ver : 5.7

추가적으로 현재 운영중인 플러스친구 계정은 다음과 같습니다.
---------------------------------------
SBS파워FM
SBS러브FM    
FEBC극동방송  
CBS 시사FM      
CBS 음악FM
CBS JOY4U   
CBS TV    
엠넷
세바시
EBS 라디오  
EBS생방송 톡!톡! 보니하니
---------------------------------------

운영중인 플러스친구 자동응답이 있어서, 빠른 처리 부탁드립니다.

감사합니다.

**Comment by infobankimedia** [comment]
![kakaotalk_20160701_100612336](https://cloud.githubusercontent.com/assets/19382791/16509067/557ebdf0-3f74-11e6-8f26-3c4eeba9189b.jpg)

1번 현상 캡쳐 화면입니다.

**Comment by plusfriendteam** [comment]
@infobankimedia 
옐로아이디/플친 신규 서비스 오픈으로 인해 해당 api 서버에 트래픽이 몰려 자동응답 정보를 내려주지 못하였습니다. 
현재는 서비스 정상화 되어 정상적으로 이용 가능합니다
불편을 드려 죄송합니다.
