### ISSUE TITLE
데이터 전송방식에 대해서 질문드립니다.

### ISSUE THREAD

**Issue by LeekeunJe** [plusfriend/auto_reply#44]
현재 linux, php를 이용해서 자동응답 서버를 구축했습니다.

이용자가 카카오톡에서 전송한 메세지와 해당 이용자의 key값(또는 id)를

서버에서 받아서 다시 그대로 채팅방으로 보내주는 방법으로 테스트를 해보고싶습니다.

사용자가 카카오톡에서 입력한 text 또는 이미지, 유저키는 어떻게 받는지.

그리고 처리된 결과값은 어떻게 반환하는지에 대해 구체적인 명시가 없어서

조금 더 자세한 설명을 듣고싶습니다. 

그리고 혹시 가능하시면 간단한 예제코드를 받아볼 수 있을까 여쭤보고싶습니다.

**Comment by suya55** [comment]
사용자가 입력한 메시지 정보는 request body에 json data로 전달이 됩니다.
request에서 json body를 추출하는 방법은 구글링을 하시면 예제가 엄청 많습니다.
