### ISSUE TITLE
서버에 요청이 들어오기도 전에 request timeout 발생

### ISSUE THREAD

**Issue by nupamore** [plusfriend/auto_reply#440]
직접 테스트해보니 간헐적으로 누르자마자 응답시간 초과 에러메세지가 옵니다.
정상적인건 ip 234~6 다 들어오는데 에러나는건 로그조차 뜨지 않네요.

**Comment by taehoonjth** [comment]
네. 지금 전체적으로 모든 플러스 친구에서 발생하는 에러입니다. 간헐적으로가 아니라 꽤 자주 발생하는 것 같습니다. 카톡이 api 요청도 안하고 바로 응답시간 초과라고 해버리네요ㅜㅜ

**Comment by SeoktaeKang** [comment]
위 장애가 계속 지속되네요. 아무리 오픈API지만 커뮤니케이션 자체가 없으니까 API를 쓰는 입장에서 답답하네요.. 빠른 조치 부탁 드립니다.

**Comment by infobankimedia** [comment]
아직도 계속 되고 있네요. 이전에 문의했을때에는 타임아웃 건으로 오는 알람이라고 하던데 애초에 문제가 있지 않았나 싶네요... 빠른 조치 부탁드립니다

**Comment by plusfriendteam** [comment]
안녕하세요. 플러스친구팀입니다.

11월 29일 23시경부터 30일 15시경까지 
시스템 장애로 인해 플러스친구 자동응답 API가 정상적으로 작동되지 않는 현상이 있었습니다.

해당 문제는 모두 해결 완료되어 현재 정상적인 서비스 이용이 가능합니다.
긴 시간 동안 서비스 이용에 불편을 드려 진심으로 사과드리며 보다 나은 서비스를 제공하기 위해 노력하겠습니다.

감사합니다.
