### ISSUE TITLE
API형 스마트채팅 연결 오류

### ISSUE THREAD

**Issue by nemusheewon** [plusfriend/auto_reply#442]
스마트채팅 API형을 사용하고 있는 플러스친구에서 모두 
"해당 프로필의 자동응답 시스템이 응답을 하지 않습니다. 문제가 보고되어 처리 예정입니다. 다음에 다시 시도해주세요"라고 응답하고 있습니다. 
@한국로슈, @SBS골프 외 다수 플러스친구에서 발생중입니다. 
메시지 내용으로 현재 확인중이신것 같은데 답변 부탁 드립니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 플러스친구팀입니다.

11월 29일 23시경부터 30일 15시경까지 
시스템 장애로 인해 플러스친구 자동응답 API가 정상적으로 작동되지 않는 현상이 있었습니다.

해당 문제는 모두 해결 완료되어 현재 정상적인 서비스 이용이 가능합니다.
긴 시간 동안 서비스 이용에 불편을 드려 진심으로 사과드리며 보다 나은 서비스를 제공하기 위해 노력하겠습니다.

감사합니다.
