### ISSUE TITLE
얼마전부터 Wrong keyboard init이 자주 발생합니다

### ISSUE THREAD

**Issue by Daseul-Hwang** [plusfriend/auto_reply#443]
정상동작하던 플친에서 Wrong keyboard init 메세지가 자주 출력되고
앱 URL 테스트에서도 OK 됐다 안됐다합니다.

다른 서버의 URL로 테스트하니 심지어

'예상하지 못한 오류가 발생했습니다.
잠시 후 다시 시도해주세요.'

메세지가 나오는 경우도 있습니다.

플러스친구 측 문제라면 플러스친구 공지사항에 문제 발생 여부에 관해서라도 먼저 올려주셨으면 좋겠습니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 플러스친구팀입니다.

11월 29일 23시경부터 30일 15시경까지 
시스템 장애로 인해 플러스친구 자동응답 API가 정상적으로 작동되지 않는 현상이 있었습니다.

해당 문제는 모두 해결 완료되어 현재 정상적인 서비스 이용이 가능합니다.
긴 시간 동안 서비스 이용에 불편을 드려 진심으로 사과드리며 보다 나은 서비스를 제공하기 위해 노력하겠습니다.

감사합니다.
