### ISSUE TITLE
타임아웃 에러가 7시간째인데..

### ISSUE THREAD

**Issue by SeoktaeKang** [plusfriend/auto_reply#448]
왜 아무런 응답이 없을까요?
API 만 응답 없는게 아니라 카카오도 응답이 없네요

**Comment by plusfriendteam** [comment]
안녕하세요. 플러스친구팀입니다.

11월 29일 23시경부터 30일 15시경까지 
시스템 장애로 인해 플러스친구 자동응답 API가 정상적으로 작동되지 않는 현상이 있었습니다.

해당 문제는 모두 해결 완료되어 현재 정상적인 서비스 이용이 가능합니다.
긴 시간 동안 서비스 이용에 불편을 드려 진심으로 사과드리며 보다 나은 서비스를 제공하기 위해 노력하겠습니다.

감사합니다.
