### ISSUE TITLE
API형 응답 지연 건 언제쯤 해결됩니까?

### ISSUE THREAD

**Issue by 1004derek** [plusfriend/auto_reply#449]
이슈에 대한 응대가 빠르지도 못하고 적극적이지도 못하네요

현재 해당 오류가 7시간 넘게 지속되고 있으며, 이로 인한 서비스 피해가 기하급수적으로 늘어나고 있습니다.

서비스를 만들어 놓고 책임 있는 운영의 의지도 안 보이네요. 

그냥 이렇게 해결되면 공지 하나 올리면 그만인가요?

빠른 해결 촉구 합니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 플러스친구팀입니다.

11월 29일 23시경부터 30일 15시경까지 
시스템 장애로 인해 플러스친구 자동응답 API가 정상적으로 작동되지 않는 현상이 있었습니다.

해당 문제는 모두 해결 완료되어 현재 정상적인 서비스 이용이 가능합니다.
긴 시간 동안 서비스 이용에 불편을 드려 진심으로 사과드리며 보다 나은 서비스를 제공하기 위해 노력하겠습니다.

감사합니다.
