### ISSUE TITLE
아이폰에서 플러스친구 대화방 진입 시에 대화창 비활성화 이슈

### ISSUE THREAD

**Issue by gwuijeonglim** [plusfriend/auto_reply#45]
금일 (7/1) 오전 10시 경부터 11시 반까지 플러스친구 대화방 진입 시에 
최초에 보이는 키보드 버튼이 보이지 않고, 대화창 자체가 비활성화 되는 이슈가 확인되었습니다.

이 현상은 iPhone 단말에서만 확인되었습니다.

현재는 정상 복구된 상태이지만 해당 시간동안 플러스친구 서비스를 사용할 수 없어 이슈가 컸습니다.

해당 이슈에 대한 발생 원인 및 조치 내역과 향후 재발을 막기 위한 계획을 공유해주세요.

**Comment by humit0** [comment]
#43 과 같은 내용입니다.

**Comment by gwuijeonglim** [comment]
#43 답변 확인하였습니다.
그런데 6/20에도 동일한 장애가 있었습니다.
그렇다면 현재 복구되었다고해서 동일한 장애가 또 발생할 수 있는 건가요?
근본적인 해결 대책은 없는 건가요? 
별도 진행 계획이 있다면 공유 부탁드립니다.

**Comment by plusfriendteam** [comment]
옐로아이디/플러스친구 서비스 개편으로 인해 해당 api 서버에 트래픽이 몰려 자동응답이 원활하게 동작하지 못했습니다. 
관련하여 동일현상이 재발하지 않도록 조치를 해두었습니다. 
이용에 불편을 드려 죄송합니다.

**Comment by gwuijeonglim** [comment]
동일 현상이 다시 나타나고 있습니다. (7/4 17:35 ~ )
조치가 되었다고 하셨는데 동일 이슈가 반복적으로 나타나고 있습니다.
빠른 조치 및 정확한 현황 공유 부탁드립니다.

재발 방지에 대한 부분도 확실히 공유 부탁드립니다.
