### ISSUE TITLE
자동응답 메세지 줄바꿈기능

### ISSUE THREAD

**Issue by hangonee** [plusfriend/auto_reply#461]
message.php에서 

if (입력==~~~)
"messsage":{ "text":" ~~~~이고 ~~~입니다"}

이런식으로 출력을 시키는데 

~~~~이고
~~~입니다


이렇게 두줄에 나눠서 출력하려합니다.

"messsage":{ "text":"~~~~이고 \n ~~~입니다"}
이렇게하면 특정 키워드를 입력해도 응답 자체가 뜨질않네요
줄바꿈하는 다른 방법이있을까요?

**Comment by ilhanjo** [comment]
반환값에 \n를 넣으면 아예 동작 자체가 안된다는 말인가요?

**Comment by hangonee** [comment]
@ilhanjo 네 "messsage":{ "text":"~~~~이고 \n ~~~입니다"} 이런식으로는 아예 작동이 안돼서 그냥 띄어쓰기 엄청 넣어서 강제로 줄바꾸기했네요 ㅠㅠㅠ
그때 다른게 오류였는지 조만간 \n이든 엔터든 넣어서 다시 수정해보려구요

**Comment by MCPE-PC** [comment]
만약 언어가 JavaScript(Node.js)이면 `(백틱) 템플릿 문자열을 사용하시면 내부에서 엔터가 가능합니다.
