### ISSUE TITLE
API 형 스마트채팅 오류문의 - 잘못된 응답입니다 를 해결해주세요! 꼭 답변주세요.

### ISSUE THREAD

**Issue by kjvjung** [plusfriend/auto_reply#462]
http://kakao.nicenomu.com/keyboard
URL 은 위와같이 등록된 상태입니다. 초기 버튼은 잘 뜨지만 버튼을 클릭시 아래와 같은 에러가 발생합니다.

[관리자에게만 발송되는 메시지입니다] 사용자 봇서버에 에러가 감지 되었습니다. 
 내용:[잘못된 응답입니다. response json parsing error. user_key : .....foxuB00, You'r server response : {
    "type" : "buttons",
    "buttons" : ["문제 풀기", "나가기"]
}]

------------------------
외부에서도 해당 URL 로는 잘 접속되고 있습니다.
http://kakao.nicenomu.com/keyboard
http://kakao.nicenomu.com/message

-----------------------
2개의 PHP 프로그램은 UTF8  파일로 저장되어 있고 내용은 아래와 같습니다.

keyboard.php --------------------------------

<?php
header("Content-Type:application/json; charset=UTF-8");

echo <<< EOD
{
    "type" : "buttons",
    "buttons" : ["문제풀기", "나가기"]
}
EOD;
?>

message.php --------------------------------

<?php
header("Content-Type:application/json; charset=UTF-8");

$data = json_decode(file_get_contents('php://input'), true);
$content = $data["content"];
 
if($content == "문제풀기"){ 
    echo <<< EOD
    {
        "message": {
            "text": "ㅈ ㅏ ㄹ ㅜ ㅁ ㅏ ㄷ ㅣ를 낱말로 만든다면 무엇이 될까?"
        },
        "keyboard": {
            "type": "buttons",
            "buttons": ["동물", "도시", "행성", "물고기"]
        }
    }
EOD;
}
else{
    echo <<< EOD
    {
        "message": {
            "photo": {
                "text" : "안녕히 가세요.",
                "url": "https://avatars2.githubusercontent.com/u/7802741?s=40&v=4",
                "width": 240,
                "height": 240
            }
        }
    }
EOD;
}
?>

감사합니다.

**Comment by ilhanjo** [comment]
http://kakao.nicenomu.com/message 의 반환값을
{
    "message": {
        "text": "안녕히 가세요.",
        "photo": {
            "url": "https://k.kakaocdn.net/dn/bddmfp/btqgWYGAH8J/LngiR8IZXonVcvu6fwsOeK/img_s.jpg",
            "width": 240,
            "height": 240
			},
        },
  "keyboard": {
    "type": "text"
    }
}
이렇게 해보세요

**Comment by SerenityS** [comment]
url 등록하실때 keyboard 없애셔야합니다.

**Comment by MCPE-PC** [comment]
user_id값은 애초에 필요없고, 나머지 정보들은 keyboard 오브젝트에 넣어야 합니다
