### ISSUE TITLE
django  JSON 받아오기 오류

### ISSUE THREAD

**Issue by skfnxhjjj** [plusfriend/auto_reply#463]
django로 개발중입니다. 

from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json,datetime

def keyboard(request):

        return JsonResponse({
                'type' : 'buttons',
                'buttons' : ['1','2','3','4']
        })

@csrf_exempt
def message(request):
        json_str = ((request.body).decode('utf-8'))
        received_json_data = json.loads(json_str)
        name = received_json_data['content']
        today_date = datetime.date.today().strftime("%m월 %d일")

        return JsonResponse({
                'message': {
                        'text' : today_date + '의' + name + '입니다.'
                },
                'keyboard': {
                        'type': 'buttons',
                        'buttons':['1','2','3','4']
                }
        })

views.py 는 이런식으로짰습니다.
카카오톡 API 테스트도 잘통과했고
카카오톡 채팅방 내에서 키보드도 잘보입니다. 그런데 POST 로 전송시 서버에
[13/Dec/2017 13:34:24] "POST /keyboard/message HTTP/1.1" 200 114
[13/Dec/2017 13:34:25] "POST /keyboard/message HTTP/1.1" 200 114
[13/Dec/2017 13:34:25] "POST /keyboard/message HTTP/1.1" 200 114
[13/Dec/2017 13:34:25] "POST /keyboard/message HTTP/1.1" 200 114
이런식으로 나옵니다.
우분투에서 curl -XPOST 'http://*.*.*.*/message' -d '{"user_key": "encryptedUserKey", "type": "text", "content": "1"}'
로 전송하면 
[13/Dec/2017 13:50:11] "POST /message HTTP/1.1" 200 232
서버에는 이렇게 나오고 우분투에서도 잘읽어옵니다. 그런데 카카오톡에서만 전송을하면
[잘못된 응답입니다. response json parsing error. user_key: ...  라고 에러가 납니다.

**Comment by ilhanjo** [comment]
우분투에서 curl 응답이 어떻게 나오나요?
text에서 한글 없이 출력해도 안되나요 ?

**Comment by skfnxhjjj** [comment]
text에서 한글이없어도 출력이 안됩니다.
curl 응답은 {"keyboard": {"buttons": ["\uc870\uc2dd", "\uc911\uc2dd", "\uc11d\uc2dd", "\uac1c\ubc1c\uc790\uc815\ubcf4"], "type": "buttons"}, "message": {"text": "12\uc6d4 14\uc77c\uc758\uc911\uc2dd\uba54\ub274 \uc785\ub2c8\ub2e4."}} 이렇게 나옵니다..

**Comment by SerenityS** [comment]
Api 설정하실때 URL에 http://server.com/keyboard 이런식으로 keyboard까지 입력하신건 아닌지요?

**Comment by skfnxhjjj** [comment]
@SerenityS  감사합니다! 덕분에 해결했습니다.
