### ISSUE TITLE
버튼별 다른응답 api

### ISSUE THREAD

**Issue by choijongsun** [plusfriend/auto_reply#464]
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json

def keyboard(request):

        return JsonResponse({
                'type' : 'buttons',
                'buttons' : ['1','2','3','4']

                })

@csrf_exempt
def message(request):
        message = ((request.body).decode('utf-8'))
        return_json_str = json.loads(message)
        return_str = return_json_str['content']

        return JsonResponse({
                'message': {
                        'text': 'ㅁㅇㄵㅈ
                },
                'keyboard': {
                   'type' : 'buttons',
                   'buttons' : ['5','6','7','8']
                }

        })

keyboard 에서 1번버튼을 누르면 a,b,c 라는 버튼이나오고
keyboard 에서 2번버튼을 누르면 d,e,f 라는 버튼이나오고
keyboard 에서 3번버튼을 누르면 g,h,i 라는 버튼이나오고
keyboard 에서 4번버튼을 누르면 j,k,l 이라는 버튼이나오고

또 각각의 버튼마다 다른 버튼이 나오게 연속적으로 할수없나요?

제가 구글링만으로 따라서 해온거라서 응용을 못하겟내요..

**Comment by SerenityS** [comment]
return_str을 if문으로 처리하시면 되겠네요
