### ISSUE TITLE
플러스친구로 등록한 사람모두에게 메세지전송

### ISSUE THREAD

**Issue by skfnxhjjj** [plusfriend/auto_reply#466]
Python3.5 Django 로 개발중입니다.
특정 시간에 플러스친구로 등록한 모두에게 메세지를 전송하는 기능을 구현하려고합니다.
구현이 가능할까요?? 구현이 가능하다면 무슨방법으로 구현해야할까요. 감사합니다.

**Comment by SerenityS** [comment]
사용자 request에 response하는것 말고는 메세지 보내는 방법이 없는걸로 알고있습니다.
이용자한테 메세지 보내는건 관리자 센터에서 판매중인 항목이니까요..

**Comment by plusfriendteam** [comment]
안녕하세요. 말씀하신 스펙은 플러스친구 관리자센터에 있는 메시지 기능을 통해 이용하실 수 있습니다. 
(https://center-pf.kakao.com/)
