### ISSUE TITLE
Home Keyboard API 관련 문의

### ISSUE THREAD

**Issue by nemusheewon** [plusfriend/auto_reply#47]
안녕하세요. 네무스텍 정희원입니다. 

이전에도 문의 드렸던 Home Keyboard API 이슈가 다시 발생하여 문의 드립니다. 

문의 내용은 #11 과 동일합니다. 

그럼 확인 부탁 드립니다.

**Comment by plusfriendteam** [comment]
안녕하세요.
#50 이슈를 통해 현재 문제상황 안내해 드렸습니다. 참고 부탁드리며, 이용에 불편을 드린 점 다시 한번 사과드립니다.

**Comment by plusfriendteam** [comment]
#50 이슈를 통해 공지드린 내용 정상화되었습니다. 이용에 참고 부탁드립니다.
