### ISSUE TITLE
입력창을 눌러도 키보드 메뉴가 나오지 않습니다

### ISSUE THREAD

**Issue by deepseasw** [plusfriend/auto_reply#474]
여러 챗봇들을 확인해봤는데 되는것도 있고 안되는 것도 있습니다. 제 챗봇도 어떤 날은 괜찮고 간헐적으로 문제가 발생합니다. 왼쪽의 화살표 버튼을 누르면 키보드가 표시됩니다. 키보드 메뉴만 그렇고 보통 입력일때는 정상입니다. 아이폰5인데 제 폰에서만 그런건가요?

**Comment by arrrggghhh** [comment]
저도 아이폰에서 화살표 버튼을 눌러야 키보드가 올라옵니다.

**Comment by plusfriendteam** [comment]
말씀하신 화살표는 플러스친구 채팅방 개편 이후 제거되었으므로 이슈 클로즈하겠습니다. 감사합니다.
