### ISSUE TITLE
새로 바뀐 세로 방향 버튼 목록 방해됩니다.

### ISSUE THREAD

**Issue by arrrggghhh** [plusfriend/auto_reply#477]
버튼 목록 핸들을 잡고 위로 올리면 뒤에 있는 텍스트가 가려지고 스크롤이 되지 않습니다.

텍스트를 보면서 버튼을 눌러야 하는데 버튼을 올리면 텍스트를 볼 수 없고,

버튼목록을 축소시켜서 내리면 텍스트는 보이지만 버튼을 누를 수 없습니다.

그리고 버튼 목록을 확장/축소시켰을 때  목록 확장/축소 상태 유지되도록 해 주세요.

사실상 버튼이 2개 이상이면 매번 응답마다 버튼 목록을 올려야 해서 사용자들 입장에서 너무 불편합니다.

안드로이드, 아이폰 모두 해당입니다.

빠른 피드백 및 수정 바랍니다.

**Comment by taehoonjth** [comment]
동의합니다

**Comment by plusfriendteam** [comment]
안녕하세요. 
플러스친구 채팅방은 챗봇 뿐만 아니라 메시지, 상담 등 여러 다른 기능도 동시에 동작해야하기 때문에 
채팅방 본연의 기능을 좀 더 쉽고 편하게 사용할 수 있는 것을 중점으로 개편을 진행했습니다. 
이에 따라 챗봇을 이용하는 일부 채팅방에서는 불편하게 작동한다는 점에 대해 깊이 공감합니다. 
추후 개편 시에는 이점 충분히 반영하여 개편될 수 있도록 하겠습니다. 감사합니다.
