### ISSUE TITLE
스마트채팅 디자인 개편 이후 1:1 채팅 전환되지 않고 사용자 입력 문구가 API 서버로 넘어옵니다

### ISSUE THREAD

**Issue by woongy** [plusfriend/auto_reply#479]
https://center-pf.kakao.com/notices/121 
공지사항에 따르면 "1:1 채팅 전환 버튼을 클릭하지 않아도 입력창에 글을 쓰면 바로 1:1 채팅으로 전환"되어야 하는데, 전환되지 않고 API 서버로 그대로 넘어오고 있습니다. 개편 이전에는 1:1 채팅으로 전환해서 상담원이 대응하고 있었는데, 이렇게 바뀌면 사용자들이 입력하는 문구가 서버에서 처리되지 못하고 상담원이 발견하지도 못하게 되는데요. 공지와 다른 스펙으로 릴리즈 된 것인지, 버그가 있는 것인지 빠른 확인 부탁드립니다.

**Comment by humit0** [comment]
내용을 잘 읽어보시면 이렇게 되어 있습니다.

1:1 채팅 전환 버튼을 클릭하지 않아도 입력창에 글을 쓰면 바로 1:1 채팅으로 전환됩니다. 

(단, **FAQ형을 사용**하는 경우에만 적용됩니다. API형과 1:1 채팅을 동시 사용하는 채팅방일 경우

"상담원과 채팅하기"라는 전환 메뉴가 그대로 제공되며 _해당 메뉴를 클릭해야 1:1 채팅으로 전환_됩니다 )

**Comment by woongy** [comment]
릴리즈 이후로 공지사항 내용이 변경된 것 같네요. 릴리즈 당일 카카오 고객센터에 연락해서 현재 릴리즈 된 스펙이 맞다고 확인받았습니다.
