### ISSUE TITLE
아이폰 키보드 메뉴 문제

### ISSUE THREAD

**Issue by SeoktaeKang** [plusfriend/auto_reply#48]
안녕하세요..
아이폰의 키보드API가 안뜨는 문제가 또 발생했습니다.
벌써 3번째네요..
빠른 확인 및 조치 좀 바랍니다.

**Comment by plusfriendteam** [comment]
안녕하세요.
#50 이슈를 통해 현재 문제상황 안내해 드렸습니다. 참고 부탁드리며, 이용에 불편을 드린 점 다시 한번 사과드립니다.

**Comment by plusfriendteam** [comment]
#50 이슈를 통해 공지드린 내용 정상화되었습니다. 이용에 참고 부탁드립니다.
