### ISSUE TITLE
새로 바뀐 새로 방향 버튼은 문제가 있습니다

### ISSUE THREAD

**Issue by taehoonjth** [plusfriend/auto_reply#484]
사용자가 버튼을 눌렀을 때

다음 버튼을 누르려면 다시 버튼을 끌어올려야 하는건 확실히 문제가 있는 UX입니다

개선 부탁드립니다

**Comment by YoungHwa** [comment]
저도 같은 문제가 있습니다.
심지어 기존 버튼이 닫히지 않아서 내렸다가 올려야 다음 버튼으로 갱신되네요.
빠른 개선 부탁드립니다.

**Comment by Weisure** [comment]
사용자 입장에서 챗봇을 사용하기에 정말 비효율적으로 바뀐 것 같아요.
빠른 개선 부탁드립니다/

**Comment by jungmuna** [comment]
진짜 너무 불편하네요.. 사용하는 업체마다 모두 문의와요...

**Comment by JaewonYi** [comment]
너무 불편해요.. 심지어 핸들을 올리면 대화창도 가려지고요..

**Comment by plusfriendteam** [comment]
안녕하세요. 
플러스친구 채팅방은 챗봇 뿐만 아니라 메시지, 상담 등 여러 다른 기능도 동시에 동작해야하기 때문에 
채팅방 본연의 기능을 좀 더 쉽고 편하게 사용할 수 있는 것을 중점으로 개편을 진행했습니다. 
이에 따라 챗봇을 이용하는 일부 채팅방에서는 불편하게 작동한다는 점에 대해 깊이 공감합니다. 
추후 개편 시에는 이점 충분히 반영하여 개편될 수 있도록 하겠습니다. 감사합니다.
