### ISSUE TITLE
[또다시발생]아이폰에서 플러스친구 대화방 진입 시에 대화창 비활성화 이슈

### ISSUE THREAD

**Issue by gwuijeonglim** [plusfriend/auto_reply#49]
#45 과 동일 현상이 다시 나타나고 있습니다. (7/4 17:35 ~ )
조치가 되었다고 하셨는데 동일 이슈가 반복적으로 나타나고 있습니다.
빠른 조치 및 정확한 현황 공유 부탁드립니다.

재발 방지에 대한 부분도 확실히 공유 부탁드립니다.

**Comment by plusfriendteam** [comment]
안녕하세요.
#50 이슈를 통해 현재 문제상황 안내해 드렸습니다. 참고 부탁드리며, 이용에 불편을 드린 점 다시 한번 사과드립니다.

**Comment by plusfriendteam** [comment]
#50 이슈를 통해 공지드린 내용 정상화되었습니다. 이용에 참고 부탁드립니다.
