### ISSUE TITLE
매일 10시마다 식단표를 좀 등록되어있는 플러스친구들한테 보내주려고하는데요

### ISSUE THREAD

**Issue by qhrtkqhs555** [plusfriend/auto_reply#496]
매일 10시마다 식단표를 좀 등록되어있는 플러스친구들한테 보내주려고하는데요

api 나 그런걸로 방법이없나요?

keyboard랑 message만 있고요

송신하는게없느너같은데 이걸 홈페이지들어가서 매번 메세지보내기 예약을 해놓는건 정말 비효율적이잖아요

프로그래밍으로 매일 10시되면 api 나 뭐시기로 쏴서 친구들한테 보내주고싶은데
이거 방법이없나요? 빠른답변좀부탁드립니다.

**Comment by humit0** [comment]
카카오톡 비즈메시지를 이용하시면 됩니다.
https://bizmessage.kakao.com/
