### ISSUE TITLE
API TEST 문의

### ISSUE THREAD

**Issue by xenon80** [plusfriend/auto_reply#5]
자동응답 API 테스트를 위해 API TEST 버튼을 누르면 아래와 같은 에러가 발생합니다.

Initialize Api test : Fail 500 : wrong keyboard initialization
Friend add Api test : Fail 500 : handshake alert: unrecognized_name
Friend block Api test : Fail 500 : handshake alert: unrecognized_name
Chatroom leave Api test : Fail 500 : handshake alert: unrecognized_name

앱 URL을 https://www.domain.com/abc/keyboard 와 같이 사용하기 위해 https://www.domain.com/abc/ 를 입력했는데, 이렇게 하는게 맞나요?

**Comment by suya55** [comment]
@xenon80 네 입력한 방식은 맞습니다. 서버에 방화벽이 셋팅되어 있지는 않는지 확인해보시겠어요?
https://github.com/plusfriend/auto_reply/issues/1
위 이슈를 참고하세요.

**Comment by xenon80** [comment]
멀티도메인 인증서를 사용중인데, 인증서의 도메인CN 으로 사용하지 않는 경우에는 오류가 발생하네요. 이슈는 해결되었습니다.
