### ISSUE TITLE
스마트 채팅 API형 장애 문의

### ISSUE THREAD

**Issue by kteran** [plusfriend/auto_reply#502]
2018년1월15일 13시 쯤 부터 
http(s)://:your_server_url/message 로 파라미터가 전달되지 않는 것 같습니다.

확인 부탁드립니다.

**Comment by SerenityS** [comment]
저는 잘작동합니다

**Comment by YoungjinShin** [comment]
저도 같은 문제를 겪다가 해결한 사람입니다.

- 원인
http(s)://도메인/.../keyboard/index.php로 설정하시면 문제가 생깁니다.
http(s)://도메인/.../keyboard로 접속하시면, http(s)://도메인/.../keyboard/index.php로 redirect 되는 방식으로 접속됩니다.
그런데 찾아보니 php://input은 redirct 시 정상 작동 안할 수 있다고 하네요.

- 해결법
http(s)://도메인/.../keyboard/index.php 에서 http(s)://도메인/.../keyboard.php로 바꾸신 다음에,
.htaccess 파일 수정을 통해 .php 없이 들어갈 수 있게 설정해보세요.

**Comment by Yurail** [comment]
YoungjinShin님 감사합니다.
덕분에 해결했네요

**Comment by kteran** [comment]
YoungjinShin님 감사합니다.
해결했습니다.
