### ISSUE TITLE
관계자 분들 #504 이슈  빠른 답변 부탁드립니다.

### ISSUE THREAD

**Issue by Paranoidkr** [plusfriend/auto_reply#507]
기존에는 잘 되던 서비스가 카카오톡의 이슈로 인해 오류가 발생합니다.
이슈게시판을 보면 같은 문제를 제기 하시는 분들이 많습니다.

두개의 계정에 같은 챗봇 링크를 붙였는데, 한개는 아무런 값이 안넘어오고,
하나는 정상 작동하는 이슈 입니다.

관계자 분들은 확인 하시고 빠른 답변 부탁드리겠습니다.

ps. 깃헙 뺴고는 다른 컨텍 포인트가 없으니 답답하네요.

**Comment by YAKKISOBA** [comment]
저 역시 마찬가지로 안되네요~
/message 호출 시 return 되는 값이 없습니다. 
빨리 증상이 해결되었으면 좋겠네요.

**Comment by Paranoidkr** [comment]
readme 파일 업데이트 된 내용 보고 해결 완료 하였습니다.
