### ISSUE TITLE
메시지 줄넘김(줄바꿈) 출력

### ISSUE THREAD

**Issue by kr2rochi** [plusfriend/auto_reply#512]
https://github.com/plusfriend/auto_reply/issues/390

위 이슈에도 동일한 내용이 있는데 
text에서 줄넘김을 하려고 해도 \n도 안먹히고 html도 들어가지 않네요. 줄넘김 어떻게 해야할까요

**Comment by eternal203** [comment]
CRLF(￦r￦n)로 한번 해보세요.
저는 이걸로 되는 것 같더라구요.

**Comment by kr2rochi** [comment]
\\n 으로 처리됐습니다( iwi모사 웹호스팅)
