### ISSUE TITLE
keyboard 요청 후 에러

### ISSUE THREAD

**Issue by pandagirin** [plusfriend/auto_reply#516]
코노하에서 가상서버 하나 만들어서 우분투 , 아파치, php 로 카카오봇을 제작중입니다.
api테스트에서 keyboard.php가 제대로 작동하였고
들어온 값을 message에 잘 보내기만 하면 되는데 오류가 걸리네요;
관리자에게만 발송되는 메시지입니다] 사용자 봇서버에 에러가 감지 되었습니다. 
 내용:[잘못된 응답입니다. response json parsing error. user_key : VHOtQyijyast, You'r server response : {
    "type" : "buttons",
    "buttons" : ["GP감꽃푸드코트", "공학관 교직원식당", "공학관 학생식당", "복지관 교직원식당", "복지관 학생식당", "정보센터식당"]
}]

라고 나옵니다.
php로 운영할땐 확장자명 없이 작동하게 해야한다고 해서 그렇게 설정했습니다.
아래는 message.php 파일입니다.
<?php
 
// 요청을 받아 저장
$data = json_decode(file_get_contents('php://input'), true);
 
// 받은 요청에서 content 항목 설정
$content = $data["content"];
 
 
 
// 'GP감꽃푸드코트' 버튼 처리
if( $content == "GP감꽃푸드코트" )
{
echo <<< EOD
    {
        "message": {
            "text": "아직 개발중이라 대답을 잘 못해도 이해해줘^^;"
        }
    }
EOD;
}
// '공학관 교직원식당' 버튼 처리
else if( $content == "공학관 교직원식당")
{
echo <<< EOD
    {
        "message": {
            "text": "이제 곧 정식 버전이 출시될거야. 조금만 기다려~~~"
        }
    }    
EOD;
}
// 'GP감꽃푸드코트' 버튼 처리
if( $content == "GP감꽃푸드코트" )
{
echo <<< EOD
    {
        "message": {
            "text": "아직 개발중이라 대답을 잘 못해도 이해해줘^^;"
        }
    }
EOD;
}
// '공학관 교직원식당' 버튼 처리
else if( $content == "공학관 교직원식당")
{
echo <<< EOD
    {
        "message": {
            "text": "이제 곧 정식 버전이 출시될거야. 조금만 기다려~~~"
        }
    }    
EOD;
}
// '공학관 학생식당' 버튼 처리
if( $content == "공학관 학생식당" )
{
echo <<< EOD
    {
        "message": {
            "text": "아직 개발중이라 대답을 잘 못해도 이해해줘^^;"
        }
    }
EOD;
}
// '복지관 교직원식당' 버튼 처리
else if( $content == "복지관 교직원식당")
{
echo <<< EOD
    {
        "message": {
            "text": "이제 곧 정식 버전이 출시될거야. 조금만 기다려~~~"
        }
    }    
EOD;
}
// '복지관 학생식당' 버튼 처리
if( $content == "복지관 학생식당" )
{
echo <<< EOD
    {
        "message": {
            "text": "아직 개발중이라 대답을 잘 못해도 이해해줘^^;"
        }
    }
EOD;
}
// '정보센터식당' 버튼 처리
else if( $content == "정보센터식당")
{
echo <<< EOD
    {
        "message": {
            "text": "이제 곧 정식 버전이 출시될거야. 조금만 기다려~~~"
        }
    }    
EOD;
}
// '안녕'이란 단어가 포함되었을때 처리
else if( strpos($content, "안녕") !== false )
{
echo <<< EOD
    {
        "message": {
            "text": "안녕~~ 반가워 ㅎㅎ"
        }
    }    
EOD;
}
// 그밖의 문장일때 
else
{
echo <<< EOD
    {
        "message": {
            "text": "나랑 놀자 ㅋㅋㅋ"
        }
    }    
EOD;
}
 
?>

http://localhost/message
이렇게 했을때
{ "message": { "text": "나랑 놀자 ㅋㅋㅋ" } }
라고 잘만 나오는데
 
왜 카톡에선 오류가 나는 걸까요?

**Comment by SerenityS** [comment]
API 주소 등록하실때 url.com/keyboard처럼 keyboard까지 등록했는지 확인해보세요

**Comment by pandagirin** [comment]
네..! php빼고 keyboard까지 등록되어있어요..! 등록까지는 잘 잘동하네요 흠..

**Comment by SerenityS** [comment]
keyboard 지우셔야해요

**Comment by pandagirin** [comment]
아아..!! 됐습니다!! 잘 작동하네요!! 정말 감사합니다 !! 복 많이 받으세요!!
