### ISSUE TITLE
카카톡 플러스친구의 특별기능 (카로셀 카드, CTA 버튼) 어떻게 사용 할수있나요?

### ISSUE THREAD

**Issue by 5amuraix** [plusfriend/auto_reply#518]
![screen1](https://user-images.githubusercontent.com/29794581/35671610-53fca1fc-077f-11e8-9ffb-9f9721fe01cb.png)

Fig. 1:  옆쪽 슬라이딩 카로셀 

![screen2](https://user-images.githubusercontent.com/29794581/35671615-56b29b7c-077f-11e8-8079-2496e17a7c30.png)

Fig. 2: CTA /inline 버튼

안녕하세요,

위의 스크린샷에서 빨간 동그라미 표시된 기능들 사용할 수 있습니까?  가능하면, auto_reply API으로 어떻게 사용하면 됩니까?

감사합니다.

**Comment by SerenityS** [comment]
아직 공개 API에선 사용 불가능한걸로 알고있습니다

**Comment by plusfriendteam** [comment]
안녕하세요. 
말씀하신 스펙은 현재 지원하고 있지 않지만 
추후 오픈될 플랫폼(http://bot-builder.kakao.com/)에서 
지원할 예정이니 참고해주시기 바랍니다. (오픈 시기는 미정)
