### ISSUE TITLE
사용자 메세지에 텍스트 버블 메세지 두 개를 연속으로 보내는 것 가능할까요?

### ISSUE THREAD

**Issue by entheos37** [plusfriend/auto_reply#527]
안녕하세요, 

카카오톡 자동응답 api에 챗봇 api를 연결해서 쓰고 있는데요, 

사용자 메세지에 답으로 텍스트버블 메세지 두 개를 연속으로 보내는 것 가능할까요?

output.text.length >= 2이면,

output.text[0] 이 첫번째 버블 메세지 바로 연속으로 그 아래에 output.text[1] 버블 메세지를 주고 싶었습니다.

가능한 방법이 있을까요?

**Comment by plusfriendteam** [comment]
안녕하세요. 
말씀하신 스펙은 현재 지원하고 있지 않지만 
추후 오픈될 플랫폼(http://bot-builder.kakao.com/)에서 
지원할 예정이니 참고해주시기 바랍니다. (오픈 시기는 미정)
