### ISSUE TITLE
message 에서 텍스트로 보낼 수 있는 문자..

### ISSUE THREAD

**Issue by pandagirin** [plusfriend/auto_reply#528]
안녕하세요! 
우분투 아파치 php mysql 을 이용해서 챗봇을 만들고 있습니다.
해당 버튼을 누르면 맞는 내용을 php로 mysql 에서 불러와 message text 로 보내는 흐름으로 만들었습니다. 거의 다 왔는데 어떤거는 정상으로 보내지는데 몇개는 보내지지 않더군요.
우선 문자 " 나 \ 는 안보내지고 mysql 에 눈으로 보이진 않지만 tab으로 띄워쓰기 된것과 줄바꿈 된것 (html 태그로 눈에 표시된게 아니라) 그것도 문자에 포함되어 있으면 전송이 안되더군요. 이런 문자들은 일일이 제외할 수 밖에 없는 건가요?

**Comment by humit0** [comment]
하드 코딩을 하지 마시고 아래처럼 이용하시면 됩니다.
```php
$msg = ''; // mysql에서 불러온 값
echo json_encode(array("message"=>array("text"=>$msg)));
```

**Comment by pandagirin** [comment]
그런방법이..감사합니다!! 아주 잘 됩니다 ^^ !!

**Comment by humit0** [comment]
잘 작동해서 다행이네요 ㅎㅎ
