### ISSUE TITLE
message 로 호출할때 어떤방식으로 호출이되나요?

### ISSUE THREAD

**Issue by hwansday** [plusfriend/auto_reply#53]
해당 주소로 json데이터를 날리면 405에러가 생기는데 

아래 형태로 호출하면 에러가 생기고
http://ip/message

아래 형태로 호출하면 에러는 생기지 않습니다.
http://ip/message/

옐로우아이디쪽에서 message를 호출할때 어떤방식으로 잡히는지 알고싶습니다.

**Comment by suya55** [comment]
message는 POST 방식으로 
설정 페이지에서 입력해주신 host 뒤에 message를 붙여서 호출하게 됩니다.

입력을 http://ip 또는 http://ip/로 입력해주셨으면
카카오 서버가 POST http://ip/message로 호출하게 됩니다.
