### ISSUE TITLE
카카오플러스친구 자동응답 API 반영 시 사전협의 진행 요청 건

### ISSUE THREAD

**Issue by hancsun** [plusfriend/auto_reply#530]
안녕하세요, LG CNS 한치선입니다.

카카오플러스친구를 통해 고객사들에게 자동응답API로 서비스중에 있습니다.
카카오에서 자동응답 API  서비스 반영 시 적용되는 사항에 대해 별도 고지가 없거나
임박해서 공지사항 내용 정도로 확인이 되고 있어 자동응답API를 활용한 서비스 대응에
어려움이 있습니다. 

카카오플러스친구 자동응답API 의 Feature 변경 또는 주요사항에 대한 변경 시 
안정적인 서비스를 위해 사전에 협의를 진행할 수 있도록 프로세스 수립 부탁드립니다.

LG CNS (한치선, 010-3937-8068)

감사합니다.

**Comment by plusfriendteam** [comment]
보내주신 의견 면밀히 검토하여 불편함이 없도록 하겠습니다. 
감사합니다.
