### ISSUE TITLE
keyboard에서 보이는 버튼

### ISSUE THREAD

**Issue by Juneyoung-Kang** [plusfriend/auto_reply#531]
최근에 아래와 같은 버튼이 플러스 친구 고객센터에서 서비스되는 것을 확인했습니다.

기존 버튼과는 다르게 PC 버전에서도 작동하고 많이 편리한 기능인것 같은데 레퍼런스 문서에 나와있지 않은 것 같네요...

이것은 어떻게 구현해야 할까요?

![img_3545](https://user-images.githubusercontent.com/30204441/36153499-cd937176-1111-11e8-8255-5e6e9aacbb50.PNG)

**Comment by plusfriendteam** [comment]
안녕하세요. 
말씀하신 스펙은 현재 지원하고 있지 않지만 
추후 오픈될 플랫폼(http://bot-builder.kakao.com/)에서 
지원할 예정이니 참고해주시기 바랍니다. (오픈 시기는 미정)
