### ISSUE TITLE
PHP에서 http(s)://:server_url/message로 POST 요청이 제대로 들어오지 않는 것 같습니다.

### ISSUE THREAD

**Issue by mjy9088** [plusfriend/auto_reply#532]
server_url을 (파일이름).php?로 끝나게 했습니다.

```
<?php

if($_SERVER['QUERY_STRING'] == '/keyboard')
{
    header('Content-Type: application/json; charset=utf-8');
    echo '{"type":"buttons","buttons":["버튼1"]}';
}
else if($_SERVER['QUERY_STRING'] == '/message')
{
    header('Content-Type: application/json; charset=utf-8');
    ob_start();
    var_dump($_REQUEST);
    $msg = ob_get_contents();
    ob_end_clean();
    echo '{"message":{"text":"'.str_replace("\n", "\\n", addslashes($msg)).'"}}';
}
else
{
    header('Content-Type: text/plain; charset=utf-8');
    var_dump($_REQUEST);
}

?>
```

아파치는 Apache/2.4.25 (Raspbian), PHP는 PHP Version 7.0.27-0+deb9u1을 사용중입니다.

`curl -XPOST 'http://(주소/파일명).php?/message' -d '{"user_key" : "enc", "type" : "text", "content" : "cont"}'`

이렇게 테스트하면

`{"message":{"text":"array(2) {\n  [\"/message\"]=>\n  string(0) \"\"\n  [\"{\n\"user_key\"_:_\"enc\",_\"type\"_:_\"text\",_\"content\"_:_\"cont\"}\"]=>\n  string(0) \"\"\n}\n"}}`

이렇게 응답합니다.

그러나 실제 자동응답 메시지의 내용은

```
array(1) {
  ["/message"]=>
  string(0) ""
}

```

이렇습니다.

어떻게 해결해야 할까요?

**Comment by Juneyoung-Kang** [comment]
모든 것에 앞서서 
```
curl -XPOST 'http://(server_url)/message' -d '{
  "user_key": "enc",
  "type": "text",
  "content": "cont"
}'
```
이렇게 해야 할 거 같습니다. 

루트 경로든 하위 경로든 어딘가에 `message.php` 파일이 위치해야 하고 `POST request`를 보낼때에는 `(url 경로)/message`라고 보내야 합니다.

그리고 `POST request` 보낸 것은 아래처럼 나오네요
```
{ 
   	"message":{ 
      			"text":"array(2) {
			 		["/message"]=>
 						string(0) ""
 					["{"user_key" : "enc", "type" : "text", "content" : "cont"}"]=>
						string(0) ""
			 }"
   	}
}
```
제대로 된 json인지 확인해보시면 될 거 같습니다.

**Comment by mjy9088** [comment]
응답은 제대로 됐는데 복사-붙여넣기 하는 과정에서 문제가 생겼던 것을 확인했습니다.

` `

서버 주소에 `?`가 들어가지 않게 `message.php`파일로 바꿨습니다.

` curl -XPOST '(앱 URL)/message' -d '{"user_key":"enc","type":"text","content":"cont"}'`

이렇게 테스트 해 본 결과

`{"message":{"text":"array(1) {\n  [\"{\"user_key\":\"enc\",\"type\":\"text\",\"content\":\"cont\"}\"]=>\n  string(0) \"\"\n}\n"}}`

이렇게 잘 나옵니다.

그러나 스마트채팅 설정에서 앱 URL을 바꿨음에도 불구하고 여전히
```
array(0) {
}

```
자동응답 메시지는 계속 이렇게만 오고 있습니다.

80번이 아닌 포트를 사용하고 있는데 이것과 유관한 문제일까요?

포트 번호 말고는 특별히 문제 될 게 있을지 잘 모르겠습니다...

**Comment by Juneyoung-Kang** [comment]
포트와 관련된 문제는 아닌 것 같습니다.

POST request를 날린 결과를 보면 아래와 같은데
```
{
"message":{
	"text":"array(1)" {
		 ["{"user_key":"enc","type":"text","content":"cont"}"]=>
				string(0) ""
		}"
	}
}
```
자동응답 메세지를 확인하기 앞서  message.php로 `POST request`날리실 때 부터 아래와 같은 결과가 나와야 합니다.
```
{
"message":{
	"text":"blah blah blah~"
	}
}
```
지금 위 두개를 비교해보면 위에 나온 출력 값은 `text` key의 value 값으로 문자열이 아닌 배열을 가지고 있습니다. 일단 이 부분이 문제가 되는 부분 같습니다. 그리고 `{"user_key":"enc","type":"text","content":"cont"}`이 부분은 parameter 라는 것을 참고하시면 될 거 같습니다.

-----

음... 제 설명이 좀 많이 부족한 거 같네요ㅠㅠ 혹시라도 개인적으로 도움 필요하시다면 카카오톡 (ID rebuskorea)이나 깃허브 프로필에 나와 있는 이메일로 알려주세요. 바로 피드백 드릴 수 있을 것 같습니다.

**Comment by mjy9088** [comment]
`curl -XPOST '(앱 URL)/message' -d '{"user_key":"enc","type":"text","content":"cont"}'`

이렇게 테스트했을 때의 응답

`{"message":{"text":"array(1) {\n [\"{\"user_key\":\"enc\",\"type\":\"text\",\"content\":\"cont\"}\"]=>\n string(0) \"\"\n}\n"}}`

이 text에 다른 게 들어가 있는 게 아니라

```
{
"message":{
	"text":"blah blah blah~"
	}
}
```

여기에서 `"blah blah blah~"`만

```
array(1) {
 ["{"user_key":"enc","type":"text","content":"cont"}"]=>
 string(0) ""
}

```

이런 내용의 텍스트로 바뀐 정상적인 응답입니다.

POST로 무언가를 보내면 array(n) { ... } 안에 무언가가 하나라도 있어야 하는데

실제 자동응답 메시지에서는 저 안에 아무것도 없어서 이렇게 글 남겼습니다..

감사합니다!

**Comment by humit0** [comment]
```php
<?php
header('Content-Type: application/json; charset=utf-8');
ob_start();
var_dump(json_decode(file_get_contents('php://input'), true));
$msg = ob_get_contents();
ob_end_clean();
echo '{"message":{"text":"'.str_replace("\n","\\n",addslashes($msg)).'"}}';
?>
```
로 바꿔서 시도해보시겠어요??

**Comment by mjy9088** [comment]
`file_get_contents('php://input')`으로 바꿔서 해결했습니다.

그냥 제가 잘못 쓰고 있던 거였군요...

감사합니다!!!
