### ISSUE TITLE
메시지 자동응답입니다.

### ISSUE THREAD

**Issue by dsluritas** [plusfriend/auto_reply#533]
![image](https://user-images.githubusercontent.com/27723289/36463118-0fef3baa-170b-11e8-8b24-d649719c4207.png)
위와 같이 버튼을 구성하고 싶은데 어떻게해야하나요?
API에서 없는것 같은데 다른데서는 많이 하고 있더라고요.

**Comment by plusfriendteam** [comment]
안녕하세요. 
말씀하신 메시지는 카카오톡 비즈메시지(https://bizmessage.kakao.com/) 
상품을 이용하시면 사용이 가능합니다. 

또는 추후 오픈될 플랫폼(http://bot-builder.kakao.com/)에서 
지원할 예정이니 참고해주시기 바랍니다. (오픈 시기는 미정)
