### ISSUE TITLE
말풍선 안에 버튼

### ISSUE THREAD

**Issue by joepineapplesoft** [plusfriend/auto_reply#534]
다른 플친 보니 말풍선 안에 버튼이 여러개 들어가서 보기 편하게 되어 있던데 API 명세서를 보니깐 구현할수 없는 것 같네요.
자동응답 API에서 `말풍선안에 들어가는 텍스트에 버튼`을 넣을 수 있는 방법을 알려주세요.
감사합니다.

**Comment by plusfriendteam** [comment]
안녕하세요.
현재 말씀하신 스펙은 지원하지 않습니다만
추후 개편 시 반영될 수 있도록 검토해보겠습니다.
