### ISSUE TITLE
카카오톡프렌즈 생성시 8080포트로 연결해 주려하는데 ERROR 해결 부탁드립니다.

### ISSUE THREAD

**Issue by foonia** [plusfriend/auto_reply#539]
CURL로 REQUEST요청시 잘 받아 옵니다. 여기까진 문제가 없는데 
앱 등록하기에서 url check 할 때, keyboard failed라고 뜨네요.. 80포트로 하면 잘 되는 상황이구요.
80은 보안상 쓰지 않는것이 좋다하여 다른포트로 바꾸고 싶은데 해결 부탁드립니다!

**Comment by plusfriendteam** [comment]
안녕하세요.
개발하시는 환경의 방화벽 설정을 확인해주세요.

https://github.com/plusfriend/auto_reply 페이지에서 
'7.1. Proxy Server information' 을 참고하시면 됩니다.
