### ISSUE TITLE
#42 이슈 관련추가 사항 입니다.

### ISSUE THREAD

**Issue by mcvzone** [plusfriend/auto_reply#54]
안녕하세요.

#42 번 이슈 관련하여, 추가 사항이 있습니다.

| 1. 친구 차단 상태에서 채팅방에 들어 오면, 대화가 가능 합니다.
이 상태가 정상인 것인지요? 친구가 아니면, 대화가 불가능 해야 정상 아닐런지요.
(일반 친구인 경우엔, 채팅 입력창이 없는 상태가 되지만, 플러스 친구는 채팅 입력창이 유지됩니다.)

| 2. 카카오 버전이 최신이 아닌경우, API2.0에서 채팅 입력창이 생성되지 않습니다.
해당 부분에 대하여, 각 파트너 사들은 해당 문제에 대해 컨트롤 할수 있는 방법이 없음으로, 고객에게 안내 메시지(예, 카카오톡을 UPDATE 받으세요.)를 보낼 수도 없는 상태가 됩니다.

관련 화면 첨부 하였습니다.

1. 이슈화면
![default](https://cloud.githubusercontent.com/assets/13563636/16643956/1a02ca34-4454-11e6-8270-4f71196c99e6.jpg)

2. 카카오톡 버전
![default](https://cloud.githubusercontent.com/assets/13563636/16643963/23ad3e48-4454-11e6-8f62-8de3673b9014.jpg)

**Comment by plusfriendteam** [comment]
클라이언트가 개편되면서 부터 봇기능이 사용가능해진것이기 때문에 5.4.0 이전 버전 유저는 2.0 api를 사용한 봇을 사용못하게 되었습니다.
그리고 친구 차단 상태에서 봇 이용이 가능한건 의도된 정상작동입니다.

감사합니다.

**Comment by mcvzone** [comment]
그렇다면 업그레이드를 하라는 멘트를 보내줘야 하는데
Api2.0 에서는 고객의 카카오톡 앱 버전을 알수 없는 상태에서 어떻게 가이드를 줄수 있을까요?
