### ISSUE TITLE
Keyboard API에서 유저를 식별할 수 있으면 좋겠습니다

### ISSUE THREAD

**Issue by hallazzang** [plusfriend/auto_reply#541]
현재 API 개요에는 Keyboard API에 대해 다음과 같이 명시되어 있습니다:

> 유저가 자동응답으로 메시지를 주고 받았을 경우는 마지막 메시지에 담겨있던 자동응답 명령어 목록이 표시됩니다. 다만 메시지에 저장된 자동응답 명령어는 10분간 유효합니다. 10분이 지난 다음에는 다시 keyboard api를 호출하여 자동응답 목록을 초기화하게 됩니다.

이 방식은 다음과 같은 시나리오에서 문제를 일으킵니다:

1. 유저가 대화방에 처음 들어왔을 때(Keyboard API 호출) `First`, `Second`, `Third` 버튼이 표시됩니다.
2. 추가 선택지가 있는 `First` 버튼을 클릭하면 `First-A`, `First-B`, `First-C`, `Cancel` 버튼이 표시됩니다.
3. 유저가 버튼을 클릭하지 않은 채로 대화방을 나갑니다(채팅방 나가기를 해서 완전히 대화방을 삭제하는 것은 아닙니다).
4. 10~20분 후 대화방에 들어오면 다시 Keyboard API가 호출돼 `First`, `Second`, `Third` 버튼이 표시되지만 앱 입장에서 유저는 아직 `First` 버튼을 눌렀을 때의 컨텍스트(2의 상황)에 있습니다. 따라서 맞지 않는 응답을 반환합니다.

만약 Keyboard API에서 유저를 식별할 수 있는 방법이 있다면(Query Parameters를 이용하거나 POST 방식으로의 변경) Keyboard API가 호출될 때 앱에서 해당 유저에 대한 컨텍스트를 초기화할 수 있을 겁니다.

**Comment by SerenityS** [comment]
저같은 경우엔 유저가 버튼을 선택하면 DB에 어떤걸 선택했는지 매번 저장해두고 키보드를 띄워주고 있습니다.. 이게 효율적인 방식인진 잘 모르겠지만 이것 말고 다른 방법이 떠오르진 않네요.

**Comment by hallazzang** [comment]
@SerenityS 저도 그렇게 만들어뒀는데 키보드 API를 호출하는 시점에서 어떤 유저인지를 모르니 이전의 선택을 초기화할지 유지할지 정하기가 힘드네요. 일단은 유저별로 마지막으로 메시지를 보낸 시간과 현재 시간의 차이를 구해 10분 이상이면 초기화 된것으로 간주하게끔 만들어두긴 했습니다

**Comment by SerenityS** [comment]
의미를 잘못 이해하고 있었네요 ㅠㅠ

확실히 10분뒤 초기화면 Initial keyboard를 GET하기만 하는 상황에서는 크게 해결책이 보이질 않는군요..

**Comment by plusfriendteam** [comment]
안녕하세요. 
말씀하신 스펙은 현재 지원하고 있지 않지만 
추후 개편 시 지원이 가능한 부분일지 내부 검토해보도록 하겠습니다.
