### ISSUE TITLE
keyboard Fail 415 문의 드립니다

### ISSUE THREAD

**Issue by WolfGarden** [plusfriend/auto_reply#543]
API로 챗봇 개발하고있는 학생입니다.

geosungmeal.dothome.co.kr/keyboard 로 들어가는 것도 정상 작동 되고
postman 으로도 잘 나오는데
API 테스트를 하면 keyboard Fail 415 wrong keyboard initialization 이라고 나오네요.

API 테스트에서
http://geosungmeal.dothome.co.kr/ 도 해보고
http://geosungmeal.dothome.co.kr/keyboard 도 해봤고
http에 s도 붙여서 해봤는데 다 안됩니다

htaccess에 Options +Multiviews 도 써놨는데
안되네요

답변 부탁드립니다

**Comment by plusfriendteam** [comment]
안녕하세요.

개발하시는 환경의 방화벽을 확인해보시겠습니까?

https://github.com/plusfriend/auto_reply 페이지의 
"7.1. Proxy Server information" 부분을 참고해주세요.
