### ISSUE TITLE
message 에러 좀 확인해주세요.

### ISSUE THREAD

**Issue by billionpjh** [plusfriend/auto_reply#544]
스마트 채팅 > API형

앱 URL 에 주소를 넣고 체크하면 아래와 같이 성광 확인을 하고 진행하였습니다.

> Required*
> keyboard OK
> {"type":"text"}

그런데 message 부분을 진행하면 아래와같이 오류가 납니다.
내용이 리턴된다는것은 저희 서버랑 연결되었으며 신호를 정상적으로 주고받는것으로 보이는데
response되는 json 구문이 잘못된건가요?

> [치매친구들] [오후 2:37] [관리자에게만 발송되는 메시지입니다] 사용자 봇서버에 에러가 감지 되었습니다. 
> 내용:[잘못된 응답입니다. response json parsing error. user_key : xxxxxxxxxxxxx, You'r server response : {"d":"{\"message\":{\"text\":\"메세지 연결 성공!!\"}}"}]

> [치매친구들] [오후 2:37] 해당 프로필의 자동응답 시스템이 응답을 하지 않습니다. 문제가 보고되어 처리 예정입니다. 다음에 다시 시도해주세요.

답 부탁드립니다~

감사합니다.

**Comment by SerenityS** [comment]
API를 참고해보시면 초기 keyboard 호출시엔 type을 button으로 두고 반환하게 되어있습니다. 근데 글쓴이분의 경우엔 텍스트로 반환되네요.

**Comment by billionpjh** [comment]
api에서 Keyboard 호출시에
1. 직접입력
2. 버튼입력
두개가 있는데 저는 1번을 선택하여서 텍스트로 반환되는것 같습니다.

**Comment by SerenityS** [comment]
초기 keyborad를 text로 해본적이 없어서 몰랐었네요;;
저 에러는 대게 URL에서 잘못된 경우였는데 혹시 URL 등록하실때 chatbot.com/keyboard 처럼 keyboard까지 입력하신건 아닌지 확인해보세요.

**Comment by billionpjh** [comment]
음.. 주소에서 keyboard 나 message같은 부분은 제거하고 url을 입력했는데..

keyboard 리턴값은 잘 인식하는데 이상하게 message 리턴에서 인식을 못하네요..

심지어 api에서 예시로 보여주는 return json을 복사 붙여서 리턴해도 위와같은 에러

" 해당 프로필의 자동응답 시스템이 응답을 하지 않습니다. 문제가 보고되어 처리 예정입니다. 다음에 다시 시도해주세요. "

가 뜨네요ㅠ

**Comment by SerenityS** [comment]
여러가지 원인이 있더라구요.. 소스를 안봐서 잘은 모르겠네용

**Comment by plusfriendteam** [comment]
안녕하세요. 
/message 호출 시 반환되는 response 를 다시한번 확인해보시길 바랍니다.
response json parsing 하는 과정에서 오류가 발생하고 있는듯 하네요.
