### ISSUE TITLE
해당 프로필의 자동응답 시스템이 응답을 하지 않습니다... 문구가 발생 합니다.

### ISSUE THREAD

**Issue by pbj0812** [plusfriend/auto_reply#545]
django로 카톡 플러스 친구를 만들고 있는데 만들고 나서 버튼을 누르면 제목과 같은 문구가 발생을 하게 됩니다. 터미널을 보면 

[13/Mar/2018 01:29:30] "POST /message HTTP/1.1" 404 2075
Not Found: /message

이렇게 뜨는데 어디를 수정해야 되는지 알 수 있을까요??
메세지 찾을수 없다고 나오는데 메세지 함수는 구현이 되었고, 코드를 돌리면 에러는 나지 않습니다.
버튼을 클릭하면 저런 오류가 발생을 합니다.
참고로 방화벽은 다 풀고 진행을 하였습니다.

**Comment by billionpjh** [comment]
message 페이지를 찾을수 없다는것 같은데 url을 확인해보세요~

**Comment by plusfriendteam** [comment]
안녕하세요.
윗분 말씀대로,
/message 호출 시 페이지를 못찾는다는 내용이므로 url을 다시한번 확인해보시기바랍니다.
