### ISSUE TITLE
메세지 버튼 관련 문의

### ISSUE THREAD

**Issue by zavp001** [plusfriend/auto_reply#547]
![k001](https://user-images.githubusercontent.com/34624275/37378217-9e7d7334-2771-11e8-924c-07281c34bd84.JPG)

키보드버튼, 링크버튼 말고 위의 사진속의 버튼은 api로 제공 하고 있지 않나요?..

**Comment by plusfriendteam** [comment]
안녕하세요. 
말씀하신 스펙은 현재 지원하고 있지 않지만 
추후 개편 시 지원이 가능한 부분일지 내부 검토해보도록 하겠습니다.
