### ISSUE TITLE
js 카카오봇

### ISSUE THREAD

**Issue by Sunghyuns** [plusfriend/auto_reply#548]
js로 개발한 카카오봇은 웹 서버가 있어야지 플러스친구에 올릴수 있나요?

**Comment by halrequin** [comment]
네 호스팅된 주소도 있어야 합니다 ~_~

**Comment by plusfriendteam** [comment]
안녕하세요.
restful api를 통하여 플러스친구 봇서버와 통신할 수 있는 서버를 구축하셔야 합니다.
