### ISSUE TITLE
message 호출 방식물어봤었는데

### ISSUE THREAD

**Issue by hwansday** [plusfriend/auto_reply#55]
iis 환경에서는 어떤 설정을해줘야하나요??
iis 환경에서는 http://ip/message 이상태로 호출이 안되는데요
http://ip/message/ 이상태로 호출을 해야 인식을하는데

**Comment by plusfriendteam** [comment]
개별 클라이언트에서 진행한 서버설정 내역은 플러스친구/옐로아이디의 자동응답 서버에서 확인할 수 없습니다. 
보다 상세히 이슈상황을 기술해주시거나, 자동응답 서버에 요청을 보냈을 때의 에러상황을 기술해주셔야 정확한 상황/이슈 파악이 가능합니다. 

단, 자동응답 서버에 직접 관련하지 않은 이슈의 경우 구조적으로 대응이 어려울 수 있음은 양해 부탁드리겠습니다.

**Comment by hwansday** [comment]
curl -XPOST 'https://your_server_url/message_**/**_' -d '{
  "user_key": "encryptedUserKey",
  "type": "photo",
  "content": "http://photo_url/number.jpg"
}'
밑줄쳐진 저 부분의 슬러시를 넣냐 마느냐에따라서 응답여부가 달라지는데 iis서버설정에서 
" / "  가없는상황에서는 디렉토리 주소로 인식하지 않는걸로아는데 
java환경에서는 맵핑을통해서 넘어간다고하지만 iis설정에는 안되는걸로알아서요~ 
저형태로 동작하지않는 회사는 작업을 못하는건가요?

**Comment by suya55** [comment]
root 디렉토리 밑에 message 라는 파일을 하나 만드시고
그 파일 내용을 json으로 만드신다음
응답 헤더에 application/json으로 세팅을 하신다면 그리고 그 json data가 양식에 맞다면 data 내용대로 사용자에게 응답이 가는것을 보실 수 있을겁니다.

다만. 그게 무슨 소용이 있는지 모르겠습니다. 무슨 내용이든 유저에게는 하나의 응답만 가능하겠지요.
해당 api는 static 서버를 대상으로 만들어진것이 아닙니다.
그리고 일반적인 회사에서 static hompage가 아닌 web application에서는 iis 하나만 가지고 구성하지 않습니다.

**Comment by hwansday** [comment]
static 환경이 아닙니다 ㄷㄷㄷㄷ iis + asp환경입니다. 
java 나 .net환경이 아니라서 해당 구조가 가능하지 않아서 질문하는거입니다.

**Comment by jjuakim** [comment]
@hwansday  
제가 iis/asp  환경은 잘 모르지만 아래 포스트가 도움이 되었으면 좋겠습니다. 
http://ruslany.net/2009/04/10-url-rewriting-tips-and-tricks/
