### ISSUE TITLE
예상하지 못한 오류가 발생했습니다.

### ISSUE THREAD

**Issue by khh9477** [plusfriend/auto_reply#552]
다른 사용자분들은 keyboard Fail 415가 많이 보이는데 제 사례는 없어서 한번 올려보네요...
구글링해서 노드로 서버도 구축하고 자바스크립트도 작성 완료했는데

Required*
Keyboard Fail
이라는 문구만 나오네요...

혹시 어떤 문제가 있는지 여쭤보고 싶습니다ㅠㅠ

----------------------------------------------------

//express 모듈 불러온 후 express 변수에 저장
var express = require('express');

//http 모듈 불러온 후 http 변수에 저장
var http = require('http');

//express 객체를 app 변수에 저장
var app = express();

//http://서버주소/keyboard
app.get('/keyboard', function(req, res) {
    //전달할 데이터
    var data = {
        'type': 'buttons',
        'buttons': ['버튼1', '버튼2', '버튼3']
    };
    
    //JSON 형식으로 응답
    res.json(data);
});

//2121포트로 서버 실행
http.createServer(app).listen(2121, function() {
    console.log('서버 실행 중..')
});

---------------------------------------------

URL :
http://175.194.76.216:2121

+
localhost:2121/keyboard 테스트는 문제 없습니다

**Comment by humit0** [comment]
해당 포트가 방화벽에 의해서 막혀있는 것으로 보입니다.

**Comment by plusfriendteam** [comment]
안녕하세요.
외부에서 개발하시는 서버로 접근이 안되는 듯합니다.
ACL 설정이 되어 있는지 확인해보시길 바랍니다.
