### ISSUE TITLE
PC 카톡에서 스마트채팅을 할 때 buttons가 보이질 않습니다.

### ISSUE THREAD

**Issue by Yunster** [plusfriend/auto_reply#553]
스마트폰 카톡으로 하면 buttons가 잘 보이고, 해당 버튼을 클릭하기 전에는 채팅도 안되어서 잘 작동됩니다.

그런데 PC 카톡으로 하면 buttons가 나와야 되는 상황인데도 나오지를 않고 채팅도 칠 수 있어서 일관성도 없고 여러 문제가 발생합니다.

확인하시고 수정 부탁드립니다.

**Comment by SerenityS** [comment]
PC버전은 지원하지 않습니다

**Comment by plusfriendteam** [comment]
안녕하세요. 사용하고 계신 PC버전 카카오톡이 최신 버전인지 확인해주세요. 
(Window PC : 2.6.5v 이상, MAC OS : 2.4.4v 이상)
