### ISSUE TITLE
구글 Short URL 이 막힌듯 합니다

### ISSUE THREAD

**Issue by EugeneJang** [plusfriend/auto_reply#554]
금일 어느새부턴가 구글 Short URL이 작동을 안해요

오류인가요? 업데이트해야하나요?

**Comment by plusfriendteam** [comment]
안녕하세요.
해당 일시에 일시적으로 이슈가 있었습니다. 
지금도 동일한 상황인지 확인부탁드립니다.

**Comment by EugeneJang** [comment]
안녕하세요. 답변 감사합니다.
너무 설명없이 적어서 양해부탁드립니다.

저희가 사용하는 방식이 구글 Short URL로 플러스친구 채팅방으로 바로 유입할수 있게 만들어서 사용하고있습니다.

원인은 카카오톡 플러스친구 바로가기 링크로 주입시 안드로이드는 정상 , 아이폰은 오류가 나는 현상이 있습니다.

많은 고객사에서 에러가 발생하고 있는 상황인지라 빠른 확인 부탁드립니다.

감사합니다.
