### ISSUE TITLE
플러스친구 URL 접근시 문구 차단 문의

### ISSUE THREAD

**Issue by hancsun** [plusfriend/auto_reply#555]
안녕하세요, LG CNS 한치선입니다.

기존 서비스시에 플러스친구 URL 뒤에 메뉴명이나 특정문구( 예:상품주문하기)를 넘겨서 카카오플러스친구 진입 시 해당 문구로 메세지 처리를 하고 있었는데 금일 오후부터 작동이 되지 않고 하단과 같은 문구가 발생되고 있습니다. (안드로이드는 정상 작동되나 아이폰에서 이슈발생됨)
해당 이슈 건 빠른 확인 부탁드립니다.

-> 관리자가 채팅을 OFF한 상태입니다. 우측 상단의 홈 아이콘을 클릭해 플러스친구 홈을 방문해 보세요. 

* URL 형태 -> http://plus.kakao.com/talk/bot/@검색용아이디명/상품주문하기

**Comment by plusfriendteam** [comment]
안녕하세요. 
시스템 작업으로 인해 잠시 문제가 발생했던 것으로 보입니다. 
현재는 정상 작동되니 확인해보시기 바랍니다.
