### ISSUE TITLE
채팅방 관련 버그 입니다.

### ISSUE THREAD

**Issue by mcvzone** [plusfriend/auto_reply#56]
안녕하세요.

친구톡 채팅방에 입장하여, 이미지를 첨부 하기 위해, + 버튼을 누르고, 다시 x 버튼을 누르면, 키보드가 생성 되지 않습니다.
해당 문제는 안드로이드 계열에서만 발생하며, 아이폰에서는 정상 작동 됩니다.
그리고 테스트 된 폰의 카카오톡 버전은 최신 입니다.

관련 이미지 첨부 합니다.

1. "+" 버튼을 누른 모습 입니다.

2. "x" 버튼을 누른 모습 입니다. (+버튼을 누르고 아무것도 전송 하지 않은 채 바로 x 버튼을 누른 상태 입니다.)

그리고 API2.0 을 이용하여, 자동응답형 API 서비스를 개시 하였습니다.
그런데 아래와 같은 메시지가 수시로 오고 있습니다.
저희 측 서버 로그에는 해당 시간대에 에러관련 된 로그가 남지 않았습니다.

확인 부탁 드립니다.

2016.07.11 추가 사항으로, 해당 글에 첨부되었던 이미지 파일은 당사 내부적으로 문제가 될 수도 있어 삭제 하였습니다.

관련 버그 내용은 충분히 전달 되었으리라 생각 되지만, 혹여 필요 하시면 댓글 남겨 주시기 바랍니다.

감사합니다.

**Comment by suya55** [comment]
버그제보 감사합니다. 확인해보겠습니다.

**Comment by plusfriendteam** [comment]
버그제보 감사합니다. 확인해보겠습니다.

**Comment by plusfriendteam** [comment]
친구톡 사용시 키보드 사라짐 문제는 확인중에 있습니다.

가끔 악사측 서버에서 

`[warn] 2016-07-08 15:23:10.999 : {"messages":{"message":"Server error"}`

이런 메시지를 카카오서버가 response로 받고있습니다.
저 메시지를 받을 때 마다 관리자에게 에러 노티 메시지가 발송됩니다.
유저로부터 어떤 메시지가 인입되었을때 해당 에러가 발생하는지를 로깅되지 않아서 
어떤 메시지 유입으로 발생하는 에러인지 로깅하는 코드를 보완해두었습니다. 다시 발생하면 알려드리겠습니다.

**Comment by mcvzone** [comment]
감사합니다 해당 이슈에 대하여 저희쪽에서 확인 해보면 될것 같습니다

**Comment by plusfriendteam** [comment]
@mcvzone 에러로그를 다시 확인했는데요. 메일주소 알려주시면 유저가 보낸 원본 로그랑 같이 보내드리겠습니다.

**Comment by mcvzone** [comment]
감사합니다.

mcvzone@naver.com << 보안상 회사 메일로는 첨부파일을 받을 수 없어서, 개인 메일 알려 드립니다.

입니다.

**Comment by mcvzone** [comment]
한가지 추가 질문이 있습니다.
관리자에게 노티 되는 메시지 내용에, 해당 문제를 유발시킨 user-key 를 보내 주실 수 있으신가요?

**Comment by plusfriendteam** [comment]
@mcvzone 기술적 검토해보겠습니다.

**Comment by plusfriendteam** [comment]
@mcvzone 요청하신데로 관리자 톡으로 user_key를 포함하여 메시지를 보내도록 적용해드렸습니다.

**Comment by mcvzone** [comment]
감사드립니다^^

**Comment by plusfriendteam** [comment]
위 이슈는 수정되어 최신 톡버전에 반영 되었습니다.
