### ISSUE TITLE
플러스친구 주소 진입 시  @검색용아이디명 뒤의 문구 정상작동 안함 (아이폰)

### ISSUE THREAD

**Issue by hancsun** [plusfriend/auto_reply#560]
안녕하세요, LG CNS 한치선입니다.

Github 답변에 시스템 작업 후 정상이라고 하였으나 해당 이슈 여전히 아이폰에서 발생되고 있습니다.
빠른 재확인 및 조치 부탁드립니다.

기존 서비스시에 플러스친구 URL 뒤에 메뉴명이나 특정문구( 예:상품주문하기)를 넘겨서 카카오플러스친구 진입 시 해당 문구로 메세지 처리를 하고 있었는데 3/20 오후 4시 이후부터 작동이 되지 않고(추정) 
하단과 같은 문구가 발생되고 있습니다. (안드로이드는 정상 작동되나 아이폰에서 이슈발생됨)
해당 이슈 건 빠른 확인 부탁드립니다.

-> 관리자가 채팅을 OFF한 상태입니다. 우측 상단의 홈 아이콘을 클릭해 플러스친구 홈을 방문해 보세요.

URL 형태의 링크로 플러스친구 진입 
 -> http://plus.kakao.com/talk/bot/@검색용아이디명/상품주문하기

<현상>
1) 위의 URL로 링크로 진입 시 플러스친구 채팅장 진입
2) 상품주문하기가  문구는 채팅창에 노출되나 하단 문구(관리자가 채팅을~)가 노출되면서 
   자동응답API에  해당문구(상품주문하기)가 들어오지 않음
    (관리자가 채팅을 OFF한 상태입니다. 우측 상단의 홈 아이콘을 클릭해 플러스친구 홈을 방문해 보세요.)

**Comment by plusfriendteam** [comment]
안녕하세요.
일시적인 장애로 인하여 해당 일시에 위와 같은 현상이 발생했었습니다.
현재는 수정이 완료되었습니다.

불편을 드려 죄송합니다.
감사합니다.
