### ISSUE TITLE
IOS 대화방 바로 진입시 문제 발생 문의

### ISSUE THREAD

**Issue by EugeneJang** [plusfriend/auto_reply#561]
안녕하세요 
플러스친구 대화방에 바로 진입하기 하여, 특정 메세지를 던져주기 위해 플러스친구 URL 뒤에 메뉴명이나 특정문구( 예:메뉴)를 넘겨서 카카오플러스친구 진입 시 해당 문구로 메세지 처리를 하고 있는데요, 
현재 작동이 되지 않고(대화방 진입후 요청한 문구(메뉴)가 출력 되지 않음) 
하단과 같은 문구가 발생되고 있습니다. (안드로이드는 정상 작동되나 아이폰에서 이슈발생됨)

아래와 같은 상황이 발생이 되는 케이스는 

친구공유하기 링크를 만들었을 경우
•안드로이드 폰 : 정상적으로 해당 문구(메뉴) 뿌려줌
◦아이폰 : 해당 문구(메뉴) 뿌려지지 않고, 아래와 같은 메세지 출력

아래 URL을 SMS나, 모바일 웹페이지의 버튼에 링크를 만들어 두고 진입 시도 할 경우
•안드로이드 폰 : 정상적으로 해당 문구(메뉴) 뿌려줌
•아이폰 : 해당 문구(메뉴) 뿌려지지 않고, 아래와 같은 메세지 출력

아래 URL 형태로 던지게 되면, 아이폰 에서는 1대1 채팅으로 인식을 하는것 같습니다.
(보통 플러스 친구는 특별히 상담톡을 쓰지 않는 이상 1:1 플러스 친구 관리자 화면에서 1;1채팅을 ON을 해두지 않는 걸로 알고 있습니다.)

아래와 같은 URL 형태로 호출을 하게 되면, 왜 아래와 같은 메세지가 나올 까요?
관련하여 확인 부탁드립니다.
감사합니다.

-> 관리자가 채팅을 OFF한 상태입니다. 우측 상단의 홈 아이콘을 클릭해 플러스친구 홈을 방문해 보세요.
•URL 형태 -> http://plus.kakao.com/talk/bot/@검색용아이디명/메뉴

**Comment by plusfriendteam** [comment]
안녕하세요. 시스템 작업으로 인해 해당 URL 호출시 잠시 문제가 있었던 것으로 보입니다. 
혹시 지금도 해당 현상 발생하는지 확인해주시기 바랍니다.
