### ISSUE TITLE
photo object에서 이미지 url 관련 문의

### ISSUE THREAD

**Issue by zavp001** [plusfriend/auto_reply#563]
말풍선 메세지 안에 사진을 넣을려고 하는데요
message_button에 이미지 url을 넣으면 잘나오는데요
photo에 이미지 url을 넣으면 안나옵니다..

그리고 모바일버전에서는 안나오는데 pc버전에는 사진이 나옵니다

이미지 url: 
https://hubibotproject.ml/images/66242.jpg

api 가이드에 나온 아래정보 범위에 있는 이미지 인데도 나오지가 않습니다.
이미지 권장 사이즈 : 720 x 630px
지원 파일형식 및 권장 용량 : jpg, png /500KB

해결방법 알려주세요..

**Comment by plusfriendteam** [comment]
안녕하세요.
테스트 해보니 지금은 잘 되는 걸로 보이는데요, 혹시 문제가 지속되거나 다른 문제가 있으시면
다시 문의주셨으면 합니다. 감사합니다.

**Comment by zavp001** [comment]
다시 확인해 봤는데 모바일에서 안나옵니다. 
https://hubibotproject.ml/images/66242.jpg 
위의 이미지링크로 테스트 해봐 주시고 답변 부탁드리겠습니다.
pc 에서는 잘나오는데 모바일에서는 여전히 나오지 않습니다.
모바일에서는 엑박으로 나옵니다.

**Comment by plusfriendteam** [comment]
다시 테스트 해보려고 하고 있습니다만, 
'제1여객터미널'이라고 입력하면 해당 이미지가 보였던 것 같은데 지금은 
'제1여객터미널에서,탑승동에서,제2여객터미널에서 중에서 출발하시는 곳을 선택해주세요' 라고 응답이 오고
해당 이미지가 보이지 않네요.
해당 이미지가 나와야하는 키워드를 알려주셨으면 합니다.

**Comment by zavp001** [comment]
010-4304-2034 연락부탁드리겠습니다.

**Comment by zavp001** [comment]
plusfriend_api@kakaocorp.com 으로 메일을 보냈는데 반송됩니다...

**Comment by plusfriendteam** [comment]
네. 반송된 이유는 모르겠지만, 메일은 확인했습니다. 
곧 답신 드리도록 하겠습니다.

**Comment by zavp001** [comment]
감사합니다.
