### ISSUE TITLE
아이폰8, 아이폰X 기종 플러스친구주소 진입 시 대메뉴 갱신 안되는 현상

### ISSUE THREAD

**Issue by hancsun** [plusfriend/auto_reply#564]
안녕하세요, LG CNS 한치선입니다.

아이폰8, 아이폰X 기종에서 하기 SMS문자로 발송된 URL 로 접근 시 상품주문하기 메세지는 
자동응답API로 전송되고 있습니다.  (기존 이슈는 해결됨)
그러나 상품주문하기 메세지에 따른 키보드 버튼명 변경을 진행하였으나 
키보드버튼명이 갱신되지 않고 이전 버튼명으로 남아 있는 현상이 있습니다. 
(타 아이폰, 안드로이드는 모두 정상작동됨)
또한 입력상태인 경우에도 버튼이 나와야 하는데 입력상태로 남아있습니다.

확인 부탁드립니다.

*아래 형태의 링크로 플러스친구 진입
     http://plus.kakao.com/talk/bot/@검색용아이디명/상품주문하기

**Comment by plusfriendteam** [comment]
안녕하세요. 제보주신 문제는 카카오톡 앱이 백그라운드에 있고 
해당 채팅방에 머물러 있는 경우에만 발생하는 것으로 확인되었습니다. 

일반 사용자에게 재현될 가능성은 낮은 문제라 다음 업데이트에 수정 반영할 예정이니 
불편하시더라도 깊은 양해 부탁드리겠습니다. 감사합니다.
