### ISSUE TITLE
API형 문의드립니다.

### ISSUE THREAD

**Issue by SSImJJ** [plusfriend/auto_reply#569]
안녕하세요. 챗 기획 중에 문의드릴 사항이 있어 글 남깁니다.

플러스친구 고객센터 챗봇을 보면 이미 이지 리플라이, 카드 등 다양한 기능을 제공하고 있는것으로  보입니다. 하지만 API형 챗을 구성할 때 해당 기능들을 사용할 수 없도록 되어있습니다.
혹시 플러스 친구 고객센터 챗봇에서 사용하고 있는 해당 기능들을 API형에서 사용할 수 있는 방법이 없을까요?

확인 부탁드립니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 말씀하신 스펙은 현재 CBT 중인 카카오 I 오픈빌더(http://bot-builder.kakao.com/)에서만 제공하는 기능이며 해당 플랫폼은 추후 정식 오픈될 예정입니다. 그 전에 해당 기능을 사용하고 싶을 경우 카카오 공식 챗봇 에이전시를 통해 이용 가능하니 참고해주시기 바랍니다. (https://pf.kakao.com/_TsIAE/9233366)
