### ISSUE TITLE
옐로 아이디 자동 응답 API 인증 과정

### ISSUE THREAD

**Issue by humit0** [plusfriend/auto_reply#57]
전화번호 형태를 010-XXXX-XXXX와 같은 형태로 입력하면 처음에 인증은 성공하지만 저장을 할 때 아래와 같이 "카카오톡 인증이 되지 않는 번호입니다."라는 에러 메시지가 나오네요.

![image](https://cloud.githubusercontent.com/assets/8676247/16900223/d7b21b7c-4c59-11e6-847d-411f9319ed0f.png)

참고로 010XXXXXXXX와 같은 형태로 입력하는 경우에는 에러 없이 잘 진행이 됩니다.

**Comment by plusfriendteam** [comment]
@humit0 감사합니다. 확인후 알려드리겠습니다.

**Comment by plusfriendteam** [comment]
@humit0 해당내용 수정하였습니다. 
버그제보 감사합니다.
