### ISSUE TITLE
API keyboard test를 하면, Required* keyboard Fail

### ISSUE THREAD

**Issue by yerbn0409** [plusfriend/auto_reply#573]
안녕하세요 API형 keyboard test url에 http://192.168.0.3:5000/ 를 기입하면 다음고 같은 에러가 발생합니다.

![2](https://user-images.githubusercontent.com/30457019/38681039-bf431bda-3ea2-11e8-9198-05c73bfa6d7b.PNG)
![default](https://user-images.githubusercontent.com/30457019/38681055-cb2ee7d0-3ea2-11e8-9c40-1650441dba91.PNG)

크롬 브라우저에서 http://192.168.0.3:5000/keyboard 로 접속하면 아래와 같이 정상적으로 페이지가 로드됩니다.
{"buttons": ["start", "help"], "type": "buttons"}
방화벽과 포트포워드도 모두 열어두었고, 제 개인 스마트폰으로 http://192.168.0.3:5000/keyboard 에 접속해도 {"buttons": ["start", "help"], "type": "buttons"} 와 같이 정상적으로 출력 됩니다.

python code는 아래와 같습니다.
`def app_kakao():
    # -*- coding: utf-8 -*-

    # ---------------------------------
    # quizbot.py
    # ---------------------------------

    import os
    from flask import json, Flask, request, jsonify, Response

    app = Flask(__name__)

    @app.route('/keyboard')
    def Keyboard():

        dataSend = {"buttons": ["start", "help"], "type": "buttons"}
        json_string = json.dumps(dataSend, ensure_ascii=False)
        response = Response(json_string, content_type="application/json; charset=utf-8")
        return response

    @app.route('/message', methods=['POST'])
    def Message():

        dataReceive = request.get_json()
        content = dataReceive['content']

        if content == u"시작하기":
            dataSend = {
                "message": {
                    "text": "아직 개발중이라 대답을 잘 못해도 이해해줘^^;"
                }
            }
        elif content == u"도움말":
            dataSend = {
                "message": {
                    "text": "이제 곧 정식 버전이 출시될거야. 조금만 기다려~~~"
                }
            }
        elif u"안녕" in content:
            dataSend = {
                "message": {
                    "text": "안녕~~ 반가워 ㅎㅎ"
                }
            }
        else:
            dataSend = {
                "message": {
                    "text": "나랑 놀자 ㅋㅋㅋ"
                }
            }

        return jsonify(dataSend)

    if __name__ == "__main__":
        app.run(host='0.0.0.0', port=5000)

app_kakao()`

무엇이 문제라서 test를 통과하지 못하는 것인지 너무 알고 싶습니다.

**Comment by humit0** [comment]
192.168.0.3 은 같은 망에 있는 컴퓨터와 접속할 때 사용하는 주소입니다.
외부 IP로 보여지는 것으로 사용하셔야 합니다. https://api.ipify.org?format=json 로 들어가시면 해당 컴퓨터의 외부 IP를 얻으실 수 있습니다.
만약 공유기를 사용하시고 계시다면 추가로 포트포워딩까지 하셔야 합니다.

**Comment by yerbn0409** [comment]
humit0// 오 말씀하신 대로 외부 IP로 보여지는 것으로 사용했더니 잘 해결되었습니다!! 감사합니다. 이 문제로 고생하시는 다른 분들도 보고 잘 해결하셨으면 좋겠습니다.
