### ISSUE TITLE
#415 에러, Django, pythonanywhere 사용

### ISSUE THREAD

**Issue by YoonJ** [plusfriend/auto_reply#574]
안녕하세요 카카오 챗봇을 구현하고 있는 학생입니다.
Django와 pythonanywhere을 사용하여 카카오톡 챗봇 구현하는 블로그 글을 따라가며 구현했습니다.
로컬 서버에서는 http://127.0.0.1:8000으로 접속하면 page not found가 뜨는데 http://127.0.0.1:8000/keyboard로 접속하면 입력한 코드가 나옵니다.
하지만 python anywhere와 카카오톡 API테스트를 하면 에러가 뜹니다.
하루종일 조금씩 이것도 해보고 저것도 해보고, 다시 새로 만들어 봤지만 오류가 뜹니다.
settings.py에 ALLOWED_HOSTS = '*' 이렇게도 했고,
API test할 때에는 python anywhere의 url만 넣었습니다. 

## 1. 프로젝트>urls.py
``from django.conf.urls import url, include
from django.contrib import admin
from app import views

urlpatterns = [
    url(r'^', include('app.urls')),
    url(r'^admin/', admin.site.urls),
]``

## 2. 앱>urls.py
`from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^keyboard/', views.keyboard),
    url(r'^message/', views.message),
]`

## 3. 앱 >views.py
`from django.shortcuts import render

from django.http import JsonResponse
import json

#@csrf_exempt
def keyboard(request):

    return JsonResponse(
        {
            "type":"buttons",
            "buttons": ["1","2","3"]
       }
    )

#@csrf_exempt
def message(request):

    message = ((request.body).decode('utf-8'))
    if(message.find(u"calendar")>-1 ):
        return JsonResponse({
            "message":{
                "text":"you say calendar"
            },
            "keyboard":{
                "type":"buttons",
                "buttons" : ["1","2","3"]
            }
        })

`

**Comment by humit0** [comment]
#573 에도 단 내용이지만
127.0.0.1 은 자기 자신에게 접속할 때 사용하는 주소입니다.
외부 IP로 보여지는 것으로 사용하셔야 합니다. https://api.ipify.org?format=json 로 들어가시면 해당 컴퓨터의 외부 IP를 얻으실 수 있습니다.
만약 공유기를 사용하시고 계시다면 추가로 포트포워딩까지 하셔야 합니다.

**Comment by YoonJ** [comment]
python anywhere를 사용하여 배포하고 해당 url을 사용하면 괜찮은 것 아닌가요?
질문은 127.0.0.1을 사용하여 로컬에서 돌리면 돌아가는데,
같은 코드를 python anywhere와 API 테스트할 때에는 오류가 난다는 것입니다.

**<python anywhere에서 '~~.pythonanywhere.com'의 정상작동>**
![6](https://user-images.githubusercontent.com/15773041/38745281-11637b12-3f7f-11e8-87fe-00f80b98aceb.png)

**<python anywhere에서 '~~.pythonanywhere.com/keyboard'의 오류>**
![5](https://user-images.githubusercontent.com/15773041/38745286-16ccbd02-3f7f-11e8-9743-d7523969b193.png)

**<local에서의 정상작동>**
![cap 2018-04-14 01-01-43-742](https://user-images.githubusercontent.com/15773041/38745432-7c254e30-3f7f-11e8-82c5-2e5802b5ec8f.png)

**Comment by humit0** [comment]
https://tutorial.djangogirls.org/ko/deploy/
이 링크를 참조해서 다시 해보시겠어요?

**Comment by YoonJ** [comment]
감사합니다. 이 페이지를 보고 따라한 것인데,  가상머신 등록하는 부분에서 에러가 뜨길랜
https://help.pythonanywhere.com/pages/Virtualenvs/
이 페이지를 보고 수정하였습니다. 하지만 아직 에러메세지가 뜹니다.
![cap 2018-04-14 14-51-22-356](https://user-images.githubusercontent.com/15773041/38764927-745a4a10-3ff3-11e8-9275-ba7ec4897c99.png)
이런 메세지가 없어지지 않아서... 어떤 부분에서 잘못된 것인지 아직 모르겠습니다.
제가 url 표현방식에 대한 이해가 부족한 것인지...

**Comment by humit0** [comment]
혹시 프로젝트 폴더의 이름이 dayeasy인가요?

**Comment by YoonJ** [comment]
네 맞습니다
