### ISSUE TITLE
카카오톡 챗봇 자동입장 버튼식 문제

### ISSUE THREAD

**Issue by JavaJob** [plusfriend/auto_reply#576]
"http://plus.kakao.com/talk/bot/@플러스친구명/첫입력내용"이 챗봇 자동 입장 후 첫 입력을 자동으로 해주는 주소입니다.
카카오톡에 암호가 없는경우는 정상적으로 작동하지만, 
카카오톡에 암호가 걸려있을 때 "첫입력내용"<<이 버튼식인 경우 해당 입력 진행 후 기존에 이전 버튼식이 남아있는 버그가 있습니다.

확인 부탁드립니다...

**Comment by plusfriendteam** [comment]
안녕하세요. 해당 이슈를 처리하기 위해 좀 더 자세한 확인이 필요합니다.
플러스친구 명을 알려주시면 확인 해보도록 하겠습니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 
말씀주신 문제는 안드로이드 환경의 일부 삼성 단말에서,
삼성 브라우저를 통해 해당 링크를 열었을 경우에만 발생하는 문제인 것으로 확인되었으며
해당 문제는 수정하여 다음 업데이트에 반영할 예정입니다. (상반기 내)
모든 단말에서 발생하는 문제는 아니며, 크롬 브라우저를 통해 열었을 경우에는 
정상 작동하고 있으니 참고해주시기 바랍니다. 소중한 제보 감사합니다.
