### ISSUE TITLE
관리자님, 답변 좀 다시는게 어떨까요?

### ISSUE THREAD

**Issue by arrrggghhh** [plusfriend/auto_reply#577]
여기 문의사항 올리라고 안내되어있는데 

실상 카카오쪽에서는 답변이 전혀 없다고 해도 과언이 아닌 상황입니다.

하다못해 봤는데 더 자세히 설명을 하라던지, 

조치를 하겠다던지 하다못해 연락을 주겠다거나 뭔가 피드백이 있어야 하는 것 아닌가요?

이 글은 보시긴 하실런지 모르겠네요.

**Comment by plusfriendteam** [comment]
안녕하세요. 문의를 올려도 답변이 달리지 않아 많이 답답하셨겠습니다. 
그간 내부 정책에 의해 API 관련 문의사항을 고객센터에서만 접수받고 있다가 
얼마 전부터 깃헙을 통해서도 답변을 다시 드릴 수 있도록 정책이 변경되었습니다. 

그간 쌓인 문의에 대해서는 최선을 다해 답변 드리고 있으나 
원인 확인에 시간이 걸리는 이슈들이 대부분이라 답변이 지연되고 있는 중입니다. 
이점 깊은 양해 부탁드리며 앞으로도 더욱 노력하는 플러스친구팀이 되겠습니다. 
감사합니다.
