### ISSUE TITLE
API 2.0 PPM 기능 문의

### ISSUE THREAD

**Issue by infobankimedia** [plusfriend/auto_reply#58]
안녕하세요. 인포뱅크 김지황입니다.

과거 플러스친구 API에는 해당 유저 key값을 통해서, 메시지를 보낼 수 있는 PPM 기능이 존재 하였습니다.

현재 API 2.0 ver 문서에는 해당 기능이 명시되어 있지 않아 문의 드립니다.

혹시, 해당 기능이 현재 존재 하거나 추후 개발 예정인지 확인 부탁드립니다.

추가적으로, 사업부를 통해 ADMIN 페이지를 통해서 만건(일) 무료발송은 확인 하였습니다. 
하지만 해당 방법은 업체 입장에서 그룹생성해서 추가하여 보내고, 다시 삭제 해야 한다는 번거로움이 있어서 문의 드립니다.
혹시 어드민 그룹 생성을 컨트롤(추가/삭제/수정) 할 수 있는 API는 존재 하는지 확인 부탁드립니다.

감사합니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 
문의주신 PPM API는 더이상 제공되지 않으며, 신규 API인 친구톡으로 대체되었습니다. 
신규 API에 대한 상세한 소개는 카카오톡 비즈메시지(http://bizmessage.kakao.com/main), 문의사항은 help.bzm@kakaocorp.com 을 이용해 주시기 바랍니다.

또한 어드민 그룹 생성은 친구그룹 관리에 대한 내용을 지칭하시는 것으로 생각되는데요, 친구그룹과 관련한 API는 현재 제공되고 있지 않습니다. 이 점 참고 부탁드립니다.
