### ISSUE TITLE
php를 통한 중계 데이터 전송시 /message 를 받지 않는 오류

### ISSUE THREAD

**Issue by LunaNTR** [plusfriend/auto_reply#59]
제가 지능형 봇을 만들기위해서 vb6으로 서버를 구축해서 사용해봤으나 한글 인코딩 문제에 부딫혀서 생각해낸게 중간에 php를 놓는겁니다.

유저가 대화방에 들어가면 먼저 키보드버튼을 보여주기위해 /keyboard 를 호출하면 php에서 해당 명령을 받아서 vb6 으로 전달해주면 그에대한 결과 소스(버튼3개출력하는 JSON)를 php에게 뿌려주게 되고, 그 소스를 그대로 카카오 서버측으로 전송하도록 기능을 구현했습니다.

원래 vb6으로만 서버 만들었을때는 영어로 말하게 하고 하면 버튼형 키보드도 정상적으로 뜨고, 영어로 채팅하면 입력받은메세지에 따른 처리결과를 정상적으로 내보내고 있습니다.

그리고 이제 한국어 지원을 위해 php를 중간에 넣고 테스트를 했습니다.

채팅방 들어가자마자 비주얼베이직에 정상적으로 접속되었고 처리결과를 보냈다는 로그가 찍혔고, 카카오톡 내에서도 정상적으로 한국어 버튼이 떴습니다.

그다음은 똑같이 해서 /message . 즉 유저가 입력한 메세지를 받았을때 입력값을 그대로 반사해주는 기능도 똑같은 방법으로 구현을 하고 다시 채팅방에 들어가니

버튼입력 정상적으로 뜬 후, 버튼 누르거나 채팅을 하면 그 즉시 '해당 프로필의 자동응답 시스템이 응답을 하지 않습니다. 문제가 보고되어 처리 예정입니다. 다음에 다시 시도해주세요.' 라는 메세지가 뜨면서 채팅창의 1:1 버튼이 사라지고 봇 기능이 중지됩니다.

확인해봤더니 비주얼베이직에는 메세지를 받았다는 로그가 찍히지 않았으며, 접속되었다는 로그도 뜨지 않았습니다.

그래서 문제가 있다고 판단하고 본문에 있는 curl 예시를 가지고 메세지를 호출해보았으며

정상적으로 그에대한 연결도 되고 메세지도 정상적으로 전달되는게 확인되었습니다.

curl에서는 잘 되는게 왜 카카오에서는 안되는건가요?

**Comment by plusfriendteam** [comment]
안녕하세요. 
사용하시는 옐로아이디명을 알려주시고
사용하신 curl command를 알려주시면 조금더 자세한 안내가 가능할 것 같습니다.

**Comment by LunaNTR** [comment]
현재 사용중인 옐로 아이디명은 @lunaz 입니다.

먼저 /keyboard 를 구현하기 위해 http://서버명/keyboard 폴더 내부에 index.php 파일을 넣었으며

해당 파일의 소스는 다음과 같습니다.

<?php
$data =  json_decode(file_get_contents('php://input'));
define("_IP",    "서버명");
define("_PORT",  "포트주소");
$sock = socket_create(AF_INET, SOCK_STREAM, SOL_TCP);
$result = socket_connect($sock, _IP, _PORT);
if ($result === false) {
     echo mb_convert_encoding('{"type":"buttons","buttons":["서비스가","진행중이지","않습니다."]}', "UTF-8", "EUC-KR");
}

$head = "GET /keyboard HTTP/1.1";
$headers = getallheaders();
while(list($header, $value) = each($headers)){
    $head  = "$head\n$header: $value"; 
}
socket_write($sock, $head);
$data = socket_read($sock, 4096);
echo mb_convert_encoding($data, "UTF-8", "EUC-KR");
socket_close($sock);
?>

대충 소스 내용은 접속요청이 오면, 해당 헤더를 읽어서 그대로 비주얼베이직으로 만든 서버에 접속하여 뿌려줍니다.

만약 비주얼베이직 서버가 켜져있지 않다면 사용자에게 사용할 수 없다는 메세지를 대신 출력합니다.

비주얼베이직 서버에서는 해당 패킷을 받으면 분석해서 그에 맞는 처리결과를 뿌려줍니다.

{"type":"buttons","buttons":["사용방법","추가 설정","대해서.."]}

위의 패킷이 실제 비주얼베이직에서 보내는 패킷입니다.

비주얼베이직에서 받은 패킷을 그대로 php에서 접속요청이왔던 서버로 뿌려줍니다.

/keyboard에서는 다음과같이 작동하며, 스마트폰에서 테스트 결과에서도 정상적으로 됩니다.

근데 문제는 /message 폴더에있는 index.php파일이 되는데,

<?php
$data =  json_decode(file_get_contents('php://input'));
define("_IP",    "서버명");
define("_PORT",  "포트주소");
$sock = socket_create(AF_INET, SOCK_STREAM, SOL_TCP);
$result = socket_connect($sock, _IP, _PORT);
if ($result === false) {
     echo mb_convert_encoding('{"message":{"text":"명령어 서버가 작동하지 않습니다. 잠시후 다시 시도해 주세요."}}', "UTF-8", "EUC-KR");
}

$head = "POST /message HTTP/1.1\r\nuserkey<br>$data->user_key</br>type<br>$data->type</br>content<br>$data->content";
socket_write($sock, $head);
$data = socket_read($sock, 4096);
echo mb_convert_encoding($data, "UTF-8", "EUC-KR");
socket_close($sock);
?>

index.php파일의 소스 내용입니다.

똑같이 작동하며, 비주얼베이직으로 데이터를 보낼 때 첫번째 헤더만 그대로 포함하고, 나머지 두번째 줄 부터는 비주얼베이직에서 판단하기 쉽게 유저키값,데이터타입,내용 만을 적어서 보냅니다.

그외 소스는 위의 /keyboard와 같이 작동하구요.

역시 비주얼베이직에서 처리한 후 결과를 그대로 php로 접속 요청이 왔던 곳에 뿌려주는데

이부분이 문제가되는게

php에서 비주얼베이직쪽으로 데이터를 주지않아서 이상하다싶어서 확인해봤는데 php로 접속요청이 오지않습니다.

이상하다 싶어서 curl을 통한 테스트 방법을 보고 그대로 사용을 해보았습니다.

[스크린샷](http://test.noin.me/1.png)

비주얼베이직으로도 정상적으로 연결 요청이 왔으며, php에서도 정상적으로 해당 내용을 처리해서 리턴해줬습니다.(유저아이디는 리턴하지않도록 되어있습니다 현재)

/message는 호출방법이 다른건지, 왜 연결요청이 안오는지

그걸 알면 될거같습니다.

감사합니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 
카카오서버에서 귀하의 서버에 접근을 할 수 없다고 나옵니다.
#1 을 참고해주시기 바랍니다.

```
$ curl -H "Content-Type: application/json" -XGET http://lu.noin.me/keyboard -v
* About to connect() to proxy proxy.daumkakao.io port 3128 (#0)
*   Trying 10.20.30.90... connected
> GET http://lu.noin.me/keyboard HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: lu.noin.me
> Accept: */*
> Proxy-Connection: Keep-Alive
> Content-Type: application/json
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 403 Forbidden
< Mime-Version: 1.0
< Date: Fri, 22 Jul 2016 05:46:45 GMT
< Content-Type: text/html
< Content-Length: 15
< X-Squid-Error: ERR_ACCESS_DENIED 0
* HTTP/1.0 connection set to keep alive!
< Connection: keep-alive
< 
Access Denied!
* Connection #0 to host proxy.daumkakao.io left intact
* Closing connection #0
```
