### ISSUE TITLE
어떤 질문에 대한 답인지 알려면 어떻게 해야하나요?

### ISSUE THREAD

**Issue by oognus** [plusfriend/auto_reply#591]
예를들어서 

챗봇: 사용자의 이름을 입력하세요
사용자: 홍길동

이때 '홍길동'이라고 입력한 것이 사용자의 이름을 입력한 것인지 알려면 어떻게 해야 하나요?
따로 tag를 달거나 key값을 전달하는 방법이 있나요? 
아니면 user_key값을 이용하여 별도로 저의 서버에서 처리를 해야되는건가요?

가장 이상적인 방법이 무엇인지 답변 부탁드립니다.

**Comment by parkzel** [comment]
저도 해당 사항에 대해서 카카오톡에 문의를 해보았는대..
개인정보보호 문제로 USER_KEY값만 전달 받을수 있고..
이 USER_KEY값이 누군지..전화번호가 뭔지는 별도로 DB를 두든 해서
식별을 해야 할듯하네요.
