### ISSUE TITLE
챗봇과 대화가 진행이 안되는데 어떤게 문제인지 모르겠습니다.

### ISSUE THREAD

**Issue by seojoonha** [plusfriend/auto_reply#592]
MS Azure Bot Framework, DirectLine으로 챗봇을 만들었습니다.
Web App에 연결하는 DirectLine은 오일석봇으로,
대화를 진행하는 챗봇은 Bot Builder Sample 중에서 core-BasicMultiDialog 로 진행했는데요
(https://github.com/ilseokoh/ohilseokbot)
(https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-BasicMultiDialog)

봇이 이름과 나이를 물어보고 유저가 대답하면 
"네 이름은 @@이고 나이는 @@이구나" 라는 대답을 돌려주거든요

Azure Portal에서 제공하는 WebChat이나
연결 확인해보려고 써봤던 Postman도 테스트 해봤을때 문제없이 작동을 하고
봇-DirectLine-카카오톡 연결도 잘 됐는데
메시지를 보내보니까 어떤 입력을 해도 welcome message만 계속 나와요

어느 부분에 문제가 있는지 찾아볼 수 있는 방법이 있을까요?

**Comment by plusfriendteam** [comment]
안녕하세요. 
플러스친구 이름이 "오일석봇"이 맞으신가요?
플러스친구 관리자센터의 스마트채팅 > API형 > 앱 URL 로 입력해주신 URL 에서 아무 응답도 주지 않고 있습니다. 
서버가 정상적으로 동작하고 있는지 확인해주세요. 
감사합니다.

**Comment by seojoonha** [comment]
아앗 오일석봇이아니구요 오일석이라는 분이 만든 봇을 가지고 만든건데 제가 지금 테스트하고 있는 플러스친구 이름은 aar2 입니다

**Comment by plusfriendteam** [comment]
안녕하세요.
알려주신 플러스친구를 확인해보았습니다.
저희 쪽에서는 구현해주신 API 의 응답만 받아 채팅방에 메시지를 보내고 있기 때문에 
세부적인 API 구현 문제를 확인하기는 어렵습니다. 

최대한 응답 로그를 확인해보았는데요, 
저희 쪽에 해당 API 에서 들어온 로그로는 별다른 이상은 없습니다만 간간히 Timeout 이나 응답이 오지 않는 경우가 있습니다. 
구현하신 서버에서 응답을 늦게 주는 경우가 있는 것 같은데요,
API 에 이상이 없는지 확인해보셔야 할 것 같습니다.
감사합니다.

**Comment by seojoonha** [comment]
으어엉... 감사합니다
