### ISSUE TITLE
Keyboard 설정시 궁금한점

### ISSUE THREAD

**Issue by timothyh124** [plusfriend/auto_reply#598]
키보드 설정시, 
텍스트나 버튼 타입외에 키보드 edit field의 placeholder 값도 정할수 있게 업데이트가 가능할지요?
예:
keyboard = {
  "type": "buttons",
  "placeholder" : "please select from above",
  "buttons" : ["opt_1", "opt_2"]
}

**Comment by plusfriendteam** [comment]
안녕하세요.
의견주셔서 감사합니다.
내부적으로 업데이트 가능한지 논의해보도록 하겠습니다. 감사합니다.

**Comment by timothyh124** [comment]
감사합니다 티켓 클로즈 할께요
