### ISSUE TITLE
자동응답이 수행되지 않습니다. 

### ISSUE THREAD

**Issue by newpouy** [plusfriend/auto_reply#6]
안녕하세요. 
옐로아이디 계정 @김회경으로, 자동응답API를 사용하여 메시징 서버를 만들었는데요. 제 카카오톡 계정(newpouy@naver.com)과의 톡창에서는 자동응답이 잘 이루어지는데, 다른 사람 카톡계정과의 톡창에서는 자동응답이 수행되지 않고 있습니다. 제가 직접 옐로아이디 관리자 어플의 대화창에 들어가기 전까지는 '읽지않음'을 나타내는 표시도 없어지지 않구요. 테스트용도로 만든 계정에는 대화에 제한을 거는 장치가 어디엔가 있는 건가요?

**Comment by suya55** [comment]
@newpouy 채팅 입력창 우측의 1:1 버튼을 한번 눌러 보시겠어요?
