### ISSUE TITLE
자동응답 API 설정 - 해외 번호

### ISSUE THREAD

**Issue by federer89** [plusfriend/auto_reply#60]
안녕하세요.

호주에 거주하는 개발자인데요 옐로아이디 개설 후 자동응답 API를 활용하려고 하는데 전화번호를 한국 번호 포맷으로 입력하라고 나오면서 카카오톡 인증을 못하게 되어있습니다. 

어떻게 해결을 해야하나요? 해외라 문의전화도 드리기가 힘듭니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 아직은 해외사용자들에게는 오픈이 안되어있습니다.
정확히는 관리자의 전화번호가 국내 유저만 대상으로 서비스가 오픈되어있습니다.
이부분 안내문구로 추가하도록 하겠습니다.

감사합니다.

**Comment by plusfriendteam** [comment]
@CodinglionX 너무 늦은감이 없지 않지만 ㅠㅠ 해외번호로 인증을 받을 수 있도록 수정되었습니다. 국가번호와 함께 입력하시면 인증번호를 받으실 수 있습니다.

**Comment by CodinglionX** [comment]
감사합니다! 한국에 있는 지인을 통해 한국번호로 인증을 받아서 사용해왔는데 해외로 인증받을 수 있게 수정되었으면 이제 제 번호로 사용하려고 하거든요. 혹시 기존에 사용하던 번호를 해외번호로 바꾸었을 때 생기는 문제는 없으려나요?

**Comment by plusfriendteam** [comment]
에러 메세지와 공지사항등을 받을 수 있게 하기 위해서 존재하는 것이기 때문에 별다른 문제는 발생하지 않을거에요. ^^

**Comment by CodinglionX** [comment]
카톡을 사용하고 있는 호주 번호인 0433526597, 국가번호 합치면 +61433526597을 넣었더니 아래와 같은 에러문구가 뜨네요

> [Error]
카카오톡이 인증이 되지 않는 번호입니다. - +61433526597

어떻게 하면 좋을까요?

**Comment by plusfriendteam** [comment]
@CodinglionX + 빼고 넣어보시겠어요? 저희쪽 처리가 완벽하지 않았네요 ㅠㅠ 일단 기호 다 빼고 숫자만 넣으시면 잘 될거에요^^;

**Comment by CodinglionX** [comment]
+기호 빼고 번호만 입력하니까 제대로 작동하네요. 조금 늦어졌지만 정상처리 되도록 해결해주시고 답변해주셔서 너무 감사합니다!
