### ISSUE TITLE
415 이슈

### ISSUE THREAD

**Issue by kiyaaa** [plusfriend/auto_reply#600]
API Test를 하면 415 오류가 뜨는데요.
저는 json을 만들면 아래 형태가 아니라
{
  "type": "buttons",
  "buttons": [
    "선택 1",
    "선택 2",
    "선택 3"
  ]
}

aws URL그대로 수행하면, 아래처럼 순서가 나오는데, 이것 때문인가요.
순서를 바꾸는 방법을 찾아보는데 모르겠고, json인데 순서때문에 에러나는게 맞나 싶기도하고요.
도움부탁드립니다!
{
  "buttons": [
    "선택 1",
    "선택 2",
    "선택 3"
  ],
"type": "buttons"  
}

**Comment by plusfriendteam** [comment]
안녕하세요. 
415 에러는 Content-Type 이 application/json; charset=utf-8 인지 확인해주세요.
확인 후에도 이상이 있으시면 조금 더 자세히 확인해보겠습니다.
감사합니다.

**Comment by kiyaaa** [comment]
소스상 문제가 있었습니다. 감사합니다.
