### ISSUE TITLE
Kakao I Open Builder 오픈후 카카오톡 플러스친구 API 미래?

### ISSUE THREAD

**Issue by 5amuraix** [plusfriend/auto_reply#602]
안녕하세요?

제가 알고 있듯이, Kakao I Builder는 카카오톡의 챗봇을 개발할수있는 플랫폼 CBT (closed beta test) 상태입니다.

만약에 오픈 되면, 카카오톡 플러스친구 API는 계속 지원 예정입니까?

감사합니다.

**Comment by plusfriendteam** [comment]
안녕하세요.
현재 자동응답 API 의 종료 여부에 대해서는 결정된 바가 없습니다.
종료 결정을 하게 되더라도 충분한 시간과 함께 사전 공지를 통해 안내해 드릴 예정입니다.
감사합니다.
