### ISSUE TITLE
자동응답 API 사용중 궁금한점이 있습니다.

### ISSUE THREAD

**Issue by otac2** [plusfriend/auto_reply#61]
php 로 수신용 파일을 만들어서 동작까지 완성하였습니다

<?php
$data =  json_decode(file_get_contents('php://input'));
//입력을 받아서$data변수에 모두저장
$ment = $data->content;
if($ment =="메뉴"){

$str = $ment."테스트";

echo "
{
  \"message\": {
    \"text\": \"".$str."\"
  }

}
";

}
?>

이것까지 잘 작동하는데 저는

사용자가 메뉴 라고 입력시
말풍선이 2개 보였으면 합니다

지금은 자동응답 메시지가 길 경우에 그냥 줄바꿈해서 보내주고있는데요
아예 그냥 응답 메시지가 2개 쳐지게끔 하고싶습니다

어떻게 수정해야하나요?

**Comment by plusfriendteam** [comment]
안녕하세요.
유저의 액션 한번에 한해서 한번의 응답만 가능합니다.

감사합니다.
