### ISSUE TITLE
500/internal server error

### ISSUE THREAD

**Issue by ChoiHyeongu** [plusfriend/auto_reply#611]
오늘, 내일버튼을 클릭시 500/Internal server error가 뜹니다. 코드는 제 깃허브 Meal-bug에 올라가있습니다.
http://13.125.229.41/keyboard/ 로 접속시 {"buttons": ["\uc624\ub298", "\ub0b4\uc77c"], "type": "buttons"}이라고 잘 나옵니다. 일주일째 안되서 미치겠네요.. ㅠㅠ

**Comment by plusfriendteam** [comment]
안녕하세요.
현재 해결 된 것으로 보이는데요, 별도로 문의 사항이 있으시면 코멘트 달아주세요.
감사합니다.

**Comment by ChoiHyeongu** [comment]
http://13.125.229.41/message 로 들어가면 json decode에러가 뜹니다 주위에서 물어봤는데 빈문자열을 가지고 json.loads를 수행한것같다고 합니다

**Comment by ChoiHyeongu** [comment]
방금 수정을 조금 했는데 내일을 누르면 "내일 급식입니다!"가 나오는데 파싱을 적용시킨 오늘 버튼은 500에러가 나옵니다. 코드중에 실수가 있는것같네요..
