### ISSUE TITLE
카카오톡 스마트 채팅 관련 

### ISSUE THREAD

**Issue by ggwnags** [plusfriend/auto_reply#612]
안녕하세요.

카카오톡 플러스에서 스마트 채팅 관련 API 개발 중에 있습니다.

url/keyboard 호출시에는 잘 처리되는 것 같은데, 
url/message 호출 (TEXT 입력시)에 '해당 프로필의 자동응답 시스템이 응답을 하지 않습니다. 문제가 보고되어 처리 예정입니다. 다음에 다시 시도해주세요.' 라고 하는데, 

혹시 서버 작업중에 있는건가요?

**Comment by plusfriendteam** [comment]
안녕하세요. 
문의주신 날짜에 스마트채팅 관련된 작업은 없었습니다. 
message API 를 호출 할 때 작업하신 서버에 에러가 있었던 것 같은데요,
작업하신 서버를 확인해보셔야 할 것 같습니다.
참고해주세요. 감사합니다.
