### ISSUE TITLE
시간이 되면 사용자에게 자동으로 전송되는 기능을 구현할 수 있을까요?

### ISSUE THREAD

**Issue by Sain-Tech** [plusfriend/auto_reply#613]
현재 챗봇을 만들고 있는데요,
시간이 되면 알람 기능처럼 자동으로 메시지가 전송되게 하고 싶은데
구현이 가능한지 궁금합니다.

**Comment by SerenityS** [comment]
아직은 불가능합니다
대규모 개편 준비중인것 같던데 몇달째 아무 소식이 없더라구요

**Comment by Sain-Tech** [comment]
답변 감사드립니다~
