### ISSUE TITLE
카톡 플러스친구 무료 메시지는 스마트채팅 자동응답 API를 이용한 메시지 리턴도 포함되나요?

### ISSUE THREAD

**Issue by geoseong** [plusfriend/auto_reply#616]
안녕하세요.

혼동이 되는 부분이 있어서 문의드립니다..

제가 현재 플러스친구 스마트채팅을 API를 이용해서 챗봇개발중인데요, 

이렇게 API를 이용한 스마트채팅 응답도 무료 메시지 1건으로 간주하는 것인가요?

그러니까 
- `무료 메시지 1건` = `스마트채팅 API 응답 1건` 인지, 
- 응답이 1000건이 넘으면 과금이 되기 시작하는건지
- 이렇게 1000건이 넘어갈 시 1건 당 얼마가 청구되는 지  

궁금합니다.

답변 부탁드립니다~
감사합니다.

**Comment by tom5079** [comment]
무료메세지는 관리자 콘솔의 '메세지' 탭에서 메세지를 보낼때만 소비되는 것 같습니다. API응답은 무료인듯 합니다.

**Comment by geoseong** [comment]
@tom5079 아 그런가요, 그렇다면 제가 원하는 답을 얻게되는 거긴 하네요 ㅎㅎ 여기는 운영진들의 답이 없어서 답답하네용 ㅜㅎ

**Comment by plusfriendteam** [comment]
답변이 늦어 죄송합니다. tom5079님 말씀대로 응답 메시지는 무료입니다. 감사합니다.
