### ISSUE TITLE
하나의 질문에 복수의 응답 메세지를 보낼 수 있을까요? 

### ISSUE THREAD

**Issue by jjangga0214** [plusfriend/auto_reply#618]
사용자가 하나의 질문을 던졌을 때, 그 질문에 대한 대답으로 하나 이상의 메세지를 보낼 수 있을까요? 
(예를 들어, 가능한 경우 중 하나로, 사진 2장을 응답으로 보낸다던지 등의 경우들이 있을 것 같습니다.)

**Comment by plusfriendteam** [comment]
안녕하세요.
현재 하나 이상의 메시지를 보내는 기능은 지원하지 않고 있습니다. 
참고해주세요. 감사합니다.

**Comment by jjangga0214** [comment]
저희 서비스에 맞도록 챗봇 개발시, 

* 질문에 대한 대답으로 2개 이상의 메세지(사진을 몇장 보내려 합니다)를 보내는 기능과,  
* 질문 없이도 먼저 메세지를 보내주는 기능

이 있다면 활용도가 좋을 것이라 여겨 여쭤 보았습니다. 

현재 말씀하신 대로 두가지 기능이 지원되지 않고 있는데, 
혹시 언제쯤 가능해질지 대략적인 시기를 여쭤볼 수 있을까요?

물론 시기를 정확히 말씀해주시는 것이 어려울 수 있다고 생각합니다. 
다만, 실제 편차가 크거나 향후 계획이 변경되어도 저희는 괜찮으니 대략적이나마 시기를 일러주시면 향후 개발 계획을 개략적으로나마 세우는데 도움이 될 것 같습니다. 

감사합니다 :)

**Comment by plusfriendteam** [comment]
안녕하세요.
현재 정책 상 위의 기능들은 제공하고 있지 않습니다.
해당 기능은 *카카오톡 비즈메시지* 서비스에서 유료로 제공하고 있습니다.
https://bizmessage.kakao.com/ 이 링크에서 상세한 상품들을 보실 수 있습니다.
참고가 되셨으면 합니다.
