### ISSUE TITLE
자동응답 앱 URL API TEST

### ISSUE THREAD

**Issue by federer89** [plusfriend/auto_reply#62]
앱 URL TEST에 제 도메인 http://julysfx.com/ 을 넣고 API TEST를 눌렀더니 

"Please be advised that LiteSpeed Technologies Inc. is not a web hosting company and, as such, has no control over content found on this site."

이런 문구가 뜨면서 진행이 되지 않습니다. 

구글에 찾아보니 제 호스팅 서버에 있는 public_html 퍼미션이 750으로 되어있어야 한다고 해서 확인해봤더니 퍼미션도 750으로 되어있구요.

**Comment by plusfriendteam** [comment]
안녕하세요 
저희 서버에서 귀하의 서버에 접근이 불가능 하다고 나오는데요
ACL 설정이 되어있는지 확인 부탁드립니다. 
#1 확인 바랍니다
