### ISSUE TITLE
유저이름 불러오기

### ISSUE THREAD

**Issue by dksmsrpgla-whale** [plusfriend/auto_reply#620]
자동응답시에 유저이름을 사용해서 [유저이름]님 이번주 저희 ~~~는 ~~~~~입니다. 이런식으로 상담중인 유저이름을 불러오고 싶습니다. 예를들어 제 프로필닉네임이 a면 "공연일정확인"이란 버튼을 누르면 massage에서 답별할때 "a님 이번주 공연일정은 수요일에 있습니다. 감사합니다. "이런식으로 답변하는 것이죠. 
이런식으로 유저이름을 불러올 수 있나요?
된다면 방법을 알려주시면 감사하겠습니다. 

감사합니다.

**Comment by plusfriendteam** [comment]
안녕하세요.
현재 카카오톡 프로필 닉네임을 가져올 수 있는 기능은 제공하고 있지 않습니다.
참고해주세요. 감사합니다.
