### ISSUE TITLE
알림톡 발송 api

### ISSUE THREAD

**Issue by dksmsrpgla-whale** [plusfriend/auto_reply#621]
자동응답 외에 알림톡(상대의 발송없이 예매 등 중요사항전달)하려 하는데 
카카오톡홈페이지에서 하는거 말고는 api같은게 없내요. 
혹시 관련해서 api 같은 것 알려주세요. 
(발송건 외에 추가비용이 무료인걸로요)

**Comment by plusfriendteam** [comment]
안녕하세요.
현재 정책 상 자동응답 API 에서는 상대방의 메시지 없이 먼저 메시지를 보내는 기능을 지원하고 있지 않습니다.
해당 기능들은 **카카오톡 비즈메시지**에서 유료로 제공하고 있습니다.
https://bizmessage.kakao.com/ 이 링크에서 관련 상품들을 보실 수 있습니다. 
참고가 되었으면 합니다. 감사합니다.
