### ISSUE TITLE
메시지 형태 문의

### ISSUE THREAD

**Issue by kimsangyoun** [plusfriend/auto_reply#623]
안녕하세요. 카카오톡 플러스 친구 자동 채팅 api를 개발 중인 김상윤입니다.
![image](https://user-images.githubusercontent.com/10652587/41505816-ca3c002e-724b-11e8-9c9d-c525f4fdbef8.png)
이와 같이 메시지 버튼 형태가 일반 유저들에게 제공되지 않는 것으로 보여지는데 해당 버튼 처럼 말풍선 모양으로 버튼을 제공해 주려면 어떻게 해야하나요?

**Comment by plusfriendteam** [comment]
안녕하세요.
현재 해당 버튼은 자동응답 API 에서 제공하고 있지 않습니다.
추후에 해당 기능 개발을 고려해보도록 하겠습니다. 
자동응답 API를 이용해주셔서 감사합니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 말씀하신 스펙은 현재 CBT 중인 카카오 I 오픈빌더(http://bot-builder.kakao.com/)에서만 제공하는 기능이며 해당 플랫폼은 추후 정식 오픈될 예정입니다. 그 전까지는 카카오 공식 챗봇 에이전시를 통해 이용이 가능하니 참고해주시기 바랍니다. (https://pf.kakao.com/_TsIAE/9233366)
