### ISSUE TITLE
사용자 위치정보를 받을 수 있나요?

### ISSUE THREAD

**Issue by shpongle2634** [plusfriend/auto_reply#625]
메시지에 응답을 할 때, 사용자 위치에 따라 응답을 다르게 하고자 합니다.
때문에 사용자 위치를 메시지에 담을 수 있었으면 좋겠습니다.

**Comment by plusfriendteam** [comment]
안녕하세요.
해당 기능은 현재 자동응답 API 에서 제공하고 있지 않습니다.
또한 개인정보 문제가 생길 수 있어 차후에도 제공하기 어려워 보입니다.
참고가 되시길 바랍니다. 감사합니다.
