### ISSUE TITLE
Required* keyboard Fail 415 wrong keyboard initialization  문제...

### ISSUE THREAD

**Issue by itsandroid** [plusfriend/auto_reply#626]
curl -XGET 'http://aszx9873.ivyro.net/keyboard' 정상작동
http://aszx9873.ivyro.net/keyboard 정상작동

인데 뭐가 문제일까요
:?>.

**Comment by plusfriendteam** [comment]
안녕하세요. 
Content-Type 이 현재 text/html; charset=UTF-8 로 내려오고 있습니다.
https://github.com/plusfriend/auto_reply#51-home-keyboard-api 를 참고하셔서
application/json; charset=utf-8 로 내려올 수 있도록 변경해주세요.
변경 이후에도 문제가 계속 된다면 새 이슈로 등록해주시기 바랍니다.
감사합니다.
