### ISSUE TITLE
플러스 친구를 구별할 수 있는 고유의 값이 있습니까?

### ISSUE THREAD

**Issue by Yunster** [plusfriend/auto_reply#627]
사용자 구별을 위한 user_key 값은 있는데, 각 플러스 친구를 구별하기 위한 고유의 key 값이 있는 지 궁금합니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 
현재 API 스펙 상에는 없습니다. 
대신, 플러스친구 관리자센터에서 등록하신 앱 URL 로 동작하기 때문에 
플러스친구 별로 앱 URL 을 다르게 설정해서 구분하는 방법이 있을 것 같습니다. 
참고가 되었으면 합니다. 감사합니다.
