### ISSUE TITLE
Required* keyboard Fail  415

### ISSUE THREAD

**Issue by inhacoms** [plusfriend/auto_reply#630]
안녕하세요 답변주신 내용으로 내부 방화벽에 설정을 점검하고 API TEST를 했으나 동일한 오류가 발생하고 있습니다.
타 외부서버에서 API 호출은 정상적입니다. 카카오쪽 호출에서만 안되고 있습니다.
카카오 자동응답서비스를 강제 중지 된것인지 확인 좀 부탁드립니다.

플러스친구:레지나플라워카페
API TEST URL: https://chatbot.zetacube.co.kr/keyboard
감사합니다.

**Comment by plusfriendteam** [comment]
안녕하세요.
시간이 좀 걸렸습니다만 문의 주신 내용을 자세히 살펴보았습니다. 
해당 프로필이 강제 중지된 적은 없습니다. 

다만, 저희 서버에서 해당 API 로 HTTP 요청을 보냈을 때 403 에러가 납니다. 
요청 시에 HTTP 헤더에서 
`X-Squid-Error: ERR_ACCESS_DENIED 0 ` 가 내려오는 것으로 보아 
사용하고 계신 proxy 서버에서 에러를 내려주는 것으로 보입니다. 
proxy 서버에서 안내해드린 
https://github.com/plusfriend/auto_reply#7-server-information 와 관련된 설정들이
정상적으로 동작하고 있는지 확인해주시길 바랍니다.  
감사합니다.
