### ISSUE TITLE
Required* keyboard Fail 415 오류 추적결과 확인요청 

### ISSUE THREAD

**Issue by inhacoms** [plusfriend/auto_reply#633]
안녕하세요

안녕하세요 답변주신 내용으로 내부 방화벽에 설정은 정상이고  API TEST를 했으나 동일한 오류가 발생하고 있습니다.

카카오 API TEST LOG을 당사 WAS에서 접속로그 확인한결과 다음과 같이 호출결과 log가 들어 옵니다.
API TEST 호출내용이 맞는지 확인 부탁드립니다.

<당사 WAS로그결과>
110.76.143.235 110.76.143.235 - - [03/Jul/2018:14:46:10 +0900] "DELETE /keyboard/friend/test HTTP/1.1" 404 -
110.76.143.235 110.76.143.235 - - [03/Jul/2018:14:46:10 +0900] "POST /keyboard/friend HTTP/1.1" 404 -
110.76.143.235 110.76.143.235 - - [03/Jul/2018:14:46:10 +0900] "DELETE /keyboard/chat_room/test HTTP/1.1" 404 -
110.76.143.235 110.76.143.235 - - [03/Jul/2018:14:46:10 +0900] "GET /keyboard/keyboard HTTP/1.1" 404 -

플러스친구:레지나플라워카페
API TEST URL: https://chatbot.zetacube.co.kr/keyboard
감사합니다.

**Comment by plusfriendteam** [comment]
안녕하세요.
위의 로그에서 다음과 같은 부분에 문제가 있어보입니다. 
`110.76.143.235 110.76.143.235 - - [03/Jul/2018:14:46:10 +0900] "GET /keyboard/keyboard HTTP/1.1" 404 -` 
구현해주신 API TEST URL: https://chatbot.zetacube.co.kr/keyboard 를 앱 URL 로 넣어주신 것 같은데요,
해당 앱 URL에서 위와 같이 입력하면 /keyboard API 가 
https://chatbot.zetacube.co.kr/keyboard/keyboard 형태로 들어갑니다. 
따라서 앱 URL 을 https://chatbot.zetacube.co.kr 로 넣어주셔야 정상 동작할 것으로 보입니다. 
참고가 되셨으면 좋겠습니다.
