### ISSUE TITLE
API형에 관한 질문

### ISSUE THREAD

**Issue by secrecy27** [plusfriend/auto_reply#636]
스마트채팅 api형으로 개발하기 위해 테스트 하는 중입니다. 
/message 를 통해서 사용자로부터 온 메시지에 대한 답변을 처리하게 되는데 이 때  반드시 바로 return을 하여야 하나요? 
알아본 바로는 5초정도가 지나면 자동응답 시스템이 응답을 하지 않는다고 하는데 이런 메세지를 보여주지 않고 나중에 답변하게 만들수 있는지 , 더해서 시간이 지난 후에도 고객에게 메세지를 보낼 수 있는 지 궁금합니다.

**Comment by plusfriendteam** [comment]
안녕하세요.
현재로서는 Timeout 시간이 지난 후에 메시지를 보낼 수 없습니다. 
추후에도 사용자 동의 없이 메시지를 임의의 시간에 보낼 경우에 법무적 이슈가 발생할 소지가 있어 해당 기능 추가가 어려워보입니다. 
참고가 되셨으면 합니다. 감사합니다.
