### ISSUE TITLE
이미지 크기 문의

### ISSUE THREAD

**Issue by jhswim01** [plusfriend/auto_reply#639]
이미지 비율을 왜 고정시켜놓으셨나요?

비율 자유자재로 이용할 수 있도록 해주세요. 필수적인 기능이라고 생각합니다.

**Comment by plusfriendteam** [comment]
안녕하세요.
이미지 비율은 카카오톡 대화방에서 가장 알맞게 보이는 비율로 권장하고 있습니다.
권장 비율인 만큼 다른 비율인 이미지로 사용하셔도 괜찮습니다만,
주신 의견을 반영하여 차후에 기능을 추가하도록 검토해보겠습니다.
의견 주셔서 감사합니다.
