### ISSUE TITLE
자동응답 Response

### ISSUE THREAD

**Issue by federer89** [plusfriend/auto_reply#64]
제 서버에 파일 확장자가 붙지 않은 파일 keyboard와 message 총 2개의 파일이 있습니다. 

각 파일에는 아래와 같이 코드가 들어있구요.

> keyboard 
`{
	"type" : "buttons",
	"buttons" : ["#옵션1", "#옵션2", "#옵션3"]
}`

> message
`{
  "text": "안녕하세요.",
  "photo": {
    "url": "https://hello.photo.src",
    "width": 640,
    "height": 480
  },
  "message_button": {
    "label": "반갑습니다.",
    "url": "http://hello.world.com/example"
  }
}`

이렇게 넣었더니 키보드와 #옵션1, #옵션2, #옵션3 버튼은 다 뜹니다. 

여기서 궁금한 질문: 파일 확장자를 넣지 않았는데 어떤 식으로 if statement를 적용하여 keyboard에 있는 옵션을 눌렀을 때 message 파일에 있는 코드가 실행이 될까요?

**Comment by plusfriendteam** [comment]
안녕하세요.
서버의 동작원리부터 저희가 알려드리기 힘든점 양해부탁드립니다.
http://hashcode.co.kr/ 여기를 이용해보시는건 어떨까요?

**Comment by humit0** [comment]
간단한 봇을 구성하고 싶으시다면 https://github.com/humit0/kakao_auto_reply 로 제작을 해보실 수 있습니다. 다만 apache와 php 환경이어야 가능합니다.
