### ISSUE TITLE
메세지 형태 관련 문의

### ISSUE THREAD

**Issue by sookyeomKim** [plusfriend/auto_reply#641]
해당 형태의 메세지 자동응답 api로 가능한가요~?
<img width="282" alt="2018-07-18 1 29 06" src="https://user-images.githubusercontent.com/8381017/42831777-37fbdcce-8a2a-11e8-8c50-6e971bbf9888.png">

**Comment by plusfriendteam** [comment]
안녕하세요.
- 말씀하신 메시지는 카카오톡 비즈메시지(https://bizmessage.kakao.com/) 상품을 통해 이용 가능합니다.
- 또는 추후 오픈될 챗봇 빌더 플랫폼(https://i.kakao.com/openbuilder)에서 지원할 예정입니다. 
- 챗봇 빌더 플랫폼 오픈 시기는 미정이며 그 전까지는 카카오 챗봇 에이전시를 통해 이용 가능합니다. (https://pf.kakao.com/_TsIAE/9233366)
