### ISSUE TITLE
롯데리아 챗봇 같이 위치를 받아와서 지도를 보여주고싶은데 api가 공개가 되어있나요?

### ISSUE THREAD

**Issue by sainteyes73** [plusfriend/auto_reply#642]
아무리 찾아도 이쪽에 대한 정보가 없어서 질문드립니다. 또한 없다면 롯데리아 챗봇은 어떻게 개발되었는지 알고싶습니다

**Comment by plusfriendteam** [comment]
안녕하세요. 말씀하신 스펙은 현재 제휴사를 대상으로 클로즈베타 서비스 중인 
카카오 I 오픈빌더(http://bot-builder.kakao.com/)에서만 제공하는 기능입니다. 
- AI 사업 제휴를 원하시면 해당 사이트에서 제휴제안을 등록해주시거나 
- 카카오 공식 챗봇 에이전시를 통해 이용해주시면 됩니다. (https://pf.kakao.com/_TsIAE/9233366)
- 카카오 I 오픈빌더는 추후 정식 오픈될 예정입니다. (시기 미정)
