### ISSUE TITLE
메시지 이런 형태는 언제 제공되나요?

### ISSUE THREAD

**Issue by berserkyo** [plusfriend/auto_reply#648]
![20180731_163200](https://user-images.githubusercontent.com/24602338/43444774-96aafff6-94df-11e8-8b51-0131f588d8c3.png)

현재 제공하시는 카톡플러스api 는 메시지 형태 아니면 버튼식, 둘중에 무조건 하나만 선택해서
입력을 받게 되어있는것으로 압니다.

위처럼, 메시지 버튼이 챗팅창속에 들어가 있어서  버튼식 +  채팅 기능이 동시에 구현되는 기능은
언제 제공되는지 궁금합니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 말씀하신 스펙은 현재 제휴사를 대상으로 클로즈베타 서비스 중인
카카오 I 오픈빌더(http://bot-builder.kakao.com/) 에서만 제공하는 기능입니다.

AI 사업 제휴를 원하시면 해당 사이트에서 제휴제안을 등록해주시거나
카카오 공식 챗봇 에이전시를 통해 이용해주시면 됩니다. (https://pf.kakao.com/_TsIAE/9233366)
카카오 I 오픈빌더는 추후 정식 오픈될 예정입니다. (시기 미정)
