### ISSUE TITLE
자동응답에 대한 response를 메시지를 보여주고 싶지 않은 경우 처리방법

### ISSUE THREAD

**Issue by ma5so** [plusfriend/auto_reply#65]
안녕하세요.

자동응답 API 사용 시 response 관련 문의사항이 있습니다.
response를 하지 않거나 response에서 {type:text, text:""}으로 text를 빈값으로 전달할 경우
request 데이터를 읽지 않은('1'이 남아있는 상태) 상태로 표시가 됩니다.

request는 읽도록 표시를 하면서 request에 대한 response 메시지는 보여주고 싶지 않은 경우 어떻게 처리하면 되는지 문의드립니다.

그리고 request에 대한 response 응답 대기 time은 몇 초인지도 같이 문의드립니다.

**Comment by plusfriendteam** [comment]
안녕하세요. timout 은 10초입니다.
그리고 response data는 필수입니다.

response data내에 있는 keyboard 정보를 이용하여 사용자의 카카오톡에 어떤 키보드를 표현해줘야 하는지 결정하기 때문입니다.
카카오톡 내에 챗버블이 생성이 되어야지만 키보드가 그려지게 됩니다.
그런데 빈값으로 text를 전달주시면 챗버블을 그릴수가 없기 때문에.. 키보드를 그릴수가 없습니다.

**Comment by ma5so** [comment]
문의드릴때 코드 예를 잘못들었습니다.
키보드 생성이 아니라 아래와 같이 메세지이지만 실제로는 메시지를 사용자 창에 보여주고 싶지 않을 경우 에는 text에 어떤 데이터를 보내야 하는지 입니다.
{  'message':{ 'text' : ''   } }

실제로 빈 값과 띄어쓰기까지 테스트했었는데 사용자에게 메시지가 보여지는 것은 아니었지만,
사용자가 입력한 메시지에 대해서 읽음처리가 되지 않아서 문의드립니다.

**Comment by plusfriendteam** [comment]
실제로 메시지를 사용자 창에 보여주지 않을수가 없습니다.
위에도 말씀드렸지만 메시지 안에 키보드 정보가 있기 때문에 사용자에게 메시지를 돌려주지 않는다면 키보드를 그릴수가 없습니다.

그러므로 사용자에게 메시지를 돌려주는 사항은 필수입니다.
