### ISSUE TITLE
Homekeyboard 에러 415 / 체크 바랍니다.

### ISSUE THREAD

**Issue by Daworks** [plusfriend/auto_reply#652]
접속 URL : https://gangseo.church/api/chatbot/keyboard

테스트해보면  status도 200으로 잘 나오고 반환하는 헤더 정보나 json 문자열도 잘 출력됩니다.
계속 415 오류가 나는데 확인 부탁드립니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 
해당 플러스친구의 이름을 알려주시면 좀 더 상세하게 확인해보도록 하겠습니다.
감사합니다.

**Comment by Daworks** [comment]
플러스친구 이름은 [강서감리교회] 입니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 확인해보니 
플러스친구 관리자센터 > 스마트채팅 > API형 > 앱 등록 > 앱 URL 에 
**https://gangseo.church/api/chatbot/keyboard**  로 등록하셨네요.
/keyboard 는 keyboard API이기 때문에 입력하시지 않으셔도 됩니다. 
**https://gangseo.church/api/chatbot** 로 등록하시면 정상 동작 할 것으로 보입니다. 
감사합니다.

**Comment by Daworks** [comment]
감사합니다. 잘 동작합니다.
