### ISSUE TITLE
카카오I 오픈빌더 API 제공 유무

### ISSUE THREAD

**Issue by emergingmarket** [plusfriend/auto_reply#653]
안녕하세요. 카카오 자동응답 API를 이용해서 다양한 서비스를 개발하고 있는 개발자입니다.

다름아니라 최근 뉴스를 살펴보면..
"한편, 카카오는 이용자들의 일관된 챗봇 이용 경험을 위해 현재 플러스친구 운영자에게 제공하던 ‘자동응답API’의 신규 생성을 오픈빌더 OBT시점에 맞춰 중단할 예정이다. 이 후 오픈빌더로 전환을 독려한 뒤 약 1년 후 API 제공을 종료한다는 방침이다. 자동응답 API는 상담원이 없더라도 자동으로 메시지를 주고 받을 수 있도록 지원하는 개발툴로 다양한 형태로 활용이 가능했으나 개발인력이 없는 상황에서는 제작에 어려움이 있었다."

그렇다면, 카카오I 오픈빌더 API까지 고려하시고 계신지 아니면, 개발 플랫폼 내에서만 적용할 수 있도록 할 예정인지 궁금하네요. 답변 주시면 감사하겠습니다.

**Comment by plusfriendteam** [comment]
오픈빌더 내에서만 생성 및 제작 가능하도록 할 예정입니다. 
(그렇다하더라도 기존 API는 2019년 12월까지는 정상 동작합니다)
자세한 내용은 추후 공지해 드리도록 하겠습니다.
