### ISSUE TITLE
카톡이 현재 모바일버전인지 pc버전인지 알 수 있나요?

### ISSUE THREAD

**Issue by gyurinida** [plusfriend/auto_reply#654]
안녕하세요,

카톡이 모바일인지 pc인지에 따라서 다른 값을 주려고 하는데, 
현재 버전을 알 수 있는 값이 있나요?!

감사합니다!

**Comment by plusfriendteam** [comment]
안녕하세요.
현재로서는 모바일/PC을 구분할 수 있는 값을 내려주지 않고 있습니다.
추후에 기능 추가를 검토해보겠습니다.
감사합니다.
