### ISSUE TITLE
플러스친구 스마트채팅 API형 문의

### ISSUE THREAD

**Issue by sjnam92** [plusfriend/auto_reply#656]
1. API형에서 카카오톡 이모티콘을 사용할 수 있나요? 있다면 방법 안내 부탁드립니다.
2. 사용자가 챗봇과 대화가 끝나고 목록으로 갔다가 다시 상세 대화를 열었을 때, 처음부터 시작이 안됩니다.
처음 시작할 수 있는 방법이 있나요?

**Comment by plusfriendteam** [comment]
안녕하세요. 
1. 현재는 이모티콘을 지원하지 않고 있습니다. 이용에 참고 부탁드립니다. 
2. 대화 후에는 일정 시간 동안(10분) 대화했던 메시지가 유지됩니다. 아래 링크를 참고해주세요.
https://github.com/plusfriend/auto_reply#51-home-keyboard-api  
감사합니다.
