### ISSUE TITLE
카톡 1:1 창구 invoke개발 관련

### ISSUE THREAD

**Issue by seoav99** [plusfriend/auto_reply#66]
현재 자동응답 API를 활용하여 여러가지 응대 시나리오를 연계하는 개발을 해보고 있습니다.
대화 톡창에 사용자가 특정 단어등을 입력하면, 자동으로 1:1 상담원연결 기능으로 이동할수 있게 하고 싶은데 (사용자 굳이 1:1 버튼을 클릭하지 않더라도), 이 부분을 어떻게 처리하면 좋을까요? API 오픈을 할수 있게 되어있는지요?

**Comment by plusfriendteam** [comment]
@seoav99 안녕하세요. 
현재는 해당 기능은 지원하지 않습니다.

앞으로 기능개선에 있어서 고려해보도록하겠습니다.
좋은 의견 감사합니다.
