### ISSUE TITLE
대화방 고유번호에 대해 문의드립니다.

### ISSUE THREAD

**Issue by FKgk** [plusfriend/auto_reply#663]
플러스 친구와 특정 사용자와의 대화방 고유번호를 얻어올 수 있나요?

**Comment by plusfriendteam** [comment]
안녕하세요. 
플러스친구와 특정 사용자와의 대화방은 하나 밖에 없으므로
사용자를 특정하고 싶으신 경우에는 message API 수신시 들어오는 user_key 값을 사용하시면 됩니다.
감사합니다.

**Comment by FKgk** [comment]
그럼 user_key를 이용해서 특정 사용자에게 메세지를 던질 수 있나요?

**Comment by plusfriendteam** [comment]
네, message API 가 호출되면 
user_key 를 사용해서 메시지를 던지고 싶은 상대인지 파악하시고 응답을 보내시면 됩니다.

**Comment by FKgk** [comment]
message API가 호출되지 않고도 특정 사용자에게 메세지를 던질 수 있나요?
