### ISSUE TITLE
자동응답 API에서 전화번호 인증

### ISSUE THREAD

**Issue by saykent** [plusfriend/auto_reply#67]
안녕하세요.
호주 시드니에서 옐로 아이디를 신청했습니다.
옐로 아이디는 정상적으로 만들어 졌고요. 잘 동작합니다.
문제는 자동응답형 API를 사용하려고 하니까 발생하는데요.
전화번호를 등록해서 인증을 받으려고 하니, 한국전화번호밖에 안되네요.
옐로 아이디를 만들때는 국가를 선택할 수 있어서 문제 없이 등록을 했었거든요.
저희가 사용하려고 하는 목적으로 보면 이 부분이 꼭 해결이 되면 좋겠습니다.
어떤 계획을 가지고 계신지 말씀해 주시면 일정을 조정하는데 큰 도움이 될 것 같습니다.
감사합니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 
먼저 이용에 불편을 드린 점 사과드립니다. 현재 옐로아이디의 자동응답 API 인증 전화번호는 한국 전화번호의 등록만을 지원하고 있습니다. 해외 전화번호의 자동응답 API 인증 지원은 빠른 시일 내에는 계획되어 있지 않으나, 하반기의 자동응답 API 기능 고도화 과정에 위 항목의 지원을 포함시켜 빠른 시일 내에 문제없이 이용하실 수 있도록 개선하겠습니다. 
서비스의 개선 의견을 전달해주셔서 감사합니다!

**Comment by plusfriendteam** [comment]
@saykent 저희가 너무 늦었죠? ^^; 해외 전화번호로 인증할 수 있도록 기능이 수정되었습니다. 국가번호와 함께 전화번호를 입력하시면 카카오톡을 통해 인증번호를 받으실 수 있습니다.
