### ISSUE TITLE
플러스친구 이용가이드 처럼  안내가이드 버튼 목록이 들어가 있는 배너 형식

### ISSUE THREAD

**Issue by ggwnags** [plusfriend/auto_reply#673]
![_20180828_121108_1](https://user-images.githubusercontent.com/3987460/44699319-967bbd00-aabe-11e8-8a48-ef7d13e1a5d4.png)
이용가이드 처럼 사용자가 입력해서  배너 안에 버튼 목록이 나오고,
동시에 문구 입력 상태로 서비스 가능하게 할 수 있을까요?

**Comment by plusfriendteam** [comment]
안녕하세요. 
말씀하신 스펙은 현재 제휴사를 대상으로 클로즈베타 서비스 중인
카카오 I 오픈빌더(http://bot-builder.kakao.com/) 에서만 제공하는 기능입니다.

AI 사업 제휴를 원하시면 해당 사이트에서 제휴제안을 등록해주시거나
카카오 공식 챗봇 에이전시를 통해 이용해주시면 됩니다. (https://pf.kakao.com/_TsIAE/9233366)
카카오 I 오픈빌더는 추후 정식 오픈될 예정입니다. (시기 미정)
