### ISSUE TITLE
서비스 이용 문의

### ISSUE THREAD

**Issue by pcappli** [plusfriend/auto_reply#675]
안녕하세요.
현재 서버 응답이 잘 이루어지고 있는 상황입니다만 몇몇 버튼이 작동되지 않고 있어 문의드립니다.

http://yschool.doublehost.net/test.php 여기서 주요일정을 클릭하면 정보가 잘 뜨는 것을 볼 수 있습니다.
최근 서비스 운영을 하면서도 별 문제가 없었습니다.

그런데 언제부터인지는 확인이 되지 않으나 주요일정을 눌러도 아무작동이 되지 않습니다. 심지어 오류도 나오지 않습니다. 이유를 알 수 있을까요?

플러스친구 ID는 '급식몬' 입니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 
알려주신 플러스친구와 사이트를 확인해보았습니다. 
"주요일정" 을 클릭했을 때 response 로 들어오는 json 에 \ufeff 로 공백문자가 포함되어 있습니다. 
json format 이 해당 공백문자로 깨질 수 있습니다.
\ufeff 를 제거하고 "주요일정" 이 잘 돌아가는지 확인해주세요.
혹시 위의 문자를 제거한 후에도 문제가 계속 발생하면 코멘트 달아주시길 바랍니다. 

\ufeff 를 확인하는 방법은 다음과 같습니다. 
![2018-08-30 6 45 33](https://user-images.githubusercontent.com/19848841/44844303-7813ee00-ac85-11e8-991b-b90890717bf8.png)

크롬의 개발자 도구를 사용했을 때, Network 탭에서 위와 같이 해당 API 의 Response 를 확인할 수 있습니다.
\ufeff 가 들어있을 경우 위의 이미지처럼 빨간점이 찍혀있습니다.
참고가 되시길 바랍니다. 감사합니다.

**Comment by pcappli** [comment]
@plusfriendteam 감사합니다. 문제가 잘 해결되었습니다.
