### ISSUE TITLE
카카오톡 플러스 친구 자동응답형 API방식  어플개발 비용 문의

### ISSUE THREAD

**Issue by parkryuk** [plusfriend/auto_reply#677]
관세청 직원입니다. 

저희쪽에서 국민을 대상 홍보차원에서 자동응답형 어플을

개발하고 싶은데 우선 소요비용을 확인하고 싶습니다. 

만약에 개발이 이루어질 경우  소요 기간 및 담당자 연락처를 확인 하고 싶습니다. 

저는 관세청 특수통관과 박력이고 내선 번호는 (042-481-7838, 042-481-7837) 입니다. 

조속한 확인 부탁드립니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 플러스친구팀입니다. 
2018년 12월 오픈빌더 OBT시작과 동시에 기존 자동응답 API의 신규 생성이 중단됩니다. 
따라서 현재로서는 카카오가 선정한 공식 에이전시를 통해 오픈빌더로 챗봇을 제작하시는 것을 권장해드립니다. 

소요 기간 및 비용 또한 카카오 공식 에이전시를 통해 확인하실 수 있습니다. 
자세한 내용 아래 페이지에서 확인해주세요. 
https://brunch.co.kr/@openbuilder/7
