### ISSUE TITLE
사용자에게 photo를 보낼때 로컬 파일(이미지) 전송 가능여부

### ISSUE THREAD

**Issue by DevLeti** [plusfriend/auto_reply#678]
response 예제 코드에 photo는 url을 사용해 사용자에게 전송했는데, 로컬파일을 사용자에게 전송할 수 있나요? 예를들면 제 컴퓨터에 있는 test.png파일을 전송하는 것 입니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 
로컬 파일을 전송하는 기능은 지원하지 않고 있습니다.
온라인에 업로드하여 사용해주세요.
감사합니다.
