### ISSUE TITLE
keyboard Fail 415 에러 입니다.

### ISSUE THREAD

**Issue by leesungsul** [plusfriend/auto_reply#680]
Required*
keyboard Fail 415
wrong keyboard initialization

해당 도메인으로 접속하면 정상적으로 출력됩니다.

플러스친구의 이름은 미래엔챗봇테스트 입니다.

**Comment by plusfriendteam** [comment]
안녕하세요.
알려주신 정보로는 확인이 어렵습니다.
접속하신 도메인 명을 알려주시면 확인해보도록 하겠습니다.
감사합니다.

**Comment by leesungsul** [comment]
넵. 안녕하세요.
도메인 명은 http://devprintbiz.mirae-n.com/keyboard
입니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 상세한 정보 감사드립니다. 
확인해보니 해당 API 의 Content-Type 이 text/html;charset=UTF-8 으로 내려오고 있습니다. 
https://github.com/plusfriend/auto_reply#51-home-keyboard-api 을 참고하셔서 
Content-Type 을 application/json; charset=UTF-8 로 변경해주시길 바랍니다.

또한, 응답값도 json 형식이 아니라 다음과 같이 내려오고 있습니다. 
`{"buttons":[신청, 나의 신청 내역(고객센터)],"type":"buttons"}`

위의 값을 json 형식에 맞춰 아래와 같이 변경해주세요.
`{"buttons":["신청", "나의 신청 내역(고객센터)"],"type":"buttons"}`

위의 내용들 확인 후에도 문제가 지속적으로 발생하면 코멘트 달아주시길 바랍니다.
감사합니다.

**Comment by leesungsul** [comment]
감사합니다. 해결 되었네요.
