### ISSUE TITLE
keyboard 에러입니다

### ISSUE THREAD

**Issue by devGW** [plusfriend/auto_reply#682]
[관리자에게만발송되는 메시지 입니다]사용자 봇서버에 에러가 감지되었습니다.
내용 [wrong keyboard initialization] 

평소에는 오류없이 작동합니다. 그러나 한번씩 사용자에게 버튼이 보이지 않고 잠시 일반 채팅창이 보여집니다. 이때 위의 오류가 전송되고  일반 채팅창으로 사용자가 메세지를 보내게 되면 1:1 채팅이 시작됩니다. keyboard 는 간단한 버튼4개로 구현되어있어 문제될게 없어보이고  일정 시간이 지나면 keyboard 가 다시 생기는데 어디서 문제가 발생하나요?

http://doscm164.dothome.co.kr/keyboard.php  키보드 도메인입니다.

**Comment by plusfriendteam** [comment]
안녕하세요.
해당 도메인을 확인해보니 Content-Type 이 text/html 로 내려옵니다.
https://github.com/plusfriend/auto_reply#specification 을 참고하셔서 
Content-Type 을 application/json; charset=utf-8  로 변경해주시길 바랍니다.
변경 후에도 문제가 계속 되면 코멘트 달아주세요.
감사합니다.

**Comment by devGW** [comment]
application/json; 으로 변경을 하였습니다.
그런데 여전히 플러스친구를 들어갔을때 버튼이 생성되지 않고
사용자가 일반 채팅창에 메세지를 보내면 1:1 채팅으로 보내지게 되고 버튼이 올라옵니다.

[관리자에게만발송되는 메시지 입니다]사용자 봇서버에 에러가 감지되었습니다.
내용 [wrong keyboard initialization]
는 불규칙적으로 발생합니다.

**Comment by plusfriendteam** [comment]
안녕하세요.
아래와 같이 확인해보았을 때 여전히 Content-Type 이 application/json; charset=utf-8 이 아니라 text/html 로 내려고오고 있습니다.

`
$ curl -XGET -i http://doscm164.dothome.co.kr/keyboard
HTTP/1.1 200 OK
Date: Mon, 10 Sep 2018 08:22:35 GMT
Server: Apache/2.2.15 (CentOS)
Content-Length: 146
Connection: close
Content-Type: text/html

        {
            "type": "buttons",
            "buttons": ["학생식당", "교직원식당", "기숙사식당", "정보&문의"]
        }
`

해당 도메인이 맞는지 또는 변경사항이 정상적으로 동작하는지 확인해주시길 바랍니다.
감사합니다.

**Comment by devGW** [comment]
wrong keyboard initialization & requst timeout 에러가 주기적으로 발생합니다.
Content-Type 은 application/json; charset=utf-8 입니다.
