### ISSUE TITLE
content 문의

### ISSUE THREAD

**Issue by JoWonGi** [plusfriend/auto_reply#683]
content 값은 동일하지만 각각의 답변을 하고 싶은데 불가능한가요?

예를 들어
1. 테스트(상위메뉴) ▶ 테스트일(하위메뉴)
2. 안녕하세요(상위메뉴) ▶ 테스트일(하위메뉴)

상위메뉴는 다르지만 하위메뉴는 content 가 동일한 경우는 방법이 없나요?
php 로 개발하고 있는데 세션을 줘도 안 먹히는 것 같내요.
카카오서버에서 버튼이 실행될 때마다 세션을 초기화해서 제 서버로 값이 넘어오나요?

**Comment by plusfriendteam** [comment]
안녕하세요.
현재 세션은 지원하지 않고 있어 user_key를 사용하시는 것이 더 나아보입니다.
이전에 사용자가 클릭 했던 값을 저장하여 구분 하실 수 있을 것 같습니다.
참고가 되시길 바랍니다.
감사합니다.

**Comment by JoWonGi** [comment]
상대방의 user_key 가 암호화가 되어있는데 어떻게 사용하라는거죠?
content 같은 경우에는 입력값이 들어오기에 $content == "테스트" 라고 쓰고 if 문을 돌리면 되는데
user_key 는 사용 못하지 않나요?

**Comment by plusfriendteam** [comment]
안녕하세요. 
user_key 값은 사용자마다 고유한 값으로 생성되기 때문에 
이전에 사용자가 어떤 응답을 보냈는지 저장하여 이후에 들어온 메시지와 비교할 수 있습니다.
전부 저장하는 것이 부담스러우시면 캐시 등을 사용할 수도 있을 것 같습니다.
이용에 참고가 되시길 바랍니다.
감사합니다.
