### ISSUE TITLE
공유기능을 사용해서 플러스친구에게 미디어 타입 파일 전송하는 것이 가능한가요?

### ISSUE THREAD

**Issue by BaroqueCoding** [plusfriend/auto_reply#684]
현재 API형 스마트 채팅에서는 사용자가 + 버튼을 눌러서 서버로 미디어타입 파일을 전송하는 것이 가능하다고 알고 있습니다.
사용자가 다른 카톡방에서 **친구에게 전달 기능**(공유)을 통해 음성메세지나 파일을 전송하는 것이 가능한지, + 버튼을 눌러서 전송하는 것과 차이는 없는지 궁금합니다.

**Comment by JoWonGi** [comment]
다른 카톡방에서 플러스친구한테 공유하기능은 카카오톡으로도 불가능한걸로 알고 있습니다.
카톡방에서 카톡방은 가능한데, 플러스친구한테는 불가능한걸로 알고 있습니다.
