### ISSUE TITLE
user_key 가지고 사용자 정보

### ISSUE THREAD

**Issue by KangGeunSu** [plusfriend/auto_reply#685]
user_key 가지고 사용자 정보를 가지오고 오싶으면
어느 api를 쓰면 되나요??
플러스 친구 관리자 화면에서 찾을수가 없습니다.

**Comment by plusfriendteam** [comment]
안녕하세요.
user_key 가 특정하고 있는 사용자의 상세한 정보는 개인정보 문제가 될 수 있어 제공되지 않습니다.
이용에 참고가 되시길 바랍니다.
감사합니다.

**Comment by KangGeunSu** [comment]
카카오톡 아이디 나 프로필 이름도 못 가져오나요?

**Comment by plusfriendteam** [comment]
안녕하세요.
현재는 user_key 만 제공하고 있습니다. 
아이디 및 프로필 이름은 제공해 드릴 수 없는 점 양해해주시길 바랍니다.
감사합니다.

**Comment by KangGeunSu** [comment]
감사합니다
