### ISSUE TITLE
스마트채팅 API형과 알림톡 API를 혼용해서 사용가능한가요?

### ISSUE THREAD

**Issue by ps2ung** [plusfriend/auto_reply#688]
안녕하세요.

스마트채팅 API형을 이용하고 있는 중에 알림톡 API 서비스를 사용해서 단체 푸쉬를 보내면 
사용자들이 이것을 보고 대화를 시작할 수 있나요?
아니면 새로운 창이 뜨고 읽기 전용으로만 되는 건가요?

**Comment by plusfriendteam** [comment]
안녕하세요.
네, 스마트채팅 사용 중에 알림톡 API도 사용 가능합니다. 
새로운 창은 뜨지 않고 같은 대화방에서 이어서 대화할 수 있습니다.
감사합니다.
