### ISSUE TITLE
[php] 카카오플친 봇 답장 형태 출력 (카드형) 어떻게 하나요? 

### ISSUE THREAD

**Issue by dossa328** [plusfriend/auto_reply#689]
옆으로 넘길수 있게 되어있네요…(카드뷰 기능인듯 한데 …)

봇이 카드뷰 형태로 답장하려면 어떻게 해야하나요?

![](https://devtalk.kakao.com/uploads/default/original/2X/e/e07e909b9a07d5966bf12a7d1b8bd9a122f263a0.jpg)

**Comment by plusfriendteam** [comment]
안녕하세요. 말씀하신 스펙은 현재 제휴사를 대상으로 클로즈베타 서비스 중인
카카오 I 오픈빌더(http://bot-builder.kakao.com/) 에서만 제공하는 기능입니다.

AI 사업 제휴를 원하시면 해당 사이트에서 제휴제안을 등록해주시거나
카카오 공식 챗봇 에이전시를 통해 이용해주시면 됩니다. (https://pf.kakao.com/_TsIAE/9233366)
카카오 I 오픈빌더는 추후 정식 오픈될 예정입니다. (시기 미정)
