### ISSUE TITLE
Home Keyboard API 관련 문의

### ISSUE THREAD

**Issue by yhkong** [plusfriend/auto_reply#69]
안녕하세요.
네무스텍 공윤희입니다.

현재 서버에서 정보 변경 후에 자동응답 API 설정에서 API 테스트 버튼 클릭시 정상적으로 나오는데

카카오톡 앱에서 확인시 키보드 업데이트가 되지 않는 문제가 있습니다.

안드로이드에서 10분 이후에 대화방에 진입해도 키보드 업데이트가 되지 않고 있습니다.

확인 부탁드립니다.

**Comment by plusfriendteam** [comment]
안녕하세요. 테스트하신 프로필 명을 알려주시면 확인해드리겠습니다.

**Comment by yhkong** [comment]
"서울시" 입니다.

**Comment by plusfriendteam** [comment]
@yhkong 조치를 처했으니 다시한번 확인 부탁드립니다. =)

**Comment by yhkong** [comment]
정상적으로 동작하는 것 확인했습니다.
감사합니다.
