### ISSUE TITLE
에러가 발생했을 때의 저희 서버의 응답 내용을 알 수 있을까요?

### ISSUE THREAD

**Issue by pcappli** [plusfriend/auto_reply#692]
안녕하세요.
에러가 발생했을 때의 저희 서버의 응답 내용을 알 수 있을까요?

카카오톡 아이디 : 급식몬
오류 발생시기 9월 11일 화요일 오후 10시 00분

내용 : [잘못된 응답입니다. response is not OK(200) : 500 / Internal Server Error]

그리고 저희가 타 서버에서 내용을 파싱해 오고 있다보니 응답까지 시간이 다소 소요되는 경우가 있습니다. 응답 지연시간을 늘려주실 수 것을 건의해 드립니다. (10초라도 좋을 것 같습니다.)

**Comment by plusfriendteam** [comment]
안녕하세요.
에러 내용 확인해보니 해당 시간에는 별다른 응답없이 500 status code (Internal Server Error) 만 내려왔습니다.

응답시간에 관해서 의견 주셔서 감사합니다.
하지만 공지드린대로 현재 자동응답 API 는 종료 예정(19년 12월)이라 기능 변경 및 추가는 어려워보입니다.
이용에 참고해주시기 바랍니다.
감사합니다.
