### ISSUE TITLE
추후에 오픈빌더형도 API 지원되나요~? 유료라도 직접 스마트채팅처럼 자체서버로 하고싶어서요

### ISSUE THREAD

**Issue by deasung** [plusfriend/auto_reply#697]
추후에 오픈빌더형도 API 지원되나요~? 유료라도 직접 스마트채팅처럼 자체서버로 하고싶어서요

궁금해서 이렇게 남깁니다

**Comment by plusfriendteam** [comment]
안녕하세요. 플러스친구입니다. 
오픈빌더 표준에 맞는 API형의 블록 개발은 지원될 예정입니다. 
감사합니다.
