### ISSUE TITLE
신규서비스 오픈빌더에 대한 문의

### ISSUE THREAD

**Issue by netstep21** [plusfriend/auto_reply#698]
안녕하세요
현재 자동응답API를 통해 챗봇서비스를 하고 있는 (주)넥스트스텝입니다.
오픈빌더를 11월달에 오픈한다고 공지를 보았습니다.
궁금한점이 있어서 질문을 드립니다.
1. 공식 에이전시를 통해서만 개발할수 있는건가요? 현재처럼 OPEN API형태로는 제공하지 않는지 궁금합니다.
2. 유료화한다고 하는데 저희업체는 자체적인 챗봇엔진을 구성해서 사용하고 있습니다. 그런경우에도 비용이 발생하나요?
3. 만약에 비용이 발생한다고 하면 금액은 어느정도선이 될지 궁금합니다.
 
문의에 대한 답변 부탁드리겠습니다.

감사합니다.

**Comment by plusfriendteam** [comment]
1. 오픈빌더 CBT는 카카오가 선정한 공식에이전시(https://pf.kakao.com/_TsIAE/9233366)를 통해 제작/참여 하실 수 있습니다. 기존 제작한 API 챗봇은 2019년 12월까지 그대로 사용하실 수 있으나, 신규 생성은 불가합니다.

2. CBT 기간 동안에 카카오는 오픈빌더 플랫폼 및 챗봇의 사용요금을 받지 않습니다. 다만, OBT 이후에는 유료화 될 수 있으며 이는 OBT 이전에 공지사항 등을 통해 별도로 안내 될 예정입니다."

3. 에이전시와 파트너간의 계약 및 의뢰 내용에 따라 챗봇 제작 비용은 모두 상이하므로 자세한 비용은 각 에이전시 (https://pf.kakao.com/_TsIAE/9233366)에 문의 부탁드립니다.
