### ISSUE TITLE
해당 프로필의 자동응답 시스템이 응답하지 않습니다.

### ISSUE THREAD

**Issue by devgoodway** [plusfriend/auto_reply#705]
해당 프로필의 자동응답 시스템이 응답하지 않습니다. 메세지만 출력됩니다.

```
<?php
    $data = json_decode(file_get_contents('php://input'), true);
    $content = $data["content"];
    if($content == "메뉴1")
    {
            echo '
                {
                    "message" :
                    {
                        "text" : "메뉴1을 선택하셨습니다."
                    },
                    "keyboard" :
                    {
                        "type" : "buttons",
                        "buttons" : ["메뉴1"]
                    }
                }';
    }
?>
```

http://devgoodway.cafe24.com/bmrbus/kakao/message.php
플러스 친구 아이디 : bmrbus

**Comment by plusfriendteam** [comment]
안녕하세요. 
해당 API 를 아래와 같이 사용했을 때, Content-Type 이 text/html; charset=UTF-8 으로 내려옵니다.
Content-Type을 application/json; charset=utf-8 으로 변경해주시길 바랍니다.
변경 후에도 문제가 지속되면 코멘트 달아주세요. 감사합니다.

$ curl -XPOST http://devgoodway.cafe24.com/bmrbus/kakao/keyboard.php/message -d '{"type": "text", "content": "test"}' -i
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 15 Oct 2018 05:06:39 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 70
Connection: keep-alive
X-Powered-By: PHP/7.0.0p1

    {
        "type": "buttons",
        "buttons": ["메뉴1"]
    }
