### ISSUE TITLE
옐로아이디 특정 고객 또는 전체 고객에게 자동화된 메시지를 보낼 수 있는 방법이 있을까요?

### ISSUE THREAD

**Issue by tommy-dokgo** [plusfriend/auto_reply#72]
안녕하세요.

 옐로아이디 특정 고객 또는 전체 고객에게 자동화된 메시지를 보낼 수 있는 방법이 있을까요? 사용자가 신청한 상품의 가격 하락 알림 등의 사용 시나리오를 생각하고 있습니다.

 자동응답 API는 ARS를 구현한 것으로 사용자의 요청이 있을때만 메시지 전송 등이 가능한 것으로 이해하고있는데, 카카오톡 고객센터에서 계속 이곳으로 문의하라고하여 문의 남겨봅니다.

 답변 부탁드립니다.
 감사합니다.

**Comment by plusfriendteam** [comment]
이해하신바와 같이 현재 제공중인 자동응답 API는 ARS와 같은 성격입니다.
문의주신 기능을 구현하기 위해서는 비즈메시지 API를 이용하셔야 합니다.
자세한 내용은 [카카오톡 비즈메시지](http://bizmessage.kakao.com/main)의 상품소개서를 참고해주시기 바랍니다. 
http://bizmessage.kakao.com/main
