### ISSUE TITLE
사용자 응답의 Keyboard 타입을 객관식 응답과 주관식 응답을 동시에 사용할 수 있나요?

### ISSUE THREAD

**Issue by banbanmumani** [plusfriend/auto_reply#728]
안녕하세요.

사용자 응답에 keyboard 타입을 buttons로 선택 하면 다음과 같이 화면이 나오는데

<img width="374" alt="image" src="https://user-images.githubusercontent.com/33125793/48178359-6e30fa00-e35c-11e8-9463-5ad185dc6058.png">

buttons와 text 를 동시에 사용하는 경우가 있어서

<img width="443" alt="image" src="https://user-images.githubusercontent.com/33125793/48178295-2a3df500-e35c-11e8-95e3-2e6a5178afb7.png">
다음과 같이 keyboard 타입을 text 와 buttons 를 동시에 사용하려면 어떻게 해야 하는지 궁금합니다.

**Comment by plusfriendteam** [comment]
안녕하세요.
화면으로 보여주신 플러스친구는 스마트채팅 > API 형 이 아닌 스마트채팅 > FAQ 형 입니다. 
현재 API 형은 해당 keyboard 타입을 지원하지 않고 있습니다. 
이용에 참고하시길 바랍니다. 감사합니다.
