### ISSUE TITLE
관리자 메세지 문의

### ISSUE THREAD

**Issue by infobankimedia** [plusfriend/auto_reply#73]
안녕하세요. 인포뱅크 김지황입니다.

해당 메세지가 주기적으로 수신되고 있습니다.

![default](https://cloud.githubusercontent.com/assets/19382791/17685012/44e91648-639b-11e6-8c08-7ff5c6fb0947.PNG)

수신쪽 로그를 확인 해도, 특이사항이 보이지 않습니다.

간헐적으로 keyboard 를 호출 하여 체크하는 로직인거 같은데,
해당 메시지가 발생하는 원인 확인 부탁드립니다.

플러스친구 ID : @kbscoolfm

감사합니다.

**Comment by plusfriendteam** [comment]
해당 메세지가 발생하는 경우는 타임아웃, 200 OK가 아닌 경우, 적절히 못한 json 리턴 등입니다.
평소에 잘 동작하다가 간혹 발생하는 경우라면 아마도 타임아웃이 가장 유력한 원인이 아닐까 싶네요.
