### ISSUE TITLE
앱 등록 문의

### ISSUE THREAD

**Issue by thehyundai** [plusfriend/auto_reply#74]
안녕하세요.

자동응답 API 사용을 위한 앱 등록에 어려움이 있어 질문드립니다.

스프링 기반으로 구현할 예정인데 document를 보니 주소 연동 패턴이 REST 방식인 것 같습니다. 스프링의 기본인 .do 주소로는 앱 등록이 불가능한지요? 저희쪽 사이트는 항상 주소 요청 방식이 .do로 끝납니다. 앱 등록을 위해 주소를 입력하니 API TEST 버튼을 누르니 아래와 같은 메시지가 나옵니다.

Required*
Initialize Api test : Fail 500 : wrong keyboard initialization

혹시 스프링 기반으로는 주소 등록의 대안이 있는지요?

옐로아이디는 **@the패셔니스타**입니다.

답변 부탁드립니다.

**Comment by plusfriendteam** [comment]
.do 형식으로 끝나도 상관은 없습니다.
해당 메세지는 [Home Keyboard Api](https://github.com/plusfriend/auto_reply#51-home-keyboard-api) 문서를 참고하세요.
