### ISSUE TITLE
API TEST 관련 문의 드립니다.

### ISSUE THREAD

**Issue by Cafri** [plusfriend/auto_reply#75]
API를 테스트 했을시

Initialize Api test : Fail 200 : wrong keyboard initialization

위와 같은 에러가 나는데 어느부분의 문제일련지요.

테스트를 하는 프로필은 "Hide_Bot" 입니다.

**Comment by plusfriendteam** [comment]
[Home Keyboard Api](https://github.com/plusfriend/auto_reply#51-home-keyboard-api) 문서를 참고하세요.
