### ISSUE TITLE
원인을 알수없는에러

### ISSUE THREAD

**Issue by Coder-Iro** [plusfriend/auto_reply#754]
현재 시간표를 표시해주는 챗봇을 개발하였는데 응답부분에서 인코딩오류로보이는 오류가 발생하여서 원인을 알고싶습니다. 플러스친구 이름은 금촌중 2-7 자동응답기 입니다.

**Comment by plusfriendteam** [comment]
안녕하세요.
현재 해당 API 에 header 로 Content-Type: application/json 이 들어오고 있습니다.
Content-Type: application/json; charset=utf-8 로 변경해주시길 바랍니다.
수정 후에도 여전히 문제가 발생한다면 코멘트 달아주세요.
감사합니다.

**Comment by doohee1001** [comment]
바꿨더니 오류메시지조차 출력되지 않습니다. 응답은 없고요

**Comment by plusfriendteam** [comment]
안녕하세요.
아래와 같이 확인해보니 다음과 같은 응답이 나옵니다.

$ curl -XPOST http://nanobot.tk:5000/message -H "Content-Type:application/json; charset=utf-8" -d '{"content": "시간표📚"}' -i

HTTP/1.0 200 OK
Content-Type: application/json; charset=utf-8
Content-Length: 104
Server: Werkzeug/0.14.1 Python/3.6.7
Date: Fri, 11 Jan 2019 02:08:02 GMT

{"text": "2019년 1월 11일 시간표\r\n1교시 : 창체 (오경*)\r\n2교시 : 창체 (오경*)\r\n"}

해당 응답은 아래 링크의 스펙과 차이가 있어보입니다. 
https://github.com/plusfriend/auto_reply#52-메시지-수신-및-자동응답-api  
위의 링크를 참고하셔서 응답 형식을 수정해주시기 바랍니다.
수정 후에도 문제가 발생하면 코멘트 달아주세요.
감사합니다.
