### ISSUE TITLE
"자동응답 API"로 사용자가 한개의 검색어를 입력하면 여러개의 검색결과 URL 을 보낼 수 있나요?

### ISSUE THREAD

**Issue by esummer9** [plusfriend/auto_reply#76]
1. 사용자가 검색어를 입력하면 
2. 검색결과를 목록형태로 여러 표현 

이 가능할까요?

**Comment by plusfriendteam** [comment]
한 개의 메세지에 1000자 이내로 목록으로 답변을 주시면 됩니다.
사용자 검색어 하나에 여러개의 메세지를 보내는 것은 2016년 8월 현재로서는 구현하실 수 없습니다.
