### ISSUE TITLE
친구 추가가 되어 있는 사람에게 자동으로 메시지 전송

### ISSUE THREAD

**Issue by parkwookjin** [plusfriend/auto_reply#77]
안녕하세요. 다름이 아니라 궁금한 점이 있어서 글남깁니다.

자동응답이 아닌 친구 추가가 되어 있는 사람에게 특정시간대에 자동으로 제 서버DB의 내용을 전송하는

API가 있나요?

아래에 비슷한 게시글에서 카카오톡 비즈메시지를 사용하면 된다고 하는데 다른 방법은 없는건가요?

수고하세요!!

**Comment by plusfriendteam** [comment]
현재로선 비즈 메세지 말고 다른 방법으로는 해당 기능을 구현하실 수 없습니다. ^^;
