### ISSUE TITLE
message 응답 메시지로 글씨색을 지정해줄수는 없나요?

### ISSUE THREAD

**Issue by myeonguni** [plusfriend/auto_reply#78]
안녕하세요. 좋은 서비스를 제공해주셔서 감사합니다.

Q : message 응답 메시지로 글씨 색을 지정해줄수는 없나요?
혹시 방법이 있다거나 관련된 추후 계획이 있으면 알고싶어서요.

@명우니닷컴-맞춤법검사기

**Comment by plusfriendteam** [comment]
해당 기능은 제공하고 있지 않습니다. 앞으로의 계획도 현재로선 없는 상태입니다. :-)
