### ISSUE TITLE
응답오류 (무응답 / 응답지연)

### ISSUE THREAD

**Issue by samko635** [plusfriend/auto_reply#79]
안녕하세요, 

오늘 오후 5시경부터 일부 계정에 대한 응답지연 및 무응답 장애가 나고있어 문의 드립니다. 

아래는 문제가 되는 계정리스트입니다.
@lgcns_order (Plus friend)
@lgcnsorder (Yellow id)
@lg신상주문 (Yellow id)
@lg간편주문 (Yellow id)

원인 확인 부탁드립니다.

**Comment by infobankimedia** [comment]
해당 이슈 관련하여, 방송 및 라디오 관련 플러스 친구도 확인 부탁드립니다.
CBS 라디오, KBS 라디오, 극동방송, MNET, 보니하니 등이 있습니다.
빠른 확인 부탁드립니다.
현재 해당 방송은 생방송 진행 중인 서비스 입니다.

**Comment by gwuijeonglim** [comment]
GS홈쇼핑, CJ오쇼핑 플러스 친구에서도 동일 이슈입니다.
2시간 가량 동일 현상이 지속되고 있습니다.
언제 복구되는 건가요?

**Comment by plusfriendteam** [comment]
안녕하세요.
오늘 5시경부터 서버 장애가 발생하여 
1:1대화, 자동응답 등 응답이 지연되는 현상이 발생하였고
7시경 복구되었습니다. 불편을 드려 대단히 죄송합니다.
