### ISSUE TITLE
메세지 응답 보낼때 사진을 여러장 보낼 수 있나요?

### ISSUE THREAD

**Issue by restart916** [plusfriend/auto_reply#8]
{
  "message": {
    "text": "귀하의 차량이 성공적으로 등록되었습니다. 축하합니다!",
    "photo": {
      "url": "https://photo.src",
      "width": 640,
      "height": 480
    },
}

현재 예시에서 보면 위와 같이 사진을 url로 1개 포함 할 수 있는데

혹시 여러개를 동시에 보낼 수 있나요?

아니면 1개 메세지에 대한 응답을 여러번 할수 있는 방법은 없나요?

(사진 + 텍스트) 구조의 응답을 여러개 해주고 싶은데 방법이 없는지

혹시 기능추가가 될 계획은 있는지 문의드립니다

**Comment by suya55** [comment]
@restart916 안녕하세요. 
현재는 하나의 메시지에 하나의 사진만 전송이 가능합니다.
차후 API가 차차 업그래이드 되면 여러장 전송 기능도 고려하고 있습니다.

다른 대안으로는,

사실 꼼수인데요..
1. [옐로 아이디 어드민 페이지>전체메시지>메시지전송>이미지앨범형](https://yellowid.kakao.com/messages_v3/image/create)을 선택하셔서 메시지를 작성합니다.
2. 임시저장 버튼을 눌러서 저장을 합니다.
3. [메시지목록](https://yellowid.kakao.com/messages_v3/listMessage)으로 이동하셔서 방금 임시저장한 메시지를 불러옵니다.
4. 그럼 미리보기 하단에 링크가 하나 표시됩니다. 
5. 그 링크를 자동응답 메시지에 버튼링크로 보내시면 이미지 앨범형으로 사용하실 수 있습니다.

**Comment by restart916** [comment]
아 아래 알려주신 방법으로는 그럼 url방식의 이미지는 힘든거죠? 
앨범에 고정된 이미지를 미리 세팅해야되는거 같아서

그때그때 상황에 맞는 이미지url 들의 조합으로 메세지를 전송해주고 싶은데
다른 방법이나 차후에 업데이트가 되길 기다려야 겠네요

감사합니다

**Comment by suya55** [comment]
@restart916 네 동적으로 생성되는 이미지셋을 전달하기는 힘듭니다.
다만 비슷한 방식으로 링크 버튼에 "이미지확인하러가기" 이런식으로 버튼의 랜딩 페이지가
여러장의 이미지를 확인할 수 있는 페이지로 꾸미시면 될 것 같습니다.
