### ISSUE TITLE
자동응답 API 무응답

### ISSUE THREAD

**Issue by nemusheewon** [plusfriend/auto_reply#80]
안녕하세요. 네무스텍 정희원입니다.

현재 자동응답 API 설정된 플친(버버리, 디펜드)에서 

타 API(키보드, 친구 추가/차단, 방 나가기)는 정상적으로 서버에 Request가 들어오는데

현재 메시지수신 API는 정상적으로 동작하고 있지 않습니다. 

확인 부탁 드립니다.

**Comment by thugjong** [comment]
안녕하세요. 오늘 서버 장애로 인해 자동응답,1:1대화의 응답이 지연되었습니다.
현재 정상화되었으니 확인 부탁드립니다.
불편을 드려 대단히 죄송합니다.

**Comment by plusfriendteam** [comment]
안녕하세요.
오늘 5시경부터 서버 장애가 발생하여 
1:1대화, 자동응답 등 응답이 지연되는 현상이 발생하였고 7시경 복구되었습니다. 
불편을 드려 대단히 죄송합니다.
