### ISSUE TITLE
카카오톡 자동응답 text 길이제한문의

### ISSUE THREAD

**Issue by JoonyoungYi** [plusfriend/auto_reply#81]
전국대학 학식서비스를 봇으로 운영중인 @밥대생 입니다.
카카오톡 자동응답 api에 text 길이 제한이 있나요? 
제 폰에서는 긴 text가 잘 나오는데, 한 유저분께서 텍스트가 잘려서 나오는 걸 캡쳐떠서 보내주셔서요...

현재 400자를 초과하는 긴 text와 link를 자동응답으로 보내고 있습니다. 
감사합니다.

**Comment by plusfriendteam** [comment]
최대 1000자 까지만 지원하고 있습니다.
다음 문서를 참고해주세요.
https://github.com/plusfriend/auto_reply#62-message
