### ISSUE TITLE
시작할때 keyboard request가 원래 이렇게 많이오나요?

### ISSUE THREAD

**Issue by banatic** [plusfriend/auto_reply#83]
옐로아이디 관리페이지에서 자동응답 시작하기 누르면 순간적으로 114개의 GET이 들어오네요
API TEST할때나 실제 카톡으로 채팅방에 들어올때는 1번씩만 정상적으로 들어오는데..
원래  그런건가요?

거기다가 시작할때만 [wrong keyboard initialization] 메세지가 오네요
서버로그보면 오는응답엔 다 처리를 한거같은데 왜그럴까요?

**Comment by plusfriendteam** [comment]
해당 요청은 대화방에 진입을 할 때 마다 호출됩니다.
제 추측으로는 자동응답을 시작하자마자 114명이 챗방에 진입을 했을 수도 있겠네요. ^^;
[wrong keyboard initialization] 에러는 키보드 요청을 하였을 때 타임아웃이 나거나 200 OK가 아니거나 적절한 JSON 포맷이 아닐 경우 발생하는데, 시작 할 때 요청이 몰려서 타임아웃이 나지 않았을까 합니다.
저희쪽에서도 응답 처리를 못하는 경우가 없는지 확인 해 보도록 하겠습니다.
