### ISSUE TITLE
[wrong keyboard initialization] 에러 메시지 관련 문의

### ISSUE THREAD

**Issue by nemusheewon** [plusfriend/auto_reply#84]
봇서버 에러 메시지 관련해서 문의 드립니다. 

현재 진행되는 이벤트가 없어서 사용자 요청이 많거나 서버 작업을 진행하지 않고 있는데

"아모레퍼시픽백화점" 플친에서 금일 새벽에 계속 아래 오류 메시지가 계속 발생중에 있습니다. 

사용자 봇서버에 에러가 감지 되었습니다.
내용:[wrong keyboard initialization]

서버 로그를 살펴 보니 키보드 응답일 잘못되거나 응답이 늦은 경우가 없어서 

혹시 저희쪽 봇서버에서 어떤 잘못된 응답을 주어서 발생하는지 

확인 가능하시다면 부탁 드리겠습니다.

**Comment by plusfriendteam** [comment]
안타깝지만 구체적인 오류 내용은 지금은 확인이 불가능합니다. ㅠ

**Comment by nemusheewon** [comment]
@plusfriendteam 
위 이슈를 드렸을 때는 아마도 지진여파로 평상시보다 많이 발생한 것인 같은데요.
지난주에 발생한 것만 확인이 불가능한 것인가요?

해당 이슈는 평상 시에도 간헐적으로 수신되는 메시지 입니다. 
평상 시에 발생하는 오류도 확인이 불가능한가요?

**Comment by plusfriendteam** [comment]
@nemusheewon 구체적인 에러를 알 수 없는 이런 상황이 얼마나 답답한 상황일지 개발자로서 공감이 됩니다. ㅠㅠ
앞으로는 문의하지 않으셔도 답답함 없이 확인하실 수 있도록 오류에 대한 안내를 좀 더 보강할 예정입니다.
조금만 기다려주세요. ^^;
