### ISSUE TITLE
전화 입력시 오류

### ISSUE THREAD

**Issue by outdoorinterlaken** [plusfriend/auto_reply#85]
스위스 회사입니다. 카카오플러스를 사용 중에 API형을 가입하려 했으나 한국어 핸드폰 번호만 지원합니다.
해외 스위스 번호도 사용 가능한가요. 번호는 단지 *모니터링 메시지 발송을 위한 용도로 사용됩니다.
라고 뜹니다.

**Comment by plusfriendteam** [comment]
지금은 지원하고 있지 않습니다.
하지만 곧 지원할 예정이니 조금만 기다려주세요. ^^;

**Comment by plusfriendteam** [comment]
@outdoorinterlaken 너무 오래 기다리셨네요. 해외 번호로 인증받을 수 있도록 수정되었습니다. 국가번호와 함께 전화번호를 입력하시면 카카오톡으로 인증번호를 받으실 수 있습니다.
