### ISSUE TITLE
초기 keyboard Initialize 질문드립니다.

### ISSUE THREAD

**Issue by seyup** [plusfriend/auto_reply#86]
초기 keyboard를 호출 하게끔 구현을 하였습니다.

앱 설정에서 테스트를 해보니 세팅값이 나오긴하는데

Initialize Api test : OK 404: {"type":"buttons","buttons":["aaa","bbb"]}

이런식으로  OK 404(정상적으로는 OK 200)가 나오는데요 원인을 알수있을까요?

이름은 @BakePriceTime 입니다.

**Comment by plusfriendteam** [comment]
@seyup 저희쪽 프론트에 버그가 있었네요. ㅠ
테스트 잘 통과된 것으로 보입니다. ^^
