### ISSUE TITLE
Restful API 관련

### ISSUE THREAD

**Issue by JBJang** [plusfriend/auto_reply#87]
혹시 옐로아이디 자동응답 Restful API에서 상담원연결 기능이 추가될 예정이 있는지
알고싶습니다

**Comment by plusfriendteam** [comment]
안녕하세요. 
문의주신 내용은 상담톡이라는 서비스를 통해서 이용하실 수 있을 듯 한데요,
서비스 오픈이 예정되어 있어 관심있으시다면, help.bzm@kakaocorp.com로 연락 부탁드립니다.
https://bizmessage.kakao.com/
