### ISSUE TITLE
파터너 서버 미응답시 에러 메시지 문제 

### ISSUE THREAD

**Issue by SeoktaeKang** [plusfriend/auto_reply#9]
안녕하세요.
자동응답API로 톡주문 서비스를 개발하는 LG CNS 강석태 차장입니다.

키보드 확인 API를 호출하는 시점에 파트너사의 서버가 재기동하거나 또는 다른 원인으로 인해 키보드 확인에 대한 응답을 줄 수 없는 경우에 아래와 같이 에러메시지가 표시가 됩니다.

현 에러 메시지: 

자동응답 설정이 잘못되어 오류가 발생하고 있습니다. 설정을 다시한번 확인해주세요.
response is not OK(200) : 503 /Service Unable
 

이와 같은 메시지는 사용자에게 노출될 메시지로 적절하지 않아 다른 안내 메시지로 변경되어야 할 것 같습니다.

확인 부탁 드리겠습니다.

감사합니다.

**Comment by suya55** [comment]
@SeoktaeKang 안녕하세요. 

위 메시지는 봇서버의 관라자에게만 전달되는 메시지 입니다. 유저에게는 

> 자동응답 시스템이 응답을 하지 않습니다. 문제가 보고되어 처리 예정입니다. 다음에 다시 시도해주세요.

이러한 형태의 메시지가 발송됩니다.

감사합니다.

**Comment by SeoktaeKang** [comment]
안녕하세요..
저희 개발쪽에서 테스트해본 결과 해당 메시지가 사용자에게 보여지고 있어서 문의 메일 드리게 되었습니다.
여기에 이미지를 등록할 수가 없어서 올릴 수가 없네요. 

저희가 테스트한 계정은 LG신상주문 계정입니다.

다시한번 더 확인 부탁 드립니다.

**Comment by suya55** [comment]
@SeoktaeKang 에러 메시지를 받은 유저의 전화번호 또는 카카오톡 계정 번호를 알려주시면 확인해드리겠습니다. castor.k@kakaocorp.com 으로 메일 주십시오.

**Comment by suya55** [comment]
@SeoktaeKang 안녕하세요. 
확인해본 결과 전달해주신 전화번호는 옐로아이디 관리자 설정에서 관리자로 등록된 전화번호로 확인됩니다.

![image](https://cloud.githubusercontent.com/assets/955914/15664355/f7ebd658-273d-11e6-9c62-4b5c46d82a26.png)


위 화면에 전화번호를 등록하면 봇 관리자로 등록되며
관리자로 등록될시 문의 주신 내용의 메시지가 전달됩니다.

다시 말씀드리지만 일반유저에게는 

> 자동응답 시스템이 응답을 하지 않습니다. 문제가 보고되어 처리 예정입니다. 다음에 다시 시도해주세요.

라는 메시지가 전달됩니다.

감사합니다.
