### ISSUE TITLE
API TEST 가 안되네요

### ISSUE THREAD

**Issue by taehyongi** [plusfriend/auto_reply#90]
테스트로 만들어보고 있습니다.(@아름봇)  keyboard api페이지를 만들고 

앱 등록하고 API TEST 를 클릭하면 메세지가 나오는게 아니고 크롬에서는 그냥 빈화면으로

순간적으로 전환되어 버리네요..

오류 메세지조차 확인이 안되는데 제가 먼가를 잘못했을까요?

![image](https://cloud.githubusercontent.com/assets/6735863/18903535/b786e28c-8594-11e6-8c02-aeefc5f17b99.png)

**Comment by taehyongi** [comment]
제가 너무 무지한 질문을 올린걸까요? -.- 아시는분 계신가요?

**Comment by plusfriendteam** [comment]
Api test 후 에러 내용을 표시할 때 봇에서 내려주는 에러메세지를 표시해주는데 그때 문제가 생겨서 말씀해주신 오류 현상이 나타나게 되었습니다.
조만간 패치를 하도록 하겠습니다.
