### ISSUE TITLE
옐로우아이디 동적답변, php 파싱 질문.

### ISSUE THREAD

**Issue by tandemsoft** [plusfriend/auto_reply#91]
테스트라는 버튼을 만들고 눌렸을때 아래 php소스가 실행됩니다
그런데 한번이라도 서버에서 php파일을 수정하게되면 옐로아이디가 읽지 못합니다;
옐로아이디에서 아무런 반응이 없다 이말이지요.

오늘날씨를 알려주는 봇을 만들려고하는데요..

<?php
// content : 테스트
use \kakao\Msg;
use \kakao\Msg\Message;
use \kakao\Keyboard;

$url="http://weather.naver.com/rgn/townWetr.nhn?naverRgnCd=08290530";
$ch=curl_init();
curl_setopt($ch, CURLOPT_URL, $url); //연결
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); 
$result=curl_exec($ch);
curl_close($ch);

// 날씨몸통 파싱
$fparsing=explode("<th scope=\"col\">",$result); 
$sparsing=iconv("UTF-8", "EUC-KR", $fparsing[1]); 

// 오늘 오전 날씨 파싱
$todayw1=explode("<span class=\"temp\">",$sparsing);
$todayw2=explode("</span>",$todayw1[1]); // 최종결과 오늘날씨 온도

echo new Msg(
	new Message(
		"테스트에요..".$todayw2[0], // 출력 그런데 옐로아이디에서 아무런 답변, 응답이없음;
		NULL,
		NULL
	),
	TRUE
);

문제 해결방법이 있을까요 ?

**Comment by plusfriendteam** [comment]
구현에 문제가 있으신 부분에 대해서는 저희가 답변해 드릴 수 있는 문제는 아닌것 같네요. ^^;
