### ISSUE TITLE
api test 시 403 에러

### ISSUE THREAD

**Issue by iBNeer** [plusfriend/auto_reply#92]
@이노씨앤 입니다.

Required*
Initialize Api test : OK 200: {"type":"text"}
Optional
Friend add Api test : OK 200: 
Friend block Api test : Fail 403 :
Forbidden
You don't have permission to access /kakao/friend/test on this server.

Chatroom leave Api test : Fail 403 :
Forbidden
You don't have permission to access /kakao/chat_room/test on this server.

이렇게 표출됩니다.
어떤 조치를 해야할까요

**Comment by plusfriendteam** [comment]
에러메세지 그대로 403에러가 났네요.
유저가 차단하거나 대화방 나가기를 한 경우에 대한 처리가 따로 필요 없으시다면 해당 테스트 항목은 통과하지 못해도 괜찮습니다.

**Comment by iBNeer** [comment]
다른서버에서 정상 작동하는 파일을 현재 적용하려는 서버에 그대로 옮겼는데
keyboard 까지는 이상이 없으나
message 는 전혀 반응하지 않아 더이상 진행이 불가능한 상태입니다...
