### ISSUE TITLE
자동응답 API로 들어온 메시지를 admin에서 볼 수 있는 UI가 있나요?

### ISSUE THREAD

**Issue by cymonn** [plusfriend/auto_reply#93]
_**YellowID @카닥부품**_

안녕하세요. 자동응답 API를 통해서 개발중인데요,
제가 만든 옐로아이디 앱에 친구추가를 해서 메시지를 입력하면 자동응답 API를 통해서 서버로 잘 들어오고, 제가 보낸 response가 유저앱에 잘 보여지는 것은 확인을 했습니다.

다만, 이렇게 받고 보낸 메시지들을, admin입장에서 어딘가에서 확인을 할 수 있어야 할 텐데 1:1 대화가 아니면 확인할 수 있는 UI가 없는 것 같아서요. 아님 제가 못 찾고 있는 것인지..
현재 없다면 혹시 개발 계획이 있나요?

**Comment by plusfriendteam** [comment]
@cymonn 통계만 제공중이며 전체 내역 조회를 위한 UI는 검토해 보겠습니다.
