### ISSUE TITLE
플러스친구 계정명 변경이 가능한가요?

### ISSUE THREAD

**Issue by enjoyseo** [plusfriend/auto_reply#94]
안녕하세요 현재  AXA다이렉트_    로 된 계정이 있는데
이름을 바꿀수 있나요?

그리고 현재 친구추가를 한 대상들을 차단이나 친구를 끊을 수 있는지요?
확인 부탁드립니다

감사합니다

**Comment by plusfriendteam** [comment]
이름 변경 및 강제 친구관계 변경은 불가능합니다.
