### ISSUE TITLE
자동응답 API 사용을 위한 앱 URL 입력시 유의사항 표시 요청

### ISSUE THREAD

**Issue by pskalyber** [plusfriend/auto_reply#95]
현재 자동응답 API를 사용하기 위해 앱 등록할 때, 앱 이름 다음으로 앱 URL을 입력하게 되어있는데요.

앱 URL에 http://www.test.co.kr 이라고 입력 후, 끝에 / 를 더 붙이면 안된다고 미리 표시가 되면 좋을 것 같습니다. 제가 앱 URL입력시 http://www.test.co.kr/ 처럼 끝에 / 를 붙였더니 /keyboard API는 잘 동작하길래 바로 사용 인증을 받고 사용을 시작했거든요. ...대신 /message, /friend 등은 자꾸 이상한 에러가 발생해서 한참 헤맸었습니다. 

저같이 앱 URL 끝에 / 넣었는지도 모른채 계속 삽질할 수도 있는 다른 분들을 위해, 앱 URL 끝에 / 를 넣지 말라고 표시해주는 것도 좋을 것 같아서 건의한번 해봅니다.

감사합니다.

**Comment by plusfriendteam** [comment]
건의주셔서 감사드립니다. 해당 사항은 검토하여 반영해보도록 하겠습니다. ^^
