### ISSUE TITLE
자동응답 API 서비스 장애 문의

### ISSUE THREAD

**Issue by nemusheewon** [plusfriend/auto_reply#96]
안녕하세요. 네무스텍 정희원입니다. 

2016년 10월 19일 20시 48분경부터 약 10분 동안 에러 메시지가 계속 수신되었습니다. 

혹시 원인 확인이 가능할까요? 

저희 서버 변경사항 없이 현재는 정상 동작되고 있습니다.

**Comment by plusfriendteam** [comment]
@nemusheewon 해당 계정 id 알려주시면 확인해보겠습니다.

**Comment by nemusheewon** [comment]
@롯데백화점, @아모레퍼시픽백화점에서 발생하였습니다.

**Comment by plusfriendteam** [comment]
@nemusheewon 두 계정 모두 /keyboard 호출시에 타임아웃 10초를 넘겨서 에러가 발생했었네요. ^^;
