### ISSUE TITLE
서버에러 메시지 계속 옵니다.

### ISSUE THREAD

**Issue by hslim80** [plusfriend/auto_reply#97]
프로필 : @simsimi

자동응답 API를 사용하고 있습니다.
아래와 같은 에러메시지가 지속적으로 간헐적으로 옵니다.
어떤 문제인지 몰라서 해결할 수 없는 상황입니다.
저희 자체 서비스는 문제가 없는데, 이런 메시지가 계속오니 난감합니다.
빠른 답변 부탁드립니다.

> [관리자에게만 발송되는 메시지입니다] 사용자 봇서버에 에러가 감지 되었습니다. 
>  내용:[unknown error]
> 
> [관리자에게만 발송되는 메시지입니다] 사용자 봇서버에 에러가 감지 되었습니다. 
>  내용:[잘못된 응답입니다. response is not OK(200) : 504 / Gateway Time-out]
>

**Comment by plusfriendteam** [comment]
@hslim80 타임아웃이 났었습니다. 지금은 안나고 있는거 같네요.^^
