### ISSUE TITLE
응답불가

### ISSUE THREAD

**Issue by KORJAHO** [plusfriend/auto_reply#98]
api를 적용해서 버튼(키보드) 생성까지는 가능한데 답장이 불가능 하네요ㅠㅠ
@gta5kor7kkrcg신청톡

**Comment by plusfriendteam** [comment]
@KORJAHO 질문을 좀 더 구체적으로 해주시면 문제 해결에 도움을 드릴 수 있지 않을까 싶습니다만..^^;;
