### ISSUE TITLE
채팅이 불가능한 프로필입니다.

### ISSUE THREAD

**Issue by Sunggil** [plusfriend/auto_reply#99]
안녕하세요

제가 자동응답 api를 테스트중에 발생하는 문제입니다.

스마트폰의 카카오톡앱으로 대화를 하면 정상적인 결과가 나옵니다만.
피씨의 카카오톡을 사용하면 대화창에 "채팅이 불가능한 프로필입니다."라고 표시가 되며 제가 메시지를 입력하여도 응답을 하지 않습니다.

어떤 부분이 잘못된것일 까요?

첨부파일은 다른 플러스친구입니다만 동일한 상태이기에 캡쳐를 첨부 합니다.

![2016-10-24 11 53 01](https://cloud.githubusercontent.com/assets/3970947/19632394/fcc85a82-99e0-11e6-9f8c-29989a7737f5.png)

**Comment by DoHyeong** [comment]
![alt tag](http://i.imgur.com/z2YJHSgl.png)
저도 같은 문제가 있습니다.
모바일에서는 정상작동하는데, pc에서는 안되네요.
원래 pc는 지원하지 않나요?

**Comment by plusfriendteam** [comment]
@Sunggil @DoHyeong 안녕하세요.
PC버전은 향후 지원 예정입니다.
